### ISSUE TITLE
I found the f**** reason of most memory leaks!

### ISSUE THREAD

**Issue by robske110** [ClearSkyTeam/ClearSky#105]
Ok, let me explain it:
The memory leaks always occurred for me since a long time. I was using PocketMine, IM, ClearSky and all the same 
```php
Fatal error: Allowed memory size of 17179869184 bytes exhausted (tried to allocate 130968 bytes) in phar:///Users/Tim/Desktop/Pocket_Server_0.13.x/PocketMine-MP.phar/src/pocketmine/level/Position.php on line 1202
```
just an example.
Today i got several crashes, but in the last days not. Why? I thought about it and noticed I've done nothing to the server today, but the last days I often developed on it and restarted the server. But: I use the start.sh with do_loop=yes So it auto restarts often because of my plugin crashes... Ok but then i noticed, that while I'm developing I'm also killing that start.sh script. AND NOW YOU HAVE IT.
If the server restarts several times, but the start.sh script is not exited the php process will not kill itself in the right way AND WILL NOT FREE UP ALL MEMORY. Here we have it. SOLUTIONS:
1. Disable do_loop (simple, but i don't want to)
2. 
```php
echo "StartingServer1..."
echo "for((i=1; i<=1000; i++)); do sh /Users/Tim/Desktop/Pocket_Server_0.13.x/start.sh; done" > S1.command
chmod +x S1.command
open S1.command
```
This script will allow you, to kill php completly

**Comment by gaoyichuan** [comment]
Nope, the memory leak has nothing to do with DO_LOOP, since DO_LOOP just restart the server when it's crashed, you can run the phar directly and you will still get the memory leak.

**Comment by robske110** [comment]
not as of this cause
DO_LOOP does not exit the script and therefore does not clean up memory!

**Comment by gaoyichuan** [comment]
@robske110 Memory is not cleaned in the start.sh, it's cleaned in the php threads, the cause of memory leak is the new version of pthreads doesn't cleanup the memory properly.

**Comment by robske110** [comment]
I do not mean that memory leak

**Comment by robske110** [comment]
But i still have to test it...
