### ISSUE TITLE
Important to be fixed, I guess (food)

### ISSUE THREAD

**Issue by starterdragon** [ClearSkyTeam/ClearSky#107]
Both on 0.13.0 and 0.14.0 CS,

There's a same bug, I use EconomyShop to sell Foods, and after you buy and try to eat 
It eat, It won't allow you, I meanyou can see the animation and sound, but you doesn't consume it
You have to atleast drop it || relog in to eat it.

Idk if this is cause by a plugin where the item doesnt register immediately on player's inventory
Data or something else.

**Comment by TheKillerTacos** [comment]
I think the server doesnt reads it as food, until the inventory gets updated (Item drop and picked up, Player relogs), so, idk where would that problem be

**Comment by nonbe102** [comment]
[https://youtu.be/SzIXS68tknA](url)

**Comment by TheKillerTacos** [comment]
oh
found out the problem i think. update to the latest ClearSky, let me build it, there was a problem with Drops and entity, that might be..

**Comment by nonbe102** [comment]
On this video, I used ClearSky 0.14.0 build#15 from Jenkins.

**Comment by TheKillerTacos** [comment]
oh, i guess its an inventroy bug, ill see what i can do

**Comment by nonbe102** [comment]
Sure, Thanks man.

**Comment by TheKillerTacos** [comment]
had you tried with other food? like apples?

**Comment by nonbe102** [comment]
Yes, almost most of them or all, but cake, well ofcourse it must be placed, but normal players can't place ;)

**Comment by TheKillerTacos** [comment]
it might be the plugin, or something, cant find anything wrong on the inv code and the food, but i Cant find updating inventroy item code from ClearSky, i cant help by now, we should wait for the ClearSky devs :P

**Comment by aodzip** [comment]
@thebigsmileXD You rewrite the food part , have a look on this

**Comment by thebigsmileXD** [comment]
Food consuming hasn't worked before either. Also its a known bug.

**Comment by thebigsmileXD** [comment]
I give up, i can not find any bug. Must be inventory..
addItem is used by economy, these can't be consumed. But any other plugin that gives food works.

**Comment by SalmonGER** [comment]
Food bought from EconomyShop works for me.
