### ISSUE TITLE
Running GC in game crashes the server

### ISSUE THREAD

**Issue by NML32** [ClearSkyTeam/ClearSky#108]
When /GC is run in game it crashes the server. 
No crash dump created.

**Comment by nonbe102** [comment]
What ClearSky Version or Build are you using, I think I need to try this :)

CS0.14.0#15

**Comment by nonbe102** [comment]
>status
[Server] [04:57:47] [INFO]: ---- Server status ----
[Server] [04:57:47] [INFO]: Player:0/15
[Server] [04:57:47] [INFO]: Uptime: 1 minutes 8 seconds
[Server] [04:57:47] [INFO]: AverageTPS: 20 (7.64%)
[Server] [04:57:47] [INFO]: CurrentTPS: 20 (66.65%)
[Server] [04:57:47] [INFO]: Network upload: 1.16 kB/s
[Server] [04:57:47] [INFO]: Network download: 0.48 kB/s
[Server] [04:57:47] [INFO]: Thread: 6
[Server] [04:57:47] [INFO]: Main thread memory: 37 MB.
[Server] [04:57:47] [INFO]: Total memory: 74 MB.
[Server] [04:57:47] [INFO]: Total virtual memory: 81 MB.
[Server] [04:57:47] [INFO]: Heap memory: 5 MB.
[Server] [04:57:47] [INFO]: Maxium memory (system): 81 MB.
[Server] [04:57:47] [INFO]: World "frp": 0 chunks 0 entities 0 tiles Time 0.27ms
>gc
[Server] [04:57:51] [INFO]: ---- Garbge collection result ----
[Server] [04:57:51] [INFO]: Chunks:0
[Server] [04:57:51] [INFO]: Entities:0
[Server] [04:57:51] [INFO]: Tiles:0
[Server] [04:57:51] [INFO]: Cycles:0
[Server] [04:57:51] [INFO]: Memory freed:0 MB

Works fine on CS 0.14.0 #15

**Comment by TheKillerTacos** [comment]
also on mine, and i have the CS 0.14.0#14, (CS 1.1)

**Comment by TheKillerTacos** [comment]
check if you dont have an outdated version or  plugin issue.

**Comment by NML32** [comment]
OK, thanks for testing. I'll check for a bad plugin.

**Comment by Driesboy** [comment]
updated

**Comment by nonbe102** [comment]
@TheKillerTacos  How'd you add the line "%pocketmine.command.status.Maxmemorymanager 1,500 MB"? I need this

**Comment by aodzip** [comment]
In pocketmine.yml
And such question please do not ask in issue tracker, in chat group provide in readme. md
