### ISSUE TITLE
Cant Find where to change Chunk viewing distances

### ISSUE THREAD

**Issue by TheKillerTacos** [ClearSkyTeam/ClearSky#113]
Hi, since im making my Server network, i saw that the render view is way too short, and cant change it in-game, so i was looking throught the Pocketmine.yml made some changes, So here is the part of chunk config:

**max-chunks:
  trigger-limit: 256
  trigger-chunk-collect: true
  low-memory-trigger: true

 world-caches:
  disable-chunk-cache: false
  low-memory-trigger: true

network:
 batch-threshold: 128
 compression-level: 2
 async-compression: true
 upnp-forwarding: false

debug:
 level: 1
 allow-xdebug: true
 #Enables /status, /gc
 commands: true

level-settings:
 default-format: mcregion
 convert-format: false
 auto-tick-rate: true
 auto-tick-rate-limit: 20
 base-tick-rate: 1
 always-tick-players: false

chunk-sending:
 per-tick: 16
 max-chunks: 256
 spawn-threshold: 46
 cache-chunks: true

chunk-ticking:
 per-tick: 2
 tick-radius: 1
 light-updates: false
 clear-tick-list: true

chunk-generation:
 queue-size: 64
 population-queue-size: 32**

but the renderview its same short. can someone help me?

**Comment by thebigsmileXD** [comment]
.. server.config

**Comment by TheKillerTacos** [comment]
Server.config? Or server.properties? If server.config. is that a src file from CS?

**Comment by thebigsmileXD** [comment]
properties

**Comment by TheKillerTacos** [comment]
OK. But it's not there. I'll add it soon to the config files.. Plez someone close this issue. I'm on phone and I can't do so
