### ISSUE TITLE
So this happend...

### ISSUE THREAD

**Issue by TheKillerTacos** [ClearSkyTeam/ClearSky#114]
Im Making a plugin that shows all the permissions from all the plugins, now that i fixed it, it now shows a Crash error:

> ClearSky Crash Dump Sun Feb 7 00:34:11 CST 2016
> 
> Error: Class Listener not found
> File: /src/spl/BaseClassLoader
> Line: 144
> Type: notice
> 
> THIS CRASH WAS CAUSED BY A PLUGIN
> 
> Code:
> [135] 
> [136] 	        if(\method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->
>  getMethod("onClassLoaded")->isStatic()){
> [137] 		        $name::onClassLoaded();
> [138] 	        }
> [139] 	        
> [140] 	        $this->classes[] = $name;
> [141] 
> [142]             return \true;
> [143]         }elseif($this->getParent() === \null){
> [144] 	        throw new ClassNotFoundException("Class $name not found");
> [145]         }
> [146] 
> [147]         return \false;
> [148]     }
> [149] 
> [150]     /**
> [151]      * Returns the path for the class, if any
> [152]      *
> [153]      * @param string $name
> [154]      *
> 
> Backtrace:
> #0 /PermList.phar/src/PermList/Main(8): spl_autoload_call(string Listener)
> #1 /src/spl/BaseClassLoader(128): include(string phar://C:/Users/xxxx/Desktop/IT
> Servers/Servers/IT Testing/plugins/PermList.phar/src/PermList/Main.php)
> #2 (): BaseClassLoader->loadClass(string PermList\Main)
> #3 (): spl_autoload_call(string PermList\Main)
> #4 /src/pocketmine/plugin/PharPluginLoader(44): class_exists(string PermList\Main, boolean 1)
> #5 /src/pocketmine/plugin/PluginManager(132): pocketmine\plugin\PharPluginLoader-> 
> loadPlugin(string C:\Users\xxxx\Desktop\IT Servers\Servers\IT Testing\plugins\PermList.phar)
> #6 /src/pocketmine/plugin/PluginManager(276): pocketmine\plugin\PluginManager->
> loadPlugin(string C:\Users\xxxx\Desktop\IT Servers\Servers\IT Testing\plugins\PermList.phar, 
> array Array())
#7 /src/pocketmine/Server(1657): pocketmine\plugin\PluginManager->loadPlugins(string C:\Users\xxxx\Desktop\IT Servers\Servers\IT Testing\plugins\)
#8 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string > phar://C:\Users\xxxx\Desktop\IT Servers\Servers\IT Testing\PocketMine-MP.phar/, string 
> C:\Users\xxxx\Desktop\IT Servers\Servers\IT Testing\, string C:\Users\xxxx\Desktop\IT 
> Servers\Servers\IT Testing\plugins\)
> #9 (1): require_once(string phar://C:/Users/xxxx/Desktop/IT Servers/Servers/IT 
> Testing/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

> PocketMine-MP version: 1.1 #0 [Protocol 43; API 1.13.1]
> Git commit: 0000000000000000000000000000000000000000
> uname -a: Windows NT DESKTOP-70RG52G 6.2 build 9200 (Windows 8 Home Premium Edition) > i586
> PHP Version: 5.6.6
> Zend version: 2.6.0
> OS : WINNT, win

> Loaded plugins:

And here is my plugin:
https://github.com/TheKillerTacos/PermList/blob/master/src/PermList/Main.php

**Comment by TheKillerTacos** [comment]
And my plugin only has main.php and it has 48 lines of code

**Comment by BlackShadow1** [comment]
This isn't a CS fault, that's because it can't found the class Listener, and you said your plugin has only main.php

**Comment by TheKillerTacos** [comment]
yep, so what can i do?

**Comment by TheKillerTacos** [comment]
Ill fin out how

**Comment by thebigsmileXD** [comment]
This is your own fault. ***THIS CRASH IS CAUSED BY A PLUGIN***

**Comment by TheKillerTacos** [comment]
But what plugin. It doesn't show what plugin or the main source of the problem.
