### ISSUE TITLE
furnace crash

### ISSUE THREAD

**Issue by Tolo0** [ClearSkyTeam/ClearSky#115]
When touching a furnace. Players crash.

**Comment by thebigsmileXD** [comment]
Are you sure? That was fixed in the beginnings of ImagicalMine, they havent changed in ClearSky since that..

**Comment by Tolo0** [comment]
I'm using thethe latest build. Had to compress it to post.
[Furnace.mp4.zip](https://github.com/ClearSkyTeam/ClearSky/files/120985/Furnace.mp4.zip)

**Comment by NML32** [comment]
you should do /version in the video next time.

**Comment by Tolo0** [comment]
![screenshot_2016-02-07-23-51-36](https://cloud.githubusercontent.com/assets/13458191/12876248/d6b084a8-cdf5-11e5-94cd-e2770a0e628f.png)

**Comment by nonbe102** [comment]
Can the dev see your crashdump? this might be caused by a plugin.

**Comment by TheKillerTacos** [comment]
Its a crash from the client not from the server nonbe.. So there is no crash dump

**Comment by Tolo0** [comment]
Nope. No crash dumb

**Comment by thebigsmileXD** [comment]
No such problem for me on the latest build

**Comment by Tolo0** [comment]
I also crash when touching leaves sometimes.

**Comment by TheKillerTacos** [comment]
it might be the MC:PE Version, if its updated (0.13.1/2)

**Comment by thebigsmileXD** [comment]
Touching leaves and sprinting on leaves. Spawning leaf breaking particles will also crash you. Only if theres a transparent bit in a particle i reported it already as a bug to mojang

**Comment by robske110** [comment]
Client Bug (wont fix)

**Comment by thebigsmileXD** [comment]
Actually.. i am not so sure anymore, if its a client bug. I think the leaves particles are sent by the server.

**Comment by Efforto** [comment]
Ehh...Genisys and Nukkit has already fix this bug......

**Comment by thebigsmileXD** [comment]
Nice for them

**Comment by aodzip** [comment]
ImagicalMine have fix this years ago , and I cant get this bug
