### ISSUE TITLE
Server randomly crashes...

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#116]
In the crash dump it says "Bad plugin SimpleAuth 1.7.1"
How to fix it?

**Comment by PocketKiller** [comment]
SimpleAuth bug, close

**Comment by MasterWolf** [comment]
But wait. What is this bug?

**Comment by aodzip** [comment]
send the crash log too.

**Comment by MasterWolf** [comment]
@aodzip i deleted crash dump... And when i opened console here was empty... So strange!

**Comment by robske110** [comment]
Crash Dump generation is broken in ClearSky... And use SimpleAuth v1.8.1!!!!!!! (1.7.1 is massively outdated!)

**Comment by MasterWolf** [comment]
@robske110 what?!?! 1.8.1???? Its released? LINK PLZ!!

**Comment by TheKillerTacos** [comment]
isnt it here: https://github.com/PocketMine/SimpleAuth/ ?

**Comment by NML32** [comment]
I can't find SimpleAuth v1.8.1 anywhere

**Comment by aodzip** [comment]
Crash Dump is broken? I think it works well

**Comment by TheKillerTacos** [comment]
Crash Dump Works Excellent (Same as IM & PM)

**Comment by thebigsmileXD** [comment]
> Crash Dump generation is broken in ClearSky... And use SimpleAuth v1.8.1!!!!!!! (1.7.1 is massively outdated!)

Really, no problems. Maybe read write permissions in the folder are your problem..
