### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#117]
I think it will be cool if we will able to change biome. Can you add command "/biome pos1" "/biome pos2" and "/biome set [TAIGA / ICE_PLAINS]"
It will be very useful because we will be able to manage weather (snowy / rainy).

**Comment by starterdragon** [comment]
Might be better if this is a plugin rather than on main core, In my point of view, might add to work and also adds more bugs to CS, plus File size and more..

**Comment by robske110** [comment]
Just use WorldFixer by @Creeperface (or look at the source)

**Comment by MasterWolf** [comment]
@robske110 so can i change biome with this plugin??

**Comment by robske110** [comment]
The source of the plugin can do that

**Comment by TheKillerTacos** [comment]
badly, the World Generator aint, that good, so i recommend to import a pc world, or change the mcregion to leveldb to import MCPE maps to CS. idk if it works,

I didnt knew that WorldFixer CAN Change biomes?

**Comment by thebigsmileXD** [comment]
Make a plugin for that. I thought about that today, /setbiome. Because of something i read. It was a better generators plugin for Bukkit.

**Comment by MasterWolf** [comment]
@thebigsmileXD you will make plugin?

**Comment by thebigsmileXD** [comment]
Maybe.
