### ISSUE TITLE
PvP issue?

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ClearSkyTeam/ClearSky#118]
Anyone else have the random "invincible" player bug? i cant figure out what is causing it..I use a modified version of 1v1 plugin, could it be when it tp players from separate worlds they are not spawned to the other player correctly? Im not sure if thats the only time it happens witch is why i posted on here to see if anyone else has this issue.

**Comment by SalmonGER** [comment]
I think i also had this issue today. (For the first time.)

**Comment by XxDXM-hippiexX** [comment]
Ive had this issue for a while so if it is a pm or ClearSky bug then it is not bc of one of the recent updates..

**Comment by TheKillerTacos** [comment]
i we need to test this, what if its a lag issue? like low ping, or client not receiving full packets?
it might be hard to fix

**Comment by XxDXM-hippiexX** [comment]
I understand that..the last thing a dev likes to hear is that it's "random" XD but..salmon do you use 1v1? I don't think it's lag because when it happens it happens until the other player dies..I ran around the arena for 2 minutes trying to hit a guy every now and then and couldn't but he could hit me. I think it might have something to do with the teleport honestly because i haven't had any reports of it happening anywhere else than in a "1v1" arena. Now I would say the plugin did it..but the plugin doesn't stop entitydamageevent in any case, don't even use that function but it does teleport both players to the arena..maybe I'll try a different teleport method? using setworld and all that jazz

**Comment by XxDXM-hippiexX** [comment]
So if it makes any difference i tried $player->setLevel and that made it worse if anything XD this was the only time ive seen or heard of BOTH players not being able to hit each other...maybe something to do with the random invisible name tag also? /:

**Comment by XxDXM-hippiexX** [comment]
There are not many players on at this time..i think there was 7 or so players online when i was just testing so i think its safe to rule out lag?

**Comment by XiangZhao969** [comment]
I'm using IM and meet the same thing

**Comment by XxDXM-hippiexX** [comment]
@XiangZhao969 do you use 1v1?

**Comment by SalmonGER** [comment]
@XxDXM-hippiexX Yes, i use 1vs1. I had this issue two times now, once in a 1vs1 match and one time just in a random place of the world.

**Comment by XxDXM-hippiexX** [comment]
Ah..crap was hoping for some sort of pattern XD

**Comment by thebigsmileXD** [comment]
1vs1 fault

**Comment by robske110** [comment]
But 1vs1 does nothing wrong
I think its the bug with setHealth
//I will be active on ClearSky now. (preparing to switch the main server to clearsky)

**Comment by thebigsmileXD** [comment]
It does. See how it handles its arenas..

**Comment by robske110** [comment]
var_dump an arena and terminal will crash.
And how did i advertise?
