### ISSUE TITLE
[HELP] Reopening Same Short Chunk view

### ISSUE THREAD

**Issue by TheKillerTacos** [ClearSkyTeam/ClearSky#120]
Hi, im reopening this issue, since adding the following thing to the server.properties didnt work:
`view-distance=128`

So, i need help, since it looks horrible,
Here is the a video showing my lobby not rendering right since low Chunk view:
https://youtu.be/SC4gLzdiY98

Sorry for the yellow filter, im using it because my screen conector to the phone motherboard
got damaged, and it looks like everything is red, so the filter seem to fixed it.

**Comment by aodzip** [comment]
get the latest phar and remove your pocketmine.yml

**Comment by TheKillerTacos** [comment]
i did, that server was clean, since it wasnt letting me join, latest CS, (0.14.0,# 18)

**Comment by aodzip** [comment]
#20 now

**Comment by TheKillerTacos** [comment]
oh, ok!

**Comment by aodzip** [comment]
I make the pocketmine.yml give more viewdistance by default , you should update that file
