### ISSUE TITLE
Splash Potions crash when throwing

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#121]
Ever since my projectile fix, splash potions have been crashing players who use them. The other launchable items (Snowball, eggs, & exp bottles) work fine, just the splash potions.

**Comment by MCPEPIG** [comment]
Wait it's night vision splash potions only...

**Comment by aodzip** [comment]
Confirmed , it crash client only

**Comment by thebigsmileXD** [comment]
Yea. Seems because the effect color is wrong
