### ISSUE TITLE
[Question] How can I remove "[Server]" from logger?

### ISSUE THREAD

**Issue by alex2534alex** [ClearSkyTeam/ClearSky#122]
![screenshot_2016-02-09-11-20-52](https://cloud.githubusercontent.com/assets/15706847/12912157/72e7bf24-cf1f-11e5-84b2-5f22dea5c526.png)

**Comment by aodzip** [comment]
You should ask the laucher's author.

**Comment by alex2534alex** [comment]
Ouch.....Really....Forgot...
