### ISSUE TITLE
ClearSky #57 problem

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/ClearSky#126]
Can you fix a PlayerJoinEvent ? It says that global 0.13 can come but we cant.

**Comment by aodzip** [comment]
As I test it can join
Is there any plugin refuse this?

**Comment by thebigsmileXD** [comment]
0.13.1 and 0.13.2 are confirmed to work.

**Comment by Adam1609** [comment]
I have these plugin:
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
AdminJoin 1.3.1 by ZacHack for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
BenchMark 1.0-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
ChairStairsPE 0.1.1 by thebigsmileXD for API(s) 1.0.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CombinedSlots 1.0.0 by basprohop for API(s) 1.10.0
CraftingTableFix 2.0-Alpha by hm for API(s) 1.13.0, 2.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyPotionDispenser 0.0.2 by Khinenw for API(s) 1.12.0
EconomyProperty 2.0.6 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
EffectBlades 1.0.0 by MCPEPIG for API(s) 1.12.0
Farms 1.2-alpha by ifteam for API(s) 1.12.0, 1.13.0, 2.0.0
GMChecker 0.2 by  for API(s) 1.12.0
HeadShot 1.0 by DeBe for API(s) 1.12.0, 1.13.0, 2.0.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
iProtector 3.1a by LDX for API(s) 1.9.0
ItemEffects 2.5.0 by XFuryMCPE for API(s) 1.12.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
KitPro 4.1 by  for API(s) 1.10.0
LaunchPads 1.0.0 by MCPEPIG for API(s) 1.0.0
LightningJoin 0.4 by Jelly9912 for API(s) 1.13.0
MoreTrees 1.0-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
TimeRanks 1.0.2 by luca28pet for API(s) 1.12.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
RandomItem 4.2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
PmChair 1.2 by maru for API(s) 1.12.0, 1.13.0, 2.0.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
PVPMoney 0.1-Alpha by hm for API(s) 1.0.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
RPAntiLagg PreFinal_1.1 by LDX for API(s) 1.8.0
ServerLoveMCPE 3.1 by TheDeibo for API(s) 1.10.0
SignShop 2.0.0build3 by xionbig, xionbig for API(s) 1.12.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
Slapper 1.2.9.1 by jojoe77777 for API(s) 1.12.0
SpecialBlock 1.3.2 by Primus for API(s) 1.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
UsefulShears 1.0 by DeBe for API(s) 1.12.0, 1.13.0, 2.0.0
VoteBan 1.0.2 by GmWM for API(s) 1.12.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
Jail 2.1.2 by hoyinm14mc for API(s) 1.13.0, 1.13.1
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

**Comment by thebigsmileXD** [comment]
Remove chairstairs

**Comment by Adam1609** [comment]
ur plugin doesn't work :((

**Comment by Adam1609** [comment]
Its still not working. I dont know why @@

**Comment by Tolo0** [comment]
Plugin custom alerts is effecting this. Just disable the version msg then it works fine.

**Comment by Adam1609** [comment]
I removed all of my plugins but still its doesnt work

**Comment by Tolo0** [comment]
Did u try deleting ur pocketmine.yml then Rebooting

**Comment by Adam1609** [comment]
I try it..
