### ISSUE TITLE
support 0.14.0.6

### ISSUE THREAD

**Issue by SuperAdam47** [ClearSkyTeam/ClearSky#127]

**Comment by aodzip** [comment]
Universe server cant let 0.14.0.6 join?
Try the latest 0.14 repo , it is universe join ready

**Comment by aodzip** [comment]
ClearSky now support universe join now , You can use the latest phar and it will let every 0.14 client join
![photo_2016-02-11_01-28-45](https://cloud.githubusercontent.com/assets/8325441/12955642/f2be2f22-d05e-11e5-9ee5-7572b6d83b64.jpg)
