### ISSUE TITLE
Cant join to my server 0.14.0 #22

### ISSUE THREAD

**Issue by erkam2002** [ClearSkyTeam/ClearSky#128]
i have 0.14.0 alpha build 6 but i cant join

**Comment by aodzip** [comment]
ClearSky now support universe join now , You can use the latest phar and it will let every 0.14 client join
![photo_2016-02-11_01-28-45](https://cloud.githubusercontent.com/assets/8325441/12955642/f2be2f22-d05e-11e5-9ee5-7572b6d83b64.jpg)

**Comment by erkam2002** [comment]
not was me

**Comment by aodzip** [comment]
You can join ClearSky Communicate group provided on README.md and have a future discussion .

**Comment by erkam2002** [comment]
i thing older version cant join

**Comment by aodzip** [comment]
I can't understand what you mean easily , and dont chat in issue tracker . If you want future discussion , please join the group

**Comment by aodzip** [comment]
I can't understand what you mean easily , and dont chat in issue tracker . If you want future discussion , please join the group

**Comment by MasterWolf** [comment]
I have same problem?

**Comment by TheKillerTacos** [comment]
`I can't understand what you mean easily , and dont chat in issue tracker . If you want future discussion , please join the group`
MasterWolf... update your CS

**Comment by MasterWolf** [comment]
@TheKillerTacos what is CS?

**Comment by SalmonGER** [comment]
@MasterWolf ClearSky
