### ISSUE TITLE
Telegram group doesn't seem to work right

### ISSUE THREAD

**Issue by robske110** [ClearSkyTeam/ClearSky#129]
As i saw you have an telegram group i immediatly had to click it. It opened my telegram app and it loaded for an very long time until it came back with this:
![image](https://cloud.githubusercontent.com/assets/16020100/12958921/4f5b9484-d034-11e5-9797-88fdf3b1b948.png)

**Comment by PocketKiller** [comment]
what 'this'?

**Comment by robske110** [comment]
An uploading pic

**Comment by robske110** [comment]
Pic had to upload, sorry

**Comment by thebigsmileXD** [comment]
Invalid. Wrong group link. Its this one, (see readme -.-")
https://telegram.me/joinchat/AlErxAY3tx0MPBGYuGtpDA

**Comment by robske110** [comment]
@thebigsmileXD it may be invaild but it is not finished or fixed!

**Comment by robske110** [comment]
It is still saying the same error
//I love Telegram ;)

**Comment by thebigsmileXD** [comment]
Remove the old group and add this one. #learnhowtousetelegramandhowtoreadthefaq

**Comment by TheKillerTacos** [comment]
Sure! *adding #learnhowtousetelegramandhowtoreadthefaq,
wait, nvm

**Comment by robske110** [comment]
Fixed
