### ISSUE TITLE
[REQUEST] Event for golems

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#130]
Can you add an event for snow & iron golems?

**Comment by thebigsmileXD** [comment]
I'll add a spawn event.

**Comment by TheKillerTacos** [comment]
but, why?

**Comment by MCPEPIG** [comment]
For developers. I need an event to detect when someone makes a snow golem for my minigame to work

**Comment by TheKillerTacos** [comment]
k,

**Comment by thebigsmileXD** [comment]
AS I SAID ITS SPAWN ENTITY EVENT!!!

**Comment by thebigsmileXD** [comment]
EntitySpawnEvent.
