### ISSUE TITLE
Shows 0.13 instead of 0.13.2

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#131]
![image](https://cloud.githubusercontent.com/assets/16523741/12968453/2e2b9e44-d016-11e5-9d89-4cdf74af32f3.png)

Still allows players to join, but it shows 0.13 in red so users think their version is incompatible.

**Comment by aodzip** [comment]
This is caused by universal join feature , 0.13.0 0.13.1 0.13.2 are able to join together , but it have to show as a red one

**Comment by Aericio** [comment]
I see now. Is there a way to make it 0.13 in green instead of red?

**Comment by aodzip** [comment]
You can get it back to green only by modified the code , and unable use universal join feature

**Comment by robske110** [comment]
Please revert this to only support 0.13.2 this is stupid, its causing issues and my players are reporting some strange stuff about that

**Comment by thebigsmileXD** [comment]
Its client sided. You cant change it via CS code. But i think 0.13.* instead of 0.13 would be better

**Comment by thebigsmileXD** [comment]
There are no issues at all for me. Tested for 3 days!
