### ISSUE TITLE
Invisible Tiles.

### ISSUE THREAD

**Issue by Tolo0** [ClearSkyTeam/ClearSky#133]
Lately a lot of players have been complaining about chest going invisible and loosing ther items. Is anyone else experiencing this?

**Comment by robske110** [comment]
Yes thats this tile bug: https://github.com/ImagicalMine/ImagicalMine/issues/641

**Comment by robske110** [comment]
Could anyone rename this to ^Tiles do not show up/break^
And here is an video with skulls (the sams with chests and signs)
https://www.dropbox.com/sh/fmhfsx5tpucto07/AADRm5jIbujeZoiYXF8bY_7za?dl=0

**Comment by Tolo0** [comment]
Shouldn't this be a critical bug?

**Comment by robske110** [comment]
Rename it please to ^Tiles dissapear^ or something like that

**Comment by Tolo0** [comment]
What happens in ur video has never happend to me. Does it still do that on the latest build?

**Comment by thebigsmileXD** [comment]
I almost think its lag. Not server lag, but packet lost

**Comment by robske110** [comment]
@Tolo0 you described the same thing as in the video, only with chests! (Chest = Sign = Heads)

**Comment by Tolo0** [comment]
Oh lol didn't know that.

**Comment by MCPEPIG** [comment]
Do you use MineReset?

**Comment by robske110** [comment]
Nope

**Comment by thebigsmileXD** [comment]
Not happening anymore, right?

**Comment by robske110** [comment]
Fixed as of 0.14
