### ISSUE TITLE
Linux64

### ISSUE THREAD

**Issue by Cecil107** [ClearSkyTeam/ClearSky#14]
How to install it on Ubuntu 14.04 x64

**Comment by aodzip** [comment]
You just follow the step how to install offical pm
Then replace PocketMine-MP.phar with This repo one.
Remember comment xdebug out

**Comment by Cecil107** [comment]
Its not Working i cant install PM

**Comment by aodzip** [comment]
wget -q -O - http://get.pocketmine.net/ | bash -s - -v development

You can run this to install offical PM

**Comment by Cecil107** [comment]
Its not Working

**Comment by thebigsmileXD** [comment]
Then its not the fault of ClearSky

**Comment by thebigsmileXD** [comment]
But we'll still try to help you. What errors do you get?

**Comment by Cecil107** [comment]
its says its needs root but i am logged as root
