### ISSUE TITLE
Can't get on the server

### ISSUE THREAD

**Issue by GreenNature-MC-Server** [ClearSkyTeam/ClearSky#141]
I'm tried ClearSky today on my own server but when players try to get in the server they become a message that say, that the version which they using is outdatet und in the right of the world menu there is in red "0.13"! The same with the 0.14 version! I'm used the newest version on the Jenkins Website for information!

**Comment by robske110** [comment]
UNCONFIRMED
I have no issues with latest build

**Comment by aodzip** [comment]
dont have this too ... can you paste your server IP and port here for test?

**Comment by thebigsmileXD** [comment]
Unconfirmed also.

**Comment by GreenNature-MC-Server** [comment]
I will sent in some minutes a link to some screenshots

**Comment by GreenNature-MC-Server** [comment]
https://www.dropbox.com/sh/b1woesx3ogxt7q5/AAAPIHXgu2Vy7BQfuWQw8zX8a?dl=0

Here are 2 screens from the console! If you need some other things please tell me!

**Comment by SURVAml** [comment]
I think it's an issue with CustomAlerts (or maybe plugins which are using custom outdated messages), you must disable the custom server outdated message in the config. I also had this problem.

**Comment by GreenNature-MC-Server** [comment]
Ok! I try it now without this plugin and i will write if it's not worked!

**Comment by GreenNature-MC-Server** [comment]
Danke SURVA.ml! Es funktioniert, wenn man es alleine schon deaktiviert! :D

**Comment by SURVAml** [comment]
You don't need to remove it, just disable the server outdated message like this:
Write custom: false at OutdatedClient and OutdatedServer.

```
---
datetime-format: "H:i:s"
Motd:
  update-timeout: 1
  custom: true
  message: "&c&lSURVA.ml&r &eServer Netzwerk"
OutdatedClient:
  custom: false
  message: "&cSorry, dein Minecraft ist veraltet!"
OutdatedServer:
  custom: false
  message: "&cServer ist veraltet - wir arbeiten daran!"
WhitelistedServer:
  custom: true
  message: "&eDie Server werden gewartet, &abitte versuche es später nochmal."

**Comment by thebigsmileXD** [comment]
Thanks alot
