### ISSUE TITLE
"Server is Outdated" Error for 0.13.2

### ISSUE THREAD

**Issue by jazzwhistle** [ClearSkyTeam/ClearSky#145]
Hi, I've got this working on one server where build 70 works well, but on all my other servers it won't let 0.13.2 alpha (android) join. I deleted pocketmine.yml before start for them all, - is there something in server.properties that might trigger this? I confess I haven't yet tried removing all plugins, but if anyone can save me the hassle of trying all that, I'd be very grateful.

Thanks

**Comment by aodzip** [comment]
#141

**Comment by jazzwhistle** [comment]
thanks, should have found that myself :-/
