### ISSUE TITLE
php7 Offset LightPopulated not found

### ISSUE THREAD

**Issue by Driesboy** [ClearSkyTeam/ClearSky#153]
ClearSky Crash Dump Sat Feb 13 14:47:14 GMT 2016

Error: Offset LightPopulated not found
File: /src/pocketmine/nbt/tag/CompoundTag
Line: 45
Type: error

Code:
[36] 	public function offsetGet($offset){
[37] 		if(isset($this->{$offset}) and $this->{$offset} instanceof Tag){
[38] 			if($this->{$offset} instanceof \ArrayAccess){
[39] 				return $this->{$offset};
[40] 			}else{
[41] 				return $this->{$offset}->getValue();
[42] 			}
[43] 		}
[44] 
[45] 		assert(false, "Offset $offset not found");
[46] 		return null;
[47] 	}
[48] 
[49] 	public function offsetSet($offset, $value){
[50] 		if($value instanceof Tag){
[51] 			$this->{$offset} = $value;
[52] 		}elseif(isset($this->{$offset}) and $this->{$offset} instanceof Tag){
[53] 			$this->{$offset}->setValue($value);
[54] 		}
[55] 	}

Backtrace:
#0 /src/pocketmine/level/format/anvil/Chunk(100): pocketmine\nbt\tag\CompoundTag->offsetGet(string LightPopulated)
#1 /src/pocketmine/level/Level(2759): pocketmine\level\format\anvil\Chunk->isLightPopulated(boolean)
#2 /src/pocketmine/level/Level(2344): pocketmine\level\Level->loadChunk(integer 59, integer -33, boolean 1)
#3 /src/pocketmine/level/Level(3025): pocketmine\level\Level->getChunk(integer 59, integer -33, boolean 1)
#4 /src/pocketmine/Player(842): pocketmine\level\Level->populateChunk(integer 59, integer -33)
#5 /src/pocketmine/Player(1772): pocketmine\Player->sendNextChunk(boolean)
#6 /src/pocketmine/Server(2462): pocketmine\Player->checkNetwork(boolean)
#7 /src/pocketmine/Server(2202): pocketmine\Server->tick(boolean)
#8 /src/pocketmine/Server(2082): pocketmine\Server->tickProcessor(boolean)
#9 /src/pocketmine/Server(1677): pocketmine\Server->start(boolean)
#10 /src/pocketmine/PocketMine(445): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Driesc\Desktop\PhP-7 server\Lobby V3\, string C:\Users\Driesc\Desktop\PhP-7 server\Lobby V3\, string C:\Users\Driesc\Desktop\PhP-7 server\Lobby V3\plugins\)

PocketMine-MP version: 2.1dev #0 [Protocol 37; API 1.20.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT DRIESC-PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
PHP Version: 7.0.2
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
1vs1 0.0.6 by  for API(s) 1.0.0, 1.1.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
AfkKick 1 by XxDXM_hippiexX for API(s) 1.11.0, 1.13.0
BetaTester 0.14.0 alpha build 4 by PeratX for API(s) 1.13.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ChatLogin 1.4 by EvolSoft for API(s) 1.11.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
ColorMatch 1.1.1 by CreeperFace for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
FactionsPro 1.5b3 by Tethered_ for API(s) 1.12.0
GoogleAnalytics 1.0.0 by  for API(s) 1.0.0
HealthTag 1 by EnderKenji for API(s) 1.3.1
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
LIAB 1.0.0 by aliuly for API(s) 1.10.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
PurePerms 1.3.0-BETA-1 by 64FF00 for API(s) 1.13.0
RestartMe 1.1.0 by Gamecrafter for API(s) 1.10.0
RocketPads 1.0.0 by Gamecrafter for API(s) 1.12.0
ServerAuth 2.13 by EvolSoft for API(s) 1.11.0
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
Slapper 1.2.9.3_PHP7 by jojoe77777 for API(s) 1.12.0
TapToDo 2.1.2 by Falk for API(s) 1.0.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
PureChat 1.3.4-INDEV by 64FF00 for API(s) 1.11.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0

**Comment by robske110** [comment]
Php7 isn't finished yet

**Comment by Driesboy** [comment]
Please fix it

**Comment by robske110** [comment]
I don't think we are working on php7 yet.
Why don't you use PHP5? This isn't IM it does not lag.
And of course, we will fix this, but i'm sure more will come up (If this happened on startup)

**Comment by Driesboy** [comment]
its laggy for me

**Comment by VonHirsch** [comment]
One reason for this is if you're attempting to use a region map (mcr) as opposed to anvil (mca)

**Comment by aodzip** [comment]
We wont support php7 version after we make it as "master"

**Comment by thebigsmileXD** [comment]
Still affects the latest versions.

**Comment by robske110** [comment]
Fixed?

**Comment by thebigsmileXD** [comment]
Did not autoclose

**Comment by robske110** [comment]
lol github
