### ISSUE TITLE
Get a possible NBT area for Boat Color

### ISSUE THREAD

**Issue by aodzip** [ClearSkyTeam/ClearSky#158]
![2016-02-14 20_40_24-ida - e__pocketmine_clearskyteam_ida_libminecraftpe i64 libminecraftpe so](https://cloud.githubusercontent.com/assets/8325441/13033693/5a204386-d35b-11e5-9e1f-dd8cb5b43541.png)
Any Idea?

**Comment by aodzip** [comment]
![2016-02-14 20_44_41-ida - e__pocketmine_clearskyteam_ida_libminecraftpe i64 libminecraftpe so](https://cloud.githubusercontent.com/assets/8325441/13033708/d16ffc4c-d35b-11e5-85a2-d034b4e8b2e3.png)
in nbt data

**Comment by PocketKiller** [comment]
try set for it a new CompoundTag with {display{woodID:id}} ? and replace id with the meta of wood block?

**Comment by aodzip** [comment]
I should learn assembly language...

**Comment by aodzip** [comment]
![2016-02-14 21_10_25-ida - e__pocketmine_clearskyteam_ida_libminecraftpe i64 libminecraftpe so](https://cloud.githubusercontent.com/assets/8325441/13033835/81a5dd36-d35f-11e5-8287-22d8ea76352d.png)
I bet it is something like 
Compound(xxxx"woodID"=>xxxxxxx)
Leave a note here , maybe do in days
