### ISSUE TITLE
Cant join...

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#163]
I updated everything but i cant join my server! Other players cant join too! It says "Outdated server"...
I am using build 24.

**Comment by thebigsmileXD** [comment]
If you have CustomAlerts, disable the outdated server message

**Comment by MasterWolf** [comment]
@thebigsmileXD Thank you! You helped me very much! =)

**Comment by thebigsmileXD** [comment]
@MasterWolf welcome

by the way, its mentioned in the readme :)
> Note¹ - Please set 'Outdated Server' message to 'false' in the CustomAlert plugin or any related plugin if you encounter Outdated server

Note² - Please set 'Full server' message to 'false' in the CustomAlert plugin or any related plugin if you encounter Full server

**Comment by MasterWolf** [comment]
@thebigsmileXD LOL i never read readme file!! xD

**Comment by thebigsmileXD** [comment]
@MasterWolf thats the problem xD
