### ISSUE TITLE
Due to decompile there is some NBT for mobs

### ISSUE THREAD

**Issue by aodzip** [ClearSkyTeam/ClearSky#165]
Sheep have a "Sheard" , boolean , "Color" , Byte
Aged animals have "InLove" , Int

**Comment by thebigsmileXD** [comment]
> Sheep have a "Sheard" 
don't

**Comment by aodzip** [comment]
![2016-02-15 16_58_44-ida - e__pocketmine_clearskyteam_ida_libminecraftpe i64 libminecraftpe so](https://cloud.githubusercontent.com/assets/8325441/13043797/6ef12122-d405-11e5-8004-ebcfc84fc8ef.png)

**Comment by thebigsmileXD** [comment]
@aodzip oh that you mean..

yea i'll check. and add

**Comment by aodzip** [comment]
Due to 0.14 update they seems changed😑

**Comment by thebigsmileXD** [comment]
Yes.. Almost totally -.-"
