### ISSUE TITLE
Red version number

### ISSUE THREAD

**Issue by SURVAml** [ClearSkyTeam/ClearSky#167]
Hi, I'm using the latest build #112 and Minecraft PE 0.13.2, and the version-number 0.13 is red in Minecraft PE.
Is there any way to make it green (maybe like Lifeboat does?)?
I've attached a screenshots that you know what I mean.

![img_0302](https://cloud.githubusercontent.com/assets/15860314/13053612/ae7bf3ee-d405-11e5-982b-bf267206f8a1.jpg)

**Comment by thebigsmileXD** [comment]
Thats correct.. You wether only see 0.13.2 green or all red

We should change it back to 0.13.2 so atleast some guys see green

**Comment by robske110** [comment]
@thebigsmileXD
The string has nothing to do with green/not green
It's the main protocol!
Look at that PR (i and @aodzip tried to figure out best soloution)

**Comment by robske110** [comment]
https://github.com/ClearSkyTeam/ClearSky/pull/132

**Comment by PocketKiller** [comment]
@robske110 is correct

**Comment by robske110** [comment]
I will soon make an config in pocketmine.yml for this!

**Comment by Tolo0** [comment]
Yea I've had players saying they can't join cos it's red. Even though they can join. They just don't try lol.

**Comment by robske110** [comment]
As i said working on property
