### ISSUE TITLE
warning msg on console 

### ISSUE THREAD

**Issue by Tolo0** [ClearSkyTeam/ClearSky#168]
:33] [CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to RakLib Thread crashed [BaseClassLoader]: Cannot use raklib\Binary as Binary because the name is already in use2016-02-15 [11:34:33] [INF

**Comment by robske110** [comment]
Fixed

**Comment by Tolo0** [comment]
Thanks 😉
