### ISSUE TITLE
health glitch

### ISSUE THREAD

**Issue by Tolo0** [ClearSkyTeam/ClearSky#169]
Picture ses it all.
![screenshot_2016-02-15-19-19-53](https://cloud.githubusercontent.com/assets/13458191/13058206/96b49ee6-d419-11e5-941d-555be4e40548.png)

**Comment by robske110** [comment]
Known issue
Working...

**Comment by Tolo0** [comment]
Ok cool.

**Comment by robske110** [comment]
Please do reopen

**Comment by thebigsmileXD** [comment]
thats cool.. but whats the bug?

**Comment by Tolo0** [comment]
Really? Can u not see in the picture 😅

**Comment by thebigsmileXD** [comment]
The hearts aren't intended to be there?

**Comment by Tolo0** [comment]
Nope. No effects on. Every player logged on with that many hearts.

**Comment by thebigsmileXD** [comment]
Never had that issue lol

**Comment by Tolo0** [comment]
It was on build 115

**Comment by thebigsmileXD** [comment]
Sooo.. gone?

**Comment by Tolo0** [comment]
I'm not sure if it's gone.. Aodzip reopened it. So I guess not.

**Comment by robske110** [comment]
This is 0.14

**Comment by Tolo0** [comment]
Latest build for 0.13.2 heart bug is still ther. 
ClearSky-master-#127.phar. is this only happening on my server?
![screenshot_2016-02-16-19-56-10](https://cloud.githubusercontent.com/assets/13458191/13089469/9fa1bfa0-d4e8-11e5-8f63-b15a5fb9f952.png)

**Comment by erkam2002** [comment]
Ip?

**Comment by Tolo0** [comment]
I'm using a old build now lol.

**Comment by Tolo0** [comment]
Could it be a plugin I'm using?

**Comment by thebigsmileXD** [comment]
@Tolo0 send a list okay?

**Comment by Tolo0** [comment]
EssentialsPE v1.1.3, 
ChatCensor v1.4, 
ItemCasePE v1.0.8, 
iProtector v3.1a, 
TimeCommander v2, 
VIPSlots v0.0.4,
 CustomAlerts v1.6, 
BuyCraft v1.2.2, 
PlanB v1.3.0, 
TapToDo v2.2.1, 
SimpleAuthHelper v2.0.1,
 VoteReward v2.1, 
FoodEffect v1.0.0,
 PurePerms v1.2.2, 
EconomyShop v2.0.6, 
MineReset v2.1,
 CombatLogger v1.2.0,
 Alias v1.2.0, 
PureChat v1.3.3, 
EconomySell v2.0.6, 
MyPlot.

**Comment by Tolo0** [comment]
![screenshot_2016-02-17-08-14-41](https://cloud.githubusercontent.com/assets/13458191/13103485/b598c284-d54e-11e5-8b4c-628ffdcd46c3.png)

**Comment by Tolo0** [comment]
I solved the problem. All I had to do was delete the players folder lol alot of unhappy players loosing ther items. But it's fixed 😅

**Comment by thebigsmileXD** [comment]
Hmm.. but not good if everyone looses their stuff

**Comment by robske110** [comment]
Find an NBT-mass programm and mass-reset health

**Comment by Tolo0** [comment]
It's OK the players will get over it lol

**Comment by thebigsmileXD** [comment]
@robske110 Code one ;)

**Comment by robske110** [comment]
Come on, wich f***** language?
