### ISSUE TITLE
ClearSky logo

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#170]
Logo

**Comment by MasterWolf** [comment]
P.S. I am making a new logo for ClearSky team! I think you will like it ^^

**Comment by MasterWolf** [comment]
Logo is ready! Do you like it? If it looks bad i can make another one :)
![dscn0690](https://cloud.githubusercontent.com/assets/15979343/13076173/27cd5a68-d4b9-11e5-9913-f052ee983efc.jpg)

**Comment by thebigsmileXD** [comment]
Uhh.. We have one already but thx xD

**Comment by MasterWolf** [comment]
@thebigsmileXD i know but i think that it is too simple. Can you plz change it to this?

**Comment by robske110** [comment]
To 1: We have an telegram chatroom (will talk with the team...)
To 2: Let's say NO
To 3: It looks old...

**Comment by MasterWolf** [comment]
@robske110 ok thanks for comments! What about logo, i will try to make it more modern xD

**Comment by robske110** [comment]
Use another Font

**Comment by MasterWolf** [comment]
@robske110 is background good?

**Comment by robske110** [comment]
@thebigsmileXD ??

**Comment by MasterWolf** [comment]
@robske110 what about this?
![dscn2j](https://cloud.githubusercontent.com/assets/15979343/13077045/1edd349a-d4bf-11e5-8037-ef610880a423.jpg)

**Comment by aodzip** [comment]
join our telegram group!

**Comment by robske110** [comment]
Even bader

**Comment by MasterWolf** [comment]
@robske110 lol. Wait xD

**Comment by robske110** [comment]
Use this font: Avenir Next

**Comment by MasterWolf** [comment]
@robske110 i havent got it :/
But i am downloading adobe illustrator and maybe i will make something better

**Comment by MasterWolf** [comment]
@robske110 @thebigsmileXD 
What do you think about this logo??
![cslogo](https://cloud.githubusercontent.com/assets/15979343/13082486/928bc586-d4d9-11e5-8136-f67b0cce6bcb.png)

**Comment by robske110** [comment]
Do you even modern?

**Comment by robske110** [comment]
Wait shortly will edit that

**Comment by MasterWolf** [comment]
@robske110 i think this one is better

**Comment by robske110** [comment]
Quite good, but i want to make some edits

**Comment by MasterWolf** [comment]
Just say what to add/remove
i will do it

**Comment by MasterWolf** [comment]
@robske110 tell me when done

**Comment by robske110** [comment]
![928bc586-d4d9-11e5-8136-f67b0cce6bcb](https://cloud.githubusercontent.com/assets/16020100/13083412/3325a408-d4d5-11e5-970e-91245f2ec819.jpg)
HERE

**Comment by robske110** [comment]
Looks more clean

**Comment by robske110** [comment]
But we need clouds

**Comment by MasterWolf** [comment]
ok wait i will try to make clouds

**Comment by MasterWolf** [comment]
but wait. "ClearSky"... Not "CloudSky"

**Comment by robske110** [comment]
hmm

**Comment by robske110** [comment]
![928bc586-d4d9-11e5-8136-f67b0cce6bcb](https://cloud.githubusercontent.com/assets/16020100/13083649/3c58bf82-d4d6-11e5-9d52-604b3a8df2b0.jpg)
This would be it...

**Comment by MasterWolf** [comment]
cool bro!

**Comment by MasterWolf** [comment]
Great job!

**Comment by MasterWolf** [comment]
Publish it

**Comment by robske110** [comment]
Nah the team doesn't want it ...

**Comment by MasterWolf** [comment]
Why??

**Comment by MasterWolf** [comment]
I think that this is great

**Comment by MasterWolf** [comment]
@robske110 ask ClearSky owners for publish it.

**Comment by KubixQ** [comment]
This looks like a painted in pain xdd

**Comment by robske110** [comment]
Look at the last pic

**Comment by MasterWolf** [comment]
@ClearSkyTeam please set this picture as ClearSky Team logo (on github) 
![3c58bf82-d4d6-11e5-9d52-604b3a8df2b0](https://cloud.githubusercontent.com/assets/15979343/13086503/27ee7b2a-d4ec-11e5-88e1-0992dac7fc1b.jpg)
:)

**Comment by thebigsmileXD** [comment]
Nope, your Paint skills are shit.
@KubixQ thanks, i have the same oppinion
