### ISSUE TITLE
Breath when swimming under surface

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#171]
I talked to @aodzip already

You still have the air saved and get damage, but a new timer starts.
You get twice damage when both air things are timed out

**Comment by thebigsmileXD** [comment]
Same when slightly out of water and client already shows new bubbles

**Comment by thebigsmileXD** [comment]
After attributes rewrite: swimming under a surface gives you breath even you should drown.

**Comment by thebigsmileXD** [comment]
Seems fixed in latest MCPE

**Comment by robske110** [comment]
Is this now really fixed?

**Comment by robske110** [comment]
Closing
