### ISSUE TITLE
Test ClearSky performance.

### ISSUE THREAD

**Issue by KubixQ** [ClearSkyTeam/ClearSky#175]
Hey, I changed my server engine to ClearSky, on my server I have 20-50 players, this is not English server but anyone can check performance.
hardpe.pl:19132
(YOU//I CAN DELETE THIS ISSUE [THIS IS ONLY TO ANYONE CAN CHECK PERFORMANCE]

BTW Can ClearSky team create ClearSky gitter chat?

**Comment by aodzip** [comment]
We have telegram group , join it by the invention link in readme.md

**Comment by aodzip** [comment]
And your ClearSky version is outdated. plz update to the latest version

**Comment by KubixQ** [comment]
Okay.
