### ISSUE TITLE
About Mobs

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/ClearSky#177]
When i spawn a mob it says: Mob AI isnt implemented yet!
When and how?

**Comment by MasterWolf** [comment]
Download plugin EntityManager if you want mobs on your server

**Comment by thebigsmileXD** [comment]
I added this once, because players said "Add Mob AI!"
There are plugins for that

**Comment by robske110** [comment]
And we shouldn't add it. Use plugins.

**Comment by MCPEPIG** [comment]
This should be closed, @aodzip

**Comment by aodzip** [comment]
We will finish mobs AI future . But need a long time
