### ISSUE TITLE
RCON Error: Warning: socket_read(): unable to read from socket [104]

### ISSUE THREAD

**Issue by TheKillerTacos** [ClearSkyTeam/ClearSky#178]
So i was trying out some RCON apps on Play store, and after closing connections this happend:

Warning: socket_read(): unable to read from socket [104]: Connection reset by peer in phar:///home/big/Desktop/ITLobby/PocketMine-MP.phar/src/pocketmine/network/rcon/RCONInstance.php on line 42

So, any fix for that, idk what happend

**Comment by TheKillerTacos** [comment]
Here is the "bad" code...:
`private function readPacket($client, &$size, &$requestID, &$packetType, &$payload){
		socket_set_nonblock($client);
		$d = socket_read($client, 4);
		if($this->stop === true){
			return false;
		}elseif($d === false){
			return null;
		}elseif($d === "" or strlen($d) < 4){
			return false;
		}
		socket_set_block($client);
		$size = Binary::readLInt($d);
		if($size < 0 or $size > 65535){
			return false;
		}
		$requestID = Binary::readLInt(socket_read($client, 4));
		$packetType = Binary::readLInt(socket_read($client, 4));
		$payload = rtrim(socket_read($client, $size + 2)); //Strip two null bytes
		return true;
	}
`

**Comment by aodzip** [comment]
Will this crash server, I think this is an unpack issue caused by ubstable connection

**Comment by TheKillerTacos** [comment]
The Server didnt crashed, let me connect via MCRcon app, and then disconnect, and show you a pic of the server log...

**Comment by TheKillerTacos** [comment]
i thnk you meant uNstable, no ubstable, so i think it was that, Tried to do it again, and nothing bad happend, closing...
