### ISSUE TITLE
Low rendering distance

### ISSUE THREAD

**Issue by NML32** [ClearSkyTeam/ClearSky#180]
Running ClearSky build #33 (0.14) with default pocketmine.yml that was created with Build#33.
Very low render distance and they seem to load only 4-6 chunks at a time.
Please tweak and optimize. 

Thanks

**Comment by TheKillerTacos** [comment]
I have the same problem, they "Fixed it" either they "added" more rendering distance, for me its the same render distance, wait for @aodzip

**Comment by Landy005** [comment]
Same problem. Hope this is the first thing they'll adjust.

**Comment by robske110** [comment]
Duplicated lol
