### ISSUE TITLE
Light update fails often after Server restart

### ISSUE THREAD

**Issue by robske110** [ClearSkyTeam/ClearSky#182]
Espacially with Redstone Lamps (But flowstone and torches have the same bug)
They just don't update the light level. Not much to say.
Here are some pics: (Wait, there will be some in a few minutes)

**Comment by PocketKiller** [comment]
Confirmed.

**Comment by thebigsmileXD** [comment]
Confirmed, 2.

**Comment by robske110** [comment]
Here its confirmed, in telegram you were like 'Let's ignore him' :P

**Comment by thebigsmileXD** [comment]
I said: Never when you asked about a fix

**Comment by robske110** [comment]
Ok then we're never gonna see an fix :P

**Comment by aodzip** [comment]
This should fixed in recent commit

**Comment by robske110** [comment]
@aodzip
Always refereence the commit please

**Comment by thebigsmileXD** [comment]
Thats why we name the commits.. Not like genisys

**Comment by robske110** [comment]
It wasn't named
Stil did not find it

**Comment by robske110** [comment]
And the issue still exists! PLEASE REOPEN

**Comment by aodzip** [comment]
I dont have this bug anymore

**Comment by thebigsmileXD** [comment]
I do

**Comment by aodzip** [comment]
Why......Why I dont have these bug

**Comment by robske110** [comment]
Do you use the jenkins version?

**Comment by robske110** [comment]
And again:
PLEASE LINK ME THE COMMIT WICH FIXED THIS

**Comment by aodzip** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/94d488794d03588d878204be43500dc76a20aae4

this one , and I tested jenkins phar , no bug
