### ISSUE TITLE
Some World's Aren't Working

### ISSUE THREAD

**Issue by BobbyTowers** [ClearSkyTeam/ClearSky#183]
I just updated my server to the latest 0.14.0 build #142 All of my world's worked fine in 0.13.2 but now when moving to a different world it just doesn't load. The only world that seems to load is the main spawn world.

**Comment by robske110** [comment]
Whats happening?
Is it just don't transferring you? Or are you in white space?

**Comment by BobbyTowers** [comment]
Yeah it just won't transfer and then my client crashes.

**Comment by BobbyTowers** [comment]
I think this is because of a lighting issue like #182 and the reason why #184 cant join.

**Comment by XxDXM-hippiexX** [comment]
Pc map?..i had to convert my map

**Comment by BobbyTowers** [comment]
I converted the only two PC maps I use. I never had any problems before 0.14.0

**Comment by XxDXM-hippiexX** [comment]
same here..works after the conversion tho :p

**Comment by BobbyTowers** [comment]
Trying to reconvert it again.

**Comment by BobbyTowers** [comment]
Yeah converting it again worked.

**Comment by TheKillerTacos** [comment]
if it worked, then close this issue... please.
