### ISSUE TITLE
0.14 blocks/items

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#185]
When maps, slimeblocks, repeaters and all 0.14 items and blocks will be added to clearsky?
And i want to say THANK YOU for this amazing project and i think that this is really the best server software for MCPE!

**Comment by TheKillerTacos** [comment]
Redstone stuff is still being optimized and created by @aodzip and Slimeblocks, i think they should implement that, the fishing rod is still wip, and other objects still on waiting to be created

**Comment by MasterWolf** [comment]
ok thx for info

**Comment by thebigsmileXD** [comment]
Red sandstone and all variants are in, slime block also
