### ISSUE TITLE
Extra Inventory Slots With Permissions

### ISSUE THREAD

**Issue by BobbyTowers** [ClearSkyTeam/ClearSky#186]
I noticed the in the new build #144 you could add more inventory slots in the pocket mine config. Is there anyway you could add permissions to get more slots? Something like pocketmine.inv.extra.3 or something like that.

**Comment by Adam1609** [comment]
let's wait for the next update. At first keep enjoying ur inventory slot okay?

**Comment by BobbyTowers** [comment]
I'm not in a rush. Just asking for a new feature.

**Comment by MasterWolf** [comment]
thx for this awesome thing! its very cool feature ^^

**Comment by robske110** [comment]
@BobbyTowers We may create an plugin API for that :)

**Comment by XShockinFireX** [comment]
That would be cool!

**Comment by BobbyTowers** [comment]
@robske110 Awesome

**Comment by aodzip** [comment]
We *MAYBE* add API for this

**Comment by robske110** [comment]
Didn't i wrote that

**Comment by thebigsmileXD** [comment]
I think i will remove this. Maybe an api to set max slot size. But really.. There is "addCreativeItem". Maybe doing that for survival as api, but anyways, all this should be plugin side.
