### ISSUE TITLE
Chunks dont load in 0.14

### ISSUE THREAD

**Issue by darkspive** [ClearSkyTeam/ClearSky#187]
Please fix it. Dev of genisys said that it is batchet packet.

**Comment by BobbyTowers** [comment]
My load just fine.

**Comment by Adam1609** [comment]
my sv load fine. pls check if u use pc map

**Comment by darkspive** [comment]
I use pc map

**Comment by aodzip** [comment]
try latest build

**Comment by MasterWolf** [comment]
in latest build all is fixed. chunks are loading as fast as a rocket!!

**Comment by MCPEPIG** [comment]
It works, @aodzip

**Comment by thebigsmileXD** [comment]
Does not.. Latest phar.. And sometimes they just wont load. Sometimes /gc forces them to load.. Many times not
