### ISSUE TITLE
client crash

### ISSUE THREAD

**Issue by Tolo0** [ClearSkyTeam/ClearSky#191]
It seems some items are making the client crash and everyone around.  Post any items you find. So they can be fixed.
Aodzip discovered item splash potion of harming.

**Comment by MasterWolf** [comment]
Any boat crashes server! (Not client)

**Comment by TheKillerTacos** [comment]
Enchantment table, it used to crash on 0.13.*, but in the 0.14.0 Doesntt shows anything, (Client)

**Comment by thebigsmileXD** [comment]
Yea.. Enchanting table shows brewing stand for a second, brewing stand shows.. Furnace i think.. I posted in our Telegram group. Furnace=NOTHING

**Comment by robske110** [comment]
I don't see the point of this issue
