### ISSUE TITLE
Can't open containers in creative 

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#192]
You can't open chests, furnaces, etc in creative.

**Comment by TheKillerTacos** [comment]
What did you espected? but opening chests would be good,

**Comment by aodzip** [comment]
In 0.14.0 client , it should open containers , new game rule

**Comment by MCPEPIG** [comment]
There is code to disable doing it in creative in the classes...

**Comment by Pub4Game** [comment]
fixed #231
