### ISSUE TITLE
SetEntityLinkPacket not working

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#194]

**Comment by aodzip** [comment]
The Boat seems work fine ,

**Comment by MCPEPIG** [comment]
Strange...

**Comment by MCPEPIG** [comment]
Yep it works for boats but doesn't work for other entities anymore. :/

**Comment by thebigsmileXD** [comment]
Its because.. @aodzip remember that think when i linked player to fishing hook? Thats why they removed this. Theres a new package.. Riding.. Havent found it yet
