### ISSUE TITLE
Chunk Radius Packet

### ISSUE THREAD

**Issue by robske110** [ClearSkyTeam/ClearSky#195]
We need to add the packet (more details below!)

**Comment by robske110** [comment]
So they unload too near

**Comment by Landy005** [comment]
I have the same problem.

**Comment by robske110** [comment]
Issues on org pocketmine come up too

**Comment by robske110** [comment]
Looks like Client ISSUE

**Comment by robske110** [comment]
But think we can fix that

**Comment by robske110** [comment]
@PEMapModder Just checked with MiNET. Yes, MCPE 0.14 adds Chunk Radius (New packet).

Packet: 0xc9

It's sent by the server, not the client.

And the fields are: Name, Type, Size, Chunk radius, & int.

**Comment by robske110** [comment]
https://github.com/PocketMine/PocketMine-MP/issues/3931#issuecomment-188327049

**Comment by MasterWolf** [comment]
for me all is ok

**Comment by thebigsmileXD** [comment]
I have a vanilla server with latest yml. when they unload they never load again.

**Comment by Landy005** [comment]
how come it works for masterwolf then?

**Comment by thebigsmileXD** [comment]
This packets are related to the Map-item, but i think this also does affect chunk loading i guess

**Comment by robske110** [comment]
They're only related to chunks, as far as i know

**Comment by Landy005** [comment]
does this mean it's solved?

**Comment by SalmonGER** [comment]
@Landy005 I think so. It's fixed for me.

**Comment by thebigsmileXD** [comment]
Nope

**Comment by Landy005** [comment]
@SalmonGE What build do you use and what is your render distance?

**Comment by MasterWolf** [comment]
my is 6

**Comment by robske110** [comment]
@thebigsmileXD mind reopening
I'll take a deep look at other repos

**Comment by thebigsmileXD** [comment]
The packet itself is done.. also on my server all works fine, but on the test server not..

**Comment by robske110** [comment]
So the complete lobby loads

**Comment by thebigsmileXD** [comment]
@robske110 well.. on the official one. Not on the vanilla one

**Comment by Landy005** [comment]
is genisys atm the only one who got chunks fixed?

**Comment by robske110** [comment]
We're still working here

**Comment by Landy005** [comment]
I really need it though, my server is unplayable atm because chunks not loading.

**Comment by robske110** [comment]
Fixed in 255

**Comment by Landy005** [comment]
i love you @thebigsmileXD pls i owe you my life <3

**Comment by thebigsmileXD** [comment]
Love @aodzip he fixed it
