### ISSUE TITLE
Crafting bug

### ISSUE THREAD

**Issue by twilightsay** [ClearSkyTeam/ClearSky#197]
Player can't decomposition diamond block and other can decomposition blocks.

**Comment by thebigsmileXD** [comment]
You mean.. Break?

**Comment by robske110** [comment]
No they cannot craft diamond block to 9 diamonds

**Comment by Adam1609** [comment]
sometime the crafting is wrong, only 1 wood and 3 wools? come on!!!

**Comment by twilightsay** [comment]
This bug now fixed.but break block
