### ISSUE TITLE
TNT Lags

### ISSUE THREAD

**Issue by XFuryMCPE** [ClearSkyTeam/ClearSky#198]
TNT Lags so badly... The server freezes for 4-5 seconds before it explodes

**Comment by thebigsmileXD** [comment]
I confirm.. It took 1:30 hours for 5000 tnt to explode..

**Comment by robske110** [comment]
Redstone

**Comment by aodzip** [comment]
I dont have this issue

**Comment by TheKillerTacos** [comment]
I gave this issue, IT FREEZES the server with 5 tnts, or more,

**Comment by SuperDude36** [comment]
Maybe get a better computer or allow more space.

**Comment by Landy005** [comment]
4000 mb space and tnt still freezes so more space isn't really the case i think

**Comment by SuperDude36** [comment]
Could just be old hardware...

**Comment by TheKillerTacos** [comment]
intel i3 fifth generation, 16Gbs of ram, 256 SSD Samsung disk, ASUS Motherboard? I dont internet might be the problem, but 10Gb connection (yea, thats possible for customers at my country)

**Comment by Aericio** [comment]
How much would 10gb internet cost 0.0 Anyways my server only starts to lag when 100+ tnt is lit. It crashes when around 1000 tnt has exploded.

**Comment by thebigsmileXD** [comment]
tested 50000 tnt. 1 hour 55 minutes processing

**Comment by thebigsmileXD** [comment]
Closed because we cant fix that. They are entities

**Comment by Aericio** [comment]
Okay.
