### ISSUE TITLE
Server Outdated

### ISSUE THREAD

**Issue by wiligangster** [ClearSkyTeam/ClearSky#199]
Problem with the version I have message with "Oops Server Outdated" please fix the problem I have 0.14.0

**Comment by PocketKiller** [comment]
set custom alerts outdated message to false.

**Comment by wiligangster** [comment]
Hmmmm... Okay thank And sorry .... I Love you <3

**Comment by thebigsmileXD** [comment]
And read the readme :)

**Comment by wiligangster** [comment]
:O okay thank I Love the version :')
