### ISSUE TITLE
Golden Apple doesnt work fix please .

### ISSUE THREAD

**Issue by wiligangster** [ClearSkyTeam/ClearSky#200]
I have problem with golden apple please fix

**Comment by thebigsmileXD** [comment]
> I have problem with golden apple

Which would be? We can't fix what we do not know.

**Comment by TheKillerTacos** [comment]
The OP apple (Super Golder Apple works) works

**Comment by thebigsmileXD** [comment]
they both work for me

**Comment by wiligangster** [comment]
Work sorry mistake .
