### ISSUE TITLE
glitch in 0.14 and enchant not working

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/ClearSky#202]
Something happened when i drop an item in creative mode and get it. It has gltich.
And enchant is not working either, please check if it's okay

**Comment by MasterWolf** [comment]
Enchant is working for me.

**Comment by Aericio** [comment]
They said enchants can be used but its using a command, not with the enchant books.

**Comment by TheKillerTacos** [comment]
Enchants on the Enchanting Table? since i know it doenst works?

**Comment by thebigsmileXD** [comment]
only /enchant
