### ISSUE TITLE
Server Crash Error: Out of memory

### ISSUE THREAD

**Issue by NML32** [ClearSkyTeam/ClearSky#204]
Build#163
ClearSky Crash Dump Sat Feb 20 17:20:27 EST 2016

Error: Out of memory (allocated 1108344832) (tried to allocate 268435456 bytes)
File: /src/pocketmine/level/Level
Line: 2
Type: E_ERROR

**Comment by Adam1609** [comment]
Please check if ur memory r full

**Comment by thebigsmileXD** [comment]
Correct, you are out of memory.
