### ISSUE TITLE
About break blocks bug

### ISSUE THREAD

**Issue by twilightsay** [ClearSkyTeam/ClearSky#205]
Player break blocks,can't show blocks break particle.

**Comment by MCPEPIG** [comment]
and no sound...

**Comment by xpyctum** [comment]
maybe mcpe issue

**Comment by thebigsmileXD** [comment]
@xpyctum Nope.. don't think so.

**Comment by MCPEPIG** [comment]
It's not a MCPE issue. Just checked

**Comment by Pub4Game** [comment]
i fix it :D #205

**Comment by thebigsmileXD** [comment]
@Pub4Game how? Wait.. have you made a pr?

**Comment by aodzip** [comment]
I have merged lol
