### ISSUE TITLE
Signs are always clearing

### ISSUE THREAD

**Issue by SURVAml** [ClearSkyTeam/ClearSky#209]
Old bug is there again, if you write signs, they are clearing.
Only sometimes, you can write a sign.
I think 3 of 4 signs are clearing.

**Comment by thebigsmileXD** [comment]
I do not have that issue.. its mostly caued by lag

**Comment by SURVAml** [comment]
Maybe, but it wasn't there before

**Comment by TheKillerTacos** [comment]
No, thats not the problem, if you have a Area protector (iProtector, and those) it will bug, disable the plugin or unprotect the land, since Protector plugins sometimes bugs when OPs build signs, (it happend to me)

**Comment by SURVAml** [comment]
@TheKillerTacos Maybe WorldProtect? Would be difficult to remove because it's the lobby. I'll do some tests.

**Comment by thebigsmileXD** [comment]
Its not WorldProtect. And as long as i know Surva doesn't have myplot either.

**Comment by SURVAml** [comment]
We have MyPlot, but it's no plot world where I'm trying it.

**Comment by thebigsmileXD** [comment]
But myplot has problems with world assigning.

Like: water+lava flowing disabled In all worlds

I have a fixed version.. That atleast fixed the water and lava. And some other things

But it runs mysql. Also /p auto will clear the owner of the plot you are teleported to

**Comment by SURVAml** [comment]
MySQL should be no problem. When you're talking about bugs with water and lava, maybe BanItems could be the reason. But I can try the fixed version on the server.

**Comment by thebigsmileXD** [comment]
@SURVAml water flow was the reason of MyPlot ;) After removing, it flows in all worlds again
