### ISSUE TITLE
Paintings make you crash

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#21]
Title says everything

**Comment by aodzip** [comment]
confirmed

**Comment by thebigsmileXD** [comment]
Better letting the client crash than the server. That happened before. Paintings do not work at all.

**Comment by MCPEPIG** [comment]
AddPaintPacket not AddEntityPacket... Quit using AddEntityPacket for paintings.

**Comment by thebigsmileXD** [comment]
Which will crash the server.

**Comment by thebigsmileXD** [comment]
"AddPaintingPacket could not be converted to int"

**Comment by aodzip** [comment]
in which file?

**Comment by aodzip** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/ad449d62f27ee1f858f0e11c7765e4ed84dcf9de

See this , one of the "cant convert to int" is cause by there is a "-" behand $pk

**Comment by thebigsmileXD** [comment]
What the actual.. How can this happen lol

**Comment by thebigsmileXD** [comment]
Fixed
