### ISSUE TITLE
0.14 does not exists in all branch and in jenkins!!! Sorry for dublicate!!! Please fix it!!!

### ISSUE THREAD

**Issue by darkspive** [ClearSkyTeam/ClearSky#210]
Version of php7 = 3x it is 0.13 please fix to 0.14 and fix login packet. 
Pleeeeeeease!!!

**Comment by robske110** [comment]
Use the master branch

**Comment by MasterWolf** [comment]
@darkspive 0.14 branch = master branch

**Comment by VonHirsch** [comment]
Change current protocol to 45
https://github.com/ClearSkyTeam/ClearSky/blob/master/src/pocketmine/network/protocol/Info.php#L13
