### ISSUE TITLE
Hotbar switches around when picking up items (sometimes)

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#212]

**Comment by HuaYoyuDoge** [comment]
hmm,is fix at genisys
see this
https://github.com/iTXTech/Genisys/commit/2bbac340da8b9f9267651a6cbdcdf909dfb7c910

**Comment by thebigsmileXD** [comment]
Thx, was on my todo for a while but forgot about that

**Comment by HuaYoyuDoge** [comment]
:D

**Comment by HuaYoyuDoge** [comment]
so when u fix this?

**Comment by HuaYoyuDoge** [comment]
jk, sorry about this my bad can i help u ?
