### ISSUE TITLE
Pop sound plays Click sound instead

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#215]

**Comment by TheKillerTacos** [comment]
You should make a WHOLE LIST OF ALL YOUR ISSUES! you just made 15 (11 latest one) and just hate to see too many issues on clearsky

**Comment by aodzip** [comment]
One bug one issue.
It is good.

**Comment by TheKillerTacos** [comment]
Ok, but this issue isnt Client side bug?

**Comment by thebigsmileXD** [comment]
No

**Comment by SkygridRex** [comment]
Network bug?

**Comment by robske110** [comment]
Close?
