### ISSUE TITLE
Missing Blocks & Items List

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#217]
# Items / Blockitems:
- [ ] Written Maps with data
# Blocks:
- [x] Dispenser (Bonemealing)
- [x] Observer (Update fixes)
- [ ] Repeater
- [ ] Comparator
- [x] Hopper (implement item transportation)
- [ ] Cauldron
- [ ] MobSpawner
- [ ] Pistons
# Entities:
- [x] TNT-Minecart //TODO: Explosion
- [x] Hopper-Minecart //TODO: inventories
- [x] Chest-Minecart //TODO: inventories

**Comment by robske110** [comment]
Redstone items (the new ones)

**Comment by thebigsmileXD** [comment]
@robske110 have i got all?

**Comment by MCPEPIG** [comment]
What about new Minecart types?

**Comment by thebigsmileXD** [comment]
@MCPEPIG added.

**Comment by Landy005** [comment]
Does coloring your water works ?

**Comment by thebigsmileXD** [comment]
You mean cauldrons with potions. Not yet

**Comment by Landy005** [comment]
Oh okay, when do you think chunks will be fixed? I'm planning to make a cinematic of https://twitter.com/sb_server soon on the server.

**Comment by robske110** [comment]
the chunk-unload-too-fast issue :package:

**Comment by thebigsmileXD** [comment]
"Missing blocks and item list"
"The chunk unload too fast issue"

-.-" MAN!

**Comment by MCPEPIG** [comment]
You forgot cauldron, camera (New secret feature, & yes, it's back!), enderpearl (Also new secret feature), & witch spawn egg

**Comment by thebigsmileXD** [comment]
@MCPEPIG EnderPearls are already done ;) Did them in 0.13 already

**Comment by MasterWolf** [comment]
@thebigsmileXD nice work!

**Comment by MasterWolf** [comment]
@MCPEPIG how can i get ender pearl? do you knpw id?

**Comment by thebigsmileXD** [comment]
Updated

**Comment by MasterWolf** [comment]
cool! So can i spawn witch using egg?

**Comment by thebigsmileXD** [comment]
Sure, i am about to upload

**Comment by Landy005** [comment]
what do you know about why the chunks aren't loading or glitching? And if it's really because the mojang dev's touched the load chunk type, won't they fix it soon anyway? Since it's such a big problem.

**Comment by MasterWolf** [comment]
@Landy005 What? Chunks? I know that it was fixed fev days ago. On my server chunks are loading with rocket speed!

**Comment by thebigsmileXD** [comment]
@Landy005 @MasterWolf wrong issue!!!

**Comment by Landy005** [comment]
I know, sorry

**Comment by Landy005** [comment]
Do you think about adding paintings too in the future?

**Comment by MasterWolf** [comment]
@Landy005  its already added!

**Comment by Landy005** [comment]
Is there a way where i can contact you masterwolf besides here?

**Comment by MasterWolf** [comment]
@Landy005 yes. i have twitter and gitter.

**Comment by Landy005** [comment]
Whats your twitter

**Comment by MasterWolf** [comment]
@MineTournaments

**Comment by MasterWolf** [comment]
its my twitter

**Comment by thebigsmileXD** [comment]
You really spam this issue. I wanted to keep it clean

**Comment by MasterWolf** [comment]
ok sorry

**Comment by TheKillerTacos** [comment]
Well, Delete the useless comments :P

**Comment by Aericio** [comment]
How long do you think these will take? (i'll delete comment after to reduce spam)

**Comment by thebigsmileXD** [comment]
@MCPEPIG The EnderPearl item has no texture in MCPE.

**Comment by thebigsmileXD** [comment]
Updated

**Comment by Landy005** [comment]
maps is enabled above but yet it doesn't work for me?

**Comment by Landy005** [comment]
i do 'create map' yet nothing happens and i keep having the map item in my hands from where you take it in your inventory.

**Comment by Landy005** [comment]
maps don't work for me?

**Comment by thebigsmileXD** [comment]
Updated

**Comment by Landy005** [comment]
ty fam

**Comment by Landy005** [comment]
In the new build or the previous one?

**Comment by thebigsmileXD** [comment]
-.-" in the issue list up there
^^^^^^^^^^

**Comment by thebigsmileXD** [comment]
Updated

**Comment by robske110** [comment]
Updated

**Comment by robske110** [comment]
Ticked  Observer and Hopper

**Comment by thebigsmileXD** [comment]
@robske110 Ticking without doing anything? Now i see why i have such leveltick overload..

**Comment by robske110** [comment]
-_-
I hope you weren't serious

**Comment by thebigsmileXD** [comment]
@robske110 i actually experience a really high level tick lag on my creative world.

**Comment by thebigsmileXD** [comment]
Aren't cauldrons already fully working?

**Comment by thebigsmileXD** [comment]
Finally again: updated

**Comment by XtremePlayzCODE** [comment]
ooh i think i might know chest-minecart inventory implementation
