### ISSUE TITLE
Containers open wrong inventory

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#218]
brewing stan = anvil invi
Enchanting table = brewin invi
oven is oven
anvilis nothing
redstone chest says "Chest" as title

**Comment by MasterWolf** [comment]
LOL!

**Comment by thebigsmileXD** [comment]
redstone chest says "Chest" as title
Enchanting table -> closes

**Comment by thebigsmileXD** [comment]
Cant open dispenser hopper dropper brewing stand.
Others are fixed.

**Comment by thebigsmileXD** [comment]
registerTile in server.php
