### ISSUE TITLE
Boats are invincible

### ISSUE THREAD

**Issue by SalmonGER** [ClearSkyTeam/ClearSky#220]
I can't destroy boats. They also don't break when they fall out of the world.

**Comment by MasterWolf** [comment]
Same problem

**Comment by ItzQuiet** [comment]
@SalmonGER Hab dich gewhitelistet, kannst drauf :D

**Comment by Efforto** [comment]
+1，i have a lot of useless boats in my server....QAQ

**Comment by thebigsmileXD** [comment]
Some times they break.. idk why. its really rare

**Comment by MasterWolf** [comment]
I have about 50 boats on my server!

**Comment by thebigsmileXD** [comment]
Got it.. InteractPacket:LEFT_CLICK and right click.. nice xD

I'll make boats vincible later

**Comment by thebigsmileXD** [comment]
https://github.com/PocketMine/PocketMine-MP/commit/6945256e30ea5e4b807f27ccf4481581cb74897d

**Comment by robske110** [comment]
Fixed

**Comment by SalmonGER** [comment]
Same for me. When I destroy them and rejoin they disappear.

**Comment by thebigsmileXD** [comment]
Is it really fixed? Got no time to test

**Comment by SalmonGER** [comment]
@thebigsmileXD Nvm boat came back after server restart. xD

**Comment by thebigsmileXD** [comment]
They break but don't despawn, right?

**Comment by thebigsmileXD** [comment]
:confounded::sweat:i know why
