### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#221]
When update CS to newer build, its creating new config.yml and I must to setup everything again... How to solve this problem?

**Comment by thebigsmileXD** [comment]
You set:
config-update: true
 #Whether the server should "try" to add new configs automatically here

to 

config-update: false
 #Whether the server should "try" to add new configs automatically here

**Comment by MasterWolf** [comment]
@thebigsmileXD thanks, really worked!

**Comment by thebigsmileXD** [comment]
@MasterWolf Thats what it is for ;)

**Comment by robske110** [comment]
I'm feeling i wrote those comments for nobody...
