### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by XiangZhao969** [ClearSkyTeam/ClearSky#225]
My server is running #182, players can't join. in the console, it said players logged out due to client disconnect, and QueryFacade + CombinedSlots "fail to receive challenge". What causing this?

**Comment by XiangZhao969** [comment]
And raklib keep blocking ips...

**Comment by thebigsmileXD** [comment]
Update

**Comment by XiangZhao969** [comment]
Nothing changed...

**Comment by aodzip** [comment]
If you can enable debug mode and get the info provide from RakLib . That will helpful.
Before you do this , I will keep this issue close
