### ISSUE TITLE
Problem with map (pocketmine.yml file)

### ISSUE THREAD

**Issue by kaitododoyt** [ClearSkyTeam/ClearSky#226]
when i use the last .phar file, this create new pocketmine.yml and the map dont charge full, then when i use pocketmine.yml backup (renamed, and changed version 9 to 11) this work great, the map is full charged. What is the problem with new file?

**Comment by MasterWolf** [comment]
Duplicated
#221

**Comment by aodzip** [comment]
Can you provide your "Work Well" yml here ?
ANd you can set config-update: true to false to prevent this .

**Comment by MCPEPIG** [comment]
This should be closed. The problem is that the PocketMine.yml was outdated. To disable it from updating itself, set config-update to false.
