### ISSUE TITLE
World not Load 

### ISSUE THREAD

**Issue by Christian665** [ClearSkyTeam/ClearSky#228]
my World not Load !
but dont a new world  .... my OLD world with BUILDS
i can fly in one direction and my world load.
change i the direction the world stop load !
i fly in a invicible wall ! 

i log out .... log in .... and i can fly in a other direction.

why ?    for 2 weeks with 0.13.2 i have no problem

**Comment by aodzip** [comment]
I can confirm this

**Comment by MCPEPIG** [comment]
Chunks are unloading too fast.

**Comment by TheKillerTacos** [comment]
CONFIRMED, they Unload fast, i tried changing config stuff, didnt work, my lobby looks really bad with this bug and low renderview, i dont want to switch to Genisys. :L

**Comment by thebigsmileXD** [comment]
In vanilla, they unload and then don't reload anymore

**Comment by BobbyTowers** [comment]
Build #225 didn't fix the problem.

**Comment by Aericio** [comment]
On a server, all you need to do is /spawn then /back so that chunk refreshes the area... But it gets annoying doing that EVERY time it doesn't load (thats what I do)
