### ISSUE TITLE
Phar for 0.14.x

### ISSUE THREAD

**Issue by ItzQuiet** [ClearSkyTeam/ClearSky#229]
I have problems with the scr File. Can you upload a phar File?

**Comment by BobbyTowers** [comment]
You need to learn to read the front page http://jenkins.clearskyteam.org/job/ClearSky/

**Comment by TheKillerTacos** [comment]
Please Close the Issue, AND always read the README.md files, there might be useful information,

**Comment by ItzQuiet** [comment]
I search a phar for php7. This work on php5

**Comment by TheKillerTacos** [comment]
Check at Jenkins. it says PHP7 or something.
