### ISSUE TITLE
Sometimes failed queries

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#238]
Sometimes http://minecraftpocket-servers.com says that server is offline but its online.

**Comment by thebigsmileXD** [comment]
Well, its a load issue.

**Comment by thebigsmileXD** [comment]
*performance.

**Comment by MasterWolf** [comment]
@thebigsmileXD ok so will you fix it?

**Comment by thebigsmileXD** [comment]
I cant fix the power of your server. Its overloaded

**Comment by MasterWolf** [comment]
But wait. I think ClearSky need some optimization. When i was using ImagicalMine, everything was good with query.

**Comment by jazzwhistle** [comment]
I've having the same problem with all PM versions since the 0.14 update, and server power and connectivity are not the problem

**Comment by MasterWolf** [comment]
yes. since 0.14 ...

**Comment by jazzwhistle** [comment]
The stats from minecraftpocket-servers.com shows that this month about 1 in 6 requests failed, but previous months were less than 1 in 10, and often much rarer.
![screen shot 2016-02-24 at 16 46 54](https://cloud.githubusercontent.com/assets/10437212/13291046/9ea29168-db16-11e5-871a-b9796707e33e.png)

**Comment by MasterWolf** [comment]
@jazzwhistle i have same statistics. So @thebigsmileXD maybe its CS problem? I tested it on very powerful pc and it never says "server is overloaded"...

**Comment by TheKillerTacos** [comment]
Try using other Servers lists, or use banners, it might be MCPE Server List getting buggy?

**Comment by MasterWolf** [comment]
@TheKillerTacos its on all server lists...

**Comment by MasterWolf** [comment]
Fixed! I just changed some settings in pocketmine.yml :)

**Comment by jazzwhistle** [comment]
Maybe you could share the answer?!

**Comment by MasterWolf** [comment]
@jazzwhistle i given it more RAM, disabled log to file and increased network speed!
