### ISSUE TITLE
Problem with PHP7 Binaries on Linux

### ISSUE THREAD

**Issue by jazzwhistle** [ClearSkyTeam/ClearSky#239]
Hi, I'm having problems with clearsky php7 builds on a CentOS7 CLI dedicated server - I'm using the ClearSky 7.0.2 x64 PHP binaries, but get an "Out Of Memory" error before the new pocketmine.yml is even created, despite having plenty of available RAM. After some testing I realized that even ./php -v gives the same Out Of Memory" error... I've tried using the official pocketmine version of PHP7 that I compiled, but ClearSky complains about "missing weakref", as it does when using the Genisys binaries too. Any ideas? Thanks

**Comment by aodzip** [comment]
you need compile by yourself if you want use .

**Comment by jazzwhistle** [comment]
Ok, I couldn't find a clearsky PHP7 compile script, and assumed the Jenkins
binaries would work if I edited php-config... Since official and Genisys
builds no longer use weakref, is there a PHP7 install script that you
recommend?

Thanks

**Comment by dterweij** [comment]
@jazzwhistle use PHP7 from REMI repository. Install also from REMI pthreads and weakref extentions. Then start Clearsky with the zts-php binary.  # zts-php ./ClearSky.phar
Works 100% and no problems.

**Comment by aodzip** [comment]
https://github.com/PocketMine/php-build-scripts/
you can find wht you need here
