### ISSUE TITLE
Major issues?

### ISSUE THREAD

**Issue by legoboy0215** [ClearSkyTeam/ClearSky#24]
Are there any major issues? I want to use it in my production server. Also, do all switches work? I do not want EXP and rain so...

**Comment by aodzip** [comment]
All swich is work

**Comment by aodzip** [comment]
Major issue ... just see issue tracker

**Comment by aodzip** [comment]
And , weather is rewritten ... dont worry abot too much rain.  And it is configable in pocketmine.yml

**Comment by legoboy0215** [comment]
Thanks :) I will let you know if it works out :)
