### ISSUE TITLE
[Question/Idea] Send private messages of players to OP's and logger

### ISSUE THREAD

**Issue by alex2534alex** [ClearSkyTeam/ClearSky#241]
Can u realise this idea? Also add permission for this: ".seemsg" or somesing like this.

**Comment by MasterWolf** [comment]
here is plugin SocilaSpy for this.

**Comment by alex2534alex** [comment]
But what about to do native support? I mean built-in feature

**Comment by MasterWolf** [comment]
good idea

**Comment by thebigsmileXD** [comment]
You know why they are called "Private" Messages, right?

**Comment by MasterWolf** [comment]
@thebigsmileXD ahahahaha. But yeah you are right. other players must not know others private messages!

**Comment by alex2534alex** [comment]
Ohhhhh. Just do enabler in pocketmina.yml . And sometimes players want to griff
other players, and they discuss it in
private messages. Also, it will help
administrators learn a lot of good
and bad about the players, so it is
very important

**Comment by MasterWolf** [comment]
@alex2534alex its good but if someone will tell his phone number in private messages? Its as same as you will know all private information about me...

**Comment by MasterWolf** [comment]
@alex2534alex but if you want to do this, just use plugin. I think CS team wont do this.

**Comment by alex2534alex** [comment]
Ohh, OK...

**Comment by Aericio** [comment]
A plugin like CommandTracker can track all their commands and private messages... But it can start to spam console unless you make it log to file but then you'll need to click that log file to see their messages. With this plugin you can only see it in console, not in game which is sad :(
