### ISSUE TITLE
Beds . . .

### ISSUE THREAD

**Issue by ScandiePlay** [ClearSkyTeam/ClearSky#248]
I tried to make a bed, but I couldn't craft. So whatever, I gave it to myself, but this time I couldn't place it. I placed - it returns back to the invemtory.

**Comment by thebigsmileXD** [comment]
Any messages in the console?

**Comment by ScandiePlay** [comment]
No errors, no messages about this.

**Comment by Aericio** [comment]
Beds work for me... Is it a plugin that isn't allowing you to do that?
(I am using the latest version of ClearSky)

**Comment by ScandiePlay** [comment]
Sorry, guys. Bed, that was bought in EconomyShop, doesn't work. But given bed works perfectly.
