### ISSUE TITLE
Crash on weather clear

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#25]
Fatal error: Call to undefined method pocketmine\level\Level::setRaining() in phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/WolvesFortressIM/ClearSky_1.0dev.         phar/src/pocketmine/command/defaults/WeatherCommand.php on line 51

**Comment by aodzip** [comment]
Due to rewrite .. also happened in exp before XD

**Comment by aodzip** [comment]
WIP

**Comment by aodzip** [comment]
fixed
