### ISSUE TITLE
Chuks unload client side only

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ClearSkyTeam/ClearSky#250]
So the chunks loading/unloading is better than ever but they seem to only unload on the client side. Used /status to come to this conclusion XD could using cache chunks cause this?

**Comment by TheKillerTacos** [comment]
No, is the New packet from 0.14.0, we should wait for a 0.14.1 release?

**Comment by robske110** [comment]
Fixed with the packet i think

**Comment by thebigsmileXD** [comment]
Its not
