### ISSUE TITLE
Error: Out of memory

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#251]
http://pastebin.com/B91n9qYe
Error report (Theres 2GB ram already dedicated to it... Why is it still crashing?)
The world saves correctly, but plugins arn't correctly unloaded. It also happens every 20 minutes... 
When it crashes, it shows this message and no unloading plugin messages:
**[bin\php\php.exe: Segmentation fault]**
Any help?

**Comment by lolcraftboy14** [comment]
y have to

**Comment by Aericio** [comment]
I think it is our start.bat, but it shouldn't be that because it starts the server but on the updates it says:
![image](https://cloud.githubusercontent.com/assets/16523741/13343717/7e1ded1a-dbf3-11e5-8cd8-99858e77ec8d.png)
And we're using a script that if the server crashes it automatically turns it back on... Might be the problem.

**Comment by TheKillerTacos** [comment]
Show that code... :L

**Comment by Aericio** [comment]
[(http://pastebin.com/HyPBqxtG)]
[(https://forums.pocketmine.net/plugins/restartme.1509/)]

**Comment by robske110** [comment]
Windows isn't meant for server hosting :P

**Comment by MasterWolf** [comment]
@robske110 so what do you mean? Windows cant host server, android too! Maybe linux cant do this too? Ok, lets dont create mcpe servers because here is no OS which can be a server hosting!!
My serevr is hosted on Android and it has not ANY lags!

**Comment by thebigsmileXD** [comment]
Mine is on Windows, no lags either

**Comment by TheKillerTacos** [comment]
I host mine on Ubuntu, Not having any lags,

**Comment by Aericio** [comment]
The server isn't having any lag, it just keeps crashing for some reason.

**Comment by aodzip** [comment]
If you can provide crashlog it will be helpful . before you do this I will keep this issue close.

**Comment by aodzip** [comment]
Edit:
Sorry I didn't notice your crash log . this is a memory leak issue , maybe cause by server or plugin . We cant direct fix such type issue(memory leak) , please check your pugin and we will improve memory management step by step.

PS: windows php binary cant handle a ram bigger than around 1320MB

**Comment by Aericio** [comment]
The memory part in pocketmine.yml?
`memory:
 global-limit: 0
 main-limit: 0
 main-hard-limit: 2048
 check-rate: 20
 continuous-trigger: true
 continuous-trigger-rate: 30`
