### ISSUE TITLE
Server just......depends....

### ISSUE THREAD

**Issue by alex2534alex** [ClearSkyTeam/ClearSky#254]
![screenshot_2016-02-25-14-52-25](https://cloud.githubusercontent.com/assets/15706847/13320178/9ce2caaa-dbcf-11e5-8c3d-3060159ef786.png)
![screenshot_2016-02-25-14-52-20](https://cloud.githubusercontent.com/assets/15706847/13320181/a38d4376-dbcf-11e5-9d10-c4de71610771.png)

**Comment by alex2534alex** [comment]
After some minutes of "stop"
![screenshot_2016-02-25-14-54-41](https://cloud.githubusercontent.com/assets/15706847/13320220/e9b22984-dbcf-11e5-8575-dc2d78cb9b7d.png)

**Comment by thebigsmileXD** [comment]
Just to tell you 2 things. 1st You use an outdated version, i see this because there are no yellow messages on startup.
2nd wether its REALLY OUTDATED or you use Pocketmine.
"Non packaged POCKETMINE installation"

**Comment by alex2534alex** [comment]
@thebigsmileXD , it's the latest version of ClearSky at the moment -_- 
1st. Just I modify MainLogger.php, because I really don't like [Server thread]
2st. It's always show "Non packaged POCKETMINE installation" -_-

**Comment by alex2534alex** [comment]
So, can u open issue again?

**Comment by TheKillerTacos** [comment]
try using the ORIGINAL version, or post the code somewhere,

**Comment by alex2534alex** [comment]
@TheKillerTacos , I changed only main-logger file ( https://gist.github.com/alex2534alex/d97154800214521cd619 )

**Comment by TheKillerTacos** [comment]
Im really confused, the player is Disconnecting within the game (client disconnect), and what plugins you got?

**Comment by alex2534alex** [comment]
CommandTracker 1.1 by Scott Handley for API(s) 1.10.0
iFriend 1.0.4 by LilCrispy2o9/Angelo Vidrio for API(s) 1.11.0
AdvancedKits 4.0.1 by luca28pet for API(s) 1.12.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
GMLimit 1.1.0 by Richen for API(s) 1.13.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
CustomChat 5.0.0 by Array for API(s) 1.7.1
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
MCPEhost_Teleports 2 by  for API(s) 1.0.0
RestartMe 1.2.0 by Gamecrafter for API(s) 1.10.0
RegionGuard 1.2_ByLexo by SumWell-MB_Lexo for API(s) 1.9.0
NoAdvertisingPE 1.0.1 by Vaivez66 for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
BlockLogger 1.0.0 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
SWorldEditor Beta_1.5 by Sergey_Dertan for API(s) 1.8.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
NoExplode 1 by  for API(s) 1.0.0
DB 1 by Unknown for API(s) 1.13.1
WorldFixer 1 by CreeperFace for API(s) 1.12.0
PurePerms 1.1.12 by 64FF00 for API(s) 1.13.0
SimpleAuth 1.6.0 by PocketMine Team, shoghicp for API(s) 1.8.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0

**Comment by TheKillerTacos** [comment]
try disabling SimpleAuth, BlockLogger for the moment, and see if it works?

**Comment by alex2534alex** [comment]
@TheKillerTacos , emmmmm, buuut, no, I'm trying. I enable BlockLogger few days ago. And before it was all the same. Also, they are disconecting after server depends, then they try to connect again. Console just standing still, and is updated only one time per minute.

**Comment by alex2534alex** [comment]
I can enable debuging.

**Comment by thebigsmileXD** [comment]
"We do not support modified builds"

-> Readme

**Comment by alex2534alex** [comment]
Ohhhh, OK. I can install original ver. of ClearSky, but it will not change anything.

**Comment by alex2534alex** [comment]
Debug does not show anything .....

**Comment by thebigsmileXD** [comment]
i crash on win10 really often when opening inventory

**Comment by robske110** [comment]
Closed due to inactivity and probably an duplicate of https://github.com/ClearSkyTeam/ClearSky/issues/146
