### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by alex2534alex** [ClearSkyTeam/ClearSky#255]
http://youtu.be/r2atv-iWqfY

**Comment by alex2534alex** [comment]
My players have million of diamonds!!!! Please, fix.

**Comment by thebigsmileXD** [comment]
Uhm.. isn't the amount the same or even less?

**Comment by alex2534alex** [comment]
Amount of what exactly?

**Comment by XxDXM-hippiexX** [comment]
I can confirm this /:

**Comment by XxDXM-hippiexX** [comment]
Crafting blocks back to ingots instantly after closing a chest.

**Comment by alex2534alex** [comment]
It works on the condition that in the inventory there is still realties. For example, in the inventory 20 diamonds and 2 stacks of cobblestone. When crafting diamonds blocks, cobblestone used instead of diamonds, and so on until all the cobbles, or any other objects will disappear. Generally somewhere like that. If i told something wrong, sorry for my English :3

**Comment by alex2534alex** [comment]
#274
