### ISSUE TITLE
 ( HELP ) How Dedicate A RAM Amount Of For My Server

### ISSUE THREAD

**Issue by RenanGamerz** [ClearSkyTeam/ClearSky#258]
# HELP PLS

**Comment by robske110** [comment]
Go to pocketmine.yml and set the memory limit higher
And close this lol

**Comment by RenanGamerz** [comment]
in console show only 80mb i set 2028

**Comment by alex2534alex** [comment]
....

**Comment by robske110** [comment]
Close this
The console shows the
USED_RAM/ALLOCATED_RAM/SYSTEM_ALLOCATED_RAM
So don't worry everything is working and your server has 2048 RAM, if it suprasses that limit it would kill itself (hard limit)
