### ISSUE TITLE
[Server] [23:09:04] [Server thread/CRITICAL]: "Could not tick level "+": Triying to get properly of non-object

### ISSUE THREAD

**Issue by SoyPro** [ClearSkyTeam/ClearSky#259]
What is this??? Console spam this every second

**Comment by thebigsmileXD** [comment]
When this appeared?

**Comment by SoyPro** [comment]
When i change to level +

**Comment by TheKillerTacos** [comment]
specify "+" ?

**Comment by Aericio** [comment]
Level as in what world you spawn in?
![image](https://cloud.githubusercontent.com/assets/16523741/13343639/ae77f3d0-dbf2-11e5-94be-cdb18f4b66c7.png)
If it is, try changing the file name to world instead of +

**Comment by thebigsmileXD** [comment]
Lol yea the world name might be it

**Comment by SoyPro** [comment]
I Spawn in a flat world,name: world,seed:nothing

**Comment by Aericio** [comment]
Make sure you put the world in the "worlds" folder and switch the level-name in server.properties to the world. Or try doing /world (world name)

**Comment by robske110** [comment]
I have this error too on my main servers mostly caused by my builders world some block must cause that (or Entity)

**Comment by SoyPro** [comment]
Yes robske110

**Comment by thebigsmileXD** [comment]
Seeds must be numbers
