### ISSUE TITLE
Enchanted Golden Apple

### ISSUE THREAD

**Issue by ScandiePlay** [ClearSkyTeam/ClearSky#261]
When I eat Enchanted Golden Apple, I get the same effects like I ate simple Golden Apple. Make addition of the right effects.

**Comment by thebigsmileXD** [comment]
Maybe something messed up, but they should give the right effects

**Comment by TheKillerTacos** [comment]
Dont eat both apple at the same time, it may bug, also check for any lag, that may be the problem also

**Comment by ScandiePlay** [comment]
![screenshot_2016-02-26-23-03-05](https://cloud.githubusercontent.com/assets/17462298/13365374/4a5476d0-dcdd-11e5-85f0-cf7a7c88d5bd.png)

I ate Enchanted Golden Apple, and, as you see, I got the same effects, just like I ate simple Golden Apple. It's my Russian server, the scoreboard is made by myself (if it's important =3)

**Comment by thebigsmileXD** [comment]
It doesnt matter if you eat "both same time" (thats not even possible)

The effects will be overwritten

**Comment by thebigsmileXD** [comment]
As i already mentioned, i know what went wrong. @MCPEPIG fixed the ID once and removed the effects. Then he added the wrong effects back.

**Comment by TheKillerTacos** [comment]
haha, i mean eat one, then the other one :P, haha lol

**Comment by thebigsmileXD** [comment]
@MCPEPIG May you fix?
