### ISSUE TITLE
PHP7 + Port > 32767 = Invisible Server

### ISSUE THREAD

**Issue by jazzwhistle** [ClearSkyTeam/ClearSky#262]
I'm having a problem that was recently fixed in IM PHP7 builds, where clients cannot connect to PHP7 servers if the port ≥32768: https://github.com/PocketMine/PocketMine-MP/issues/3912

**Comment by thebigsmileXD** [comment]
Bigger than Integer value? Then use -1 for unlimited

**Comment by jazzwhistle** [comment]
I was referring to the port number - if it is greater than 32768 then the PHP7 versions of the official, clearsky and genisys refuse all connections, only IM works. I've just fixed this in Genisys by replacing their raklib and spl folders with those of IM...

**Comment by robske110** [comment]
We do not support php7 (yet)
We need to define it as float...

**Comment by aodzip** [comment]
I think it is long , not float lol

**Comment by thebigsmileXD** [comment]
True

**Comment by robske110** [comment]
Oh forgot that data type... I do never use it and if i use it its in PHP5 where i don't care lol

**Comment by IndianaStone** [comment]
On my php 5 it will not let clients connect if they are from the Internet yet locally I can connect, i am port forwarded and it says the server is up and running you just cannot connect

**Comment by thebigsmileXD** [comment]
Dont use localhost. Use actual IP
