### ISSUE TITLE
Fix now ?

### ISSUE THREAD

**Issue by NguyenQuangLap** [ClearSkyTeam/ClearSky#266]
I lifted 255 then some on the server 1 of the ddis was crash ... If not what 254 down? What is it

**Comment by aodzip** [comment]
What is ddis mean?

**Comment by NguyenQuangLap** [comment]
were getting out of the game when it is load on server

**Comment by NguyenQuangLap** [comment]
Now if you are free I can up a 255 and I go to the server I see how

**Comment by aodzip** [comment]
I cant understand you ....

**Comment by NguyenQuangLap** [comment]
@@@ Error 255 huhu

**Comment by MaryVictoria** [comment]
what kind of error?crashes?glitches?server close?

**Comment by NguyenQuangLap** [comment]
I lifted 255 then some on the server 1 of the ddis was crash ... If not what 254 down? What is it

**Comment by MaryVictoria** [comment]
post the crash dumps.

**Comment by NguyenQuangLap** [comment]
no crash

**Comment by NguyenQuangLap** [comment]
can not join

**Comment by robske110** [comment]
I KNOW WHAT HE MEANS:
You have to keep the value for chunk-radius UNDER 65!

**Comment by robske110** [comment]
(Client crash)

**Comment by MaryVictoria** [comment]
server online?but cant join?

**Comment by aodzip** [comment]
update to 256
