### ISSUE TITLE
Can't join via MCPE 0.14.0

### ISSUE THREAD

**Issue by MastersFaster** [ClearSkyTeam/ClearSky#269]
0.14.0 is red in the MCPE app, and it says the connecting timed out doe to Login Attempt in the console.

**Comment by MastersFaster** [comment]
also should have mentioned 'This server is running ClearSky version 1.1 (API Sunrise)'

**Comment by TheKillerTacos** [comment]
aer you using latest version? not using MCPE 0.14.0 B* ?

**Comment by MastersFaster** [comment]
yes, and am using the pocketmine dev 1.6 atm for my server as the players can connect

**Comment by TheKillerTacos** [comment]
Pocketmine? this is ClearSky...

**Comment by MastersFaster** [comment]
yes, i had clearsky on but had to switch to the pocketmine dev phar supporting 0.14.0 because of the issue

**Comment by TheKillerTacos** [comment]
Download the latest Clearsky Phar, from jenkins. remove old Pocketmine.yml, and start the server.

**Comment by MastersFaster** [comment]
I did that and the issue occured. It was the PHP7 phar #25

**Comment by TheKillerTacos** [comment]
You have the right PHP7 libraries? try sending any screenshots of the console log

**Comment by MastersFaster** [comment]
![clearskystuff](https://cloud.githubusercontent.com/assets/13714046/13374806/3c95c39a-dd4c-11e5-8ee5-f3464bdceac6.PNG)

**Comment by TheKillerTacos** [comment]
its the client, Either he has an old version, or he doesnt has a Username.

**Comment by thebigsmileXD** [comment]
Your Protocol version set in the YML is incorrect.

**Comment by MastersFaster** [comment]
what protocol version? there is no such thing in the YML. The only thing I think it may be is
-the Clearsky Phar:
const MINECRAFT_VERSION = "v0.14.x beta/alpha";
const MINECRAFT_VERSION_NETWORK = "0.14.0"
-the pocketmine phar
const MINECRAFT_VERSION = "v0.14.0.0 alpha";
const MINECRAFT_VERSION_NETWORK = "0.14.0.0";

**Comment by MastersFaster** [comment]
@haniokasai

**Comment by thebigsmileXD** [comment]
Look at Protocol

**Comment by thebigsmileXD** [comment]
In the pocketmine.yml? There is. protocol, and version-string

**Comment by haniokasai** [comment]
i forgot to changed protocol...

**Comment by aodzip** [comment]
And seems your ClearSky is a bit outdated. No build numbers show.

**Comment by MastersFaster** [comment]
I posted this before 26 came out. 26 didn't fix the issue, here is the IP so you guys can see what im talking about
76.27.36.157:19132

**Comment by aodzip** [comment]
Why your server show red version number .. I think it is outdated.
or you are using php7 version . but we do not support php7 version now.

**Comment by MastersFaster** [comment]
yes I am using the PHP7 build 26: 1.1 Sunrise

**Comment by aodzip** [comment]
please use php5 version .

**Comment by MastersFaster** [comment]
will switch over now.
