### ISSUE TITLE
Sign tile will disappear 

### ISSUE THREAD

**Issue by aodzip** [ClearSkyTeam/ClearSky#270]

**Comment by robske110** [comment]
Rename to: Tiles are completely broken CRITICAL

**Comment by thebigsmileXD** [comment]
Uh.. Then why does it work for me, even after restart?

All my signs are still working and the "sign text glich away" doesn't happen anymore

**Comment by aodzip** [comment]
Maybe my PC 's face is too ugly. lol

**Comment by thebigsmileXD** [comment]
:D

**Comment by robske110** [comment]
CONFIMED SUPER-CRITICAL

**Comment by robske110** [comment]
You know i have developed an traffic light plugin
It reacts to, if an player touches an sign with [AMPEL] on it! But if i place an sign with that and click it it doesn't recognize it. -> the tile doesn't even exist

**Comment by robske110** [comment]
I will look if BlockPlaceEvent is called

**Comment by robske110** [comment]
No, its not called

**Comment by robske110** [comment]
SIGN PLACING BROKE COMPLETELY

**Comment by thebigsmileXD** [comment]
-.- keep calm and have a cookie

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/8e4cfcd9787c36f6c60b9b890bd6f3c753673e14
