### ISSUE TITLE
Refresh sign doesnt work ?

### ISSUE THREAD

**Issue by wiligangster** [ClearSkyTeam/ClearSky#273]
Refresh sign doesnt work ?

**Comment by thebigsmileXD** [comment]
What refresh sign?

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/8e4cfcd9787c36f6c60b9b890bd6f3c753673e14

**Comment by wiligangster** [comment]
the sign is not updated with my plugin version pocketmine when everything works well

**Comment by thebigsmileXD** [comment]
?

**Comment by thebigsmileXD** [comment]
Then plugin fault.
