### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#275]
`ClearSky Version #267 Crash`
http://pastebin.com/w4xFaNWR
Inventory? (Don't know what caused it, but shuts down server correctly)

**Comment by Aericio** [comment]
`ClearSky Version #268`
This version fixed the crash with the inventory.

**Comment by thebigsmileXD** [comment]
Trying to fix hotbar gliches but
```Call to a member function getWindowId() on boolean```
