### ISSUE TITLE
Carpet has no hitbox

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#276]

**Comment by PocketKiller** [comment]
what do you mean by 'hitbox'?

**Comment by thebigsmileXD** [comment]
-.- @PocketKiller you know, that google is your friend? i will not answer this.

**Comment by gaoyichuan** [comment]
@PocketKiller I think he means bump box

**Comment by thebigsmileXD** [comment]
@gaoyichuan i have no idea if that even is a word.

I talk about the boundingBox/collisionBox.
