### ISSUE TITLE
Fatal error: float

### ISSUE THREAD

**Issue by Dudoleitor** [ClearSkyTeam/ClearSky#278]
When I try to start the server from linux Debian 8 x64 it give me this error:

`Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///home/dudoleitor/PocketMine/PocketMine-MP.phar/src/pocketmine/Server.php on line 2`

**Comment by SalmonGER** [comment]
Do you use PHP7?

**Comment by PocketKiller** [comment]
You are using PHP7,

**Comment by Dudoleitor** [comment]
Yes, I'm using PHP7, downloaded from the PocketMine Bintray

**Comment by Aericio** [comment]
Use PHP5

**Comment by Dudoleitor** [comment]
I've deleted everything and user your installer, now it works!
Thank you
