### ISSUE TITLE
Hotbar Glitched

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#279]
https://www.youtube.com/watch?v=_Y2YaFTIeAE
Inventory glitch too lazy to write it.
Also recording messed up sorry.

**Comment by SURVAml** [comment]
Same here with latest Build #266, if you choose one item in creative, you have the full hotbar of this item.

**Comment by Dudoleitor** [comment]
I also have the same bug.
Are the developers fixing it or they don't know how to fix it?

**Comment by Aericio** [comment]
There fixing it...
