### ISSUE TITLE
MCPE Crashing After Joining

### ISSUE THREAD

**Issue by CLiu13** [ClearSkyTeam/ClearSky#28]
MCPE is crashing on IOS when joining server. No error messages on console. Latest ClearSky phar version.

**Comment by aodzip** [comment]
I will release a new one . This crash may cause by painting . But fix in latest code . Would you like to have a try?

**Comment by aodzip** [comment]
And , if you watch the release repo , you will get a email when we release a new version

**Comment by CLiu13** [comment]
Sure thing!

**Comment by aodzip** [comment]
have this fixed?

**Comment by thebigsmileXD** [comment]
Yes, doesn't happen anymore. Was because of paintings

**Comment by CLiu13** [comment]
Hm... Still occurring, even when using latest ClearSky release with painting fix. If you need me to post more info about my server etc, just tell me and I will provide it :)

**Comment by aodzip** [comment]
1.First remove all plugin see if it still crash yout client
2.Remove player save data see if it still crash

**Comment by CLiu13** [comment]
I did all of that, and it still crashes MCPE.

**Comment by aodzip** [comment]
Then , start a clean server . See if it is config error or world save data broken

**Comment by aodzip** [comment]
If still crash , please pack your whole server dir and upload here if you like . Or , you can give us your server IP and port for future test

**Comment by CLiu13** [comment]
Alright, I will try setting up a new server.

**Comment by isoz** [comment]
My server is crashing when player joins. I think it's the Y being 0 problem, I thought it was fixed? Using latest build. If i delete player file goes to normal.

Error: Undefined offset: -1
File: /src/pocketmine/level/format/generic/BaseChunk
Line: 82
Type: notice

**Comment by aodzip** [comment]
Another offset bug…

**Comment by isoz** [comment]
Sorry but what's the status on the offset? There was no release or fix assigned to the close so I was confused. Thank you.
