### ISSUE TITLE
Where is gone Ukrainian language??

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#284]
I cant see ukr.ini here. But it was here few days ago...

**Comment by TheKillerTacos** [comment]
Check up in the commits, and try to Pull Request, or maybe they are updating the way the server will be translated?

**Comment by MasterWolf** [comment]
@TheKillerTacos maybe...

**Comment by aodzip** [comment]
It is in oldlang

**Comment by aodzip** [comment]
You can copy it out .
Because I need add "Build number " string to lang file,I put these original file into a folder

**Comment by MasterWolf** [comment]
@aodzip ok!
