### ISSUE TITLE
ClearSky creates core.* files

### ISSUE THREAD

**Issue by SURVAml** [ClearSkyTeam/ClearSky#293]
Hi,
I'm using ClearSky with Multicraft on Debian 7.0 x64, and every time when I stop (or restart) the server in Multicraft, it creates a file named "core.12345" (a random number). Here's a screenshot of those files:

![ohne titel](https://cloud.githubusercontent.com/assets/15860314/13462766/45351c7c-e089-11e5-9399-bf501bf11128.jpg)

It's a real problem because those files are huge, and I've already got my 1 TB disk full if I don't delete them daily. After some searching on google, I think it's a [core dump](https://www.google.de/search?client=safari&rls=en&q=php+core.12345&ie=UTF-8&oe=UTF-8&gfe_rd=cr&ei=z_XWVqWeHYmh8wfsgY-ICg#q=php+core+dump).

**Comment by robske110** [comment]
Try lowering debug level?
Really haven't seen such files in my whole life

**Comment by thebigsmileXD** [comment]
I confirm.. I saw the files..

**Comment by thebigsmileXD** [comment]
Debug is off

**Comment by SURVAml** [comment]
Where I can get the latest PHP5 binaries for ClearSky? I think it's something with the PHP binaries, because on every other OS, everything works. When I stop ClearSky on Mac OS X:

```
[18:44:01] [Server thread/INFO]: Disabling EconomyAPI v2.0.9
[18:44:01] [Server thread/INFO]: Disabling GunGame v1.0.0
[18:44:01] [Server thread/INFO]: Unloading level "world"
[18:44:01] [Server thread/INFO]: Unloading level "CG1"
[18:44:01] [Server thread/INFO]: Stopping other threads
Segmentation fault: 11
Jarnes-iMac:ClearSky Jarne$ 
```

There's also a segmentation fault 11, but it creates no core dump. Is there any way to set core dump off on Debian x64? I think segmentation fault is because ClearSky / PocketMine does not correctly stop.

I found a german article about it (https://entwickler.de/online/web/segmentation-faults-der-schlimmste-aller-fehler-ist-132888.html), sorry, there's nothing on english.

**Comment by robske110** [comment]
I did think you guys are german?!
That german article says it is an memory writing issue, mostly caused by c errors
http://www.cyberciti.biz/faq/linux-disable-core-dumps/
This should help

**Comment by robske110** [comment]
Should i write the email regarding the plugin in english or german?

**Comment by SURVAml** [comment]
Ja, bin deutsch, schreibe nur auf GitHub auf Englisch damit Leute, die das hier lesen auch alles verstehen

**Comment by SURVAml** [comment]
But I think it isn't an issue on the server because the bug is only when I stop ClearSky.

**Comment by aodzip** [comment]
This should a memory dump of PHP run enviroment .
Please change your run enviroment settings

**Comment by SURVAml** [comment]
Okay I think it's not a bug in ClearSky, but nevertheless, it would be nice if you could help me. Tried http://www.cyberciti.biz/faq/linux-disable-core-dumps/, but it still creates core dumps. With PHP environment you mean my PHP binary installed on the web server? What should I change there?
