### ISSUE TITLE
Wrong time and date

### ISSUE THREAD

**Issue by Dudoleitor** [ClearSkyTeam/ClearSky#295]
I'm running a server on a Debian VPS. The VPS is hosted in France, and the OS time is correct. I use CET (UTC +1) time. Pocketmine uses CST time (UTC -6).
Is there a way to configure it or is it a bug?

**Comment by SURVAml** [comment]
I think you can change it in the php.ini of the PHP binary in the ClearSky folder (ClearSky folder/bin/php5/bin/php.ini), there's a value named date.timezone , so you can change it to date.timezone="Europe/Paris"

**Comment by robske110** [comment]
@SURVAml sorry for asking here
But you requested an warn plugin
And I'm in development of one, i can send you an email with screenshots... (I'm german)

**Comment by Pub4Game** [comment]
fixed :D

**Comment by Pub4Game** [comment]
oops :D I fix game time... 

Anyway this fix is correct

**Comment by SURVAml** [comment]
@robske110 Yeah, that would be great. You can write to [support@surva.ml](mailto:support@surva.ml).

**Comment by Dudoleitor** [comment]
Thank you SURVAml, it works!
