### ISSUE TITLE
Client crash when opening furnace with tool

### ISSUE THREAD

**Issue by jjplaying** [ClearSkyTeam/ClearSky#297]
Hi,
I found a bug in the latest ClearSky build.
If you touch a furnace with the hand, everything works.
But if you open it with a stone pickaxe (or any other tool), Minecraft PE crashes.

**Comment by SURVAml** [comment]
But only sometimes, I'll try to find the other things

**Comment by Adam1609** [comment]
Maybe it effect in some reason because 0.13do not have this bug

**Comment by thebigsmileXD** [comment]
How about now?

**Comment by thebigsmileXD** [comment]
No answers.
