### ISSUE TITLE
Client death when they hit bedrock layer

### ISSUE THREAD

**Issue by IndianaStone** [ClearSkyTeam/ClearSky#298]
When a client touches the bedrock layer they teleports into the air and die

**Comment by Aericio** [comment]
I don't think thats ClearSky's fault since its not doing that to me (latest), try searching through your plugins and testing each one to find which one does that.

**Comment by IndianaStone** [comment]
Yeah i apologize I should have looked through and checked through my plugins, it was NoVoid sorry about that again my bad
