### ISSUE TITLE
Lava/water bucket bug

### ISSUE THREAD

**Issue by Dudoleitor** [ClearSkyTeam/ClearSky#300]
Hi all,
I'm running a PocketMine server (using ClearSky) and some users found a bug.
They said that they placed a water bucket to extinguish fire but they placed lava instead of water.
It happend more than one time, so I think it's a code bug

**Comment by Driesboy** [comment]
ok thx for reporting

**Comment by thebigsmileXD** [comment]
Interesting. This should definitely not happen, due to buckets having the meta of the block that the'll place. Lava :10 Water: 8

**Comment by aodzip** [comment]
Cant get this bug too.
