### ISSUE TITLE
API Server Error

### ISSUE THREAD

**Issue by thelucyclub** [ClearSkyTeam/ClearSky#301]
When I join my server I get this:
``[19:55:45] [Server thread/WARNING]: API Server Returned Error Message: Monthly Request Limit Reached when iCreepyKid tried to connect
[19:55:45] [Server thread/CRITICAL]: Shutting down server to prevent blacklisting on API Database``
and soon after it follows a crash. Anyone know whats happening?

**Comment by GlitchPlayer** [comment]
wait, this vpn guard plugin... this is not clearsky issue

**Comment by thelucyclub** [comment]
Oh, sorry. I didn't realize that was causing it. I'll ask them instead.
JUST close this issue.
