### ISSUE TITLE
WEB FOR CLEARSKY(read pls)

### ISSUE THREAD

**Issue by ondraczsk** [ClearSkyTeam/ClearSky#306]
I do web for Clear Sky.
If you want this design, say.
Beta Available on Web [clearskybeta.esy.es](http://clearskybeta.esy.es/)

**Comment by thebigsmileXD** [comment]
Slow and way too much animation

I like the github automatic buildt one better

**Comment by ondraczsk** [comment]
choose design on html5up.net

I inspired of nukkit.cn website

**Comment by ondraczsk** [comment]
github.io?

**Comment by robske110** [comment]
Yes, when we have time we will update our github.io site ;)
