### ISSUE TITLE
Crash on placing Redstone

### ISSUE THREAD

**Issue by meetloaf13** [ClearSkyTeam/ClearSky#31]
Server crashes when placing Redstone.  After server reboot, redstone placed still exists.  Log attached.

[CrashDump_Tue_Jan_19-08.32.54-MST_2016.log.zip](https://github.com/ClearSkyTeam/ClearSky/files/96142/CrashDump_Tue_Jan_19-08.32.54-MST_2016.log.zip)

P.S.  I'm new to GIT, let me know if I need to post this different or in a different place.

Thanks for the server, it's pretty awesome!

**Comment by aodzip** [comment]
Fixed

**Comment by aodzip** [comment]
New release pushed , check it out , and hope you can have a good time with ClearSky

**Comment by meetloaf13** [comment]
Awesome, thanks aod!

**Comment by meetloaf13** [comment]
Confirmed no crash, thanks!
