### ISSUE TITLE
Nothing of "living" spawns in a new world

### ISSUE THREAD

**Issue by ehasting** [ClearSkyTeam/ClearSky#312]
I am not sure where to get any help or anything - however i cant get anything to spawn, like animals, monsters, villagers, when creating new world. 

Using latest jenkins build (2016-03-05).
[18:19:27] [Server thread/INFO]: This server is running ClearSky 1.1 「Sunrise」 implementing API version 1.13.1 for Minecraft: PE v0.14.x beta/alpha (protocol version 42)

Is there any undocumented tricks to get animals and such to spawn?

**Comment by thebigsmileXD** [comment]
-.-"

Okay. First of all go though the readme.

After that give me an answer if you found the solution, or the reason why it may not work. Thanks.

**Comment by ehasting** [comment]
" - Variations of Mobs (Rabbits, Villagers etc.)" , this implies that there are no AI?
 - or is it the part regarding xdebug ?

**Comment by thebigsmileXD** [comment]
Okay. Now we can go on.

Spawning them randomly isn't implemented yet. But actually planned. 

But they would just stand around.

**Comment by ehasting** [comment]
ok, thanks!   so status is pretty much the same as the origin project.   Is there any Minecraft PE server software that mimics LAN play hosted inside minecraft PE app currently?
