### ISSUE TITLE
Client overload

### ISSUE THREAD

**Issue by Christian665** [ClearSkyTeam/ClearSky#313]
Clearsky work very fast and fine.
But after 3min Play the Server was slowly and slowly 
It jerk fast !
When i go to the Start menu and back to the game the server run perfekt. ..but only 3 minutes long. 
When i dont go to the Start menu and Play With jerk the server crash ! i must restart the server

**Comment by thebigsmileXD** [comment]
As we saw in your video, the game doesn't react.

**Comment by thebigsmileXD** [comment]
Try to enable and disable "block feedback viration"
