### ISSUE TITLE
Server Stopped

### ISSUE THREAD

**Issue by MasterWolf** [ClearSkyTeam/ClearSky#314]
For some reason in random moment server stops. In console i can see "Server Stopped" (Without disabling plugins). What is the problem and how to fix it?

**Comment by robske110** [comment]
Please show full log with debug enabled (debug level 2)

**Comment by MasterWolf** [comment]
@robske110 i havent any log. just "Server stopped" message

**Comment by robske110** [comment]
Enable debug

**Comment by MasterWolf** [comment]
i need to enable it? xdebug or what?

**Comment by robske110** [comment]
In pocketmine.yml

**Comment by MasterWolf** [comment]
ok

**Comment by MasterWolf** [comment]
i turned on. when it will stop i will give you log.

**Comment by Aericio** [comment]
http://pastebin.com/Ek5e68p8
Was it something like that? I'm getting that also.

**Comment by robske110** [comment]
Thats an memory crash, give your server more memory

**Comment by Aericio** [comment]
How? Main-Hard-Limit is 2000, isnt that the memory?

**Comment by robske110** [comment]
Yes put an higher mem in it

**Comment by Aericio** [comment]
Will this lag the host computer a little? The computer only has 4GB ram. How much should I increase it by? 500?

**Comment by robske110** [comment]
php.EXE thats it you're running it on windoof
And to the ram yes, write 2048+1024/2

**Comment by Aericio** [comment]
Could it be because of this?:
[23:44:45] [Server thread/NOTICE]: Memory overload restarts are enabled. If memory usage goes above 700M, the server will restart.

**Comment by robske110** [comment]
Yes, plugin issue
