### ISSUE TITLE
An unrecoverable error has occurred and the server has crashed

### ISSUE THREAD

**Issue by Fightingfire** [ClearSkyTeam/ClearSky#316]
# **Issue description**

Write a short description about the issue
Crash but no reason
Steps to reproduce the issue

1.Launch server
2.Connect
3.Wait
4.Crash
# **OS and versions**

This server is running ClearSky 1.1-#22 「Sunrise-#22」 implementing API version 1.13.1 for Minecraft: PE v0.14 (protocol version 40)

    OS: Linux ubuntu 14.04

# **Crashdump, backtrace or other files**

[CrashDump_Sun_Mar_6-11.13.15-CET_2016.txt](https://github.com/ClearSkyTeam/ClearSky/files/160265/CrashDump_Sun_Mar_6-11.13.15-CET_2016.txt)

**Comment by thebigsmileXD** [comment]
i'll now show you some words of your crashdumb.

***Permission denied***

**Comment by thebigsmileXD** [comment]
Solution: Set the permissions to 777

**Comment by Fightingfire** [comment]
ok but where is/are this/there permission ?

**Comment by Aericio** [comment]
Search it up on Linux fourms
