### ISSUE TITLE
Fire and flint and steel bug

### ISSUE THREAD

**Issue by Dudoleitor** [ClearSkyTeam/ClearSky#317]
You can't exetinguish fire, when you tap it, it disappears but appears again after a few seconds.
When you use flint and steel the durability doesn't decrease.

**Comment by thebigsmileXD** [comment]
Fire may be fixed

**Comment by Dudoleitor** [comment]
Are you going to fix it or is it fixed now?

**Comment by Dudoleitor** [comment]
I've just seen the changelog of build #293, thank you!

**Comment by thebigsmileXD** [comment]
Works?

**Comment by Dudoleitor** [comment]
I'm using build 294 but the fire and the flint and are still bugged.

**Comment by thebigsmileXD** [comment]
Okay. I'll check later

**Comment by thebigsmileXD** [comment]
Still buggy.

**Comment by thebigsmileXD** [comment]
Fire now gone until chunk reload

**Comment by thebigsmileXD** [comment]
Fire is related to a MCPE bug where interaction with fire is not sendt to the server.
