### ISSUE TITLE
Tools drop bug

### ISSUE THREAD

**Issue by Dudoleitor** [ClearSkyTeam/ClearSky#319]
If you have 5 pickaxes in your inventory, when you drop a single pickaxe on the ground all 5 pickaxes disappers from the inventory, but there is only a drop on the ground.

**Comment by thebigsmileXD** [comment]
Windows 10. we cant fix this.

**Comment by Dudoleitor** [comment]
I'm using iPad Pro, not windows

**Comment by thebigsmileXD** [comment]
Are you really sure that are 5 pickaxes, or is your hotbar just linked incorrect. take other items, place them in the hotbar, and you'll see.
