### ISSUE TITLE
Egg Spawned Mobs

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#321]
When people on my server use spawn eggs to spawn entities, it gets spawned and said "MobAI not implemented yet" . Then, the mob doesn't move or do anything and stays there, even when restarting the server. Is there a way to kill all the mobs in the server every restart or with a command? Sadly my server is creative so any player can place the spawn eggs and BanItem doesn't work.
**Mob stays in place, Cannot be killed or despawned:**
![image](https://cloud.githubusercontent.com/assets/16523741/13592722/06c153ac-e499-11e5-9814-32201fcd5b9e.png)
**Message:**
![image](https://cloud.githubusercontent.com/assets/16523741/13592740/328b6356-e499-11e5-852a-508d1f875306.png)

**Comment by XxDXM-hippiexX** [comment]
Use laggClear or /gc to get rid of them. use BanItem to stop players from spawning mobs.

**Comment by Aericio** [comment]
I did /gc already. It doesn't clear them. /lagg clear also doesn't remove the mobs. BanItem doesn't work for me.

**Comment by thebigsmileXD** [comment]
/et nuke and /et nuke others
Which is in grabbag

**Comment by Aericio** [comment]
Thanks, but can it be implemented into ClearSky to remove the mobs every restart or will MobAI need to work before that? I'll try out Grabbag

**Comment by IndianaStone** [comment]
I just used lava and it killed them

**Comment by Aericio** [comment]
Lava didn't kill them for me lol

**Comment by thebigsmileXD** [comment]
This won't be implemented. This is a plugin task. If you don't want mobs at all, just use a plugin that removes eggs from the inventory or disallows the using of these.

**Comment by Aericio** [comment]
Okay then.
