### ISSUE TITLE
Weather + Xp

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#322]
**Weather**
![image](https://cloud.githubusercontent.com/assets/16523741/13594542/4e4f2cd4-e4a9-11e5-9733-eec17f107105.png)
**Xp**
![image](https://cloud.githubusercontent.com/assets/16523741/13594555/5f16a330-e4a9-11e5-9f6e-414007fb3cea.png)

**Comment by thebigsmileXD** [comment]
What language do you use? It would be nice if you could add it in /pocketmine/src/lang

**Comment by robske110** [comment]
Why do i have to mess up langs every time :)

**Comment by aodzip** [comment]
Fixed
