### ISSUE TITLE
No Melee Damage

### ISSUE THREAD

**Issue by SuperCraftFacs** [ClearSkyTeam/ClearSky#324]
When ever I punch or hit someone the person doesn't take any damage, but when I shoot them with a projectile, it works. Please fix this.

Thanks!

**Comment by thebigsmileXD** [comment]
It must be a plugin you use. I am on the latest build and everything works.

**Comment by robske110** [comment]
I'm having this issue too

**Comment by robske110** [comment]
I've debugged every plugin and no plugin does cancel it!

**Comment by thebigsmileXD** [comment]
Well, i don't have problems. Maybe spawn area?

**Comment by SuperCraftFacs** [comment]
I don't think so. I don't have PeacefulSpawn. I will try to do the server.properties.

**Comment by robske110** [comment]
I will try to delete server.whydoistillexist

**Comment by SuperCraftFacs** [comment]
Immmmm, what is 'server.whydoistillexist'?!?

**Comment by robske110** [comment]
server.properties -_-

**Comment by SuperCraftFacs** [comment]
Oh...

**Comment by SuperCraftFacs** [comment]
Tell me if it worked.

**Comment by SuperCraftFacs** [comment]
Why would deleting server.properties help?

**Comment by thebigsmileXD** [comment]
It will be generated again with vanilla settings. Maybe theres just an error in allow-pvp.
Its On/Off, not 1/0

**Comment by SuperCraftFacs** [comment]
...........Oh 1/0 not on/off... Well I am very dumb... So 1 = php on right?

**Comment by SuperCraftFacs** [comment]
pvp instead of php sorry.

**Comment by thebigsmileXD** [comment]
Try it?

**Comment by SuperCraftFacs** [comment]
Ok.

**Comment by SuperCraftFacs** [comment]
Meh, i'm the only one online :/

**Comment by SuperCraftFacs** [comment]
Can you join?

**Comment by thebigsmileXD** [comment]
@SuperCraftFacs Just to remind you: please edit your messages instead of sending many messages, thanks.

IP?

**Comment by SuperCraftFacs** [comment]
Ok, IP is sc.superdude36.com:19132

**Comment by thebigsmileXD** [comment]
pvp=on

**Comment by thebigsmileXD** [comment]
this is what i have:
```pvp=on```

**Comment by SuperCraftFacs** [comment]
Didn't work...

**Comment by thebigsmileXD** [comment]
Nope. I wasn't able to write this, changed it now

**Comment by SuperCraftFacs** [comment]
What do you mean by that?

**Comment by thebigsmileXD** [comment]
Nevermind

**Comment by SuperCraftFacs** [comment]
Is their anything else that could work?

**Comment by robske110** [comment]
I've fixed it::I forgot to add { to an if statement!

**Comment by thebigsmileXD** [comment]
Where

**Comment by robske110** [comment]
In my plugin
So there is no issue in ClearSky

**Comment by SuperCraftFacs** [comment]
Hey, em he fixed it but I didn't.

**Comment by robske110** [comment]
Yes, its an plugin issue
Test it with no plugins and then tell us if it doesnt work there too
