### ISSUE TITLE
Chinese Readme.md

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#325]
![image](https://cloud.githubusercontent.com/assets/16523741/13659445/b92c89d4-e625-11e5-9d9c-cf7fcd0c3096.png)
"Netowrk" supposed to be "Network"? (网络 = Network)
**Google Translate:**
Compatible network bad players , you can turn off cheat detection (anti-cheat) in [netowrk] or loss tolerance rate increases.

**Comment by aodzip** [comment]
Good
