### ISSUE TITLE
No Melee Damage V2

### ISSUE THREAD

**Issue by SuperCraftFacs** [ClearSkyTeam/ClearSky#329]
This IS ClearSky's issue. I removed all of my plugins and it still didn't work. When ever Someone punches someone they person doesn't take damage.

Ill put my pm.yml and server.properties here.
[server.properties.zip](https://github.com/ClearSkyTeam/ClearSky/files/170579/server.properties.zip)
[pocketmine.yml.zip](https://github.com/ClearSkyTeam/ClearSky/files/170580/pocketmine.yml.zip)

**Comment by robske110** [comment]
spawn protection

**Comment by robske110** [comment]
and can you send us your server-ip for testing?

**Comment by SuperCraftFacs** [comment]
sc.superdude36.com

Thats IP

And I went out of 16 blocks...

**Comment by SuperCraftFacs** [comment]
When ever I change spawn protection it always goes back to 16...

**Comment by SalmonGER** [comment]
Do you change it while the server is offline?

**Comment by SuperCraftFacs** [comment]
Ya

**Comment by SuperCraftFacs** [comment]
Ok, maybe not.

**Comment by thebigsmileXD** [comment]
~le facepalm

**Comment by SuperCraftFacs** [comment]
lol, it still doesn't work .-. ill just use genius or what ever its called...

**Comment by thebigsmileXD** [comment]
But its interesting that only you have this problem

**Comment by Aericio** [comment]
You could possibly try to reinstall Pocketmine-MP and just add ClearSky to your folder once its done maybe?

**Comment by robske110** [comment]
Close this.
No one else reported this.
You do sth wrong

**Comment by thebigsmileXD** [comment]
Was reported on PM too.

**Comment by robske110** [comment]
Link?
