### ISSUE TITLE
Unable to get into minecart

### ISSUE THREAD

**Issue by meetloaf13** [ClearSkyTeam/ClearSky#33]
I can't produce an error, but I am unable to get into a minecart that is sitting on a rail.  The "Ride" button shows up but nothing happens when you click on it.

If I repeatedly click on "Ride" the card sits there until 20-30 clicks then it is destroyed.

If I place a cart, log out, then log back in, the cart is gone.

The carts are also fairly difficult to place.  I've found that I can usually only place them on the rail on a corner.

Additionally, this may be attributed to my 'n00b' status, but anything except the standard rail only places in one orientation (it will not rotate, form a corner, or place properly on an incline).   The standard rail places without error.

**Comment by thebigsmileXD** [comment]
You can spawn them? I can't even spawn them

**Comment by meetloaf13** [comment]
so, make a track and put a bend in it.  Equip your cart and then try to place it on the bend of the track, after a little effort, you should be able to get it to place.
