### ISSUE TITLE
Ban Message

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#333]
![image](https://cloud.githubusercontent.com/assets/16523741/13732236/ec120ece-e921-11e5-8fad-f5beeba73feb.png)
Shows this when you do /ban. This layout is kind of like a /tempban layout
**Normal Ban Message**
I think the default in Pocketmine is: Banned by admin. Reason: (reason)

**Comment by robske110** [comment]
We changed the ban design and the other thing is an plugin...

**Comment by thebigsmileXD** [comment]
It shouldn't show up this way. I will check this later.

**Comment by Aericio** [comment]
Well the temp-ban message is almost the same as that so I guess its fine?
