### ISSUE TITLE
Stair Lighting Issue?

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#335]
![image](https://cloud.githubusercontent.com/assets/16523741/13773002/33f9c03c-ea3b-11e5-855b-c9e32b8bd610.png)
^ When not attached to any blocks
![image](https://cloud.githubusercontent.com/assets/16523741/13773033/534541f0-ea3b-11e5-8b2b-b97f0398caf6.png)
^ Attached to 1 block (bottom does not effect)
![image](https://cloud.githubusercontent.com/assets/16523741/13773065/85b4c37c-ea3b-11e5-8dd3-993322c64af8.png)
^Attached on top, right, and left. Stairs positioned up and down. 
**I didn't change the stair type at all, it just seems to darken up as more blocks are surrounding it**
Is this supposed to be this way?

**Comment by thebigsmileXD** [comment]
THIS IS AN MCPE CLIENT ISSUE

Really.. This is so known.. And you havent tested in singleplayer i think

**Comment by Aericio** [comment]
k
