### ISSUE TITLE
Server is up, Its not Showing on lan, either with Ext ip

### ISSUE THREAD

**Issue by TheKillerTacos** [ClearSkyTeam/ClearSky#336]
So, I updated to latest Clearsky, and used the installer for Linux (I use Ubuntu), and i started the server, installed some plugins, then when i wanted to test it, it didnt showed up in LAN, either with external ip, and the Domain i used to forward to my ip, i removed all plugins and still the same, ports are open, i have my website in the same PC,  and it does loads with ext ip and domain.

**Comment by kam187** [comment]
It's a bug caused by this commit: 'Fix annoying "localhost" or 0.0.0.0 IP'.

It's the same for me on mac, i just reverted the code.

**Comment by Efforto** [comment]
Ahhhh~If you want to fix it,just edit server.properties and add a line like this:
server-ip=x.x.x.x
:)

**Comment by thebigsmileXD** [comment]
I confirm. But interesting fact:

It fixes servers not being visible on windows servers 😂

**Comment by TheKillerTacos** [comment]
@Efforto I did so. Nothing Changed

**Comment by Aericio** [comment]
Get the latest version. It reverted the changes from the "Fixing annoying localhost"
