### ISSUE TITLE
Able to enter minecart, but it glitches into the ground, upon exit you are ~ 10 blocks down in the ground

### ISSUE THREAD

**Issue by meetloaf13** [ClearSkyTeam/ClearSky#34]
So with new server release, I can now enter the cart, but the cart instead of riding along the tracks will simply bury itself with you in it.  When jumping out to exit the cart, I am buried in the ground, about 10 blocks down.

I was playing with it for the bit and got the server to crash after a few cycles of getting into and out of the cart.

See the screenshots ( m.imgur.com/a/hSLZ7 ) and attached crash log.

[CrashDump_Wed_Jan_20-14.56.45-MST_2016.log.zip](https://github.com/ClearSkyTeam/ClearSky/files/98170/CrashDump_Wed_Jan_20-14.56.45-MST_2016.log.zip)

**Comment by aodzip** [comment]
Thx for reporting , making a new release

**Comment by meetloaf13** [comment]
Not sure if this is relevant anymore, but I cannot destroy the minecarts, HOWEVER.  If I clear out the space around them underground, and I jump in the minecart, and I will ride down the empty shaft.  Also the minecarts are multiplying...like rabbits!  Haha.  

First pic you'll see 3 minecarts.  Second pic the top cart I rode down to the bottom and jumped out.

imgur.com/a/5Nxi5

**Comment by aodzip** [comment]
Minecart doesn't finish. I have already turn it off in the latest(#2) build

**Comment by meetloaf13** [comment]
Sounds like you guys are working on a fix though?

**Comment by thebigsmileXD** [comment]
Of cause, thats what issues are for

**Comment by meetloaf13** [comment]
Sweet, well let me know if you need a tester :)
