### ISSUE TITLE
Splash Harming kills CMODE players

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#341]
![image](https://cloud.githubusercontent.com/assets/16523741/13894869/c037db56-ed10-11e5-8954-6c31304a597b.png)
if you can see splash potion in background

**Comment by jasonwynn10** [comment]
same with poison

**Comment by thebigsmileXD** [comment]
Duplicate

**Comment by TheKillerTacos** [comment]
what? where? LINK or no duplicate

**Comment by robske110** [comment]
1. I'll fox this asap
2. WHERES THE DUPLICATE?

**Comment by TheKillerTacos** [comment]
Fox? or fix? haha

**Comment by Aericio** [comment]
I didn't see another duplicate... so I made this sorry.

**Comment by robske110** [comment]
Fix will be submitted in a few hours.
And @thebigsmileXD wheres the duplicate?

**Comment by thebigsmileXD** [comment]
Can't find it. Maybe i saw it somewhere else.

**Comment by jasonwynn10** [comment]
then remove the duplicate tag!

**Comment by robske110** [comment]
BTW this is fixed

**Comment by Aericio** [comment]
lol. thanks for fixing though.
