### ISSUE TITLE
Readme.MD

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#342]
![image](https://cloud.githubusercontent.com/assets/16523741/13894978/2c68deb4-ed2b-11e5-84f0-93975ffd237b.png)
Unofficial, not Inofficial.

**Comment by Aericio** [comment]
fix meslef

**Comment by robske110** [comment]
Its inoffical

**Comment by thebigsmileXD** [comment]
http://wikidiff.com/unofficial/inofficial

**Comment by TheKillerTacos** [comment]
I just learnt something new today!
