### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#344]
http://pastebin.com/6ykzeEEp
It says Error: Out of memory but why does it say tried to allocate 268MB and allocated 120MB but crashes but the computer allows ClearSky 2GB ram? Sometimes, its only on 100MB and the server just says "bin\php\php.exe: Segmentation fault"? The only time it goes above 300MB is if someone is flying around loading a lot of chunks but its not often.
```
Fatal error: Out of memory (allocated 1097072640) (tried to allocate 268435456 bytes) in phar://D:/GMMCPE/Plots/ClearSky.phar/src/pocketmine/level/Level.php on line 1456
[16:48:47] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:48:47] [Server thread/EMERGENCY]: Please upload the "D:\GMMCPE\Plots\crashdumps/CrashDump_Fri_Mar_18-16.48.47-AKDT_2016.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
It also says level.php so I don't think its about how much memory is allowed in the Pocketmine.yml so... any help? Also, the Fatal error message happens only sometimes and the php.exe/bin whatever thing happens way more often and doesn't unload plugins but generates a crash file.

**Comment by TheKillerTacos** [comment]
Upload the pocketmine.yml on pastebin or something

**Comment by thebigsmileXD** [comment]
Check if you set a memory limit in php.ini.

**Comment by Aericio** [comment]
Memory limit is 4000M in php.ini. Thats 4GB?

**Comment by robske110** [comment]
Increase main hard limit to 4096 and in php ini replace 4000 with 4096

**Comment by thebigsmileXD** [comment]
or -1

**Comment by Aericio** [comment]
Ok. I'm trying it, waiting for results. In a plugin, its set to restart the server at 1500M. Do I have to remove that also so it doesn't conflict or something?

**Comment by TheKillerTacos** [comment]
Set autoreport to false, since this is CS not PM, 3Gb= 3072mbs, also check if you got PHP Binaries x64  or x86,

**Comment by Aericio** [comment]
I switched it to true on accident, autoupdater was supposed to be set on true. I made it false now. I put 3072MB now. And how do I check if my php binaries are x64 or x86?

**Comment by TheKillerTacos** [comment]
your sistem is 32 bits i think, or is it  64 bits? however, check at bin/php5/phpconfig, and check that says 32bits or 64bits something like:

prefix="/var/lib/jenkins/jobs/PHP-PocketMine-Windows/workspace/compile/linux/**32bit**/bin/php5"

**Comment by thebigsmileXD** [comment]
set hard limit in config to -1

**Comment by Aericio** [comment]
@TheKillerTacos 64bit computer.
![image](https://cloud.githubusercontent.com/assets/16523741/13996821/8f98cee4-f0ec-11e5-8ee4-37665b1d3a29.png)
I guess its php5?
@thebigsmileXD Okay

**Comment by thebigsmileXD** [comment]
@Aericio pocketmine.yml

**Comment by Aericio** [comment]
Okay.

**Comment by TheKillerTacos** [comment]
haha, forgot it was windows, but try reinstalling Clearsky **with the installer** not the phar.

**Comment by Aericio** [comment]
Use ClearSky's own installer?  I'll set the memory to that.

**Comment by Aericio** [comment]
woops lol

**Comment by robske110** [comment]
Can anyone close this now? This is not a ClearSky issue!

**Comment by Aericio** [comment]
I guess i'll try to find the plugin that is causing it to crash. It crashes less though now.
