### ISSUE TITLE
Translation Esp, is not showing on installer!

### ISSUE THREAD

**Issue by TheKillerTacos** [ClearSkyTeam/ClearSky#345]
So yea, After i translated CS to spanish, i asked my self, how ill it show up in the installation lang list? so thats the question, How it would show?
![screenshot from 2016-03-18 21-24-22](https://cloud.githubusercontent.com/assets/14338036/13896418/2182cac6-ed50-11e5-88a5-6dc240b8a8b3.png)

**Comment by thebigsmileXD** [comment]
I think there are extra installer languages files.

**Comment by TheKillerTacos** [comment]
.ini's? there are 2 in Installer and locale, it might be a script somewhere, i guess, but placing esp on the pocketmine.yml does work (obviously since is in the lang files).

**Comment by robske110** [comment]
You have to name it spa to make ther server recognise it

**Comment by TheKillerTacos** [comment]
I said when i made the pull request. "Should i name it spa.ini or esp.ini?" so ill try that.

**Comment by MasterWolf** [comment]
@TheKillerTacos do as you want. but esp is right.

**Comment by robske110** [comment]
spa is right
pocketmine has it so too

**Comment by SalmonGER** [comment]
@robske110 but why is deu.ini not ger.ini if it's spa.ini?

**Comment by robske110** [comment]
Donmt ask me

**Comment by TheKillerTacos** [comment]
Well, so renaming the file will show up on the installer?

**Comment by thebigsmileXD** [comment]
Give it a try ;)

**Comment by robske110** [comment]
Fixed in PR #389
