### ISSUE TITLE
Function returns an string

### ISSUE THREAD

**Issue by robske110** [ClearSkyTeam/ClearSky#347]
```php 
Player::getCurrentExperience()
``` 
returns an string WHY?

**Comment by robske110** [comment]
Ok
```php
Player::getExperience()
```
works

**Comment by robske110** [comment]
Why?

**Comment by TheKillerTacos** [comment]
He hates you..... probably, hehehe

**Comment by Aericio** [comment]
He disapproves that your fixing too many things :3

**Comment by robske110** [comment]
Ok, I'll fix this now

**Comment by thebigsmileXD** [comment]
Wait. You said getExperience is correct.

**Comment by robske110** [comment]
Yeah but not getCurrentExperience

**Comment by thebigsmileXD** [comment]
isn't this just internal?

**Comment by robske110** [comment]
Then it should be private (I'll check this now)

**Comment by robske110** [comment]
Hmm it's defined as LONG

**Comment by robske110** [comment]
But in fact that should be private
