### ISSUE TITLE
Boat always sinking

### ISSUE THREAD

**Issue by jjplaying** [ClearSkyTeam/ClearSky#348]
When you enter a boat which is in water, it always sinks and drops you out.

**Comment by robske110** [comment]
Confirmed

**Comment by thebigsmileXD** [comment]
Partly confirmed. sometimes they stay on top..

**Comment by jjplaying** [comment]
Yes, sometimes you don't sink, but I didn't found out when.

**Comment by thebigsmileXD** [comment]
Maybe after leaving them or after pushing them

**Comment by aodzip** [comment]
the fix of pressure plate (bounding box offset) also fix this

**Comment by aodzip** [comment]
It was cause the boat cant detect wether is it in water
