### ISSUE TITLE
Dispenser + Dropper (Or duplicate?)

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#354]
![image](https://cloud.githubusercontent.com/assets/16523741/14002144/2c09e758-f107-11e5-9e48-73203425e39c.png)
![image](https://cloud.githubusercontent.com/assets/16523741/14002149/3835cf24-f107-11e5-833e-fa8eaa885a0e.png)
Both are named `Dispenser` but their supposed to be `Dispenser` and `Dropper`
Or it could be duplicated on accident.

**Comment by thebigsmileXD** [comment]
:O they are duplicated.. thx

**Comment by Aericio** [comment]
I think its supposed to be Dispenser on the Left and Dropper on the Right.
Left:
![image](https://cloud.githubusercontent.com/assets/16523741/14028592/92698432-f1ba-11e5-9f5f-b993d168d126.png)

Right: 
![image](https://cloud.githubusercontent.com/assets/16523741/14028579/88f5ac8c-f1ba-11e5-87cb-b234b08f1a17.png)
But its wrong texture

**Comment by thebigsmileXD** [comment]
idont think so..

**Comment by Aericio** [comment]
Go on single player it was that. I'm not completely sure though.
