### ISSUE TITLE
Mobs and Animals not spawning

### ISSUE THREAD

**Issue by rivermigue** [ClearSkyTeam/ClearSky#355]
Hello,

Mobs and animals are not spawning, I'm using the latest phar build located here http://jenkins.clearskyteam.org/job/ClearSky/lastStableBuild/
I've been flaying all the world and wasn't able to find any mob or animal, how can animals spawn?
I'm using centos 6.5 64bits

**Comment by robske110** [comment]
Animals spawning isn't implemented yet :)

**Comment by thebigsmileXD** [comment]
@rivermigue Duplicate.
But we are about to create automatic mob spawning. They won't move anyways

**Comment by rivermigue** [comment]
Yeah, I know its duplicated when I found other answers here, therefore I closed it.
Thank you for your answers, is this AI issue something in general or just for ClearSky?

**Comment by thebigsmileXD** [comment]
General.

**Comment by robske110** [comment]
There is a AI branch, but it cannot do anything (probaly crashing)
