### ISSUE TITLE
Cannot use pocketmine\nbt\tag\Float

### ISSUE THREAD

**Issue by rivermigue** [ClearSkyTeam/ClearSky#356]
Hello,

I just did a search on this error and it may be linked to the phar file not supporting php7
I currently have php7 installed and compiled using this https://github.com/PocketMine/php-build-scripts/blob/master/compile.sh

I've downloaded the latest ClearSky phar version and whenever I want to start it I receive this error message:
25.03 10:12:41 [Server] INFO Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///clearsky.phar/src/pocketmine/Server.php on line 87

The front page says that PHP7 is supported now, and the php7 version I have works good with ImagicalMine what the issue could be?

**Comment by jjplaying** [comment]
It seems like an error because current ClearSky PHAR is on PHP 5.6, there is a PHP 7 branch: https://github.com/ClearSkyTeam/ClearSky/tree/php7

**Comment by jjplaying** [comment]
But I think it's not working yet

**Comment by Aericio** [comment]
ClearSky isn't going to support php7. On that /tree/php7, scroll down and it says:
![image](https://cloud.githubusercontent.com/assets/16523741/14051937/963327de-f283-11e5-8483-bae4e85037e5.png)
Download php 5 and try running it. It should run with php 5.
