### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fdfdffdf** [ClearSkyTeam/ClearSky#359]
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar://C:/Users/carlf_000/Desktop/ClearSky/ClearSky.phar/src/pocketmine/Server.php on line 87
help?

**Comment by fdfdffdf** [comment]
does anyone know?

**Comment by robske110** [comment]
Please use php5 binaries and close this

**Comment by robske110** [comment]
Please use php5 binaries and close this
https://github.com/ClearSkyTeam/PHPbinary
