### ISSUE TITLE
REDSTONE TOOL NOT WORK 0.14.0

### ISSUE THREAD

**Issue by kipra** [ClearSkyTeam/ClearSky#362]
i've tried to search if there any way to solve this. idk, only my poor knowledge or what, but, i really confuse about, i can't use any redstone tool (dispenser, repeater, etc).

i started server,  i played in new creative world,when i check to inventory .creattive mode, there are many things deleted like MOB eggs, and redstone tool. 
i only can use RedstoneLight, Redstone Torch, and Redstone It self. the other thingss about redstone tool are gone (repeater, etc), and when i try to put dispenser on block, its blinking, and after a milisecond, its gone.. 
idk its kind of blocked item or setting from the owner ? 
please, dont block any redstone item

i wanted to create redstone creation in my server, and i want to easyly spawn MOB in my server. how can i fix this ?? also i can't programming. :( all help will apreciated.

i using ClearSky-Sunrise version 1.1 (API 1.13.1) Build 153 for v0.14.x beta/alpha

**Comment by kipra** [comment]
i' just will wait the develepor now :) i know its so hard

**Comment by robske110** [comment]
1. Use a newer build (availible here: jenkins.clearskyteam.org)
2. some redstone items aren't implemented yet

**Comment by kipra** [comment]
wow quick respon ! thanks. i've tried it and it was better . keep it up.
but, like u said, some redstone not ilmplemented yet, hope  it will
fixed soon :)

2016-03-28 1:50 GMT+07.00, Tim (robske_110) <notifications@github.com>:

**Comment by robske110** [comment]
We are already working on the new redstone items
Be sure to keep your ClearSky UpToDate

**Comment by thebigsmileXD** [comment]
Next time check out other issues first.
For example the 0.14.0 Todo list.

**Comment by thebigsmileXD** [comment]
And shut the fuck up with CAPS

**Comment by kipra** [comment]
of course i will !!

2016-03-28 18:15 GMT+07.00, Dan <notifications@github.com>:

**Comment by kipra** [comment]
i'm so sorry about that. i'm new with github :3

2016-03-29 1:04 GMT+07.00, Rizky Pratama <rizky00797@gmail.com>:

**Comment by kipra** [comment]
okay okay.. easy man easy..  i just dont know what i've done...

2016-03-29 1:05 GMT+07.00, Rizky Pratama <rizky00797@gmail.com>:
