### ISSUE TITLE
CS build 2016-01-21 Error when server is being closed

### ISSUE THREAD

**Issue by nonbe102** [ClearSkyTeam/ClearSky#37]
[Server] [05:08:57] [INFO]: [Zed: Set the time to 0]
[Server] [05:10:16] [INFO]: Zed can't take it anymore!
[Server] [05:10:27] [INFO]: ● Zed left.
[Server] [05:10:27] [INFO]: Zed[/192.168.1.8:19132] logged out due to client disconnect
[Server] [05:10:27] [INFO]: There are 0/10 players online:
[Server] [05:10:27] [INFO]: 
>stop
[Server] [05:10:32] [INFO]: [CONSOLE: Stopping the server]
[Server] [05:10:43] [INFO]: Disabling EconomyAPI v2.0.9
[Server] [05:10:44] [INFO]: Disabling iProtector v3.1a
[Server] [05:10:44] [INFO]: Disabling CustomAlerts v1.6
[Server] [05:10:44] [INFO]: Disabling ServerAuth v2.11
[Server] [05:10:44] [INFO]: Disabling LightningOnDeath v1
[Server] [05:10:44] [INFO]: Disabling PurePerms v1.2.2
[Server] [05:10:44] [INFO]: Disabling EssentialsPE v1.1.3
[Server] [05:10:44] [INFO]: Disabling PureChat v1.3.3
[Server] [05:10:44] [INFO]: Unloading level "2"
[Server] [05:10:45] [ERROR]: Error while unloading a chunk: Argument 2 passed to pocketmine\level\Level::dropItem() must be an instance of pocketmine\item\Item, integer given, called in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/entity/Painting.php on line 38 and defined
[Server] [05:10:45] [NOTICE]: InvalidArgumentException: "Argument 2 passed to pocketmine\level\Level::dropItem() must be an instance of pocketmine\item\Item, integer given, called in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/entity/Painting.php on line 38 and defined" (E_RECOVERABLE_ERROR) in "/src/pocketmine/level/Level" at line 1599
[Server] [05:10:45] [EMERGENCY]: Crashed while crashing, killing process
[Server] [05:10:45] [INFO]: Stopping other threads
[PocketMine] Server was stopped.

**Comment by thebigsmileXD** [comment]
Should be fixed now

**Comment by thebigsmileXD** [comment]
Thanks to @MCPEPIC

**Comment by nonbe102** [comment]
thanks
