### ISSUE TITLE
Worlds

### ISSUE THREAD

**Issue by ZaurioKS** [ClearSkyTeam/ClearSky#370]
How i can load all worlds in the server start?. thanks

**Comment by TheKillerTacos** [comment]
Use a multiworld plugin from pocketmine, Make sure its compatible with API 1.3.0 and with PHP5 i guess

**Comment by TheKillerTacos** [comment]
Close this issue, Not CS Related ;p

**Comment by robske110** [comment]
You even can add worlds in pocketmine.yml

**Comment by TheKillerTacos** [comment]
What? so thats the maps: thingy for, hehe, Now I can load multiple maps, sorry for not knowing :|

**Comment by ZaurioKS** [comment]
Thanks robske110, but where is this in the yml.

**Comment by SalmonGER** [comment]
@ZaurioKS https://github.com/ClearSkyTeam/ClearSky/blob/master/src/pocketmine/resources/pocketmine.yml#L119

**Comment by thebigsmileXD** [comment]
"worlds" at the bottom

**Comment by MaryVictoria** [comment]
see attachment..

**Comment by ZaurioKS** [comment]
i get it, but i try:

world:
 seed: 404
 generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)

...and level doesn´t load, can anyone give me an example please?. Thanks for replies

**Comment by MaryVictoria** [comment]
world:
seed: 404
generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)
PvPworld: []
City: []
etc: []

**Comment by ZaurioKS** [comment]
Thanks, i tried and the problem was funny, i need some spaces in code. Closed.
