### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Skull3x** [ClearSkyTeam/ClearSky#375]
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar://C:/Users/jross/Desktop/ClearSky-Server/ClearSky.phar/src/pocketmine/Server.php on line 87

Is my issue, just installed and thought I was ready to go and then this happens

**Comment by TheKillerTacos** [comment]
Run as Admin the start.cmd? and try Downloading again the LATEST version of CS

**Comment by SalmonGER** [comment]
Isn't this a PHP7 Issue?

**Comment by Skull3x** [comment]
It still happens

**Comment by Skull3x** [comment]
![clearskyerror](https://cloud.githubusercontent.com/assets/15986189/14268115/6fbfbd22-faa5-11e5-8149-a597ac6544e7.PNG)

**Comment by TheKillerTacos** [comment]
Well, @thebigsmileXD has been updating CS, so wait for him

**Comment by robske110** [comment]
Oh come on:
You have php7 binaries installed. Grab php5 bin folder and try it again!

**Comment by thebigsmileXD** [comment]
I have updated nothing.

**Comment by robske110** [comment]
Please close this.

**Comment by Skull3x** [comment]
I thought it required php7

**Comment by Skull3x** [comment]
nvm, yes please close this
