### ISSUE TITLE
AIs not working

### ISSUE THREAD

**Issue by KairusDarkSeeker** [ClearSkyTeam/ClearSky#381]
Hi, I would like to suggest some things for the clear sky team to make mobs move the thing is its so hard to import it because the code is on [Organization's EntityManager](https://github.com) I wouldn't try porting it but soon I will join ClearSkyTeam and make it better when I mastered PHP cuz I suck

**Comment by thebigsmileXD** [comment]
Do people even read the readme and the main issue?
