### ISSUE TITLE
/dist-upgrade command not working 

### ISSUE THREAD

**Issue by KairusDarkSeeker** [ClearSkyTeam/ClearSky#385]
When I use /dist-upgrade it doesn't show updates at all even if there's a new update

**Comment by robske110** [comment]
Well known issue &dist upgrade will never work @aodzip 
But we have some issues with update/checkng too.

**Comment by KairusDarkSeeker** [comment]
On the older builds its not like this

**Comment by robske110** [comment]
https://github.com/ClearSkyTeam/ClearSkyStable/commit/db30cb42bdc7dcf54385a6061c644a15a6e0c3bb

**Comment by Aericio** [comment]
"Close" -robske110's famous statement.

**Comment by Aericio** [comment]
He ignores me lol

**Comment by robske110** [comment]
Close is not completely right here, as this is not fixed

**Comment by thebigsmileXD** [comment]
"Close" -robske110's famous statement.
