### ISSUE TITLE
CPU

### ISSUE THREAD

**Issue by Varfalomey** [ClearSkyTeam/ClearSky#388]
On my VDS cores of 8 , the server is loaded to 100% and the kernel uses only 2
where to set ?

**Comment by SkygridRex** [comment]
@Varfalomey in PocketMine.yml set async-workers to 8

**Comment by thebigsmileXD** [comment]
Maybe read the readme? And isn't load issue a duplicate?

**Comment by SkygridRex** [comment]
@thebigsmileXD i don't understand you

**Comment by thebigsmileXD** [comment]
I dont know why

**Comment by robske110** [comment]
Close
