### ISSUE TITLE
update to mcpe 15.0

### ISSUE THREAD

**Issue by lolcraftboy14** [ClearSkyTeam/ClearSky#391]

**Comment by aodzip** [comment]
is there any available 15.0 apk?

**Comment by TheKillerTacos** [comment]
0.15.0a3 i guess, on Aptoide :L

**Comment by aodzip** [comment]
If anyone can send me one , I will start update work

**Comment by TheKillerTacos** [comment]
i havent tested it neither heard any info at Mojang

**Comment by lolcraftboy14** [comment]
protcol is 60 but y cant join

**Comment by TheKillerTacos** [comment]
Its first realms update. You need Xbox live to join in but I don't see any other features

**Comment by lolcraftboy14** [comment]
Y now

**Comment by lolcraftboy14** [comment]
But cant join on my server

**Comment by TheKillerTacos** [comment]
https://www.dropbox.com/s/nllqyibkbbch8vd/mcpe0.15.0a2.apk?dl=1
This link is just the apk FOR testing purpose

**Comment by lolcraftboy14** [comment]
Oke

**Comment by lolcraftboy14** [comment]
When doe you tink its ready

**Comment by Syntaxious** [comment]
I tried joining my test server using ClearSky and didn't let me connect?

**Comment by thebigsmileXD** [comment]
Sure, other protocol

**Comment by lolcraftboy14** [comment]
y now but online it say it the protocol

**Comment by thebigsmileXD** [comment]
Sorry, what did you try to say? @lolcraftboy14

**Comment by lolcraftboy14** [comment]
@thebigsmileXD wen is it done ?

**Comment by thebigsmileXD** [comment]
0.15 isnt out yet. Features are still getting added.

**Comment by TheKillerTacos** [comment]
@lolcraftboy14 sine MCPE 0.15 its alpha, we need to Wait for BETA, so Main Developers start adding the stuff of the version, so lets wait for MC:PE Developers to finish up

**Comment by remotevase** [comment]
0.14.2 protocol is 60, and since it's alpha 3, I assume that the 0.15 A3 protocol is 63

**Comment by TheKillerTacos** [comment]
@remotevase the Latest Alpha its 4 (0.15.0a4)

**Comment by remotevase** [comment]
Ah, so would it be 64, then?

**Comment by TheKillerTacos** [comment]
but i guess protocol changes since Realms, @remotevase i guess
