### ISSUE TITLE
Clearsky + EssentialsPE = PlayerQuitEvent lag.

### ISSUE THREAD

**Issue by andris155** [ClearSkyTeam/ClearSky#392]
![13035427_1194438390589779_1832716416_o](https://cloud.githubusercontent.com/assets/8324198/14536282/e1e3b36c-0271-11e6-9f8c-3ad811300cf8.png)

**Comment by robske110** [comment]
EssentialsPE's fault

**Comment by thebigsmileXD** [comment]
Not sure about that

**Comment by andris155** [comment]
Imagicalmine, Pocketmine + EssentialsPE = works perfectly
Clearsky + EssentialsPE = generate player left lags.

**Comment by thebigsmileXD** [comment]
I will check this. But i don't have enough players to test the full load. How many players do you have on your server?

**Comment by andris155** [comment]
40-50

**Comment by thebigsmileXD** [comment]
:C 1-14

**Comment by robske110** [comment]
I have one thought, the api functions of set EXP lagg as shit
Maybe its that

**Comment by thebigsmileXD** [comment]
everyone who uses Essentials please do timings for 10 minutes, i want to compare

**Comment by thebigsmileXD** [comment]
http://timings.aikar.co/?url=15848412

Even better:
http://timings.aikar.co/?url=15848716
