### ISSUE TITLE
Clearsky php 5 files download Linux 64 bit?

### ISSUE THREAD

**Issue by andris155** [ClearSkyTeam/ClearSky#393]

**Comment by TheKillerTacos** [comment]
If you can use the [Installer](, or download the Binaries here: https://github.com/alex2534alex/ClearSky-INSTALL_FILES/blob/master/php5_linux_x64.tar.gz

**Comment by TheKillerTacos** [comment]
And please close this issue :D

**Comment by andris155** [comment]
Thanks!
