### ISSUE TITLE
Other players invisible

### ISSUE THREAD

**Issue by robske110** [ClearSkyTeam/ClearSky#399]
When you get teleported to a world with a plugin while you already were in the world, the other players become invisible!
ClearSky: Latest
MCPE: 0.14.1 (occuring since UNKNOWN)

**Comment by Aericio** [comment]
Like reloading a plugin to add the plugin to a server and your in the server?

**Comment by Aericio** [comment]
I don't get this glitch. how to get?

**Comment by robske110** [comment]
If you have a plugin wich has /worldtp <levelName> (or sth like that) and you enter /worldtp Lobby and then again /worldtp Lobby, then you will not ser other players anymore

**Comment by robske110** [comment]
it does

**Comment by thebigsmileXD** [comment]
Haven't have this in ages now.

**Comment by Aericio** [comment]
Same
