### ISSUE TITLE
Paint related i think?

### ISSUE THREAD

**Issue by isoz** [ClearSkyTeam/ClearSky#40]
[ERROR]: Error while unloading a chunk: Argument 2 passed to pocketmine\level\Level::dropItem() must be an instance of pocketmine\item\Item, integer given, called in phar:///root/pmine/ClearSky.phar/src/pocketmine/entity/Painting.php on line 38 and defined
[02:57:51] [NOTICE]: InvalidArgumentException: "Argument 2 passed to pocketmine\level\Level::dropItem() must be an instance of pocketmine\item\Item, integer given, called in phar:///root/pmine/ClearSky.phar/src/pocketmine/entity/Painting.php on line 38 and defined" (E_RECOVERABLE_ERROR) in "/src/pocketmine/level/Level" at line 1599

Doesnt seem to be doing anything but, getting that often

**Comment by MCPEPIG** [comment]
It was fixed. Update your ClearSky...

**Comment by isoz** [comment]
I guarantee you I'm using the latest release.

**Comment by MCPEPIG** [comment]
Your not up to date with the repo. Your using the phars.

**Comment by thebigsmileXD** [comment]
There is no release for the latest version, but the source folder is up to date. Your version is too old!

**Comment by meetloaf13** [comment]
Hey guys, I'm a minecraft n00b to be sure.  MCP made a statement above, "not up to date with the repo, just the phars".

How do I get my entire server setup up to date completely, I've only been updating the phars.

Thanks!

**Comment by aodzip** [comment]
FIxed and Released
