### ISSUE TITLE
Telegram Group Invite Invalid [readme.md]

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#400]
![image](https://cloud.githubusercontent.com/assets/16523741/14771325/3744c658-0a23-11e6-9525-eec18980e3bd.png)

**Comment by robske110** [comment]
Known issue, Telegram's issue

**Comment by Aericio** [comment]
oh okay

**Comment by Aericio** [comment]
but can i have a link to the telegram ? :D

**Comment by robske110** [comment]
Hmm. Gonna ask again...

**Comment by Aericio** [comment]
Okey :D

**Comment by thebigsmileXD** [comment]
@aodzip Only you can fix it.

**Comment by thebigsmileXD** [comment]
Fixed

**Comment by Aericio** [comment]
k
