### ISSUE TITLE
W10 Build at spawn issue

### ISSUE THREAD

**Issue by c-hri-s** [ClearSkyTeam/ClearSky#401]
Using a Windows 10 client you cannot build in close proximity to your spawn point - the blocks disappear when placed.

Using an iPad client on the same map you can build right where you spawn (i.e. in the same place where the blocks previously vanished)

I'm not running any protection plugins or mods.

Using the latest build of CS. 
ClearSky 1.1 [Sunrise] implementing API version 1.13.1 (protocol version 40)

**Comment by thebigsmileXD** [comment]
Are you maybe OP on your iPad?
is the Spawn radius higher than 0?

**Comment by c-hri-s** [comment]
Sorry - that was it.
I wasn't Op on the Windows 10 client since a name change.
