### ISSUE TITLE
Growing/RandomTicking blocks

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#407]
Growing:
- [x] Cocoa
- [x] Wheat
- [x] Carrot
- [x] Potato
- [x] Melonstem
- [x] Melons
- [x] Pumpkinstem
- [x] Pumpkin
- [x] Saplings
- [x] Netherwarts
- [x] Grass block spreading
- [x] Grass block "dying" (turning into dirt)
- [x] Cactus
- [x] Sugarcanes

**Comment by thebigsmileXD** [comment]
Nether wart wrong growstages

**Comment by thebigsmileXD** [comment]
Bonemeal on cacti and sugarcane bugs

**Comment by robske110** [comment]
I need that grass spreadong, I'll do that soon ;)

**Comment by stayandwait** [comment]
Grass still generates underwater, I'm using the most current build 451

**Comment by stayandwait** [comment]
@thebigsmileXD and this hasn't been fixed in case your wondering. I created a NEW world.

**Comment by thebigsmileXD** [comment]
Are you sure that you use the generator branch? i don't think so.

**Comment by thebigsmileXD** [comment]
Grass spreading fixed? I dont actually know, who can test?

**Comment by thebigsmileXD** [comment]
Actually tried new methods. DaylightSensor as example ticks when its tile is initalized. We should use that method for blocks that continousely ticks

**Comment by thebigsmileXD** [comment]
Only remaining issue: Farmland. #410 . Its okay to close this issue.
