### ISSUE TITLE
Rewrite Liquid.php

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#411]
Can anyone help rewriting liquids?

https://hub.spigotmc.org/stash/projects/CATS/repos/craftbukkit/browse/src/main/java/net/minecraft/server/BlockFlowing.java?at=e1586e017aa8082a9fe404825c012ace889ff026

this would be the source i'd like to translate..

Liquid flow in PM + forks is SLOW AS HELL, lags, and there are several bugs. (incorrect flowing, liquids don't decay anymore, cobble generates where it shouldn't, source blocks disappear when flown into from above)

**Comment by robske110** [comment]
I'll help

**Comment by robske110** [comment]
Cam you provide a link where the most liquid calc in pm is?

**Comment by thebigsmileXD** [comment]
Its Liquid.php https://github.com/ClearSkyTeam/ClearSky/blob/master/src%2Fpocketmine%2Fblock%2FLiquid.php

**Comment by robske110** [comment]
Omg. That looks realy messed up

**Comment by robske110** [comment]
The water+lava management is finished, but the water flow calculation is too complicatrd

**Comment by SkygridRex** [comment]
@thebigsmileXD You never change?
If you wanna rewrite Liquid.PHP based in bukkit code you need add other files for work corecctly

**Comment by thebigsmileXD** [comment]
@SkygridRex The correct code is on Spigot

**Comment by thebigsmileXD** [comment]
#630

**Comment by thebigsmileXD** [comment]
Give it up.
