### ISSUE TITLE
0.14.2 clients can't connect | Outdated Server

### ISSUE THREAD

**Issue by sero583** [ClearSkyTeam/ClearSky#419]
So as the title already says, 0.14.2 MC:PE isn't able to connect, it says for some reason, just 'Could not connect: Outdated server!', i'll use the latest committed build, but still it don't work.

**Comment by ZizzyZizzy** [comment]
Confirmed. The client does show "0.14.2" in green for the server, but you cannot connect.

I'm curious if they are fixing the slew of other issues with the new protocol. ImagicalMine has updated so you can connect with 0.14.2, but it has a ton of bugs, such as not being able to break or place blocks or interact with signs:

https://github.com/ImagicalMine/ImagicalMine/issues/231447

**Comment by sero583** [comment]
@ZizzyZizzy By me the version number is showing up in 0.14.2, but not in the green color too.

**Comment by robske110** [comment]
We're already working on it. The latest version should make it green (PR is still waiting to get merged) but there are massive changes

**Comment by Pandaken** [comment]
Just curious, but what makes 0.14.2 not capable of joining any 0.14.0 server? (0.14.1 was capable, all this new update just does is fix bugs??)

**Comment by thebigsmileXD** [comment]
@Pandaken Protocol changed. They can join now, but placing breaking interacting with blocks will not work.

**Comment by thebigsmileXD** [comment]
https://bugs.mojang.com/browse/MCPE-14242

**Comment by remotevase** [comment]
ImagicalMine fixed

**Comment by robske110** [comment]
No?!

**Comment by remotevase** [comment]
yes. In the latest build that was released

**Comment by jjplaying** [comment]
Sorry, but I can't see any commit to IM newer than 9 hours ago?, and that's the join fix :)

**Comment by thebigsmileXD** [comment]
They did not fix the error.

**Comment by robske110** [comment]
No, just relooked at the commits

**Comment by remotevase** [comment]
It's not titled properly, but I have been able to connect

**Comment by jjplaying** [comment]
Sure, that's already fixed, but problems like block placing / breaking (https://github.com/ImagicalMine/ImagicalMine/issues/231447)

**Comment by thebigsmileXD** [comment]
I delete unused +invalid messages

**Comment by robske110** [comment]
We just fixed the connection, too

**Comment by HimbeersaftLP** [comment]
Yeah, but not the blocks problem

**Comment by robske110** [comment]
Now fixed completly. Close
