### ISSUE TITLE
SnowLayer placement needs fixes. Resets to 1 layer after chunk reload

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#423]

**Comment by Landy005** [comment]
Hello, 
Our server has updated to the latest update and we got several reports of snow melting. Previously we had the same with ice. But since we use a lot of snow layers in our modern homes (2kx2k city) the damage has been dramatically going up. Meanwhile i stopped the server and have tired to look for a rollback of the city. How more vanilla the game is and how more block updates there are how less limited we are with creating our structures and interiors.  Is there a way to implement a toggle for this? And maybe also for ice and how for instance grass can be placed on every block?
Thanks,
Landy

**Comment by Landy005** [comment]
And btw with world edit you can make snow layered to each level without it dissapearing after reload.

**Comment by thebigsmileXD** [comment]
pocketmine.yml, add the id's of the blocks to disable-blockticking-for

**Comment by Landy005** [comment]
Alright, thanks alot for your help kepe up the good work guys :)

**Comment by Landy005** [comment]
i guess in clearksy this is called disabled-randomly-ticking-blocks or am i looking at the wrong setting?

**Comment by robske110** [comment]
yes

**Comment by thebigsmileXD** [comment]
@Landy005 it will be renamed again, when ticking gets better options

**Comment by Landy005** [comment]
when i add this to the list the server is not able to startup i know it's alot but we need all of the blocks without blockupdates though.[12,12:1,13,37,38,38:1,38:2,38:3,38:4,38:5,38:6,38:7,38:8,31,31:1,31:2,31:3,31:4,79,147,83,330,193,194,195,196,197,96,96:4,96:8,96:9,96:10,96:11,167,167:4,167:8,167:9,167:10,167:11,65:1,65:2,65:3,65:4,65:5,65:6,65:7,65:8,65:9,65:10,65:11,65:12,32,59:1,59:2,59:3,59:4,59:5,59:6,59:7,26,26:1,26:2,26:3,26:4,26:5,106,106:1,106:2,106:3,106:4,106:5,106:6,106:7,106:8,106:9,106:10,106:11,106:12,124,127,127:1,127:2,127:3,127:4,127:5,127:6,127:7,131,131:1,131:2,131:3,131:4,131:5,131:6,131:7,131:8,131:9,131:10,131:11,131:12,145,145:3,247,247:1,247:2,246,51,8,9,10,11,90,23,23:1,23:2,23:3,23:4,23:5,23:6,23:7,23:8,23:9,23:10,23:11,23:12,158,158:1,158:2,158:3,158:4,158:5,158:6,158:7,158:8,158:9,158:10,158:11,158:12,78,78:1,78:2,78:3,78:4,78:5,78:6,78:7,18,18:1,18:2,18:3,161,161:1,62,255,162,162:1,162:2,162:3,162:4,162:5,162:6,162:7,162:8,162:9,162:10,162:11,162:12,70,72,77,143,69,69:1,69:2,69:3,69:4,69:5,69:6,69:7,69:8,69:9,69:10,69:11,69:12,69:13,69:14,69:15,69:16,69:17,69:18,69:19,69:20,171,171:1,171:2,171:3,171:4,171:5,171:6,171:7,171:8,171:9,171:10,171:11,171:12,171:13,171:14,171:15,101,102]

**Comment by thebigsmileXD** [comment]
Remove all the meta shit. Even the pocketmine.yml comment says:
Put the id's

**Comment by thebigsmileXD** [comment]
And to completely remove updates set per-chunk to 0

**Comment by thebigsmileXD** [comment]
*per tick in chunk ticking

**Comment by Landy005** [comment]
Okay, thank you

**Comment by thebigsmileXD** [comment]
Currently unable to fix due to the client bug.
