### ISSUE TITLE
Implement skylight

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#424]
When calling that function nothing happens. Even the function calling this function does seem to return

**Comment by robske110** [comment]
To return?

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
@robske110 it just returns.. you know.. i mean like it continues like never been called

**Comment by thebigsmileXD** [comment]
omg oops

**Comment by TheKillerTacos** [comment]
Hahah! WTF?

**Comment by Aericio** [comment]
Robske... was the bug thebigsmileXD's spam?

**Comment by robske110** [comment]
It's bugged

**Comment by thebigsmileXD** [comment]
@aodzip you fixed some light calculation.. can you look at this

**Comment by robske110** [comment]
It works for me. I don't know how it can return nothings.

**Comment by thebigsmileXD** [comment]
@robske110 You worked on this, any news to REAL light, or still only that shitty test is block above transparent?

**Comment by robske110** [comment]
Working on real light. Have observerd and wrote down how light works in MCPC. Branch already created :)
