### ISSUE TITLE
Tips are being displayed at the wrong position

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#432]
Tips dont appear on 0.14.2

**Comment by robske110** [comment]
MCPE problem, I'll look into it, but it seems if you get a tip and then open your chat window, you'll see it so it's a client problem

**Comment by Driesboy** [comment]
popup work

**Comment by robske110** [comment]
yes

**Comment by thebigsmileXD** [comment]
How do they now just without any change work?

**Comment by Driesboy** [comment]
popup work tip dont work

**Comment by robske110** [comment]
They do atlas show up now
