### ISSUE TITLE
MCPE itself or CS?

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#433]
When you type a percentage sign (x% ~ x can be any number) in chat, it will show when your in the chatting bar menu, but when you go back in game and there is the chat box, it just shows x, not x%.
![image](https://cloud.githubusercontent.com/assets/16523741/14908542/35a22940-0d74-11e6-9bf3-06fd03148a7e.png)
![image](https://cloud.githubusercontent.com/assets/16523741/14908549/441b082a-0d74-11e6-9944-e38d7ea176e7.png)
Can just be MCPE, or can be CS. Pretty sure its MCPE though, but I don't know what handles chat so don't get mad at me if its not CS's problem.

**Comment by thebigsmileXD** [comment]
Client

**Comment by robske110** [comment]
Mcpe 0.14.2 is messing with the chat :(

**Comment by Aericio** [comment]
ikr robske :(

**Comment by Aericio** [comment]
And its still here in 0.15.2... >:(
