### ISSUE TITLE
How do you update this for server.pro?????

### ISSUE THREAD

**Issue by Alextheserverowner** [ClearSkyTeam/ClearSky#435]
I downloaded the latest version of clearsky I puted it on the server here is proof(https://cloud.githubusercontent.com/assets/18748510/14934438/d4995580-0ea7-11e6-8909-132511f46b7d.jpeg)

**Comment by Aericio** [comment]
You can't manually update in server.pro, they do it themselves. Or they will update on the next Stable release. (and why server.pro lol)

**Comment by Alextheserverowner** [comment]
How do you make a server with you then?

**Comment by Aericio** [comment]
Simple, but not simple if you want friends to join. Home host the server, you can find tutorials on how to do this. Then, just replace Pocketmine-MP.phar with ClearSky's phar. (rename ClearSky's phar to Pocketmine-MP.phar) or use clearsky's installer if it works. If you want other friends to join, then learn how to port forward.

**Comment by robske110** [comment]
I'm closing this, as this does not seem to be a issue
