### ISSUE TITLE
Anvil worlds have sign problem's

### ISSUE THREAD

**Issue by Landy005** [ClearSkyTeam/ClearSky#436]
The signs don't get converted well:
http://imgur.com/wRIBLst

Original sign was: 
line1:middle
line2:
line3:
line4:

This world is anvil loaded on clearsky.

**Comment by robske110** [comment]
That's 1.8/1.9
We cannot fix this, as this is normally parsed by the client, but MCPE does nor support this.
You could write a plugin analysing these strings for each sign and then remove/repair these lines

**Comment by Landy005** [comment]
i was thinking the same thing, someone making a plugin to fix those things but i'm not a developer :/
