### ISSUE TITLE
Freeze when 0.14.0 joins, Crash when 0.14.1 joins

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#437]
Maybe because packets are different (things added/removed to/from packet encoding/decoding)

Maybe only allow 1 version.

**Comment by robske110** [comment]
Currently we only allow one version?
Or did someone merge my PR

**Comment by thebigsmileXD** [comment]
Even with only 1 version allowed

**Comment by robske110** [comment]
Oh

**Comment by robske110** [comment]
Not happening anymore to me

**Comment by thebigsmileXD** [comment]
you want to verarschen me, right? I JUST send a screenshot of a freeze into the group YESTERDAY

**Comment by robske110** [comment]
But that onw wasn't related to wrong client joining

**Comment by robske110** [comment]
And i tried to reproduce it but i can't

**Comment by robske110** [comment]
I still can't reproduce this

**Comment by thebigsmileXD** [comment]
PHP7 works fine
