### ISSUE TITLE
Open Chest Crash Minecraft

### ISSUE THREAD

**Issue by RenanGamerz** [ClearSkyTeam/ClearSky#440]
I Open The Chest And Minecraft Crash and this not is the minecraft i tested what you need to help me?

i use this plugins 

 1vs1 v0.0.5, Alias v1.2.0, AlwaysSpawn v2.2.2, BouncyBlocks v1.1, BuyCraft v1.2.2, Cameraman v1.1, ClearLagg v1.1.0, CmdSnooper v1.0.0, CombatLogger v1.2.0, CraftingTableFix v2.0-Alpha, DevTools v1.10.0, EasyMOTD v1.0a, EconomyAPI v2.0.9, EconomyAuction v2.0.2, EconomyCasino v2.0.2, EconomyJob v2.0.4, EconomyLand v2.0.9, EconomyPotionDispenser v0.0.2, EconomyProperty v2.0.6, EconomyPShop v2.0.2, EconomySell v2.0.7, EconomyShop v2.0.7, EconomyTax v2.0.3, EconomyUsury v1.0.1, EssentialsPE v1.1.3, FactionsPro v1.3.2, iProtector v3.1b, ItemCasePE v1.0.8, itemID_DoDo v1.1.0, JoinCommands v1.4.1, KitPro v4.1, ManyWorlds v2.0.3, MultiTP v1.0.0, NoAdvertisingPE v1.0.0, NoExplode v1, ImportMap v2.2-1.5upd2, PurePerms v1.3.7, RestartMe v1.2.0, seat v2.1.0, ServerAuth v2.11, ServerMail v0.0.2, SimpleMessages v1.2, Slapper v1.2.9.1, TimeCommander v2, VoteBan v1.0.3, VoteReward v3.0.2, WorldEditArt v1.0.0_beta_dev_#048, xRulesx v1.0.0, EconomyAirport v2.0.4, PureChat v1.3.3, SimpleWarp v2.1.0, HungerGamesDoDo v3.0.0, SkyWarsDoDo v1.0.0 Reloaded

**Comment by c-hri-s** [comment]
Same here.

Tested with W10 client and no plugins.

**Comment by thebigsmileXD** [comment]
Can you try build 414?

**Comment by c-hri-s** [comment]
Still happens on: http://jenkins.clearskyteam.org/job/ClearSky/lastSuccessfulBuild/artifact/*zip*/archive.zip

**Comment by c-hri-s** [comment]
FWIW it crashes the W10 client, not the server.

The console says nothing except that the user 'logged out due to timeout'

Still a problem with #418

**Comment by robske110** [comment]
Windows 10, still didn't find any soloution

**Comment by c-hri-s** [comment]
Crashes iPad 0.14.2 client for me also when opening chest.

**Comment by RenanGamerz** [comment]
In Android is crashing when opening chest =( i host my server in win10

**Comment by robske110** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/8e4efde6b4e6ccade70216e96cce5591e7e251e1
