### ISSUE TITLE
Server does not appear online to client (you can join)

### ISSUE THREAD

**Issue by RenanGamerz** [ClearSkyTeam/ClearSky#443]
The server dies not appear 'online/green' in the mcpe client server/world list
This is happening since @robske110's RakLibFix

**Comment by robske110** [comment]
Does it work with build 421?

**Comment by RenanGamerz** [comment]
no

**Comment by RenanGamerz** [comment]
after this occurred # 418

**Comment by RenanGamerz** [comment]
# 418 works

i need the #421

**Comment by RenanGamerz** [comment]
or # 422

**Comment by RenanGamerz** [comment]
Do you need any more information?

**Comment by robske110** [comment]
I can't rlly figure out what's wrong. We did a RakLib update though, but it works for me

**Comment by RenanGamerz** [comment]
what do I do now? = (

**Comment by RenanGamerz** [comment]
I tried to restart my computer tried rebooting my wifi I downloaded more than 20 times file and do not know What do I do more = (

**Comment by robske110** [comment]
Hmm.
Can you send me your server ip

**Comment by RenanGamerz** [comment]
ok

**Comment by RenanGamerz** [comment]
playpixel.ddns.net

**Comment by RenanGamerz** [comment]
port is 19132

**Comment by RenanGamerz** [comment]
appear online?

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/BannerForMCPE/MainCode(PHP)/banner1.php?host=playpixel.ddns.net

**Comment by RenanGamerz** [comment]
for me the server is turned off and my friends also
You need screenshot ?

**Comment by robske110** [comment]
Try to join it

**Comment by RenanGamerz** [comment]
works but how people will know that this open server?

**Comment by robske110** [comment]
Now i finally do understand you.
The server doesn't show green/online in the client server/world list

**Comment by RenanGamerz** [comment]
that

**Comment by RenanGamerz** [comment]
Now you will try to fix it ?

**Comment by robske110** [comment]
Now that i did finally understand the issue, yes I'll look into it

**Comment by RenanGamerz** [comment]
thanks

**Comment by RenanGamerz** [comment]
and I'm sorry for not being able to explain very well

**Comment by Aericio** [comment]
Less people are on my server because of this... and their complaining that its offline lmao

**Comment by robske110** [comment]
We're already working on this, the fix will be out today.

**Comment by robske110** [comment]
Fixed
