### ISSUE TITLE
Server doesn't work on OS X

### ISSUE THREAD

**Issue by juniorRubyist** [ClearSkyTeam/ClearSky#445]
I just downloaded your program, downloaded the binary for PHP7 from PocketMine here: [BinTray](https://bintray.com/pocketmine/PocketMine/Unix-PHP-Binaries/view), renamed it to `php5`, and ran the set-up perfectly. Then, it says after `[*] PocketMine-MP will now start. Type /help to view the list of avilable commands.`, 

```
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in /Users/joseph/ClearSky/src/pocketmine/Server.php on line 87
```

What is the problem?

I have OS X Lion (10.7) with x86-based processor.

**Comment by robske110** [comment]
You need to use php5

**Comment by juniorRubyist** [comment]
I don't have access to a PHP5 binary.

**Comment by juniorRubyist** [comment]
@robske110 Could you push a PHP5 binary or do we have to DIY.

**Comment by robske110** [comment]
such os du you have?

**Comment by juniorRubyist** [comment]
You can politely close the issue i just opened. Sorry.

**Comment by Aericio** [comment]
You can close it yourself too lol.
