### ISSUE TITLE
PHP5 Binaries not available for Mac OS X/Linux

### ISSUE THREAD

**Issue by juniorRubyist** [ClearSkyTeam/ClearSky#446]
I just downloaded your program, downloaded the binary for PHP7 from PocketMine here: BinTray, renamed it to php5, and ran the set-up perfectly. Then, it says after [*] PocketMine-MP will now start. Type /help to view the list of avilable commands.,

Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in /Users/joseph/ClearSky/src/pocketmine/Server.php on line 87

I learned that i need a PHP5 binary, **but where are they?**
I have OS X Lion (10.7) with x86-based processor.

**Comment by robske110** [comment]
look in #445

**Comment by robske110** [comment]
You could either install an old version from pocketmine.net
or grab mine here:
http://robskebueba.no-ip.biz/SomeOtherStuff/Start.shANDbin.zip
