### ISSUE TITLE
Puffer Fish Causes crash?

### ISSUE THREAD

**Issue by jasonwynn10** [ClearSkyTeam/ClearSky#448]
Fatal error: Undefined class constant 'pocketmine\item\Fish::FISH_PUFFERFISH' in phar://C:/Users/jason/PocketMine-MP Factions/PocketMine-MP.phar/src/pocketmine/tile/Tile.php on line 68
[15:29:37] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by robske110** [comment]
Please set debug level to 2 in pocketmine.yml and then send the new error message

**Comment by MCPEPIG** [comment]
This is fixed.

**Comment by Aericio** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/4911e312fede9c366a461be2b31e64d45f94bbfc

**Comment by Aericio** [comment]
Don't you remove the tags? @robske110 lol
