### ISSUE TITLE
Players cannot connect to server getting blocked for 5 seconds message in debug

### ISSUE THREAD

**Issue by stayandwait** [ClearSkyTeam/ClearSky#454]
I just updated the server to the latest phr (ClearSky Build #409) and now this is what I get whenever someone connects.

[02:38:23] [RakLibServer thread/NOTICE]: Blocked 192.168.0.101 for 5 seconds
[21:38:24] [Server thread/INFO]: JuniorHero joined the game

**This hasn't happened in the past.**

**Comment by robske110** [comment]
Strange, we're getting multiple reports on this, but we can't reproduce it

**Comment by Aericio** [comment]
@robske110 Does debug level 2 help at all? (And on build #425, I don't think its a problem)

**Comment by robske110** [comment]
Yes it does help, and i think some random versions were broken but the last should work

**Comment by c-hri-s** [comment]
I still get this error with #443 

Debug level 2: http://pastebin.com/gxtPc5Pj

**Comment by c-hri-s** [comment]
Fixed in #444 - thanks
