### ISSUE TITLE
Grass generates underwater

### ISSUE THREAD

**Issue by stayandwait** [ClearSkyTeam/ClearSky#455]
When you create a new world and you go to a large lake, there will be grass at the button. Grass used to generate underwater in the older versions of MCPE but no longer does.
![2016-04-29_1909](https://cloud.githubusercontent.com/assets/15825041/15374237/462cc236-1d17-11e6-80b1-7cfcbbfdc506.png)

**Comment by SkygridRex** [comment]
It's generator fault

**Comment by Aericio** [comment]
Like multiworld? or whatever plugin it is

**Comment by robske110** [comment]
Does it 'die' then and wich build are you using

**Comment by thebigsmileXD** [comment]
@robske110 https://github.com/ClearSkyTeam/ClearSky/issues/407

**Comment by TheKillerTacos** [comment]
This is a PM Generator error, in CS it hasnt been updated, ill "Try" if i every try to, change the generator and make a better one for CS, but ill just see if i "can", and Its not Multiworld Error either other plugin

**Comment by thebigsmileXD** [comment]
It HAS been changed in the generator branch.. since.. 3 weeks!

**Comment by robske110** [comment]
Should i pull the change from the generator branch?

**Comment by thebigsmileXD** [comment]
@robske110 no.

**Comment by thebigsmileXD** [comment]
Fixed via 8b006f56b26ed1ce42e5f6b3990ea582e5cb03c0

**Comment by thebigsmileXD** [comment]
TODO: fix gravel islands
