### ISSUE TITLE
Unable to place blocks

### ISSUE THREAD

**Issue by scot99** [ClearSkyTeam/ClearSky#456]
#447, can mine but not place blocks, disappear immediately when placed, block count goes down then up.

**Comment by robske110** [comment]
MCPE version?

**Comment by Pub4Game** [comment]
Check Nukkit, I fix it

**Comment by robske110** [comment]
again protocol changes ugh, fine

**Comment by robske110** [comment]
fixed with https://github.com/ClearSkyTeam/ClearSky/commit/a2aba3fdab3c284fd44db51741bb2bc75a202671
