### ISSUE TITLE
Generator: ToDo + discussion

### ISSUE THREAD

**Issue by NycuRO** [ClearSkyTeam/ClearSky#459]
hello :) I noticed that you have a branch that binds generator :) want to help him? I know how to add biomes in generator and I would be very happy if you can help. Here a picture with a creation of mine and a change and I would be very proud if I could
![screenshot_2016-04-30-17-34-52](https://cloud.githubusercontent.com/assets/13573011/15510806/aa81638a-21e1-11e6-96b1-56bf5ceec012.png)

![screenshot_2016-05-02-11-25-27](https://cloud.githubusercontent.com/assets/13573011/15510707/46132ed8-21e1-11e6-88fb-cdc2fe870d81.png)

**Comment by thebigsmileXD** [comment]
well, first look they are good.. some seconds later i was like: wtf, spruce acacia (already done), the mesa is cool, there really are many flowers etc.

strange stuff.

we are working on villages and new kinds o trees.

**Comment by NycuRO** [comment]
Is not spruce Acacia ,is dark oak log . Trees is working fucking hard. Idk how... 

Villages needs mobs. Without mobs not generate villages.
But,my question is : i can help? :)

**Comment by robske110** [comment]
Why without mobs no generation of the structure of a village?
You can start off with a few PRs to the generator branch, and if you'r work is good we'll add you to the team
-

**Comment by thebigsmileXD** [comment]
and.. the fist screenshot shows acacia ;)

**Comment by NycuRO** [comment]
@robske110  sorry,i don't understand. you mean start working on the map after you think I did something to show you or what?

**Comment by NycuRO** [comment]
??

**Comment by Aericio** [comment]
Just wait.

**Comment by thebigsmileXD** [comment]
I checked out our generator branch finally. I would LOVE to have your mesa biome, and there are several bugs like biome borders are like walls, oceans look dumb, too many trees in hills+ almost no stone in that, caves go down to bedrock, taiga biomes are only the non snowy ones and the mossy cobblestone patches are only 1 block, under the podzol are 3 layers of mossy cobblestone, no jungle biome yet, way too many cacti, sugarcane + cacti placed where they couldnt even be, cacti + sugarcane are sometimes really huge etc

**Comment by thebigsmileXD** [comment]
And the terrain generation at all looks weird

**Comment by thebigsmileXD** [comment]
Welcome to the team. Lets keep this issue to talk about the bugs

**Comment by robske110** [comment]
Welcome!

**Comment by NycuRO** [comment]
Thanks :)

**Comment by NycuRO** [comment]
But,i have one idea. you have facebook or what's up , we could do a group where we can discuss and solve some problems :)

**Comment by robske110** [comment]
We already have a group in Telegram
Go check out the readme for the join link

**Comment by robske110** [comment]
And i don't have facebook and hate whatsapp so scratch that pls

**Comment by NycuRO** [comment]
Ok

**Comment by Aericio** [comment]
![image](https://cloud.githubusercontent.com/assets/16523741/15632105/9332e466-2523-11e6-90c9-2a25b8532443.png)
Fix that lol

**Comment by NycuRO** [comment]
Ok

**Comment by thebigsmileXD** [comment]
lel da island

**Comment by thebigsmileXD** [comment]
will you post mesa to cs?

**Comment by NycuRO** [comment]
no. srry.

**Comment by Aericio** [comment]
Is this done 10% complete already

**Comment by Aericio** [comment]
:3
