### ISSUE TITLE
Can't consume Enchanted apple

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#46]
@MCPEPIG May you have a look into it? /give X enchanted_golden_apple works, can't consume them and getting raklib block

**Comment by MCPEPIG** [comment]
Same here when I try to eat it while I'm at full hunger, it won't work but works without full hunger

**Comment by thebigsmileXD** [comment]
@MCPEPIG found it.
 $eatItem instead of  $eatenItem

**Comment by MCPEPIG** [comment]
That's not it, there's a pair of parenthesis that shouldn't be there. I'll dix

**Comment by MCPEPIG** [comment]
Made a pull request.
