### ISSUE TITLE
Command::unregister() doesnt work

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#460]

**Comment by robske110** [comment]
What did you use to call it?

**Comment by MCPEPIG** [comment]
$this->getServer()->getCommandMap()->getCommand("op")->unregister($this->getServer()->getCommandMap()); on enable

**Comment by thebigsmileXD** [comment]
the bug is onEnable. i think atleast. Class still loads and you try to stop it. Try to delay it.

**Comment by MCPEPIG** [comment]
Still doesn't work.

**Comment by MCPEPIG** [comment]
Maybe because it doesn't remove the command from the command map's knowncommands array?

**Comment by MCPEPIG** [comment]
I made a pull request to fix this.
