### ISSUE TITLE
Command::setAliases() doesn't seem to work

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#463]
After being ran, the aliases stay the same.

**Comment by thebigsmileXD** [comment]
Works as intended.

**Comment by MCPEPIG** [comment]
Not for me. When I tried to set the aliases for /tell to blank, the aliases stayed.

**Comment by thebigsmileXD** [comment]
> to blank

Problem solved.

**Comment by thebigsmileXD** [comment]
Closed: Incorrect usage of SetAlias

**Comment by MCPEPIG** [comment]
By blank, i mean a empty array.

**Comment by MCPEPIG** [comment]
Ive also tried with an array with "test" in it.

**Comment by MCPEPIG** [comment]
And didnt work.

**Comment by thebigsmileXD** [comment]
Read the docs. They help you to understand how the api is used.
