### ISSUE TITLE
Minecraft :: Windows 10 Crafting not supported

### ISSUE THREAD

**Issue by indianbhaji** [ClearSkyTeam/ClearSky#472]
Hello,

If Minecraft : Windows 10 is meant to be supported by ClearSky then here:

I believe that crafting on Minecraft : Windows 10 isn't supported. I'm unsure whether this is a PocketMine issue or a ClearSky issue, but the crafting system does not work as intended. When you go to craft something, the output is normal, except when you go to retrieve the output, you are either:
a) Given the output, then given back the original and the output is removed
b) Given back the input

If Minecraft : Windows 10 isn't supported, then I shall just stick with minigames! 
Thanks!

**Comment by robske110** [comment]
We are working on a bugfix for this but as for now we can't say when we get this to work.
So it's not like we don't want to support Win10 crafting it's just that we right now can't

**Comment by thebigsmileXD** [comment]
Also.. cant get items in creative mode to hotbar... after like.. 3 times it works

**Comment by indianbhaji** [comment]
Perfectly fine! It's just not clearly marked that ClearSky is actually being designed for PE and Windows 10.

**Comment by Aericio** [comment]
@thebigsmileXD The item you take our and place in your hotbar has to be the one you are currently holding. ex: on Slot 9, have to place item on Slot 9.

**Comment by robske110** [comment]
Look at the win10-fixes branch

**Comment by thebigsmileXD** [comment]
#549

**Comment by thebigsmileXD** [comment]
json recipes: added or todo? @dktapps do you still want to rewrite that whole thing?

**Comment by thebigsmileXD** [comment]
#549
