### ISSUE TITLE
Hoppers.

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#473]
Minecraft: PE Single Player > Off Server
![image](https://cloud.githubusercontent.com/assets/16523741/15695567/2b9a1928-2744-11e6-85ba-5cc0c933d04e.png)

Minecraft: PE ClearSky > On Server
![image](https://cloud.githubusercontent.com/assets/16523741/15695631/bef1982c-2744-11e6-9f83-ca1f33a8faf5.png)
When I place the hopper to the block, it instantly turns back to when it on down.
![image](https://cloud.githubusercontent.com/assets/16523741/15695651/0431d596-2745-11e6-9d29-5e8e995cc704.png)
Even if I place it to a chest, it instantly points down.

**Comment by thebigsmileXD** [comment]
I know. They have no code yet, they are just blocks.

**Comment by Aericio** [comment]
Ohhh... I see.

**Comment by robske110** [comment]
dan, please close this if it's fixed

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/0ff1e73fcfcaf58fc5b7c070f4783b769abc55c6

**Comment by Aericio** [comment]
Finally :D

**Comment by thebigsmileXD** [comment]
Yea sry that it took so long lol
