### ISSUE TITLE
/banlist ips

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#474]
When I do /banlist ips, it shows me all the IP's banned, but when I went to look at the total number of IP's banned, it said:
`[18:50:34] [Server thread/INFO]: There are %d total banned IP addresses:`
It should have said something more like:
`[69:69:69] [Server thread/INFO]: There are 1000 total banned IP addresses:`
It shows perfectly fine on /banlist players (shows the number of players banned)
`[18:53:45] [Server thread/INFO]: There are 847 total banned players:`

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/ClearSky/blob/master/src/pocketmine/lang/locale/esp.ini#L107
%d -> {%0}

**Comment by Aericio** [comment]
I am using English version btw.

**Comment by Aericio** [comment]
bruh .-. lmao

**Comment by Aericio** [comment]
wtf why is that there

**Comment by thebigsmileXD** [comment]
@Aericio Due to a mention of the issue
