### ISSUE TITLE
Server Freezing more than Normal.

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#477]
yayayayayy freezes i wud luv to not say it here since it can be the 0.14.0 join 0.14.3 freeze thing but i was previously on # 457?? or something but it auto-updated i think maybe to # 460 so yeah but from that to that, there weren't any code edits besides the reduce file size and my amazing readme.md edits. any help? sorry if this is that 0.14.0 join 0.14.3 freeze thing i got banned so. sorry for typing so horribly also i am lazy today

**Comment by robske110** [comment]
We know that freezes exist, we do not have a soloution, we may try to debug stuff with strace or valgrind soon. But this issue will be closed due to [DUPLICATE]
