### ISSUE TITLE
Bucket doesn't change image when taking water/lava

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#48]
^- but i can place and take the water.

**Comment by MCPEPIG** [comment]
It's cause it doesn't update the inventory when it does it, you should be able to fix it now ;)

**Comment by thebigsmileXD** [comment]
But after i drop the bucket (always writing bukkit..) and pick it up still appears as normal bucket.

**Comment by MCPEPIG** [comment]
Strange...

**Comment by MCPEPIG** [comment]
![image](https://cloud.githubusercontent.com/assets/8540562/12533321/40e0870e-c1e1-11e5-8a0e-c2a042ecfc36.png) It doesn't happen for me, I'm in the latest build.

**Comment by thebigsmileXD** [comment]
Hmm.. thats interesting

**Comment by thebigsmileXD** [comment]
@MCPEPIG i have this bug on a vanilla server

**Comment by aodzip** [comment]
Tested , no bug now
