### ISSUE TITLE
Transfer world

### ISSUE THREAD

**Issue by rivermigue** [ClearSkyTeam/ClearSky#481]
Hello there,

Does clear sky support my android MCPE world?
Can I just do a drag and drop of the world folder and upload it to my pocketmine server?

**Comment by thebigsmileXD** [comment]
Should, give it a try. PC worlds: https://www.youtube.com/watch?v=rjGfAzdk8Sw

**Comment by rivermigue** [comment]
Well, it didn't work, the world I have on the mobilo phone doesn't have any region folder, instead it has:
db <-- Folder
players <-- Folder
level.dat <-- File
level.dar_old <-- File

**Comment by robske110** [comment]
Look for a converter in the web
