### ISSUE TITLE
Brewing doesnt work

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#49]
When you're brewing something and you close the inventory, the items in the brewing stand disappear. Also, when I try to get the potion I brewed after its finished, it disappears when I hold it.

**Comment by thebigsmileXD** [comment]
xD

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/f0a743f9f7a40e8510f037c992a428c44f36673f read the title

**Comment by MCPEPIG** [comment]
Oops lmao
