### ISSUE TITLE
Lava > Obsidian

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#493]
Error shown in console:
```
cFH::doHarden() doHarden()
setObsidian()
Calculation ERROR::TYPE 0
```
Debug level 2 shows the same message as the error.
There is no error in the process of making it obsidian, though.

**Comment by robske110** [comment]
Hmm that Error occurs through an unknown level of water source in the calculations process.. will check

**Comment by robske110** [comment]
Ok, I can't really find the error here... Will simply remove that error message

**Comment by Aericio** [comment]
Awesome
