### ISSUE TITLE
Not a problem with ClearSky but..

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#498]
When I installed the php7 binary, it told me to install all these api-ms-win-crt-THING things and after I installed like 15 of them, it said:
![image](https://cloud.githubusercontent.com/assets/16523741/15995251/babfd02a-30b3-11e6-81f5-db7cfbbeda1a.png)
How do I fix this? All I wanted was to get php7 :( It worked fine on my Windows 10 computer, but it said that in my Windows 8 computer. Sorry for posting this not-clearsky issue thing.

**Comment by thebigsmileXD** [comment]
"api-ms-win-crt-THING" ?
Never saw that, give the error before you install it

**Comment by Aericio** [comment]
like api-ms-win-crt-runtime, api-ms-win-crt-enviorment, etc.

**Comment by thebigsmileXD** [comment]
I am almost sure you loaded the x86 instead of x64 or opposite

**Comment by Aericio** [comment]
x64 binaries? Or downloaded the wrong api-ms-win-crt-things?

**Comment by Aericio** [comment]
@SalmonGER fixed it for me :D

**Comment by SalmonGER** [comment]
Lol

**Comment by thebigsmileXD** [comment]
@SalmonGER how? xD

**Comment by SalmonGER** [comment]
@thebigsmileXD I just told him to install this C++ 2015 Redistributable thing 
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by thebigsmileXD** [comment]
I see..

**Comment by Aericio** [comment]
But did I really need to install all those ms api things? Or did I just need that?

**Comment by robske110** [comment]
I managed to get php7 running on windows without this mess

**Comment by Aericio** [comment]
It loaded perfectly fine on my personal PC running Windows 10 and my hosting PC running windows 8 had that problem. It also happened on my friends computer, so it was just missing the c++ thingy
