### ISSUE TITLE
Saturation not displayed on client

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#500]

**Comment by robske110** [comment]
? I don't have this...

**Comment by thebigsmileXD** [comment]
Well, i do. /effect speed and /effect saturation both dont work, hunger neither

**Comment by robske110** [comment]
php7 then....

**Comment by thebigsmileXD** [comment]
You setill use php5? and you wonder why you get ERR_TPS? You are cute.

**Comment by Aericio** [comment]
Saturation doesn't work in PHP7 for me either :)

**Comment by MCPEPIG** [comment]
Maybe because the speed/slowness effects use setMovementSpeed() and it no longer exists...

**Comment by MCPEPIG** [comment]
Just revert this... https://github.com/ClearSkyTeam/ClearSky/commit/8866b1022f8ddb23a68e7be10cd8bfbdd234cdd2

**Comment by thebigsmileXD** [comment]
setMovememtSpeed does exist

**Comment by MCPEPIG** [comment]
it doesn't...

**Comment by MCPEPIG** [comment]
It got removed

**Comment by thebigsmileXD** [comment]
Fun fact: somehow speed potions now work on my server

**Comment by robske110** [comment]
it seems to work for me... what does exactly not work?

**Comment by thebigsmileXD** [comment]
Slowness, for example.

**Comment by robske110** [comment]
@self TODO::re-confirm this

**Comment by thebigsmileXD** [comment]
not for me anymore
