### ISSUE TITLE
Fatal error: Call to a member function getChunk() on null

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#501]
`Fatal error: Call to a member function getChunk() on null in phar://C:/Users/imauserhello/Desktop/Plots/ClearSky.phar/src/pocketmine/level/Level.php on line 2746`
Happens near the stopping of the server, PHP7 version.

**Comment by Aericio** [comment]
After all plugins and worlds are unloaded, that happens right before it goes to segment fault. It doesn't show that, but after a minute it shows "Took to long to shut down, server was terminated". Not word by word, but something like that.

**Comment by thebigsmileXD** [comment]
I mean before unload

**Comment by Aericio** [comment]
Before stopping the server? All plugins got disabled without problem.

**Comment by thebigsmileXD** [comment]
BEFORE PLUGIN UNLOAD OR SEND CRASH DUMP

**Comment by Aericio** [comment]
There is no crash dump and nothing happened before plugin unload

**Comment by robske110** [comment]
Please send debug level 2 traceback

**Comment by Aericio** [comment]
I only got this once... i'll try to get a debug lvl 2 but it might take a long time

**Comment by robske110** [comment]
Much appreciated

**Comment by robske110** [comment]
Any news for the debug?

**Comment by Aericio** [comment]
No... :(

**Comment by Aericio** [comment]
Isn't happening again... I guess it could just be a plugin?

**Comment by thebigsmileXD** [comment]
I dont think worldgm, maybe something related to breakblockevent etc

**Comment by Aericio** [comment]
Close? I don't get it anymore.

**Comment by robske110** [comment]
I got it yesterday with debug lvl two on, but still no trace

**Comment by robske110** [comment]
https://github.com/iTXTech/Genisys/pull/1073
This is somehow related to this.
the level is closed but something calls loadChunk() idk what,maybe trigger a fake exception

**Comment by thebigsmileXD** [comment]
@robske110 wasnt that fixed via the entity-close-instead-of-kill thing?

**Comment by robske110** [comment]
@Aerico do you still experience this. This could also be a plugin fault

**Comment by Aericio** [comment]
I haven't had this for a while now.

**Comment by robske110** [comment]
Closing now
