### ISSUE TITLE
Add WeatherManager

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#504]

**Comment by robske110** [comment]
Actually, why should we

**Comment by thebigsmileXD** [comment]
-.-

**Comment by robske110** [comment]
Good answer

**Comment by Aericio** [comment]
All of his replies was just "-.-" for most of the issues.

**Comment by robske110** [comment]
-_-

**Comment by thebigsmileXD** [comment]
Because Multi world weather, simpler anti weather in nether, no more hilarious mess in level.php etc, and plugins can set/cancel weather events

**Comment by Aericio** [comment]
So like making it simpler for plugin creators?

**Comment by thebigsmileXD** [comment]
And core devs. And player multiworld handling

**Comment by robske110** [comment]
Dan, I have time now. I'd like to do this right now.

**Comment by robske110** [comment]
@thebigsmileXD As already said I can do this. Will probably start doing this in my 'Urlaub'.

**Comment by thebigsmileXD** [comment]
Look how Genisys implemented it, a good way
