### ISSUE TITLE
mcpe 0.15.0 is out ;D

### ISSUE THREAD

**Issue by lolcraftboy** [ClearSkyTeam/ClearSky#505]
y wis you luck

**Comment by NycuRO** [comment]
official out?

**Comment by lolcraftboy** [comment]
yes @NycuRO

**Comment by SalmonGER** [comment]
rip in protocol changes

**Comment by lolcraftboy** [comment]
y dont no @SalmonGER

**Comment by NycuRO** [comment]
@lolcraftboy you have telegram?

**Comment by lolcraftboy14** [comment]
@NycuRO no y dont

**Comment by HittmanA** [comment]
Any idea when a working stable build for 15.0 will be out? I really need it for my server!

**Comment by robske110** [comment]
Will take some time we have three options here:
-use IM's way: realy bad things will be buggy as fuck
-proper implement protocol like minet, will take some time
-send 0x04 on Join to disable encryption (idk if this works)

**Comment by SalmonGER** [comment]
MiNET style sounds better and safer.

**Comment by Aericio** [comment]
Why disable encryption? Also, does encryption do anything? Like for security or stuff

**Comment by robske110** [comment]
For example, hackers can't get the user passwords anymore

**Comment by Aericio** [comment]
Isn't that related to the authentication plugin?

**Comment by robske110** [comment]
No, hackers always were able to get the ChatPacket contents

**Comment by thebigsmileXD** [comment]
Wait.. Let me rofl hard. They can only do so, if they can get into he stream. Almost impossible due to: wether same network as the player, the dns or server.

**Comment by robske110** [comment]
And every server wich used to modify packets on the fly, well they've a problem

**Comment by HittmanA** [comment]
Yeah use Minets way. Sounds much better!

**Comment by daniktheboss** [comment]
So u guys are using minet way??

**Comment by robske110** [comment]
We're trying to port it

**Comment by HittmanA** [comment]
What is the latest build # for ClearSky?

**Comment by SzczepanPolska** [comment]
Please link to phar 0.15.0

**Comment by daniktheboss** [comment]
Are u joking? It's I'm development! So it's a src file!

**Comment by Aericio** [comment]
Its a src file unless you compile it on your own.

**Comment by robske110** [comment]
Now the 'offical' Statement:
WE WILL NOT SUPPORT 0.15 UNTIL PROPER ENCRYPTION AND DECRYPTION HAS BEEN WRITTEN
BY EITHER INTYRE, US (I think we're too dumb), OR ANYONE ELSE. KEY READING IS THE KEY.

**Comment by robske110** [comment]
Check php7-0.15.0 branch
