### ISSUE TITLE
Says "Server Full" when it isn't full

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#507]
I am using PHP7. After I wait a few minutes, I am able to login. I don't have CustomAlert also. Is it just client problem? It doesn't send the join thing to the server console, it just instantly puts it to "Server Full".

**Comment by robske110** [comment]
unable to reproduce...
Please give some more info

**Comment by Aericio** [comment]
I don't know what else info... thats it.

**Comment by thebigsmileXD** [comment]
Which version?

**Comment by Aericio** [comment]
PHP7... there isn't a version number on it.

**Comment by robske110** [comment]
Closing due to unable to reproduce

**Comment by Aericio** [comment]
It was kind of gone already, sorry
