### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#519]
Everyone has a custom skin, but everyones skin is alex. I checked my skin, and its using the Steve one, but on server it shows as Alex.

**Comment by robske110** [comment]
Hmm, ok we do not get the skin data properly then.

**Comment by robske110** [comment]
Found the mistake, will fix today

**Comment by Aericio** [comment]
Awesome :D

**Comment by robske110** [comment]
Plese check if this is fixed :)

**Comment by Aericio** [comment]
Okay, will do it now :D

**Comment by Aericio** [comment]
Sorry for late reply, my skin shows how it should be now :D

**Comment by robske110** [comment]
Entity movement has been fixed just now too :)

**Comment by Aericio** [comment]
Awesome :D
