### ISSUE TITLE
Water and lava problem

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/ClearSky#52]
when i try to place water and lava, it didn't flow. I dont know which plugin caused it. I cant do a Skyblock PE!!! Pls help me

**Comment by MCPEPIG** [comment]
Do you have MyPlot?

**Comment by Adam1609** [comment]
Yes i have MyPlot,

**Comment by thebigsmileXD** [comment]
Myplot and SkyBlockPE cause this bug.

**Comment by thebigsmileXD** [comment]
Due to MyPlot not working anyways its best to just remove
