### ISSUE TITLE
Fall Damage + Healing

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#520]
#### Fall Damage
When you fall, it does the thing where your skin becomes red from damage twice, like your screen moves a little twice, but it is supposed to only move once... do you know what i mean? Try jumping off something.
#### Healing
When you are healing, it does the thing when you take damage, but it still heals your hearts.

**Comment by robske110** [comment]
Is this php7 only? I think so, attributes are a work in progress there.

**Comment by robske110** [comment]
Seems the client does messy things, maybe client sided, i need to join my server finally

**Comment by Aericio** [comment]
Team at Mojang:

> We will fix bugs, while adding more bugs for a better experience!

**Comment by daniktheboss** [comment]
Lol

**Comment by thebigsmileXD** [comment]
Realms is the same.

**Comment by thebigsmileXD** [comment]
does not appear on fall damage anymore if it has been cancelled.

**Comment by thebigsmileXD** [comment]
May be the PlayerExhaustEvent.

**Comment by Aericio** [comment]
Fall damage thing still happens to me in 0.15.4

**Comment by Aericio** [comment]
Fall damage: still does it twice
Healing: fixed.
