### ISSUE TITLE
logical deadbush

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#521]
![image](https://cloud.githubusercontent.com/assets/16523741/16174459/67349c60-355e-11e6-88cf-4b7c6d925772.png)

Deadbush not on sand, floating deadbush too. Deadbush on other blocks, not sand only.

**Comment by thebigsmileXD** [comment]
"I am a floating deadbush"

**Comment by HuaYoyuDoge** [comment]
hmm,intering

**Comment by Aericio** [comment]
Isnt floating deadbush, wink wink

**Comment by MCPEPIG** [comment]
You are supposed to be able to place deadbushes on stained clay :P

**Comment by Aericio** [comment]
I never knew that, must be a new invention by MCPEPIG!

**Comment by thebigsmileXD** [comment]
Placing yes. But the air is wrong.

**Comment by Aericio** [comment]
Why are you allowed to place dead bush on stained clay? Doesn't make since lol

**Comment by thebigsmileXD** [comment]
Well lol.. mcpe tries to place them, server says no. I dont get floating deadbushes, the code is like torch or carpet etc.

**Comment by robske110** [comment]
Aerico, please provide a video

**Comment by Aericio** [comment]
Maybe it was fixed in some previous updates? It doesn't happen anymore :)
You said you are supposed to be able to be placed on stained clay, it doesn't allow it to be placed on stained clay anymore. Disappeared right when you place it.

**Comment by thebigsmileXD** [comment]
Confirmed

**Comment by thebigsmileXD** [comment]
@Aericio Farting deadbush maybe?

**Comment by Aericio** [comment]
wat?
