### ISSUE TITLE
Compiling .phar

### ISSUE THREAD

**Issue by HittmanA** [ClearSkyTeam/ClearSky#525]
I can not get DevTools to work for the life of me. Could someone please compile these two clear sky src folders into .phars for me please. Thank you in advance!

**Comment by HittmanA** [comment]
[src.zip](https://github.com/ClearSkyTeam/ClearSky/files/322505/src.zip)
[src.zip](https://github.com/ClearSkyTeam/ClearSky/files/322506/src.zip)

**Comment by thebigsmileXD** [comment]
DevTools php7 is on github https://github.com/PocketMine/DevTools/releases/download/v1.11.0/DevTools_v1.11.0.phar try with this 1

**Comment by HittmanA** [comment]
I used the one from Pm forums. But ok

**Comment by HittmanA** [comment]
It errors still. I installed the new devtools restarted my server deleted the ClearSky.phar that was already there and then did /makeserver and it says this:
2016-06-19 [17:00:09] [Server thread/CRITICAL]: Could not execute task PocketDockConsole\RunCommand: include(phar://E:\UserFiles\BENJAMINH3\GameServers\TC18022436873227481505060\PocketMine-MP.phar/src\pocketmine\event\TranslationContainer.php): failed to open stream: phar error: Cannot open phar archive "E:/UserFiles/BENJAMINH3/GameServers/TC18022436873227481505060/PocketMine-MP.phar" for reading

**Comment by HittmanA** [comment]
Anyone please help! If you can phar those files for me I would be extremely happy! Thanks in advance!

**Comment by daniktheboss** [comment]
Why can't u just use scr folder?

**Comment by Aericio** [comment]
Just use the scr folder... the phar is #CuttingEdge anyways, so there is no auto-update.

**Comment by HittmanA** [comment]
I tried using the src folder. It doesn't work at all. I doesn't log anything or show as online.
