### ISSUE TITLE
Create an easy installer for Windows and Android

### ISSUE THREAD

**Issue by SkygridRex** [ClearSkyTeam/ClearSky#526]
I need it specially for windows (windows 7), cause your windows installer only work with windows 8, 8.1 and 10

**Comment by robske110** [comment]
why? just grab a bin folder from bintray grab the src folder from one of the branches and grab the cmd

**Comment by SkygridRex** [comment]
Link?

**Comment by thebigsmileXD** [comment]
Readme?
