### ISSUE TITLE
Could not tick level "world": Bit shift by negative number

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#532]
Message: `[19:00:35] [Server thread/CRITICAL]: Could not tick level "Lobby": Bit shift by negative number`
When I was in game, I typed in commands and it didn't respond.

**Comment by robske110** [comment]
Never, ever heard of 'Bit shift by negative number'

**Comment by robske110** [comment]
debug lvl2 needed

**Comment by Aericio** [comment]
I'll try to get a debug level 2. Does dan know anything?

**Comment by robske110** [comment]
Idk @thebigsmileXD

**Comment by thebigsmileXD** [comment]
*ignores the issue.*

**Comment by robske110** [comment]
Closing due to NotEnoughInfo, if you get a debug lvl2 we may be able to fix this issue
