### ISSUE TITLE
MCPE Crash if unknown Blocks/Entities are sent by server

### ISSUE THREAD

**Issue by 2449673842** [ClearSkyTeam/ClearSky#533]
while the players were joining the game ,the game on their phone was stopping

**Comment by HuaYoyuDoge** [comment]
any crashdump?

**Comment by robske110** [comment]
See the try-to-fix-client-crash branch

**Comment by 2449673842** [comment]
ok
l,will try

**Comment by MCPEPIG** [comment]
The branch doesn't work.

**Comment by MCPEPIG** [comment]
You continue to crash.

**Comment by robske110** [comment]
I know, it's still WIP

**Comment by 2449673842** [comment]
I use the latest version, but it is still a question

**Comment by Heroata** [comment]
Because it's a MCPE Client problem

**Comment by kam187** [comment]
Found one problem.  It's entity 'Fire' set to 65535 when using converted PC worlds.  There still must be other issues though.

**Comment by thebigsmileXD** [comment]
The fire looks interesting.. Thanks

**Comment by TheBluePinguin1** [comment]
fixed in 0.16.0 by mojang

**Comment by robske110** [comment]
Oh, yes we never realized that
