### ISSUE TITLE
FloatingTextParticle no longer working

### ISSUE THREAD

**Issue by Guillaume351** [ClearSkyTeam/ClearSky#534]
There is only a shadow where the text should be. Server-side issue : InPvP fixed it (using MiNET)
(Was working with 0.14.3)

**Comment by robske110** [comment]
Show nametags flag

**Comment by Guillaume351** [comment]
@robske110 Doesn't work (I tried to add flag 0x20)

**Comment by HuaYoyuDoge** [comment]
@robske110  https://github.com/iTXTech/Genisys/commit/afb2a6be5ea41892f28df5e78eac069a397a6080
hope.this help

**Comment by robske110** [comment]
Already in the TODO list :P 
https://github.com/ClearSkyTeam/ClearSky/issues/413

**Comment by HuaYoyuDoge** [comment]
:DDD

**Comment by thebigsmileXD** [comment]
TODO: Change it to something else somehow, its a bit hacky to use item
