### ISSUE TITLE
Can't break blocks

### ISSUE THREAD

**Issue by SalmonGER** [ClearSkyTeam/ClearSky#535]
I can't break blocks. I tried everything but the block only dissapears for less than a second and then just comes back like nothing happened.

**Comment by daniktheboss** [comment]
Ur wifi?

**Comment by SalmonGER** [comment]
@daniktheboss Using LAN with a stable connection. But I need to update my description.
It does work sometimes but then it doesn't work again.

**Comment by SalmonGER** [comment]
This issue came up for me after the two latest commits in php7-0.15

**Comment by robske110** [comment]
My block update hack maybe

**Comment by thebigsmileXD** [comment]
Because you don't face at the blocks. Yaw/pitch fail.

**Comment by robske110** [comment]
@SalmonGER Can you test it now? I reverted my blockupdate hack.

**Comment by thebigsmileXD** [comment]
#notrelatedtoblockupdate

**Comment by robske110** [comment]
#ok

**Comment by SalmonGER** [comment]
Fixed @robske110
