### ISSUE TITLE
how to get the php 7 

### ISSUE THREAD

**Issue by mimi159** [ClearSkyTeam/ClearSky#542]
i have been trying really hard but i cant really get the whole php7 file so i can run the phar

**Comment by robske110** [comment]
https://github.com/ClearSkyTeam/ClearSkyPhar

**Comment by mimi159** [comment]
wait i need the php7 file not the phar

**Comment by SalmonGER** [comment]
You mean the bin folder?
https://dl.bintray.com/pocketmine/PocketMine/

**Comment by robske110** [comment]
And exactly that link is in the readme of that repository -_-
