### ISSUE TITLE
PlayerHungerChangeEvent is never called

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#545]

**Comment by SalmonGER** [comment]
Confirmed
(Look at the Telegram group if you're in it)

**Comment by Aericio** [comment]
![image](https://cloud.githubusercontent.com/assets/16523741/16360020/d424559e-3ae6-11e6-9d50-6a1dd101b71a.png)

**Comment by robske110** [comment]
Use PlayerExhaustEvent

**Comment by SalmonGER** [comment]
@robske110 What is the difference between those two?

**Comment by robske110** [comment]
The event was really old. Remeber that we still have problems with attributes in php5 and mostly php7. I'll remove the class to avoid confusion.

**Comment by SalmonGER** [comment]
rip PlayerHungerChangeEvent

**Comment by robske110** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/bb8120446a3f1b5c77805a1ef5560e8b71085529
