### ISSUE TITLE
No Fire Damage

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#546]
Go in fire, you won't take damage. Survival mode. You also don't get the fire effect... like the flame

**Comment by robske110** [comment]
What?

**Comment by Aericio** [comment]
Go in fire, you won't take damage. Survival mode. You also don't get the fire effect... like the flame

**Comment by robske110** [comment]
@thebigsmileXD you did sth with fire lately

**Comment by thebigsmileXD** [comment]
I get damaged.

**Comment by Aericio** [comment]
oh let me check my plugins maybe

**Comment by Aericio** [comment]
[video.zip](https://github.com/ClearSkyTeam/ClearSky/files/334151/video.zip)
?

**Comment by robske110** [comment]
May be a plugin
