### ISSUE TITLE
Rewrite Crafting

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#549]

**Comment by robske110** [comment]
partly done in the win10-fixes branch but it's still a shitload of mess there

**Comment by thebigsmileXD** [comment]
Using json like pocketmine?

**Comment by robske110** [comment]
No I don't like that idea

**Comment by thebigsmileXD** [comment]
I love the idea. Because then you always have the latest recipies from mcpe, and not from scratch

**Comment by SkygridRex** [comment]
@thebigsmileXD I like the idea

**Comment by Aericio** [comment]
What is he writing it to?

**Comment by Aericio** [comment]
@SkygridRex Yoke???

**Comment by robske110** [comment]
Json and so on. TODO: talk with @dktapps about this
