### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 2449673842** [ClearSkyTeam/ClearSky#550]
[Server thread/CRITICAL]: 计算地图「zy」时出现错误︰Object of class pocketmin                                                                                                                                                                                       e\nbt\tag\Compound could not be converted to int
How to solve this problem

**Comment by 2449673842** [comment]
Fatal error: Out of memory (allocated 1713897472) (tried to allocate 65488 bytes) in C:\                                                                                                                                                                                       Users\2449673842\Desktop\PocketMine1\src\pocketmine\Player.php on line 375

**Comment by robske110** [comment]
The first problem: I think that's a plugin's problem and the secound is maybe general memory leak or just not enough memory

**Comment by thebigsmileXD** [comment]
PHP5.
