### ISSUE TITLE
Client cannot connect to servers with ports ≥32768 - update raklib please

### ISSUE THREAD

**Issue by ZizzyZizzy** [ClearSkyTeam/ClearSky#551]
The php5 and php7 versions of 0.15 are having this issue regarding connecting to a server with a port  ≥32768:

https://github.com/PocketMine/RakLib/issues/16

raklib needs to be updated in the source repository.

**Comment by Aericio** [comment]
Just stick with 19132-19xxx... why need so high?

**Comment by robske110** [comment]
I seem to have removed this patch some months ago.
https://github.com/ClearSkyTeam/ClearSky/commit/7d1b19a4a29670a7e7f219c59ea94496fdc9bfcd
I will check this and eventually revert this commit

**Comment by robske110** [comment]
I had intoduced this in https://github.com/ClearSkyTeam/ClearSky/commit/63cd91e71d9e19a4aa9c8eab7f7d00af728bee1b#diff-a54cd7d83af599f7b058797c9d4fd1caR66 and then shortly after reverted it in https://github.com/ClearSkyTeam/ClearSky/commit/7d1b19a4a29670a7e7f219c59ea94496fdc9bfcd

**Comment by ZizzyZizzy** [comment]
@robske110 Thanks!

**Comment by robske110** [comment]
Ok will revert that commit

**Comment by robske110** [comment]
Fixed in the 0.15 branches
