### ISSUE TITLE
Rename tile -> blockentity

### ISSUE THREAD

**Issue by mixailenko5** [ClearSkyTeam/ClearSky#554]
Rename tiles to blockentity as https://github.com/iTXTech/Genisys/commit/a2f4995ce17c859d617baa7b8ba664202244b3e0 please.
For my opinion it's important fo plugin developers, because they like support of their plugins on all popular nucleis.

**Comment by Aericio** [comment]
Turning into Genisys 2.0 ._.

**Comment by mixailenko5** [comment]
@Aericio sorry, but Nukkit, Minet use blockentity too. And it ischange in namespaces only, not new codes and interfaces.

**Comment by SalmonGER** [comment]
Renaming would be bad for old plugins.
And if you have tile + blockentity like Genisys does it would just increase the file size.
Well, Iit's not necessary I think.

**Comment by mixailenko5** [comment]
@SalmonGER i think, that every person can change "tile" to "blockentity" in a old plugins. And also "tile" was a fake name of object, because there is "blocktile" in the original code of mcpe client.

**Comment by robske110** [comment]
We will not do this. Our api is always being aimed to be compatible with pocketmine. When pm uses setExp and genisys setExperience we can simply make a function that is redirecting, but this is not possibile in this case

**Comment by thebigsmileXD** [comment]
We will never rename this to java shit ;)
