### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by 2449673842** [ClearSkyTeam/ClearSky#555]
how to set animal ai

**Comment by robske110** [comment]
What?

**Comment by 2449673842** [comment]
Why animals in the game will not move

**Comment by 2449673842** [comment]
@robske110

**Comment by robske110** [comment]
because it's not implemented

**Comment by 2449673842** [comment]
ok

**Comment by 2449673842** [comment]
How to send an error report

**Comment by 2449673842** [comment]
ClearSky Crash Dump Tue Jun 28 21:32:00 CST 2016

Error: Object of class pocketmine\nbt\tag\Compound could not be converted to int
File: /src/pocketmine/utils/Binary
Line: 306
Type: notice

Code:
[297] 
[298] 	/**
[299] 	 * Writes a 16-bit signed/unsigned little-endian number
[300] 	 *
[301] 	 * @param $value
[302] 	 *
[303] 	 * @return string
[304] 	 */
[305] 	public static function writeLShort($value){
[306] 		return pack("v", $value);
[307] 	}
[308] 
[309] 	public static function readInt($str){
[310] 		if(strlen($str) != 4){
[311] 		 return 0;
[312] 		}
[313] 		if(PHP_INT_SIZE === 8){
[314] 			return unpack("N", $str)[1] << 32 >> 32;
[315] 		}else{
[316] 			return unpack("N", $str)[1];

Backtrace:
#0 /src/pocketmine/utils/Binary(306): pack(string v, integer 1)
#1 /src/pocketmine/nbt/NBT(561): pocketmine\utils\Binary::writeLShort(pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:102.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.})
#2 /src/pocketmine/nbt/tag/Short(19): pocketmine\nbt\NBT->putShort(pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:102.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.})
#3 /src/pocketmine/nbt/NBT(545): pocketmine\nbt\tag\Short->write(pocketmine\nbt\NBT object)
#4 /src/pocketmine/nbt/tag/Compound(77): pocketmine\nbt\NBT->writeTag(pocketmine\nbt\tag\Short pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:102.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.})
#5 /src/pocketmine/nbt/NBT(545): pocketmine\nbt\tag\Compound->write(pocketmine\nbt\NBT object)
#6 /src/pocketmine/nbt/NBT(464): pocketmine\nbt\NBT->writeTag(pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\String:ItemFrame.pocketmine\nbt\tag\Int:260.pocketmine\nbt\tag\Int:17.pocketmine\nbt\tag\Int:87.pocketmine\nbt\tag\Short:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:102.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.}.pocketmine\nbt\tag\Byte:0.pocketmine\nbt\tag\Float:1.})
#7 /src/pocketmine/tile/Spawnable(24): pocketmine\nbt\NBT->write(boolean)
#8 /src/pocketmine/tile/Spawnable(47): pocketmine\tile\Spawnable->spawnTo(pocketmine\Player Player(5))
#9 /src/pocketmine/tile/Spawnable(37): pocketmine\tile\Spawnable->spawnToAll(boolean)
#10 /src/pocketmine/tile/ItemFrame(26): pocketmine\tile\Spawnable->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\String:ItemFrame.pocketmine\nbt\tag\Int:260.pocketmine\nbt\tag\Int:17.pocketmine\nbt\tag\Int:87.pocketmine\nbt\tag\Byte:0.pocketmine\nbt\tag\Float:1.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:102.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.}.})
#11 /src/pocketmine/tile/Tile(68): pocketmine\tile\ItemFrame->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\String:ItemFrame.pocketmine\nbt\tag\Int:260.pocketmine\nbt\tag\Int:17.pocketmine\nbt\tag\Int:87.pocketmine\nbt\tag\Byte:0.pocketmine\nbt\tag\Float:1.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:102.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.}.})
#12 /src/pocketmine/level/format/generic/BaseFullChunk(151): pocketmine\tile\Tile::createTile(string ItemFrame, pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\Compound pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\String:ItemFrame.pocketmine\nbt\tag\Int:260.pocketmine\nbt\tag\Int:17.pocketmine\nbt\tag\Int:87.pocketmine\nbt\tag\Byte:0.pocketmine\nbt\tag\Float:1.pocketmine\nbt\tag\Compound:pocketmine\nbt\tag\Compound{.pocketmine\nbt\tag\Short:102.pocketmine\nbt\tag\Byte:1.pocketmine\nbt\tag\Short:0.}.})
#13 /src/pocketmine/level/Level(2772): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#14 /src/pocketmine/level/Level(2367): pocketmine\level\Level->loadChunk(integer 16, integer 5, boolean 1)
#15 /src/pocketmine/level/Level(3066): pocketmine\level\Level->getChunk(integer 16, integer 5, boolean 1)
#16 /src/pocketmine/Player(959): pocketmine\level\Level->populateChunk(integer 16, integer 5)
#17 /src/pocketmine/Player(1940): pocketmine\Player->sendNextChunk(boolean)
#18 /src/pocketmine/Server(2622): pocketmine\Player->checkNetwork(boolean)
#19 /src/pocketmine/Server(2348): pocketmine\Server->tick(boolean)
#20 /src/pocketmine/Server(2226): pocketmine\Server->tickProcessor(boolean)
#21 /src/pocketmine/Server(1820): pocketmine\Server->start(boolean)
#22 /src/pocketmine/PocketMine(446): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\2449673842\Desktop\PocketMine1\, string C:\Users\2449673842\Desktop\PocketMine1\, string C:\Users\2449673842\Desktop\PocketMine1\plugins\)

ClearSky version: 1.1 #CuttingEdge [Protocol 81; API 1.13.1]
uname -a: Windows NT VIP40 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

**Comment by 2449673842** [comment]
Don't blame me, I'm an English slag.

**Comment by thebigsmileXD** [comment]
@2449673842 is about to get blocked from the repo because he comments wrong stuff at wrong sections ;) but this issue relating: get an AI plugin
