### ISSUE TITLE
Translate item/block names too

### ISSUE THREAD

**Issue by SalmonGER** [ClearSkyTeam/ClearSky#556]
Is it possible to translate them too within the language file?
So if you change items in the hotbar it will show the name of the item in the choosen language and something like

`$id = 265;                                            
$item = Item::get($id)->getName();`

would say "Eisenbarren" if you use German

**Comment by SalmonGER** [comment]
I once saw on a server that those things were translated too

**Comment by robske110** [comment]
This can be easily done through a  plugin

**Comment by thebigsmileXD** [comment]
It already says "Eisenbarren", set language in pocketmine.yml to not forceor force it to german
