### ISSUE TITLE
Survival Inventory Save

### ISSUE THREAD

**Issue by aodzip** [ClearSkyTeam/ClearSky#56]

**Comment by thebigsmileXD** [comment]
As i said i might rewrite the inv class, i'll add that in

**Comment by aodzip** [comment]
I think with 0.14 , creative and survival 's inventory&hotbar should save too..

**Comment by thebigsmileXD** [comment]
They'll share the same inventory

**Comment by aodzip** [comment]
When player change modes won't remove their inventory?
I think this is useless in 0.14
And give plugins a event call if somebody want change this .

**Comment by thebigsmileXD** [comment]
ok
