### ISSUE TITLE
inactive

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#560]
sorry guys my wifi adapter burned through because of an energy drink in my school back i may be active again friday or up to monday.. Not in group also, currently writing this in school

**Comment by robske110** [comment]
ok

**Comment by SalmonGER** [comment]
@thebigsmileXD ;( We'll miss you ;((((

**Comment by Aericio** [comment]
rip dan D:

**Comment by SkygridRex** [comment]
@thebigsmileXD do u have a phone? Make USB tethering.
PS: this is not a forum, Don't put useless comments here

**Comment by Aericio** [comment]
He can make it a forum. you cant make him not make it a forum.

**Comment by thebigsmileXD** [comment]
Guess what, my gf has my phone lol

**Comment by SkygridRex** [comment]
@thebigsmileXD 
I should not say this because it is not a forum, but made the worst mistake of your life, better than your phone is locked

**Comment by SalmonGER** [comment]
@SkygridRex Why is that the worst mistake lol

**Comment by robske110** [comment]
He seems to be back

**Comment by SkygridRex** [comment]
@SalmonGER 
All calls, messages, emails, etc, will go through it rather than Dan, and something can be misinterpreted and the PS relationship ends
PS: I'm psychologist

**Comment by SalmonGER** [comment]
@SkygridRex Not everyone has top secret data on his phone. lol.

**Comment by SkygridRex** [comment]
@thebigsmileXD Really go for your phone

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/16526060/a38d66d2-3faf-11e6-91f6-6818f6562940.png)
Guess what part burned through. The power / wifi switch circuit. by the way circuits.. Observer on my TODO

**Comment by SkygridRex** [comment]
@thebigsmileXD an internal PCI wireless card?
Nope buy an USB wireless card it helps a lot

**Comment by thebigsmileXD** [comment]
What. Is. Your. Problem. First of all: internal ones are way faster. Second: The internal one is not attached to the circuit, but the power button and "airplane mode"-toggle is. Third:Its not a PCI one.. -.-

**Comment by robske110** [comment]
You don't seem inactive anymore->AI
