### ISSUE TITLE
Brewing Stand :)

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#561]
`Notice: Undefined property: pocketmine\Server::$limitedCreative in C:\Users\garre_000\Desktop\Network\src\pocketmine\block\BrewingStand.php on line 76`
Opening a Brewng Stand

**Comment by thebigsmileXD** [comment]
-> genisys.. maybe a copied string

**Comment by robske110** [comment]
not again

**Comment by robske110** [comment]
Fixed

**Comment by Aericio** [comment]
:+1:
