### ISSUE TITLE
Effects do not work correctly (hideParticles, sec+amp switched) [0.15]

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#565]
Usage: /effect (player) (effect) [seconds] [amplifier] [hideParticles]
Hide particles doesn't work. I tried "true, yes, hideParticles" and it still didn't hide the particles. Is it still supposed to show the particles or is hideParticles not even supposed to work?

**Comment by robske110** [comment]
It seems like the client doesn't accept the hideParticles anymore

**Comment by robske110** [comment]
Even plugins with hided Particles do show them now

**Comment by robske110** [comment]
Yep, calling setInvisible() on a effect doesn't work anymore

**Comment by thebigsmileXD** [comment]
..i laugh about you captain obvious

**Comment by Aericio** [comment]
lol?

**Comment by thebigsmileXD** [comment]
Changed Packet values
Not client fault (well kind of)

**Comment by Aericio** [comment]
wow what the hell is mojang doing now...

**Comment by thebigsmileXD** [comment]
Checked the code, actual client bug

**Comment by robske110** [comment]
0.15.4?

**Comment by thebigsmileXD** [comment]
Same

**Comment by VCraftMCPE** [comment]
15.6?

**Comment by Aericio** [comment]
0.15.6 = still.

**Comment by Heroata** [comment]
also setAmplifier too doesn't work normally.

**Comment by Sandertv** [comment]
Yeah setAmplifier always puts the amplifier 1 higher than you want it to be...

**Comment by thebigsmileXD** [comment]
@everyone who fucking complains: its correct. setAmplifier(0) is effect strength 1. Thats vanilla.

**Comment by HimbeersaftLP** [comment]
> @everyone who fucking complains: its correct. setAmplifier(0) is effect strength 1. Thats vanilla.

Finally someone who understands that :)

**Comment by Aericio** [comment]
Found a new bug, I think this is Mojang's fault again.
*How its supposed to be:* ` /effect (player) (effect) [seconds] [amplifier] [hideParticles]`
*How it is right now:* `/effect (player) (effect) [amplifier] [seconds] [hideParticles]`
***UPDATE:*** hideParticles still does not work in 0.15.10 >:C

**Comment by thebigsmileXD** [comment]
I may fix the sec+amp. particle colors seem to be calculated client sidednowadays :(

**Comment by thebigsmileXD** [comment]
effect <player> <effect> [seconds] [amplifier] [hideParticles]
Thats how it should be

**Comment by thebigsmileXD** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/20d3e8f64101a0cf11578076ffe1b907d558033f
