### ISSUE TITLE
Server doesn't show and can't connect

### ISSUE THREAD

**Issue by kam187** [ClearSkyTeam/ClearSky#566]
Hi guys,

I'm using the php5 branch:

1) The server doesn't show up in Minecraft PE under the friends tab. I ran wireshark and the packets are getting back to the device but it's not displaying.  I see in 0.15.0 there's an extra number at the end of the ping response, maybe it's that?

2) If i connect by IP it gets stuck on locating server and on the console it says login timed out.

This is the latest dev branch php5

**Comment by robske110** [comment]
I don't have this issue at all..

**Comment by Aericio** [comment]
I'm using PHP7, but the MOTD doesn't show. Other than that, joining isn't an issue for me

**Comment by kam187** [comment]
Hmm that's really weird.  It works in php7 but not in php5.  Are you on windows, linux or mac?  I can try on a different OS.  Also which php binary are you using?  I'm using the latest php5 from the pocketmine page.

**Comment by Aericio** [comment]
I am on WIndows, and using PHP7 binaries.

**Comment by kam187** [comment]
Ok i'm using osx.  It doesn't show with php5 or 7 in mcpe, and if i join by ip it just times out.  I'll try on windows next!

**Comment by Aericio** [comment]
Also make sure you port forwarded correctly.

**Comment by robske110** [comment]
I have php5Branch+MacOSX+PMphp5Libs
And for me it works...

**Comment by karanpatel567** [comment]
I have the same issue rob I have the same issue as kam

**Comment by robske110** [comment]
Gonna check that...

**Comment by robske110** [comment]
well fixed

**Comment by kam187** [comment]
Nope still not showing in MCPE.  (I manually made the edit in the file since you didn't comit it to php5 branch yet).  Also as before if i connect by IP it still says timeout logging in.

**Comment by robske110** [comment]
hmm
gonna check that

**Comment by kam187** [comment]
Re-open the issue?

**Comment by tytot** [comment]
Same thing happens to me.

**Comment by robske110** [comment]
It should be somehow better now, but we're still having issues

**Comment by kam187** [comment]
Thanks.  Could you merge into the php5 branch when you get a chance?  Saves manually making the changes :)

**Comment by thebigsmileXD** [comment]
Locating and connecting works

**Comment by kam187** [comment]
Merge into php5 please?

**Comment by robske110** [comment]
Will do later, but please note that php5 support may be discontinued at any time
