### ISSUE TITLE
 Error: "Undefined class constant 'ANVIL_BLOCK'

### ISSUE THREAD

**Issue by Heroata** [ClearSkyTeam/ClearSky#567]
This error appears when server starts.

```
[18:58:08] [Server thread/CRITICAL]: Error: "Undefined class constant 'ANVIL_BLOCK'" (EXCEPTION) in "/src/pocketmine/item/Item" at line 618
[18:58:08] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
```

- ClearSky version 1.1-php7 "DarkSunset" (API 2.0.0) Build CuttingEdge

EDİT 1: "ANVIL_BLOCK" changed to "ANVIL" here:
https://github.com/ClearSkyTeam/ClearSky/commit/60e73ee476080b429f739f50e0696c4d261794dd
EDİT 2: " init() should be changed.

**Comment by robske110** [comment]
What should be changed in init()

**Comment by robske110** [comment]
Fixed, but still what should be changed in init()

**Comment by Heroata** [comment]
Lots of stuff that you changed here: https://github.com/ClearSkyTeam/ClearSky/commit/60e73ee476080b429f739f50e0696c4d261794dd

like ANVIL

**Comment by robske110** [comment]
Ah yeah, will fix that

**Comment by Heroata** [comment]
Oh okay :D Few off-topic but did you fix client crash alternatively?

**Comment by robske110** [comment]
Well, looking at the time I'll have now I may take another shot on messing with the chunks

**Comment by Heroata** [comment]
I have a question about clearsky's capacity for a big server project. Where can I ask you?

**Comment by Aericio** [comment]
@Heroata Telegram ;)

**Comment by robske110** [comment]
> I have a question about clearsky's capacity for a big server project. Where can I ask you?

CS's core capacity is pretty high, depending on ClockSpeed and plugins.
I would say max 200, but we have no way to test that...
Also always depends on what you're doing. You can compare CS'es performance with the original PM, maybe even a little bit better

**Comment by Heroata** [comment]
We are working for plugins now and thinking about buy this dedicated server for ClearSky "intel xeon e3 1230v3 / 32GB RAM / 2 x 240GB SSD / 1Gbps / HP Gen8v2 & IBM M5 ". How many players can this machine handle with no lag? İt will in our country also. İn second month, we will open server globally with multilanguage. Skywars-survival games-bed wars-(probably) smash minigames will be.. Please share your experience with me :)

**Comment by robske110** [comment]
32GB RAM: more than enough lol (you need max 4GB, we're not genisys :P)
E3-1230v3: 3.3Ghz @ 4cores could be more Ghz, but it's ok :)
SSD: doesn't really do anything
Bandwith: more than enough, set network compression to 1 and the packet limit to -1 [Less lag then]
Without plugins it should handle 300-400 players.
And for your plugin devs: Watch what you're doing. Don't do foreach(player) often a large number of this.

**Comment by robske110** [comment]
I'll see if i can simulate a bot

**Comment by Heroata** [comment]
Thank you a lot for your help

**Comment by Aericio** [comment]
Bot attack your server? xd

**Comment by robske110** [comment]
I'll write a thingy wich imitates mcpe packets maybe

**Comment by thebigsmileXD** [comment]
Or just try to update Specter

**Comment by Heroata** [comment]
Maybe 1000 players. I think 5 different server is better for performance. Is mysql database only way for sync servers and is it better than 1000 players in one server?

**Comment by robske110** [comment]
1000 player for one CS server. We would love the statistics that we could get from such a server (fixing small player tick related issues) but without such an optimization we can't really say that CS will pretty much kill itself.
MySQL is a way to transfer data between servers. But i personally don't like it, allthough you should use it. If you are running your servers on the same machine you could even try throwing stuff between your servers around, but let's not do that.
I'll really look into some simulator wich will just simulate spawn packets and then continiusly sends movement packets in random directions. That'll be fun :D

**Comment by Aericio** [comment]
Good luck with that... Is the source going to be on GitHub though? :p

**Comment by Heroata** [comment]
@robske110 
    We are using foreach in our minigames. So, for 24-12 players per mini game room. And if without plugins it can handle 300 players, with players can this machine handle with maximum 100-200 players. Hope I understood wrongly :p 

 And I didnt understand this part "If you are running your servers on the same machine you could even try throwing stuff between your servers around, " can you more explain?

@Aericio 
    If you are talking about our server's plugins, no we wont. We editing plugins but mostly developing our plugins. And don't worry we will create a credits room or a command. Respect for labour ✌

**Comment by Aericio** [comment]
Was asking Robske, buts that nice to know :)

**Comment by robske110** [comment]
That thowing stuff between server around was not really meant to be a soloution. But i meant 'throwing' objects between processes (funnelling,...) around. But that is low level programming and as php is not even capabale of this, let's forget bout' this :)

**Comment by robske110** [comment]
But a considerable way is creating sockets between the server

**Comment by robske110** [comment]
@Aericio Of course the player spam bot will be opne source if i find time to actually do it

**Comment by Aericio** [comment]
I don't have any plans for that spam bot... Don't be suspicious :3 Hope you get the time to do it.

**Comment by robske110** [comment]
oh i forgot you could abuse it
dawn
then i won't publish it

**Comment by SalmonGER** [comment]
@robske110 cri

**Comment by Aericio** [comment]
Please Robske publish it I won't do anything ;-;

**Comment by Heroata** [comment]
:D sorry i wasnt read last paragraph @robske110 

if without plugins machine can handle 300 players, with players can this machine handle with maximum 100-200 players. Hope I understood wrongly :p

**Comment by Aericio** [comment]
If you would want a big server (200+) you could go with MiNet but everything would need to be custom-coded D:

**Comment by robske110** [comment]
And @Herota The machine itself can handle more servers. And I'm really gonna write that attack bot and then we'll see :)
