### ISSUE TITLE
Fishing on Bedrock

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#568]
[Fishing on Salmon's Bedrock](https://youtu.be/LroFyTYII_I) <--click

**Comment by robske110** [comment]
Hmm. I don't know if Dan has ever implement checking if the thingy is in water

**Comment by thebigsmileXD** [comment]
Reason: check if in water gone

**Comment by robske110** [comment]
already fixed...

**Comment by thebigsmileXD** [comment]
Yea yea but i mean i had this done already.

**Comment by Aericio** [comment]
No more fishing while digging in caves D:
