### ISSUE TITLE
Control app? 

### ISSUE THREAD

**Issue by daniktheboss** [ClearSkyTeam/ClearSky#570]
Is there a chance any one could write a plugin and app like leet? I mean the app to edit files?? I know there's rcon but that's not enough! And now plugswork discontinued the project!

**Comment by Aericio** [comment]
I think you could just download Pocketmine  on phone and then replace it
with a ClearSky.phar... But you will need  to port forward your phone.
Leet's app is hosting from their company, and I don't think anyone at
clearsky wants to setup a hosting thing like that...

**Comment by Aericio** [comment]
Do you mean like a hosting app hosted by a company or home hosted?

**Comment by daniktheboss** [comment]
If I download the pocketmine app I will host the server on my phone... I mean like a control panel or somthing

**Comment by robske110** [comment]
Ugh, replied at PM repo read it there

**Comment by robske110** [comment]
AND PHONES ARE NO SERVER HOSTERS

**Comment by daniktheboss** [comment]
Ok thanks
