### ISSUE TITLE
Client side snow

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#579]

**Comment by robske110** [comment]
Biome

**Comment by thebigsmileXD** [comment]
Maybe, because it was set to ice plains once by a snow plugin

**Comment by SkygridRex** [comment]
@thebigsmileXD You aren't alone
https://github.com/Nukkit/Nukkit/issues/906

**Comment by thebigsmileXD** [comment]
Edit: also happens in my creative world, normal flat world

**Comment by Aericio** [comment]
WTF IS WRONG WITH MOJANG...

**Comment by thebigsmileXD** [comment]
Reason: SnowAccumulation

**Comment by thebigsmileXD** [comment]
Only fix: setbiome to plains everywhere..
