### ISSUE TITLE
[REDSTONE] Torches on Dispenser/Dropper does not toggle back on

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#580]

**Comment by robske110** [comment]
Why should it do so?

**Comment by thebigsmileXD** [comment]
wait, i show you what i mean.

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/16655070/02878b4c-4459-11e6-9771-ebcac5438e1c.png)
It turns off, but not on again

**Comment by robske110** [comment]
Ok

**Comment by thebigsmileXD** [comment]
Wait lol, isn't redstone lamp also an consumer?

**Comment by robske110** [comment]
Yep

**Comment by robske110** [comment]
Of course

**Comment by thebigsmileXD** [comment]
Then maybe the redstone update function of dispenser doesn't cause an update to the enviroment

**Comment by thebigsmileXD** [comment]
Wow. Wether it shoots twice, triple or doesnt update. Can't fix that.

**Comment by thebigsmileXD** [comment]
Seems like redstone update normal comes twice, maybe the torch and the string

**Comment by robske110** [comment]
TODO: check isCharged calls(call debug/throw exceptions there)

**Comment by robske110** [comment]
Found issue: isCharged missing,UPDATE call missing

**Comment by thebigsmileXD** [comment]
on what. redstone torches or all redstone consumers
