### ISSUE TITLE
Hunger in Creative Mode?

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#581]
When in Creative Mode, the hunger still affects Creative Mode.
(ex: cannot run when hunger is below 3 bars of chicken wings, even when in creative mode.)

**Comment by thebigsmileXD** [comment]
oh well.. this was fixed ages ago and is now back -.-

**Comment by Aericio** [comment]
Awesome :)

**Comment by robske110** [comment]
Awful
Not awesome

**Comment by Aericio** [comment]
Horrible.

**Comment by Aericio** [comment]
:+1:

**Comment by thebigsmileXD** [comment]
@robske110 i would rather not calculate the hunger in creative mode then calculating but ignoring the amount
