### ISSUE TITLE
EssentialsPE + ClearSky php7 = timeout login error.

### ISSUE THREAD

**Issue by andris155** [ClearSkyTeam/ClearSky#584]
2016-07-07 [16:51:40] [Server thread/INFO]: andris155[/192.168.1.122:19132] logged in with entity id 1 at (world, 128, 70, 128)
2016-07-07 [16:51:50] [Server thread/INFO]: andris155 lost connection: timeout

**Comment by robske110** [comment]
do you have the latest version
and wich port do you use?

**Comment by SalmonGER** [comment]
Probably Essentials issue.
Without Essentials it works fine.

**Comment by andris155** [comment]
ClearSky-php7-#107.phar + EssentialsPE 2.0.0 or 1.1.3 = login timout error all players.
ClearSky-php7-#107.phar + no EssentialsPE = works perfectly.

**Comment by SalmonGER** [comment]
That's what I mean. I know this issue but I really think it should be fixed in EssentialsPE since it only occurs when someone uses EssentialsPE with ClearSky.

**Comment by robske110** [comment]
report this to essentials pe then

**Comment by thebigsmileXD** [comment]
Maybe its the fault of CS, same error on other cores? (i really want the plugin back)

**Comment by robske110** [comment]
I hate the plugin. It's just a big junk of mess.
And idk what it does with joining. And i don't think we have done too much on the join handling. Check if it uses skinID anywhere

**Comment by Aericio** [comment]
Someone reported that to EssentialsPE. Their gay devs just said "We do not support other third party softwares"

**Comment by iksaku** [comment]
In deed, we never test with any other software out of PocketMine-MP due to the difference between APIs in third-party builds.
At "Join" we handle custom messages, with "Pre-login" we create sessions.
I think you will be fine with those descriptions ;)

**Comment by NikeboyHU** [comment]
iksaku, it's okey, but... PM software is outdated, and IM, Genisys, CS that newer software... Not fixing problem? :/

**Comment by robske110** [comment]
Hmm, I'll test this and actually test it with pocketmine.

**Comment by robske110** [comment]
And @iksaku I like that you say 'We don't support third-parties', even when I'm developing one. Because we should always focus on having the same API as PM.

**Comment by iksaku** [comment]
I'm not developing third-party PocketMine :P

**Comment by Aericio** [comment]
Bored of Pocketmine php? :p

**Comment by Sandertv** [comment]
I'm trying to fix this, but I can't figure out what the problem could be. (As I'm not involved in the development of ClearSky) Could one of you try and help me and try to tell me the changes that have been made in CS?

**Comment by robske110** [comment]
Is essentials working with PM? If not, it's simply not out issue.

**Comment by Sandertv** [comment]
It is working with any other fork of PM except ClearSky. It's still causing the timeout issue.

**Comment by thebigsmileXD** [comment]
Are you also sure you have the latest raklib + spl?

**Comment by Sandertv** [comment]
Yep I do.

**Comment by thebigsmileXD** [comment]
I have to say i had the same issues with EssentialsPE when i upgraded to PHP7. I may try it today
