### ISSUE TITLE
[NON-CORE] Jenkins

### ISSUE THREAD

**Issue by starterdragon** [ClearSkyTeam/ClearSky#585]
Parse error: syntax error, unexpected ')' in phar://D:/LegendsInArms-CS/ClearSky.phar/src/raklib/protocol/Packet.php on line 71

Fatal error: Exception thrown without a stack frame in Unknown on line 0
[19:37:45] [Server thread/EMERGENCY]: [RakLib Thread #1324] RakLib crashed!

**Comment by robske110** [comment]
this is a jenkins phar issue

**Comment by robske110** [comment]
please kill Dan and use the src folder

**Comment by thebigsmileXD** [comment]
I will kill you. Its not my fault that jenkins doesnt fetch the latest code correctly.

**Comment by robske110** [comment]
I think it's from that optimizing

**Comment by SkygridRex** [comment]
@robske110 I like the idea (just kidding)

**Comment by Touficbatache** [comment]
Can anyone compile the src for me please ? Thanks

**Comment by Aericio** [comment]
Just use the src folder to run your server. Phar only increases performance
by a little I think.

**Comment by Touficbatache** [comment]
That's what I did

**Comment by thebigsmileXD** [comment]
Will use Travis and ftp for now

**Comment by Touficbatache** [comment]
So from where can we get a phar ? Can you post a link ?

**Comment by thebigsmileXD** [comment]
will be out soon, i hope

**Comment by robske110** [comment]
I would just use circle ci

**Comment by Touficbatache** [comment]
Does it have phar ?

**Comment by thebigsmileXD** [comment]
@robske110 seems to be working on it.

**Comment by Touficbatache** [comment]
Okk

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/CSPhar.php

**Comment by Touficbatache** [comment]
Cool! Maybe try adding more design to the page!!

**Comment by robske110** [comment]
Sadly, i know nothing about CSS. If you know it or know anyone who knows css feel free to tell me

**Comment by Touficbatache** [comment]
Yes I know a lot about CSS

**Comment by Touficbatache** [comment]
Email me : taffou2a@gmail.com

**Comment by robske110** [comment]
I'm now closing this due to we have CircleCI + http://robskebueba.no-ip.biz/CSPhar.php

**Comment by SkygridRex** [comment]
you are stingy

**Comment by Aericio** [comment]
It works, why are you so mad? It does the same thing as Jenkins.
