### ISSUE TITLE
I WANT USE SOME PLUGINGs

### ISSUE THREAD

**Issue by 2449673842** [ClearSkyTeam/ClearSky#586]
would like to use some of the animals with plug-ins, but whether it is a plug-in with animals as long as the use of a server will shut down, I would like to use the ball to do the game

**Comment by 2449673842** [comment]
Fatal error: Cannot redeclare pocketmine\tile\Hopper::getName() in C:\Users\2449673842\Desktop\PocketMine▒▒▒▒0.14▒▒▒ϰ▒S1.0\src\pocketmine\tile\Hopper.php on line 145

**Comment by 2449673842** [comment]
what should i do

**Comment by Aericio** [comment]
Do you have the latest version of ClearSky?

**Comment by 2449673842** [comment]
yes

**Comment by 2449673842** [comment]
and How do I upload this plugin

**Comment by 2449673842** [comment]
This is a small game plug-in and comes with AI

**Comment by Aericio** [comment]
Put it in your "plugins" folder...

**Comment by robske110** [comment]
php5 issues, well will fix it maybe later

**Comment by robske110** [comment]
**PHP5 SUPPORT IS NOW OFFICALLY DISCONTINUED**
