### ISSUE TITLE
Nether 

### ISSUE THREAD

**Issue by aodzip** [ClearSkyTeam/ClearSky#59]
- [ ] Generator
- [x] Sky
- [ ] Portal

**Comment by thebigsmileXD** [comment]
Generator is already in vanilla, but needs quartz ore (exact copy of iron ore)
And.. Idk about glowstone

What you mean by sky?

The portal blocks are done, i'll add a EntityEnterPortalEvent. (Autocorrect remembered it lol)
Just needs the portal calculation.

**Comment by MCPEPIG** [comment]
I think @aodzip means the red sky

**Comment by MCPEPIG** [comment]
The glowstone isn't there yet and soul sand is needed.

**Comment by thebigsmileXD** [comment]
That must be some packet.. lol

**Comment by MCPEPIG** [comment]
Not a packet. It has something to do with the Hell/Nether biome. Any chunk with the biome has red sky

**Comment by twilightsay** [comment]
You mean..The nether system will like genisys?

**Comment by thebigsmileXD** [comment]
@twilightsay Faster and rewritten

**Comment by thebigsmileXD** [comment]
Sky done.

**Comment by robske110** [comment]
👏🏼

**Comment by Aericio** [comment]
Any more progress? :D

**Comment by robske110** [comment]
I removed InProgress

**Comment by Aericio** [comment]
Oh. Is nether near finished?

**Comment by robske110** [comment]
no

**Comment by thebigsmileXD** [comment]
The nether looks a bit better in the generator branch.
