### ISSUE TITLE
Same world generation

### ISSUE THREAD

**Issue by Touficbatache** [ClearSkyTeam/ClearSky#590]
World generation is the same... I mean a small part of the world is generated and duplicated multiple times all over the world

**Comment by robske110** [comment]
It may look the same, but the world generators work with noise and very much randomness.
It is practical impossibile that you have two exact the same chunks.

**Comment by Touficbatache** [comment]
How can I send a screenshot for proof ?

**Comment by robske110** [comment]
just post it here

**Comment by Touficbatache** [comment]
See ? Repetitive look at the top right and at the bottom center and see...

**Comment by Touficbatache** [comment]
Link : http://touficapks.ml/Screenshot_2016-07-08-18-35-19.png

**Comment by robske110** [comment]
that are two a bit-the-same hills

**Comment by robske110** [comment]
This is no issue, world generation may sometimes look the same

**Comment by thebigsmileXD** [comment]
Lol actually look same
