### ISSUE TITLE
RemoveItem Problem

### ISSUE THREAD

**Issue by Harviy** [ClearSkyTeam/ClearSky#594]
Anvil item changed the name, but not remove

`$player->getInventory()->removeItem(Item::get(276));`

Code does not work and not remove
Help me

**Comment by robske110** [comment]
?

**Comment by Harviy** [comment]
ismi değişmiş eşya kaldırılmıyor

**Comment by Aericio** [comment]
Oh item name changing using the anvil?

**Comment by TheKillerTacos** [comment]
Are you trying to **REMOVE** the item, or **RENAME** the item?
