### ISSUE TITLE
Jenkins Doesn´t work (Again)

### ISSUE THREAD

**Issue by SkygridRex** [ClearSkyTeam/ClearSky#595]
thanks @thebigsmileXD

**Comment by robske110** [comment]
Is the other issue closed?
Duplicate

**Comment by Aericio** [comment]
Other issue still open, xd

**Comment by SkygridRex** [comment]
But not same, nos jenkins Don't work

**Comment by SkygridRex** [comment]
Go to jenkins.clearsky.org, page show a internal server error

**Comment by Aericio** [comment]
http://jenkins.clearskyteam.org/ **
And there is another issue about this already.

**Comment by SkygridRex** [comment]
My first hater :yum:

**Comment by SkygridRex** [comment]
Put the issues link @Aericio

**Comment by Aericio** [comment]
#585 -_-

**Comment by SkygridRex** [comment]
Nope my issues It's different

**Comment by SkygridRex** [comment]
Issue*

**Comment by TheKillerTacos** [comment]
![wrr](https://cloud.githubusercontent.com/assets/14338036/16710470/09ea2a0a-45f5-11e6-9b10-def153091f09.PNG)

**Comment by SkygridRex** [comment]
Yeah

**Comment by SkygridRex** [comment]
@TheKillerTacos go to gitter

**Comment by SkygridRex** [comment]
http://serverfault.com/questions/185894/proxy-error-502-reason-error-reading-from-remote-server-with-apache-2-2-3-de

**Comment by thebigsmileXD** [comment]
Proxy error @aodzip has to check that.

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/CSPhar.php

**Comment by thebigsmileXD** [comment]
@aodzip we don't need jenkins anymore, thanks for providing it for so long.

**Comment by SkygridRex** [comment]
Don't make spam in my forum
@thebigsmileXD :yum:

**Comment by Aericio** [comment]
Would you like to define: "My forum"

**Comment by SkygridRex** [comment]
I take my issue (which opened here) as my forum

**Comment by Aericio** [comment]
Dan only commented twice, that is not spamming.

**Comment by SkygridRex** [comment]
I'm almost a psycologiest (because i Don't finished my studies) but I can make diagnoses 
PS: off topic (i know)

**Comment by daniktheboss** [comment]
Tf???

**Comment by thebigsmileXD** [comment]
@SkygridRex we do not have PocketMine issue tracker rules. Goodbye
