### ISSUE TITLE
How do I change "SCr Folder" into .phar from the latest scr

### ISSUE THREAD

**Issue by karanpatel567** [ClearSkyTeam/ClearSky#596]
HOW DO I CONVERT SCR FOLDER INTO .PHAR SO I CAN GO IN MY SERVER! (I KNOW ITS NOT DETAILED).

**Comment by karanpatel567** [comment]
I tried using devtools but it didnt work 7 need amswers

**Comment by SalmonGER** [comment]
Why did DevTools not work?

**Comment by Aericio** [comment]
Use the src file, put the src where you would normally put the .phar

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/CSPhar.php

**Comment by IndianaStone** [comment]
On what platform

**Comment by robske110** [comment]
That phars is for all OSes

**Comment by thebigsmileXD** [comment]
http://wolvesfortress.de/circleci.php latest
