### ISSUE TITLE
ItemFrame cannot be broken/items cannot be taken out

### ISSUE THREAD

**Issue by jdongel2004** [ClearSkyTeam/ClearSky#599]
My English is very poor.. (Korean..)
I can't use ItemFrame But.. Genisys can use ItemFrame.  Help me!

----

Does not drop its item, its removed client side but not server side. after relog item back in item frame.

**Comment by thebigsmileXD** [comment]
Okay, i'll check today

**Comment by MCPEPIG** [comment]
ClearSky !== Genisys

**Comment by robske110** [comment]
Isn't this fixed with https://github.com/ClearSkyTeam/ClearSky/commit/6e4de655bfd5754d0d27cc7319d28ad346994952

**Comment by thebigsmileXD** [comment]
Not sure, i was told they still turn invisible

**Comment by robske110** [comment]
Can anyone confirm this?

**Comment by daniktheboss** [comment]
Confirmed... they disapear when placed

**Comment by daniktheboss** [comment]
And paintings also go to the next block... and u can stack paintings

**Comment by robske110** [comment]
Please report the last two bugs somewhere else

**Comment by jdongel2004** [comment]
Must modify not perfect, but you can write.

**Comment by jdongel2004** [comment]
Repeated operation to install a frame of items and again.

**Comment by thebigsmileXD** [comment]
@jdongel2004 sorry, what

**Comment by jdongel2004** [comment]
@thebigsmileXD  Ah...Can you fix it?

**Comment by thebigsmileXD** [comment]
@jdongel2004 i can't fix something i cant understand..

**Comment by thebigsmileXD** [comment]
Notice: Does not drop its item, its removed client side but not server side. after relog item back in item frame.
TODO: Check if left click or right click interaction. If left click, drop item or break frame. If right click, place or rotate
