### ISSUE TITLE
Error on Not enough Input??

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/ClearSky#60]
When I opened my server for 2 hours, this crash appears:
Error: unpack(): Type N: not enough input, need 4, have 0
File: /src/pocketmine/utils/Binary
Line: 313
Type: warning

Code:
[304] 	 */
[305] 	public static function writeLShort($value){
[306] 		return pack("v", $value);
[307] 	}
[308] 
[309] 	public static function readInt($str){
[310] 		if(PHP_INT_SIZE === 8){
[311] 			return unpack("N", $str)[1] << 32 >> 32;
[312] 		}else{
[313] 			return unpack("N", $str)[1];
[314] 		}
[315] 	}
[316] 
[317] 	public static function writeInt($value){
[318] 		return pack("N", $value);
[319] 	}
[320] 
[321] 	public static function readLInt($str){
[322] 		if(PHP_INT_SIZE === 8){
[323] 			return unpack("V", $str)[1] << 32 >> 32;

Backtrace:
#0 /src/pocketmine/utils/Binary(313): unpack(string N, string )
#1 /src/pocketmine/level/format/mcregion/RegionLoader(75): pocketmine\utils\Binary::readInt(string )
#2 /src/pocketmine/level/format/mcregion/McRegion(186): pocketmine\level\format\mcregion\RegionLoader->readChunk(integer 27, integer 6)
#3 /src/pocketmine/level/format/mcregion/McRegion(246): pocketmine\level\format\mcregion\McRegion->loadChunk(integer 27, integer 6, boolean )
#4 /src/pocketmine/level/Level(2730): pocketmine\level\format\mcregion\McRegion->getChunk(integer 27, integer 6, boolean )
#5 /src/pocketmine/level/Level(2346): pocketmine\level\Level->loadChunk(integer 27, integer 6, boolean )
#6 /src/pocketmine/level/generator/PopulationTask(43): pocketmine\level\Level->getChunk(integer 27, integer 6, boolean )
#7 /src/pocketmine/level/Level(3049): pocketmine\level\generator\PopulationTask->__construct(pocketmine\level\Level object, pocketmine\level\format\mcregion\Chunk object)
#8 /src/pocketmine/Player(811): pocketmine\level\Level->populateChunk(integer 27, integer 5)
#9 /src/pocketmine/Player(1761): pocketmine\Player->sendNextChunk(boolean)
#10 /src/pocketmine/Server(2516): pocketmine\Player->checkNetwork(boolean)
#11 /src/pocketmine/Server(2252): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server(2130): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server(1723): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(442): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\Administrator\Desktop\MysU Survival\PocketMine-MP.phar/, string C:\Users\Administrator\Desktop\MysU Survival\, string C:\Users\Administrator\Desktop\MysU Survival\plugins\)
#15 (1): require_once(string phar://C:/Users/Administrator/Desktop/MysU Survival/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.0dev #0 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT WIN-DASDWX2 6.1 build 7601 (Windows Server 2008 R2 Enterprise Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
1vs1 0.0.5 by  for API(s) 1.0.0, 1.1.0
AdminJoin 1.3.1 by ZacHack for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
ArtificialIntelligent 0.2 by onebone for API(s) 1.12.0, 1.13.0
AutoInv 1.0.1 by HotshotHD for API(s) 1.12.0, 1.13.0
BanItem 2.1 by LDX for API(s) 1.0.0
BenchMark 1.0-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CraftingTableFix 2.0-Alpha by hm for API(s) 1.13.0, 2.0.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyPotionDispenser 0.0.2 by Khinenw for API(s) 1.12.0
EconomyProperty 2.0.6 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
Farms 1.2-alpha by ifteam for API(s) 1.12.0, 1.13.0, 2.0.0
GMChecker 0.2 by  for API(s) 1.12.0
HeadShot 1.0 by DeBe for API(s) 1.12.0, 1.13.0, 2.0.0
InvSee 0.0.1 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
iProtector 3.1a by LDX for API(s) 1.9.0
ItemEffects 2.5.0 by XFuryMCPE for API(s) 1.12.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
KitPro 4.1 by  for API(s) 1.10.0
LaunchPads 1.0.0 by MCPEPIG for API(s) 1.0.0
LightningJoin 0.4 by Jelly9912 for API(s) 1.13.0
MoreTrees 1.0-Alpha by hm for API(s) 1.12.0, 1.13.0, 2.0.0
NetherChests 1.1.1 by aliuly for API(s) 1.12.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
TimeRanks 1.0.2 by luca28pet for API(s) 1.12.0
BloodFX 1.1.0 by hoyinm14mc & CyberCube-HK Team for API(s) 1.12.0
RandomItem 4.2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
PrizeWin 1.0.6 by LilCrispy2o9/Angelo Vidrio for API(s) 1.10.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
PVPMoney 0.1-Alpha by hm for API(s) 1.0.0, 1.4.1, 1.12.0, 1.13.0, 2.0.0
RPAntiLagg PreFinal_1.1 by LDX for API(s) 1.8.0
ServerLoveMCPE 3.1 by TheDeibo for API(s) 1.10.0
SignStatus 3.0.0 by xpyctum for API(s) 1.0.0
SortInventory 1.0 by DeBe for API(s) 1.12.0, 1.13.0, 2.0.0
SpecialBlock 1.3.2 by Primus for API(s) 1.0.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
TimeCapsule 1.1.1 by Falk for API(s) 1.0.0
UsefulShears 1.0 by DeBe for API(s) 1.12.0, 1.13.0, 2.0.0
VoteBan 1.0.2 by GmWM for API(s) 1.12.0
VoteReward 3 by LDX for API(s) 1.12.0, 2.0.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
Jail 1.1.1 by hoyinm14mc for API(s) 1.13.0, 1.13.1
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

I check on pocketmine.yml but there's nothing to fix
Im using the latest version of ClearSky

**Comment by Adam1609** [comment]
No answer?

**Comment by thebigsmileXD** [comment]
The world is corrupted.

**Comment by Adam1609** [comment]
Can you tell me exactly the world that being corrupted?

**Comment by MCPEPIG** [comment]
The crash dump provided doesn't say which world...

**Comment by Adam1609** [comment]
I try to find which causes this but couldn't. I guess I have to find it

**Comment by thebigsmileXD** [comment]
A pc map

**Comment by Adam1609** [comment]
No i have no pc map in my server

**Comment by Adam1609** [comment]
Any suggested on how to fix it??
