### ISSUE TITLE
Everyone Wants to know HOW TO COMPILE A .PHAR FROM A SCR FOLDER ON ANDROID! HELP!

### ISSUE THREAD

**Issue by karanpatel567** [ClearSkyTeam/ClearSky#600]
EVERYONE WANTS TO KNOW HOW TO COMEPILE A .PHAR FROM SCR FOLDEE SINCE YOUR JENKINS IS BROKEN! AND WE ALL WANT TO KNOW HOW TO COMPILE .PHAR FROM SCR FOLDER ON ANDROID BECAUSE IF U ADD THE SRC FOLDER IN YOUR SERVER FOLDER IN ANDROID AND REMOVE CLEARSKY PHAR AND GO ON POCKETMINE IT WILL BRING UP THE VERSIONS THINGY SOOOOOO HOOWWWW DO I COMPILE ONE! I DONT WANT TO COMPILE ONE ON A LAPTOP/COMPUTER/MAC

**Comment by karanpatel567** [comment]
AND IF I DONT GET THE ANSWER AND THIS ISSUE GET CLOSED IM MOVING TO CLEARSKY TO GENISYS THATS IT I HAD ENOUGH ATLEAST THEY HAVE ADVANCED STAFF

**Comment by MCPEPIG** [comment]
Go ahead, go. We dont want babies whining all over.

**Comment by MCPEPIG** [comment]
AND JUST USE THE SRC. WHATS THE PROBLEM?

**Comment by robske110** [comment]
I don't even know how to do this on android without devtools. bye
(actually just write a php script)

**Comment by Aericio** [comment]
Its your choice to go from Less-Lag to Lagisys.

**Comment by daniktheboss** [comment]
True... no support at all!

**Comment by robske110** [comment]
And if everyone is too stupid to use the src folder until we fixed the issue then well

**Comment by thebigsmileXD** [comment]
Should i block the user

**Comment by IndianaStone** [comment]
They have an app called "Phar" it compiles phar files

**Comment by thebigsmileXD** [comment]
There is a plugin called DevTools ad it compiles phars ;)

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/CSPhar.php
here you have your phar(s)

**Comment by thebigsmileXD** [comment]
http://wolvesfortress.de/circleci.php
here you have your latest phar

**Comment by robske110** [comment]
lol the latest phar link is actual linking to that site

**Comment by AryToNeX** [comment]
"*OH THANKS ROBSKE NOW I CAN COMPILE PHARSSSS!!!"!"!111!11!11!1!1 THX THX U R DA BEST FUCK LAGISYS U R GR8 I CAN COMPILE PHAR YEA FROM SRC111!11!!!! NO MORE POCKEMTINE PHAR YEA LETS USE CLAERSKY!!11!1!!1*"

I am just joking don't block me~

**Comment by Aericio** [comment]
I find src and phar having no difference at all on performance.
