### ISSUE TITLE
[REDSTONE] Piston/Sticky piston rotation&activation&extending

### ISSUE THREAD

**Issue by XtremePlayzCODE** [ClearSkyTeam/ClearSky#601]
if you place a sticky piston it changes to a piston, and pistons dont extend

**Comment by robske110** [comment]
Pistons aren't really implemented right now

**Comment by thebigsmileXD** [comment]
Commit titles: "Placeable Pistons" commit description: "Tiles do not show" is it that hard for users to look into the commit history? sad..

**Comment by XtremePlayzCODE** [comment]
thank you, i will work to actually implement them into my version of pocketmine

**Comment by robske110** [comment]
And btw it's very rude to post a issue on the repo you forked from (yes your version from PM is defintley CS with minor changes) to let them fix your issue and then port it into your fork. This is how all the forks were created. And yes i'm partly criticising us for that, but we're active not like PM.
And i couldn't find any acknowledgement that you forked from cs.

**Comment by XtremePlayzCODE** [comment]
lol i did say it, i will close this now

**Comment by robske110** [comment]
I don't regret the fact that this is a issue

**Comment by daniktheboss** [comment]
I mean this is clearsky issue too

**Comment by robske110** [comment]
Wtf. You should not be able to close it after i reopened it

**Comment by XtremePlayzCODE** [comment]
i am, complain to github

**Comment by XtremePlayzCODE** [comment]
see?

**Comment by Aericio** [comment]
![image](https://cloud.githubusercontent.com/assets/16523741/16858168/a66bdb66-49c0-11e6-86dd-4df163e92b9d.png)
![image](https://cloud.githubusercontent.com/assets/16523741/16858169/ab15d7b6-49c0-11e6-98f3-41a36baf0d45.png)
lol

**Comment by XtremePlayzCODE** [comment]
lol it was based off of pocketmine and i forgot to change it, now i used clearsky for more features

**Comment by SkygridRex** [comment]
@robske110 Can you ban me from ClearSkyTeam?

**Comment by SkygridRex** [comment]
Please! I don't wanna see this anymore

**Comment by robske110** [comment]
I literally can't. (I have no perms for that)

**Comment by SkygridRex** [comment]
@robske110 ok, bye ClearSky! I will miss you, i will miss all ClearSky Team (not Dan, cause i hate him)

**Comment by thebigsmileXD** [comment]
@SkygridRex a reason more that you got banned. Spamming, insulting, posting inrelevant comments and simply being a dumb dickhead.

**Comment by XtremePlayzCODE** [comment]
this escalated quickly

**Comment by thebigsmileXD** [comment]
@XtremePlayzCODE not actually. He was doing that for more than a month now

**Comment by Aericio** [comment]
Yea he's kind of annoying

**Comment by robske110** [comment]
Cleaned up this discussion

**Comment by XtremePlayzCODE** [comment]
kk

**Comment by XtremePlayzCODE** [comment]
oops

**Comment by thebigsmileXD** [comment]
Yea, blame them hard. Piston extension part does not display after chunk reload/resend

**Comment by dktapps** [comment]
That's not a client issue. The only reason it renders to begin with is because that's how the client expects them to look when you place them.

**Comment by thebigsmileXD** [comment]
Its a client issue, the tiles are created and have same data like MCPE singleplayer

**Comment by dktapps** [comment]
Then there's something else wrong, because this doesn't happen in vanilla.

**Comment by thebigsmileXD** [comment]
@dktapps it happened to me in MCPE singleplayer, but only when the phone is the host

**Comment by XtremePlayzCODE** [comment]
So we are blaming Mojang right now.

**Comment by thebigsmileXD** [comment]
#217

**Comment by XtremePlayzCODE** [comment]
I will be waiting until that piston is checked.
