### ISSUE TITLE
i need php5

### ISSUE THREAD

**Issue by 2449673842** [ClearSkyTeam/ClearSky#605]
why this no php5 i am waiiting for  a long time please

**Comment by caspervanneck** [comment]
php5 is not suported  @2449673842

**Comment by caspervanneck** [comment]
use this apk no pocketmine mp android 

https://github.com/fengberd/MinecraftPEServer/releases/download/v1.0.6/PocketServer_v1.0.6.apk

**Comment by robske110** [comment]
We don't support php5 anymore. When 0.16 comes, all php5 servers are forced to update to php7.
