### ISSUE TITLE
Healing

### ISSUE THREAD

**Issue by daniktheboss** [ClearSkyTeam/ClearSky#606]
When you are in survival and you put the 2nd person view and when you are healing you turn red like someone is hitting you.

**Comment by robske110** [comment]
#520 duplicate and also this is not a CS issue, it's client sided

**Comment by daniktheboss** [comment]
Oh sorry I looked and didn't see this one

**Comment by thebigsmileXD** [comment]
@robske110 i am still not sure if it is a client issue. I thing CS somehow sends it.

**Comment by robske110** [comment]
It appears on every server software since 0.15

**Comment by thebigsmileXD** [comment]
@robske110 Except Realms, and i guess steadfast also doesnt have that. @alleskos @williamtdr do you know about that?
