### ISSUE TITLE
Infinite Slime Jumping

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#607]
Jumping on slime blocks in survival results in an endless loop of jumping, but when you turn into creative, it isn't an endless loop of jumping. I was in resistance so I would not die, but I also cleared effects to show you it happens without resistance. Also, using anticheat.
**_Edit:**_ When `allow-fly` is set to `off`, it makes you jump infinitely.

**Comment by daniktheboss** [comment]
Yea the anti cheat feature pulls down... not really a bug...

**Comment by Aericio** [comment]
Oh.

**Comment by Aericio** [comment]
If its anticheat, then I guess will just close.

**Comment by thebigsmileXD** [comment]
Well, it is a bug. Anticheat should check the real motion vector.

**Comment by robske110** [comment]
Maybe disabling anti cheat while slime blockin'(

Bad bad bad bad idea, hacks incoming

**Comment by Aericio** [comment]
People keep fly hacking, hacks already incoming. Should the ClearSky anti-cheat be enabled?

**Comment by thebigsmileXD** [comment]
Pff. Turn on anti cheat and killaura etc still works

**Comment by Aericio** [comment]
Ik, anticheat does sheet

**Comment by dktapps** [comment]
The problem is [here](https://github.com/ClearSkyTeam/ClearSky/blob/php7/src/pocketmine/Player.php#L1729). The expected velocity is too high.

**Comment by thebigsmileXD** [comment]
I'll check if i can find something similar, thanks

**Comment by Aericio** [comment]
When `allow-fly` is set to `true`, it makes it jump infinitely.

**Comment by thebigsmileXD** [comment]
TODO: check after falldamage fixes
