### ISSUE TITLE
Warning: Division by zero

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#608]
`Warning: Division by zero in phar://C:/Users/null/Desktop/Server/ClearSky.phar/src/pocketmine/entity/Human.php on line 219`

**Comment by thebigsmileXD** [comment]
Confirmed. I have no idea why "get exp to next level" could be 0, 0 would mean level up

**Comment by TDMidkwhatisxd** [comment]
so , is there a way to workaround?

**Comment by thebigsmileXD** [comment]
Actually, its no real bug and doesn't cause issues. Just ignore it for now.

**Comment by thebigsmileXD** [comment]
May be fixed anyways :P

**Comment by thebigsmileXD** [comment]
Checking in my console later

**Comment by Aericio** [comment]
It was still happening on the latest version :)

**Comment by robske110** [comment]
```php
$level = 0;
	function getTotalXpForLevel(int $level) : int{
		if($level <= 16){
			return $level ** 2 + $level * 6;
		}elseif($level < 32){
			return $level ** 2 * 2.5 - 40.5 * $level + 360;
		}
		return $level ** 2 * 4.5 - 162.5 * $level + 2220;
	}
echo(getTotalXpForLevel($level));
```

**Comment by daniktheboss** [comment]
@robske110 sorry but I don't know how to dm you... is it possible to have a mcpe server on python?

**Comment by robske110** [comment]
well, if someone would develop it

**Comment by daniktheboss** [comment]
Ok thanks! I just started the project! If someone wants to come help that would be great!

**Comment by Aericio** [comment]
If anyone wants to code in Python*

**Comment by thebigsmileXD** [comment]
Python is fast, but guess it will be the same mess like PHP or Java
