### ISSUE TITLE
0.14.0 update :)

### ISSUE THREAD

**Issue by SuperAdam47** [ClearSkyTeam/ClearSky#61]

**Comment by SuperAdam47** [comment]
hard

**Comment by PocketKiller** [comment]
...

**Comment by PocketKiller** [comment]
do youhave the APK?

**Comment by SuperAdam47** [comment]
yes sure
0.14.0 build 1 link: 
http://s3.dosya.tc/server7/ekf4jx/Minecraft_-_Pocket_Edition.apk.html

**Comment by SuperAdam47** [comment]
join beta tester:
https://play.google.com/apps/testing/com.mojang.minecraftpe

**Comment by aodzip** [comment]
0.14.0 now available in branch
