### ISSUE TITLE
Fishhook error help!

### ISSUE THREAD

**Issue by jdongel2004** [ClearSkyTeam/ClearSky#610]
Notice: Trying to get property of non-object in C:\Users\Administrator\Desktop\ClearSky-php7\src\pocketmine\Player.php on line 2247

Press the fish comes this is.

**Comment by robske110** [comment]
Will look into this, idk why there should be a non-object instead of just NULL though

**Comment by thebigsmileXD** [comment]
Isn't this a duplicate?

**Comment by robske110** [comment]
No, i fixed the other issue and possibly created this one
