### ISSUE TITLE
ClearSky And Slapper getSkinId Problem

### ISSUE THREAD

**Issue by FuxonPlayz** [ClearSkyTeam/ClearSky#611]
Hi There.

I was using Genisys And I converted to ClearSky for slow World Loading issue on Genisys
But I Get Problem With Slapper Spawning And I wasn't get this problem in Genisys Anyway this is the Problem
[CODE] 17.07 14:45:50 [Server] Server thread/CRITICAL Unhandled exception executing command 'slapper spawn Human Team Games' in slapper: Call to undefined method pocketmine\Player::getSkinId()
17.07 14:45:50 [Server] Server thread/CRITICAL Error: "Call to undefined method pocketmine\Player::getSkinId()" (EXCEPTION) in "/Slapper_v1.2.9.7.phar/src/slapper/Main" [/CODE]

I uploaded this issue to Slapper Github Page As well but the Author Closed it and told me This Problem From ClearSky

Sorry For My Long Post And My Bad English :(

**Comment by SalmonGER** [comment]
It's more likely an issue from Slapper since it uses the API of Genisys.
The only thing we could do is doing something like Dan did:
https://github.com/ClearSkyTeam/ClearSky/commit/9e0eb0b877340ef916dc87e8fef9b0e8e2e16fd8
Since doing it like Genisys maybe isn't good for PocketMine API support.

**Comment by thebigsmileXD** [comment]
Your Slapper is outdated. It is "skinName", not "skinId"

**Comment by FuxonPlayz** [comment]
@thebigsmileXD it's The Latest Version But I will edit Plugin And Change it to skinName Thanks For The Help :)
