### ISSUE TITLE
Robske, Fix website.

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#614]
Your website doesn't work, and I can't get a phar Q.Q
( @thebigsmileXD whats your website again :D)

**Comment by robske110** [comment]
Explain how it doesn't work?

**Comment by robske110** [comment]
Oh, the servers crashed. Well gonna look into this, looks like a massive attac. I'm hosting the site very stupidly

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/CSPhar.php
works again

if you want some nicer view try:
http://robskebueba.no-ip.biz/CSPhar.php?type=1&branch=php7
