### ISSUE TITLE
Lag? Why?

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [ClearSkyTeam/ClearSky#615]
http://timings.aikar.co/?url=19898147

**Comment by TDMidkwhatisxd** [comment]
I dont mean lag , just some red ticks !!! Is normal?

**Comment by robske110** [comment]
Your server seems ok. But player login events/handling is massively overloaded, some plugins may do shit there or you just have too many joining players on your server at the same time

**Comment by TDMidkwhatisxd** [comment]
Ya, there are players who join/quit , and many of them, how to stop that?
New way to flood  xd !!!

**Comment by thebigsmileXD** [comment]
-.- there are MANY solutions in the forums. maybe best way: change treeshold in network in pocketmine.yml

**Comment by Aericio** [comment]
Also you should maybe switch to SimpleAuth, less bugs :P

**Comment by TDMidkwhatisxd** [comment]
Simpleauth ... i use it!!

**Comment by Aericio** [comment]
I mean ServerAuth by Ecology, sorry.

**Comment by TDMidkwhatisxd** [comment]
xd :D  !! I put compresion lvl 5  !! is that ok?

**Comment by TDMidkwhatisxd** [comment]
I dont wanna reset all passwords , this is why i dont switch :D

**Comment by Aericio** [comment]
I believe you can convert it to ServerAuth.

**Comment by TDMidkwhatisxd** [comment]
cant !! Unless , if u use mysql? idk :D

**Comment by Aericio** [comment]
[pocketmine file.zip](https://github.com/ClearSkyTeam/ClearSky/files/370485/pocketmine.file.zip)
Try using this pocketmine.yml :D

**Comment by thebigsmileXD** [comment]
@aericio is right. There is a thread in the forums which teaches you how to convert it. in Serverauth you can set the encryption in the config i think.

**Comment by TDMidkwhatisxd** [comment]
Nvm , im going back to genisys (-_-) ... That Dos issue made me see something -_- !!!
Good luck with anti-ddos scripts =)))))))))

**Comment by robske110** [comment]
good luck with continuing being well, sorry for this, dumb

**Comment by thebigsmileXD** [comment]
@TDMidkwhatisxd You saw that we have knowledge? You are so kind :) ty!
AntiDDos scripts are SERVER (MACHINE) TASKS, not Pocket Edition Server Software tasks, also Genisys does not have "Anti-DDos-scripts" either.

**Comment by daniktheboss** [comment]
Btw thanks I installed the script works like a charm! And genisys sucks ass!

**Comment by Aericio** [comment]
Genisys has nothing for dos protection...

**Comment by robske110** [comment]
And we neither
