### ISSUE TITLE
Dos

### ISSUE THREAD

**Issue by daniktheboss** [ClearSkyTeam/ClearSky#616]
So I don't really know if I should post this or not but. People can dos servers. I tried doing it on my own and it shutdown for like 10 minutes. How can we stop apps from requesting lots of packets?

**Comment by Aericio** [comment]
I don't think there's any way to do it...

**Comment by daniktheboss** [comment]
Aww man... that sucks!

**Comment by Aericio** [comment]
Genisys could probably implement it and make it useless like Synapse.

**Comment by daniktheboss** [comment]
What is synapse

**Comment by Aericio** [comment]
Some useless thing they added... I have no idea what it does, seems useless.

**Comment by SalmonGER** [comment]
@Aericio it's a proxy to transfer players between servers

**Comment by SalmonGER** [comment]
@Aericio it's a proxy to transfer players between servers

**Comment by Aericio** [comment]
@SalmonGER That's basically useless, why not just wait until Mojang unfixes that bug, or when someone creates a more advanced plugin. No need to add it to the server, the file is hella bigger now.

**Comment by SalmonGER** [comment]
@Aericio It isn't a bug which will get fixed by Mojang. Also there are already other proxys idk why Genisys made an own one.

**Comment by Aericio** [comment]
> unfixes that bug

**Comment by thebigsmileXD** [comment]
@aericio wtf are you talking. All Synapsis does is proxy stuff. and wtf does "unfix the bug" mean? its no reason of a bug..

**Comment by robske110** [comment]
we cannot really do sth 'bout ddos, you should put the right proxies in front of your server. Some companies offer working soloutions to protect an application.

**Comment by TDMidkwhatisxd** [comment]
Even so called , anti-ddos scripts , cant do nothing!!
You need to buy a server ddos protected :)

**Comment by robske110** [comment]
DDOS protected servers use scripts too. There's no difference.

**Comment by TDMidkwhatisxd** [comment]
Are u ...... ???? LOL

**Comment by robske110** [comment]
what?

**Comment by TDMidkwhatisxd** [comment]
1. You need a big computer to handle all packets
2. Lots of bandwidth 
+ more i guess !!!!

**Comment by thebigsmileXD** [comment]
_**Locked because discussion with non-specialist**_

**Comment by robske110** [comment]
+1
