### ISSUE TITLE
Enchantment Table crash

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [ClearSkyTeam/ClearSky#617]
ClearSky Crash Dump Tue Jul 19 03:35:11 CDT 2016

Error: Call to undefined method pocketmine\item\IronChestplate::isBoots()
File: /src/pocketmine/item/enchantment/EnchantmentLevelTable
Line: 183
Type: notice

Code:
[174] 		$enchantmentIds = [];
[175] 		if($item->getId() == Item::BOOK){
[176] 			$enchantmentIds = array_keys(self::$map);
[177] 		}elseif($item->isArmor()){
[178] 			$enchantmentIds[] = Enchantment::TYPE_ARMOR_PROTECTION; 
[179] 			$enchantmentIds[] = Enchantment::TYPE_ARMOR_FIRE_PROTECTION; 
[180] 			$enchantmentIds[] = Enchantment::TYPE_ARMOR_EXPLOSION_PROTECTION; 
[181] 			$enchantmentIds[] = Enchantment::TYPE_ARMOR_PROJECTILE_PROTECTION; 
[182] 			$enchantmentIds[] = Enchantment::TYPE_ARMOR_THORNS; 
[183] 			if($item->isBoots()){
[184] 				$enchantmentIds[] = Enchantment::TYPE_ARMOR_FALL_PROTECTION; 
[185] 			}
[186] 			if($item->isHelmet()){
[187] 				$enchantmentIds[] = Enchantment::TYPE_WATER_BREATHING; 
[188] 				$enchantmentIds[] = Enchantment::TYPE_WATER_AFFINITY; 
[189] 			}
[190] 		}elseif($item->isSword()){
[191] 			$enchantmentIds[] = Enchantment::TYPE_WEAPON_SHARPNESS; 
[192] 			$enchantmentIds[] = Enchantment::TYPE_WEAPON_SMITE; 
[193] 			$enchantmentIds[] = Enchantment::TYPE_WEAPON_ARTHROPODS; 

Backtrace:
#0 /src/pocketmine/inventory/BaseInventory(134): pocketmine\inventory\EnchantInventory->onSlotChange(integer 0, pocketmine\item\ItemBlock Item Air (0:0)x0)
#1 /src/pocketmine/tile/EnchantTable(29): pocketmine\inventory\BaseInventory->setItem(integer 0, pocketmine\item\IronChestplate Item Iron Chestplate (307:0)x1)
#2 /src/pocketmine/tile/Tile(69): pocketmine\tile\EnchantTable->__construct(pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:EnchantTable.pocketmine\nbt\tag\IntTag:126.pocketmine\nbt\tag\IntTag:11.pocketmine\nbt\tag\IntTag:93.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:307.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.}.}.})
#3 /src/pocketmine/level/format/generic/BaseFullChunk(151): pocketmine\tile\Tile::createTile(string EnchantTable, pocketmine\level\format\mcregion\Chunk object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\StringTag:EnchantTable.pocketmine\nbt\tag\IntTag:126.pocketmine\nbt\tag\IntTag:11.pocketmine\nbt\tag\IntTag:93.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:307.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.}.}.})
#4 /src/pocketmine/level/Level(2795): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#5 /src/pocketmine/level/Level(2390): pocketmine\level\Level->loadChunk(integer 7, integer 5, boolean 1)
#6 /src/pocketmine/level/Level(3087): pocketmine\level\Level->getChunk(integer 7, integer 5, boolean 1)
#7 /src/pocketmine/Player(875): pocketmine\level\Level->populateChunk(integer 7, integer 5)
#8 /src/pocketmine/Player(1762): pocketmine\Player->sendNextChunk(boolean)
#9 /src/pocketmine/Server(2578): pocketmine\Player->checkNetwork(boolean)
#10 /src/pocketmine/Server(2304): pocketmine\Server->tick(boolean)
#11 /src/pocketmine/Server(2182): pocketmine\Server->tickProcessor(boolean)
#12 /src/pocketmine/Server(1777): pocketmine\Server->start(boolean)
#13 /src/pocketmine/PocketMine(449): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///root/1/root/ClearSky.phar/, string /root/1/root/, string /root/1/root/plugins/)
#14 (1): require_once(string phar:///root/1/root/ClearSky.phar/src/pocketmine/PocketMine.php)

ClearSky version: 1.1 #CuttingEdge [Protocol 81; API 2.0.0]
uname -a: Linux ast.localdomain 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64
PHP Version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

**Comment by TDMidkwhatisxd** [comment]
Server was barely on , with this crash spam :(

**Comment by thebigsmileXD** [comment]
@clearskyteam who of you messed with armor recently? this is genisys shit.

**Comment by TDMidkwhatisxd** [comment]
Yay !! :)

**Comment by TDMidkwhatisxd** [comment]
I whitelisted my server until it get fixed!!

**Comment by thebigsmileXD** [comment]
or just remove all enchanting tables.

**Comment by robske110** [comment]
or just stop copying from Genisys (no insult)

**Comment by TDMidkwhatisxd** [comment]
I cant track all enchantment tables!! :/

**Comment by TDMidkwhatisxd** [comment]
Idk who u talk to? Who is copying from genisys?

**Comment by robske110** [comment]
Nothing, we'll get this bug fixed

**Comment by thebigsmileXD** [comment]
https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/item/Item.php#L903-L918
