### ISSUE TITLE
Installation issue on Linux (./start.sh returns "Out of memory")

### ISSUE THREAD

**Issue by Pocketart** [ClearSkyTeam/ClearSky#618]
got all the necessary files ready, i just had to do ./start.sh but instead of starting server setup guide, it simply returned "out of memory"
I am on Ubuntu 16.04 x64 (4gb ram) using the latest phar build

**Comment by SalmonGER** [comment]
Sounds like bad bin files for me

**Comment by AndreTheGamer** [comment]
Have you tested it with a  different bin folder?

**Comment by robske110** [comment]
Bin files issue. Cannot reproduce with same system

**Comment by thebigsmileXD** [comment]
Had that too, simply use the PocketMine Bin folders.

**Comment by Aericio** [comment]
Or salmon's g0dly made bins (aka bad)

**Comment by SalmonGER** [comment]
;(

**Comment by thebigsmileXD** [comment]
@Aericio they only do crash as often as the pocketmine ones.

**Comment by SalmonGER** [comment]
@thebigsmileXD But the linux one's don't for me ;(
