### ISSUE TITLE
addExp() undefined

### ISSUE THREAD

**Issue by Skalin** [ClearSkyTeam/ClearSky#619]
Server version: ClearSky version 1.1 "Sunrise" (API 1.13.1) Build 4b7aa6be39c859586be76cdc1d99b8433388a970

Data from crashdump
ClearSky Crash Dump Wed Jul 20 09:45:36 CEST 2016

Error: Call to undefined method pocketmine\Player::addExp()
File: /src/pocketmine/entity/ExperienceOrb
Line: 83
Type: E_ERROR

Code:
[74] 				$this->motionX = $motX / $motSqrt * $motC * $moveSpeed;
[75] 				$this->motionY = $motY / $motSqrt * $motC * $moveSpeed;
[76] 				$this->motionZ = $motZ / $motSqrt * $motC * $moveSpeed;
[77] 			}
[78] 			
[79] 			if($Target->distance($this) <= $this->pickuprange){
[80] 				$this->timings->stopTiming();
[81] 				$this->close();
[82] 				if($this->getExperience() > 0){
[83] 					$Target->addExp($this->getExperience());
[84] 				}
[85] 				return true;
[86] 			}
[87] 		}
[88] 		
[89] 		$this->move($this->motionX, $this->motionY, $this->motionZ);
[90] 		
[91] 		$this->updateMovement();
[92] 		
[93] 		$this->timings->stopTiming();

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ClearSky version: 1.1 #4b7aa6be39c859586be76cdc1d99b8433388a970 [Protocol 81; API 1.13.1]
uname -a: Linux ms12 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt25-2~bpo70+1 (2016-04-12) x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:

**Comment by thebigsmileXD** [comment]
This should've been fixed since https://github.com/ClearSkyTeam/ClearSky/commit/9e0eb0b877340ef916dc87e8fef9b0e8e2e16fd8

See this line:
https://github.com/ClearSkyTeam/ClearSky/commit/9e0eb0b877340ef916dc87e8fef9b0e8e2e16fd8#diff-e7946cb9b02a4dba1a3d5e627e31b2ccR320

Pleaase update your phar.

**Comment by robske110** [comment]
You see that 1.1 thingy
It's not 1.1-php7
Php5 issue

**Comment by thebigsmileXD** [comment]
*Please upgrade to PHP7

**Comment by Skalin** [comment]
How am I able to update the server, when the Jenkins is offline? 
I do not wanna go to PHP7 version, I am holding on PHP5 because the compilation works everytime, not like at the PHP7. Thanks.

**Comment by thebigsmileXD** [comment]
@Skalin Please check the readme, then you find out something special ;)

**Comment by Skalin** [comment]
Yeah, I will find a PHP7 build there, not PHP5. Is it already able to work properly now? I see a lot of bugs on Windows 10 and I am scared of them. That is why I am using the PHP5 builds.

**Comment by thebigsmileXD** [comment]
Since a while! PHP7 is pretty stable. Well, in windows 10 you can't craft.. but thats same in PHP5

**Comment by Skalin** [comment]
Okay, I will try it. Thanks. :)

**Comment by thebigsmileXD** [comment]
Welcome :)
And you may concider to use the PocketMine bin files, the clearsky ones are messy

**Comment by robske110** [comment]
Win10 fixes branch helps
And i think that one is already php7 based

**Comment by thebigsmileXD** [comment]
@robske110 it fixes nothing for me at all.

**Comment by robske110** [comment]
Have you tried it

**Comment by thebigsmileXD** [comment]
@robske110 Sure i did, else i would not say it.

**Comment by robske110** [comment]
Well, for me everything works
