### ISSUE TITLE
pvp

### ISSUE THREAD

**Issue by Tolo0** [ClearSkyTeam/ClearSky#62]
I seem to be having problems when doing pvp. Not sure exactly what it is. But sometimes when players get hit with a diamond sword. They die really fast. Then other times. They don't die at all 😕

**Comment by PocketKiller** [comment]
sometimes it goes a 3-hit with 1 touch instead of 1 hit.

**Comment by Tolo0** [comment]
Any fix on this anytime soon? Players can't pvp fair.

**Comment by thebigsmileXD** [comment]
No problems on my server. not in any way.

**Comment by Tolo0** [comment]
Really 😕 wtf players keep glitching on mine. Could it be a plugin effecting it?

**Comment by Adam1609** [comment]
Does enchant system affecting it???

**Comment by TheKillerTacos** [comment]
It might be a bad Internet Connection, or uncomplete package sending? or the server overloads and makes everything CRAP, so hope they see if its fixable, It doesnt happend on my server, but if its BUG,
i wish it gets fixed..

**Comment by aodzip** [comment]
Does everyone have this bug?

**Comment by icsmoke-mcpe** [comment]
Diamond sword damage is normal on Player.php (same as original minecraft damage) , yeah i feel also very damage, and then i edited Diamond sword damage at Player.php to low

**Comment by Landy005** [comment]
Pvp doesn't work , players can't hit each other, pvp is on, gamemode is survival.

**Comment by robske110** [comment]
Still issue?

**Comment by thebigsmileXD** [comment]
Hehe. We are the only repo that asks "still an issue?"

**Comment by robske110** [comment]
will  close now
