### ISSUE TITLE
Trap Doors

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#620]
Server thinks your flying when you are on trap doors, not connected to any blocks.

**Comment by robske110** [comment]
And when it's connected to blocks, you're not flying?

Strange. I hate hitboxes

**Comment by Adam1609** [comment]
Do you mean that TrapDoor is Air?

**Comment by Aericio** [comment]
Use world edit to make the trap doors float. They are not air, they can still be used.

**Comment by thebigsmileXD** [comment]
Trapdoors can't be placed everywhere yet.

**Comment by thebigsmileXD** [comment]
hitbox, checkmovement etc so fucked up

**Comment by thebigsmileXD** [comment]
Fixed
