### ISSUE TITLE
Notice: Trying to get property of non-object in Player.php on line 2247 (PlayerFishEvent)

### ISSUE THREAD

**Issue by SalmonGER** [ClearSkyTeam/ClearSky#621]
public function onFish(PlayerFishEvent $event){
		$player = $event->getPlayer();
		var_dump($player);
	}

Something like that gives me this:

`Notice: Trying to get property of non-object in D:\Minecraft\Server\PocketMine-MP\src\pocketmine\Player.php on line 2247
object(pocketmine\Player)#9944 (0) {
}
`

**Comment by robske110** [comment]
Duplicate...

**Comment by robske110** [comment]
https://github.com/ClearSkyTeam/ClearSky/issues/610

**Comment by robske110** [comment]
I'll fix it anyways

**Comment by SalmonGER** [comment]
oh sry
