### ISSUE TITLE
Can't place spawn eggs into spawners

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/ClearSky#625]
Place a Mob Spawner, put randomly egg on the monster spawner, it throws some soft of rope item, I think it was a bug, probably!

**Comment by MCPEPIG** [comment]
Since when could u place mobs in mob spawners in ClearSky?-

**Comment by Adam1609** [comment]
I am sorry, wrong issue :) it's actually my custom plugin that do all the things

**Comment by thebigsmileXD** [comment]
@MCPEPIG i am pretty sure you already can lol

**Comment by Adam1609** [comment]
So 0.15 bug or something else?

**Comment by Aericio** [comment]
In ClearSky, you cant put mob eggs in the spawner. (For me at least, latest version)

**Comment by robske110** [comment]
So this is a plugin issue

**Comment by Adam1609** [comment]
Like I said, it's one of my plugin that do all the leashes thing (even FNPC though)

**Comment by thebigsmileXD** [comment]
Reopened with new title

**Comment by Aericio** [comment]
rofl

**Comment by robske110** [comment]
Why is this AsyncAI?

**Comment by thebigsmileXD** [comment]
I thought about adding it to 'AsyncAI due to the spawn manager

**Comment by Adam1609** [comment]
So get this though, would you?

**Comment by blakepell** [comment]
Not sure if this is related, in creative mode my 7 year old dropped zombie spawn egg and the iOS MCPE client (0.15.4) crashed immediately (and then would crash upon trying to rejoin the world).  The Windows 10 Edition (0.15.8) did not crash, the zombie was rendered with what looked like a leash, I was able to kill it allowing the iOS version to re-connect.

**Comment by Aericio** [comment]
0.15.8?

**Comment by robske110** [comment]
Try updating maybs?

**Comment by blakepell** [comment]
0.15.6*.  I will update both the phar and the iOS version this evening and test to see if the update fixed it and it's a client issue.

**Comment by blakepell** [comment]
Just reporting back, updating the iOS client to version 0.15.6 fixed the crash issue.

**Comment by thebigsmileXD** [comment]
Today's todo, will add spawn eggs placing in spawner to AsyncAI.
