### ISSUE TITLE
Some plugins are not working

### ISSUE THREAD

**Issue by TheProest35YT** [ClearSkyTeam/ClearSky#627]
Some PocketMine , ImagicalMine plugins are not working :(

**Comment by thebigsmileXD** [comment]
Fault of the plugins. The coders write them especially for one core. If they add custom functions, they should do it WITHIN the plugin instead of using core ones that are not in PocketMine.

**Comment by thebigsmileXD** [comment]
And about your PocketMine ones: i am REALLY sure its your fault because you have outdated plugins.

**Comment by TheProest35YT** [comment]
Its PHP 7

**Comment by thebigsmileXD** [comment]
So, the PocketMine ones should work. Any errors on startup? Maybe i can still help.

**Comment by TheProest35YT** [comment]
No i know but ImagicalMine's dont work

On clearsky 0.15

**Comment by thebigsmileXD** [comment]
Duplicate - Already discussed in other issues.

**Comment by TheProest35YT** [comment]
Which issue

**Comment by TheProest35YT** [comment]
There are 390 closed and 20 Open

**Comment by Aericio** [comment]
#629 - Your issue was later, but everything is explained in this one.

**Comment by TheProest35YT** [comment]
Ok @Aericio
