### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by TheBigHacker0100** [ClearSkyTeam/ClearSky#629]
Well, i used Genysis and 30 of my plugins when i switched to ClearSky only 17 of them worked :'(

**Comment by SalmonGER** [comment]
Sadly those plugins probably use methods which are not supported by ClearSky since it sticks to the PocketMine API.

**Comment by Aericio** [comment]
Genisys uses a different API than PocketMine. Most plugins from pocketmine's website should work, but most from Genisys shouldn't.

**Comment by robske110** [comment]
Have you tried setting all incompatible override settings in pocketmine.yml to true?

**Comment by TheProest35YT** [comment]
Ok @robske110
