### ISSUE TITLE
Spectator Slow, Spectator Fast.

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#631]
When you go in /gm 3, you move slowly. If you go in /gm 1, and fly fast, then switch back to /gm 3, you go the same speed as creative mode.

[Video <-- Not Working Yet](https://youtu.be/HJRxfcgPzkQ)

My wifi is being insanely slow for some reason, probably because its raining really hard.
![image](https://cloud.githubusercontent.com/assets/16523741/17090095/d196b6de-51c8-11e6-9747-c852ef4c60d7.png)
^^^ WTF? 30 second video, please ISP! I did not pay for .01 kbps speed!

**Comment by robske110** [comment]
We don't control the speed there at all, so this is very very very very likely the client being the client

**Comment by robske110** [comment]
Can you test this in singleplayer
Edit: lol, singleplayer doesn't even support spectator mode, nor switching gamemodes so i really assume this is the client

**Comment by thebigsmileXD** [comment]
@robske110 Can't even access spectator using my toolbox mod.. I guess spectator is something of the server.. like: turning off interaction/collision and vanishing the player

But i confirm the speed stuff. always annoys me in OneInTheChamber

**Comment by Aericio** [comment]
Everything is client, client, client >:C
