### ISSUE TITLE
bin\php\php.exe: Exit 127

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#633]
Server keeps doing this for some reason, started happening 2 days ago. I had debug2 on also, there was no errors. After it says that, it stops the server. I don't think its ram problem, because I'm giving it way more than enough ram, and server isn't laggy or anything when this happens. Any help?

**Comment by kam187** [comment]
127 usually means an exec was called to an illegal command.

I'm guessing your php or environment changed recently.

**Comment by Aericio** [comment]
I changed to php 7.0.8 a few weeks ago, not 2 days ago. I don't think that could be the problem since it wasn't happening before.

**Comment by thebigsmileXD** [comment]
Confirmed ALOT.

**Comment by kam187** [comment]
I think it's related to the gc bug.  I checked with gdb and there's a fault in spl_heap_object_get_gc.

I don't understand why it would return with 127 tho - which is 'command not found' for an exec call.  Could be corruption.

Anyway it's related to pthreads, i'll see if i can fix it.

**Comment by robske110** [comment]
I don't have this ever
PM bins, MacOSX

**Comment by Aericio** [comment]
We talkn about Windows here.

**Comment by robske110** [comment]
Well, then this is a php bin issue and not ours
For example pthreads using exex()

**Comment by SalmonGER** [comment]
Also never have this (Linux) Dan and you have that (Windows)
Windows only?

**Comment by kam187** [comment]
I'm already looking into pthreads.  My fork is here:

https://github.com/kam187/pthreads

Expect more commits soon.

**Comment by robske110** [comment]
so this is windows-only?

**Comment by Aericio** [comment]
Probably.

**Comment by SalmonGER** [comment]
I guess so because I don't run .exe files on my Linux system

**Comment by Aericio** [comment]
It seems like when server freezes for only a few seconds (it could probably recover from it), it just sends that message and stops the server. It doesn't save the world or properly unload all the plugins.

**Comment by robske110** [comment]
ah! Now i got it. This is indeed our issue and no php lib issue then. Because you can get exit 127 easily by doing:
```php
public function lol(){
 $this->lol();
}
```

**Comment by Aericio** [comment]
loop/such thingy?

**Comment by SalmonGER** [comment]
If you do something like Robske posted it would theoretically call itself without stopping. Server doesn't like that so it dies.

**Comment by thebigsmileXD** [comment]
Well, seems like i fixed it, haven't had a crash for a while now

**Comment by Aericio** [comment]
It still seems to do it for me, I'll update again and see.

**Comment by Aericio** [comment]
I updated, it still does it for me. It first freezes. Once it freezes for more than 5 seconds, it just terminates the server. It could recover sometimes when the server freezes... why does it just automatically just stop >:(

**Comment by robske110** [comment]
This confirms my theory of a unterminated/endless loop. This may be just a function calling itself. Or a function calling a function wich calls a function wich calls the first function. Or just a while loop. This is verryy hard to trace back. @Aerico if you get this really often, and run your server on linux i might be able to help. In this case please contact me on telegram

**Comment by thebigsmileXD** [comment]
Had 2 segfaults. alot less then before still

**Comment by Aericio** [comment]
I don't know how to get your telegram :/
Also, I'm running on windows and not on Linux. (I might plan to dual boot into Linux but setting up PuTTY is very confusing >:(

**Comment by thebigsmileXD** [comment]
Setting up putty isnt confusing at all! It doesnt even need to install! Open, enter adress, done

**Comment by Aericio** [comment]
Its confusing for me >:(
Do I need to port forward anything? And I mean setting up as in setting it up on your own computer.

**Comment by SalmonGER** [comment]
The computer u want to connect to should just run a SSH server. My system had one pre-installed. I also could use SFTP which is more secure than FTP. Default port should be 22 which you should port forward.

**Comment by Aericio** [comment]
But how do I install a SHH server on Windows?

**Comment by robske110** [comment]
Does anyone run a server on linux and has this quite often? If not, we will not be able to trace this down. It may also be a php issue.
[It is really almost not possible to track this down.]

**Comment by daniktheboss** [comment]
Run on linux(raspberrian 😂) but never had this
