### ISSUE TITLE
Player Damage + Fire Damage

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#634]
When you hit someone, they still take damage but it doesn't show the hit animation (body turns red thing). It shows for the player you hit, but doesn't show when you hit the player. I tested it without any plugins with the latest version, and it was the same.  When you are on fire, you do not see the fire animations, but others can see the fire animation
#### how2reproduce if you don't understand me:
- hit someone.
- set self on fire

**Comment by Aericio** [comment]
https://github.com/ClearSkyTeam/ClearSky/commit/811c8e61944e286c41fce4e8a7c7f688af44f2ac
I wonder why there are no hitting animations. #BlameDan

**Comment by daniktheboss** [comment]
😂

**Comment by thebigsmileXD** [comment]
> I wonder why there are no hitting animations. cough cough cough 811c8e6

I wonder if you are using the latest version or i just forgot to upload the changes.

**Comment by Aericio** [comment]
I am using the latest version, I updated the phar yesterday.

**Comment by robske110** [comment]
So should we revert 811c8e6

**Comment by Aericio** [comment]
You should really revert for a temporary solution...

**Comment by intagaming** [comment]
But sir i still can't see the hit animation after revert that commit..

**Comment by robske110** [comment]
ugh

**Comment by Aericio** [comment]
I don't think he reverted it yet

**Comment by intagaming** [comment]
But i've tried on my server with the reverted commit

**Comment by thebigsmileXD** [comment]
I already reverted it ages ago.. -.-

**Comment by Aericio** [comment]
It still happens.

**Comment by robske110** [comment]
Fuck this.

**Comment by Aericio** [comment]
Don't ;(
It makes pvp worse.

**Comment by thebigsmileXD** [comment]
@aerico its in an other commit

**Comment by Aericio** [comment]
oh ok.

**Comment by robske110** [comment]
is this still happening?

**Comment by Aericio** [comment]
Not sure, i'll check.

**Comment by Aericio** [comment]
Player damage = still bugged. (no hit animation)
Fire damage = right when you get out of the fire, fire effect doesn't stay. (flame)

**Comment by thebigsmileXD** [comment]
I could fix number 1.

**Comment by Aericio** [comment]
To be honest, I liked the player damage glitch kind of. Less laggier :D
Do you know of any plugin that could cancel that event?

**Comment by SalmonGER** [comment]
Cancel that event completly? I'm sure PvP won't work then

**Comment by Aericio** [comment]
Cancel hit animation -_-

**Comment by SalmonGER** [comment]
That's possible. But does it really reduce lag?

**Comment by Aericio** [comment]
Idk, I don't really know. Hit animation seeeeeeems to be late for me.
