### ISSUE TITLE
Dumping Items

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#635]
When you dump items out of your inventory, all of the items that are the same as the one you are throwing out gets thrown out. For example, if you are wearing iron chestplate, and there are 5 other iron chestplates in your inventory, dumping one of them will dump all of them.
Possibly l0rd Mojang himself with the jesus inventory coding.

**Comment by Aericio** [comment]
ok its probably client.

**Comment by robske110** [comment]
Let's just put that under general inventory issues. We already have issues for that :)
And btw @dktapps is rewriting pretty much of the inventory and I already have permission to copy some bits of it :)

**Comment by dktapps** [comment]
@robske110 Progress update: fixed slot dragging and that f###### irritating inventory spaz - FINALLY

**Comment by robske110** [comment]
Yey, i may start to copy your changes finally

**Comment by dktapps** [comment]
@robske110 it's not finished yet

**Comment by robske110** [comment]
I know. But starting early is good
Because i can't press a COPY button :P

**Comment by dktapps** [comment]
@robske110 I would disagree, because I'm going to be making a lot more changes yet. How about you save yourself the effort and I'll make a PR?

**Comment by dktapps** [comment]
I'm going to make PRs to everybody once it's done anyway. (Including PM itself, although it'll never be merged)

**Comment by robske110** [comment]
Thanks. But making that PR will take ages

**Comment by dktapps** [comment]
@robske110 you underestimate me ;) don't worry, it won't be long.

**Comment by robske110** [comment]
I didn't mean that you won't do it
I meant that it would take you time to do it

**Comment by dktapps** [comment]
@robske110 as I said, you underestimate me. :P trust me, it won't take me long.

**Comment by robske110** [comment]
I don't mean that bdiquz h it'll be ahulong time i did au
So

Whatever, if you feel insulted by me in any way, i aplogize for that.

**Comment by dktapps** [comment]
Don't worry about it. P.S. I've figured out how to get anvils fully functional with minimal effort

**Comment by dktapps** [comment]
Strike that last - anvils are going to be the biggest pain in the ass in the world. But I'm still going to be forced to implement them.

**Comment by robske110** [comment]
:D

**Comment by Aericio** [comment]
aka use genisys' inventory?

**Comment by robske110** [comment]
aka use @dktapps's rewrite
