### ISSUE TITLE
0.15.4 Compatibility

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#636]
0.15.4 isn't allowed to join in 0.15.0-3 servers. (y protocol change? >:C)
#fkmojangnowicanttestonmyserver

**Comment by caspervanneck** [comment]
For my it isnt out jet

**Comment by caspervanneck** [comment]
In holland

**Comment by Aericio** [comment]
448c797628809cedabcdef23846d9eac9c282c9f :+1:
