### ISSUE TITLE
How 

### ISSUE THREAD

**Issue by majovec** [ClearSkyTeam/ClearSky#637]
How to install on Debian ClearSky php5

**Comment by Aericio** [comment]
Using command terminal?

**Comment by SalmonGER** [comment]
You should ask something like that in the Telegram group. Anyways I couöd help you to install ClearSky on Debian but only with PHP7.

**Comment by majovec** [comment]
I need php5 instructions

**Comment by Aericio** [comment]
Why do you want PHP5? PHP7 has better performance and will run smoother. ClearSky soon will not support PHP5 for 0.16. If it's incompatible plugins problem, turn on all of the incompatible api loader thing in pocketmine.yml.

**Comment by robske110** [comment]
And btw, php5 branch is currently massively broken

**Comment by Aericio** [comment]
rip php5
