### ISSUE TITLE
Launch() function error

### ISSUE THREAD

**Issue by intagaming** [ClearSkyTeam/ClearSky#639]
But i have the fix. 
Line 611 in Item.php: 
if($launched instanceof Projectile){
The Projectile haven't been defined. The use Pocketmine... thing.
Also:
$player->server->getPluginManager()->callEvent($projectileEv = new ProjectileLaunchEvent($launched));
The "server" should be "getServer()" because of private.

**Comment by robske110** [comment]
$server in Player is not private/protected

**Comment by intagaming** [comment]
Please sir
https://github.com/ClearSkyTeam/ClearSky/blob/php7/src/pocketmine/entity/Entity.php#L186

**Comment by thebigsmileXD** [comment]
-.-
