### ISSUE TITLE
0.14.x

### ISSUE THREAD

**Issue by SuperAdam47** [ClearSkyTeam/ClearSky#64]
update now!

**Comment by SalmonGER** [comment]
It already is. https://github.com/ClearSkyTeam/ClearSky/tree/0.14.0

**Comment by SuperAdam47** [comment]
but not phar

**Comment by thebigsmileXD** [comment]
We'll add later

**Comment by lolcraftboy14** [comment]
Wait no phar

**Comment by lolcraftboy14** [comment]
No ClearSky fore android

**Comment by SalmonGER** [comment]
Just make a own .phar with DevTools. xD I did that, too.

**Comment by SuperAdam47** [comment]
how to

**Comment by thebigsmileXD** [comment]
@SuperAdam47 there are enough tutorials.
