### ISSUE TITLE
0.15 client still crashes

### ISSUE THREAD

**Issue by remotevase** [ClearSkyTeam/ClearSky#642]
When I try to connect to my server, the 0.15 client continues to crash due to the red laser. Why?

**Comment by remotevase** [comment]
Oops, possibly just because outdated based on
https://github.com/ClearSkyTeam/ClearSky/commit/448c797628809cedabcdef23846d9eac9c282c9f

so going to try 15.4

**Comment by Aericio** [comment]
It works fine for me...

**Comment by remotevase** [comment]
Before I do that, I would like to ask: Is there a problem with joining into converted pc maps?

**Comment by Aericio** [comment]
Oh, I converted my map to PE and it worked perfectly fine. I am still using it right now, no bugs

**Comment by remotevase** [comment]
Hmm, can you try placing a sign, then quitting the title, then rejoining. Does it crash? I think it will

**Comment by Aericio** [comment]
I have signs in my world... It doesn't crash for me.

**Comment by remotevase** [comment]
Really? Hmm, entities? Tried placing villagers, steve heads? Strange, either way...

**Comment by Aericio** [comment]
But what do you mean by red laser? The crash message?

**Comment by remotevase** [comment]
No, there is a red laser connecting me to all entities. There is no crash message. The client crashes, the server is fine. The red laser is literally a red laser beam that connects me to the entities.

**Comment by Aericio** [comment]
Oh like the leash thing that happened?

**Comment by remotevase** [comment]
it is the leash thing, repeated again!

**Comment by remotevase** [comment]
Yup, it was just a problem with that world. Fixed in a new world!
