### ISSUE TITLE
0.15.4

### ISSUE THREAD

**Issue by TheProest35YT** [ClearSkyTeam/ClearSky#643]
Protocol -----> 82
API -----> 2.0.0

**Comment by robske110** [comment]
https://github.com/ClearSkyTeam/ClearSky/blob/php7/src/pocketmine/network/protocol/Info.php#L13
https://github.com/ClearSkyTeam/ClearSky/blob/php7/src/pocketmine/resources/pocketmine.yml#L123

**Comment by Aericio** [comment]
Reset your pocketmine.yml :)
