### ISSUE TITLE
Minecarts don't move

### ISSUE THREAD

**Issue by popkechupki** [ClearSkyTeam/ClearSky#644]
Mine cart is not motions now (on ClearSky php7). Is this the Bug?
(Sorry, I'm don't good at English...)

**Comment by robske110** [comment]
This feature is not implemented yet, but it'll be implemented very soon

**Comment by thebigsmileXD** [comment]
Rails dont break if slope is broken, Minecarts on slopes are rendered higher than the Server Shows them, other minecart types dont move at all, normal minecarts "Flash", different rail types dont connect to each other, can't open hopper/chest/furnace minecarts, (can't find furnace minecarts), detector rails don't give power, powered rails dont power when placed on redstone blocks, powered rails DO power when redstone block diagonally below rail

**Comment by Aericio** [comment]
If in progress... you should re-open the issue.

**Comment by robske110** [comment]
Rails are done

**Comment by SalmonGER** [comment]
Are they in the php7 branch updated too?

**Comment by daniktheboss** [comment]
@Robske... how does the server work? Where is the folder if u know... trying to understand how the server works so I can help if if needed

**Comment by robske110** [comment]
What how the server works?

**Comment by daniktheboss** [comment]
Like where is the folder that creates the server?

**Comment by robske110** [comment]
Wtf?

**Comment by robske110** [comment]
You mean the source?

**Comment by daniktheboss** [comment]
Yes

**Comment by HimbeersaftLP** [comment]
> Rails dont break if slope is broken, Minecarts on slopes are rendered higher than the Server Shows them, other minecart types dont move at all, normal minecarts "Flash", different rail types dont connect to each other, can't open hopper/chest/furnace minecarts, (can't find furnace minecarts), detector rails don't give power, powered rails dont power when placed on redstone blocks, powered rails DO power when redstone block diagonally below rail

And if you hit it, it will show crit-particles....

**Comment by thebigsmileXD** [comment]
Snake.php

**Comment by thebigsmileXD** [comment]
todo: re-make the linkapi.

**Comment by robske110** [comment]
Is already done...

**Comment by thebigsmileXD** [comment]
i mean whole branch its quite messy and btw i think this linkapi won't support riding entities like pig/horse, AI branch does
