### ISSUE TITLE
robskeibegyoufixwebsite

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#647]
![image](https://cloud.githubusercontent.com/assets/16523741/17352506/bb00bf4e-58d2-11e6-886f-a2dac6f0c793.png)
hail robske fix website plz
maybe you should just let @thebigsmileXD host it, your website always dies.

**Comment by robske110** [comment]
Apache crashed again. Maybe i should finally start using php7 insteas of php4 and apache from 2002

**Comment by thebigsmileXD** [comment]
This is no place to contact team members about they personal issues. Contact him otherwise.

**Comment by robske110** [comment]
well, you banned him from the telegram group. might help to urban him.
Website fixed, btw. (Using php 7.0.8 now, finally)
And this is no 'personal' issue, this is an official CS website.
