### ISSUE TITLE
Crafting in Win10 Edition: Crashes due to different recipe sizes

### ISSUE THREAD

**Issue by lcswolf** [ClearSkyTeam/ClearSky#652]
Using build 142 just trying to craft in 2x2 inv grid in a gresh install

[server.txt](https://github.com/ClearSkyTeam/ClearSky/files/403647/server.txt)
[CrashDump_Fri_Aug_5-06.18.47-ACT_2016.txt](https://github.com/ClearSkyTeam/ClearSky/files/403646/CrashDump_Fri_Aug_5-06.18.47-ACT_2016.txt)

**Comment by thebigsmileXD** [comment]
Using this issue as default. (PS: update your phar.)

**Comment by robske110** [comment]
Isn't this fixed now?

**Comment by thebigsmileXD** [comment]
Reverting is not resolving.

**Comment by lcswolf** [comment]
> Using this issue as default. (PS: update your phar.)

When i looked build 142 was the latest build the log is a continuation from last issue

**Comment by Aericio** [comment]
Build 142, I think he means that's the amount of releases on Robske's website lol.

**Comment by robske110** [comment]
Temporarily fixed, better win10 handling incoming, public testing announcement will be done.
