### ISSUE TITLE
Notice: Uninitialized string offset

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#655]
`Notice: Uninitialized string offset: 0 in phar://C:/Users/garre_000/Desktop/Network/ClearSky.phar/src/pocketmine/network/Network.php on line 210`
This spammed my console for more minutes. I would've given a debug 2 if there was any but I had to disable it to prevent lag. (and our server randomly just skyrocketed so it was laggy as hell)
##### and yes im using the latest version i updated just yesterday

**Comment by robske110** [comment]
debug2 shouldn't increase lag btw

**Comment by robske110** [comment]
and this is caused by a bad Player. Maybe an attack?

**Comment by Aericio** [comment]
Because the server logs the debug also, so wouldn't that give the logger more work + lag?

**Comment by robske110** [comment]
A liiitlle bit, depends how much your plugins call debug

**Comment by Aericio** [comment]
How they call debug? achancetospamthehelloutofconsole.

**Comment by thebigsmileXD** [comment]
*cough disable logging for a day or so in the config cough*
