### ISSUE TITLE
CircleCI add fixed link to latest phar

### ISSUE THREAD

**Issue by c-hri-s** [ClearSkyTeam/ClearSky#660]
Hi,

Is it possible to add a fixed link to the latest phar on CircleCI (http://robskebueba.no-ip.biz/CSPhar.php?type=1&branch=php7). This would allow people (me) to update their ClearSky installation through a script.

Previously with Jenkins we could always get: 

http://jenkins.clearskyteam.org/job/ClearSky-php7/lastSuccessfulBuild/artifact/*zip*/archive.zip

for the latest, but with the CSPhar pages the filename and host changes every time.

Thanks

**Comment by Aericio** [comment]
Like updating ClearSky using a Auto-Updater script kinda thing?

**Comment by c-hri-s** [comment]
Exactly that, yep.

I have a shell script that stops the service, downloads the latest phar, then starts things nightly (or did back when Jenkins worked ...)

**Comment by Aericio** [comment]
Can't you do the same thing using a web server, but you need to use Circle-CI's api? (i think thats how it worked)

**Comment by c-hri-s** [comment]
Perhaps .. but I've no idea how.

**Comment by Aericio** [comment]
Maybe you could ask Robske? but he might just close issue and not care and b loik

> just update manually

**Comment by thebigsmileXD** [comment]
http://wolvesfortress.de/circleci.php

**Comment by Aericio** [comment]
Ooo yeah dan has sum awesome website skillz with no templatez

**Comment by thebigsmileXD** [comment]
its a redirect. nothing else

**Comment by thebigsmileXD** [comment]
Wait i move the link

**Comment by c-hri-s** [comment]
That's good for me - thanks!

**Comment by thebigsmileXD** [comment]
```php
`

**Comment by thebigsmileXD** [comment]
But remember its not branch specific

**Comment by robske110** [comment]
Oh yeah, that could be a problem. Will provide this soon:
http://robskebueba.no-ip.biz/directPhar.php?branch=php7

**Comment by c-hri-s** [comment]
Hi - any news on this?

Thanks

**Comment by thebigsmileXD** [comment]
what news? sorry?

**Comment by c-hri-s** [comment]
> Will provide this soon:
> http://robskebueba.no-ip.biz/directPhar.php?branch=php7

I assumed Robske would make that link work at some point and link to the latest.

**Comment by thebigsmileXD** [comment]
pff he.. he does nothing ;)

**Comment by SalmonGER** [comment]
You can use CircleCIs API to get the latest build and it's artifacts.

**Comment by c-hri-s** [comment]
Do you have any example how, please?

**Comment by SalmonGER** [comment]
Well I'm not proud of but I tested some circleci api stuff at [Apollo](https://github.com/NycuRO/Apollo/blob/master/src/pocketmine/command/defaults/UpdateServerCommand.php). It downloads the newest phar built by circleci so it should be somehow what you could search?
However the best way to learn how the CircleCI API works would be to go to their site:
https://circleci.com/docs/api/

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/directPhar.php?branch=php7
Sorry i forgot about this, reopeing for me to not forget this. Expect this in some days.

**Comment by robske110** [comment]
Almost done. It just is a bit buggy, need to fix dat...

**Comment by Aericio** [comment]
Awesome

**Comment by thebigsmileXD** [comment]
@robske110 Error: 404_SITE_NOT_FOUND :D

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/CSdirectPhar.php?branch=php7

**Comment by Aericio** [comment]
![image](https://cloud.githubusercontent.com/assets/16523741/18428980/afe473c6-786c-11e6-9707-b46a7edaaec1.png)

**Comment by robske110** [comment]
Works :)

**Comment by c-hri-s** [comment]
Could you do have the script just to a location/redirect to the phar?, so someone can:

wget http://robskebueba.no-ip.biz/CSdirectPhar.php?branch=php7

**Comment by thebigsmileXD** [comment]
@robske110 don't start to use javascript for redirects in the case of ^ that.
use php header('Location:'$link);

**Comment by robske110** [comment]
@c-hri-s Of course, i'll do that, at the moment the site has a few bugs with other branches, i need some debug. Plannning to do this with ?debug=true later

**Comment by robske110** [comment]
CLOSING...
The website is now fairly working, there are some issues, it now redirects directly. If you want debug add ?debug=doForceTrue

**Comment by c-hri-s** [comment]
Doesn't seem to work for me?

http://robskebueba.no-ip.biz/CSdirectPhar.php?branch=php7

Parse error: syntax error, unexpected 'exit' (T_EXIT), expecting ',' or ';' in /Applications/XAMPP/xamppfiles/htdocs/CSdirectPhar.php on line 176

**Comment by thebigsmileXD** [comment]
@c-hri-s yea

**Comment by robske110** [comment]
forgot a semicolon, sorry
