### ISSUE TITLE
Respawning

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#669]
The respawn screen isn't there anymore, it just makes you glitch in blocks and you cant respawn unless you relog.

Its probably one of Mojang's popular "BUG FIXES" update for 0.15.6

its probably mojang

its definitely mojang.

**Comment by thebigsmileXD** [comment]
Well.. is the screen there if you press the "lock" key and then unlock the phone really fast? Me and my GF experienced that the whole GUI simply vanishes, entities vanish etc..

**Comment by robske110** [comment]
Wait i think we need setHealthPacket for death...

**Comment by robske110** [comment]
Can you try to do it with a older version?
It may be that setHealth packet is just bugged to always show that animation.

**Comment by Aericio** [comment]
Win10 edition, I don't see any "lock" feature.
