### ISSUE TITLE
some plugins cant be loaded

### ISSUE THREAD

**Issue by VCraftMCPE** [ClearSkyTeam/ClearSky#672]
there so much plugin cant be loaded like CustomAlerts or Query facade but it loaded in Genisys sadly my host onnly offer Clear sky

**Comment by daniktheboss** [comment]
What does the error say?

**Comment by robske110** [comment]
Do you have access to pocketmine.yml?

**Comment by caspervanneck** [comment]
#Load plugins whose major API version is too old
   


set tish to true at your pocketmine.yml

**Comment by caspervanneck** [comment]
and your ready to go and play

**Comment by Aericio** [comment]
CustomAlerts should work in ClearSky. (I think I edited all of my server API versions though)

**Comment by VCraftMCPE** [comment]
Okay thx that helped me

**Comment by VCraftMCPE** [comment]
and yes i have access to pocketmine.yml

**Comment by Aericio** [comment]
Does the server plugins work? If it still doesn't work, try using DevTools to extract it (or unphar.com) and set the "API:" in plugin.yml to "API: [(currentapi), 2.0.0]" If it still doesn't work, #screwgenisysplugins

**Comment by daniktheboss** [comment]
Close issue?
