### ISSUE TITLE
please do 0.14.0 phar :)

### ISSUE THREAD

**Issue by EmreTr1** [ClearSkyTeam/ClearSky#68]

**Comment by EmreTr1** [comment]
please do 0.14.0 phar

**Comment by EmreTr1** [comment]
clearsky 0.14.0 phar

**Comment by PocketKiller** [comment]
DUPLICATE

**Comment by EmreTr1** [comment]
what?

**Comment by SalmonGER** [comment]
Just make one with DevTools.

**Comment by PocketKiller** [comment]
^^

**Comment by SalmonGER** [comment]
@EmreTr1 If you still need it.
[ClearSky_1.0dev.zip](https://github.com/ClearSkyTeam/ClearSky/files/107252/ClearSky_1.0dev.zip)
