### ISSUE TITLE
Generation

### ISSUE THREAD

**Issue by daniktheboss** [ClearSkyTeam/ClearSky#683]
When using manyworlds and I create a world... there are no ores

**Comment by thebigsmileXD** [comment]
There should be. The master/php7 branch has normal PocketMine ore generation. What is your ip?

**Comment by Aericio** [comment]
He says he gets this on all cores, but I think its just mw problem

**Comment by daniktheboss** [comment]
Ok, if you don't believe ;D ip is landofbarbs.ddns.net 19132 go check it out! Even use xray, no ores...

**Comment by thebigsmileXD** [comment]
Invalid. You use genisys

**Comment by daniktheboss** [comment]
I said, even on genisys any software if does it

**Comment by thebigsmileXD** [comment]
Confirmed by group.
