### ISSUE TITLE
setAmplifier does work... (???)

### ISSUE THREAD

**Issue by Heroata** [ClearSkyTeam/ClearSky#685]
We are increasing or decreasing effect level with setAmplifier. It's ok. But why I cant get level of the effect? 

`$efekt = Effect::getEffect(1);
   echo "Amplifier:".$efekt->getAmplifier()."<=";`

output: ![image](https://cloud.githubusercontent.com/assets/10375421/17983313/9f5db784-6b14-11e6-8913-1d2de2a3d056.png)

**Comment by robske110** [comment]
Did you set an Amplifier before that?

**Comment by Heroata** [comment]
Yes I did. How can I total amplifier?

**Comment by robske110** [comment]
But you just created the particle with no amplifier set... Your code example at least

**Comment by Heroata** [comment]
I set Amplifier on Join (actually on logged in). But used getAmplifier after set.

**Comment by robske110** [comment]
You use this wrong ::get returns a new object with no amplifier set. Save the effect object onJoin

**Comment by thebigsmileXD** [comment]
Incorrect usage of effect.

**Comment by Heroata** [comment]
@thebigsmileXD as I said, I already set an amplifier. I confirmed it from it affects to player's speed in game.

**Comment by robske110** [comment]
Effect::get gets a complete new object.

**Comment by thebigsmileXD** [comment]
And @robske110 got the point

**Comment by thebigsmileXD** [comment]
Actually setAmplifier does nothing

**Comment by robske110** [comment]
Of course it does sth

**Comment by robske110** [comment]
so the client doesn't change the amplifier?

**Comment by robske110** [comment]
Merging into #565
