### ISSUE TITLE
Import Single Player Worlds from Minecraft PE

### ISSUE THREAD

**Issue by jrlambs** [ClearSkyTeam/ClearSky#686]
I have a world I've created on the IOS version of the game that I'd like to run on the server.  I read some places that you may be able to just take your world directory and replace the world director on the server with it.. this didn't work. The server crashes at startup stating 

Uncaught pocketmine\utils\LevelException: Invalid level.dat

I tried changing the default world type in the yml file to leveldb and got the same error.  Is there any way to do this or am I out of luck? do I need to "Convert" the world from the IOS device in any way?  Thanks for the help.  I know this isn't really an "Issue" but I wasn't sure where else to ask.

**Comment by Aericio** [comment]
MCPE: LevelDB
ClearSky: MCR

**Comment by robske110** [comment]
Leveldb can't be read by php7 yet. This is due to a libary missing, theoratically it should throw no Invalid level.dat exception. Would you mind sending the world?

And for you to use your worlds: 
1. Google 'LevelDB to MCR converter'
2. Find a good one
3. Convert your world
4. You're ready to go

**Comment by thebigsmileXD** [comment]
@robske110 i think it can. We are the only core that still has leveldb.php

**Comment by robske110** [comment]
Closing due to missing php7 leveldb. Feel free to discuss this further.

**Comment by jrlambs** [comment]
Thanks everyone!  @robske110, I've attached the world to this.
[world.zip](https://github.com/ClearSkyTeam/ClearSky/files/439193/world.zip)

**Comment by jrlambs** [comment]
Hey, I successfully got my world imported into the server thanks to all your help.  I'm curious if I wanted to pull the world from the server and run it on another server or the desktop version of minecraft what would be required.  I've tried the following with no luck 

1) using a regiondb-> anvil converter. Tells me it can't be converted. 
2) just dropping the world onto the desktop world location. (Doesn't seem to see it at all)
3). Sticking it in the directory for the stock Mojang minecraft server (sees the world as it was when I imported it into clear sky, but none of the changes I made in the clear sky server. 
4) open the file in the old mcedit v1 program... Also seems to only see the original map and none of the edits made in clear sky. 

Any thoughts? 

Appreciate it. Thanks!

**Comment by robske110** [comment]
The problem probably originates from your converter leaving the old files in the world folder., Please send the converted world folder for inspection.

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/18042362/082250fa-6dc1-11e6-90a4-d805b97b1ade.png)
did you see + use this link?

**Comment by thebigsmileXD** [comment]
Oh, that could be, you would have to remove all mcr files. https://www.youtube.com/watch?v=rjGfAzdk8Sw

**Comment by jrlambs** [comment]
Thanks again for all the help.  It looks like it really was "Working" the whole time (kinda).  MCEdit just plain didn't work... I don't know that it can read the region format.  The the converter I was using wouldn't read it at all, don't know what's up.  I looked at pmimporter dev thread and converted things over and it was able to convert to anvil.. which I could start up in Genisys server.. but couldn't find anything I did... I used pmimporter to tell me the old spawn point though and set that as spawn point then reloaded and sure enough I saw my buildings.. but pmimporter had botched it pretty good.   so I tried again just dumping my original world file (in MCRegin Format) into Genisys and set the spawn point.. and yeah, everything works fine.

So here's what I've learned.
1) There doesn't seem to be any tool (that I've found) that can convert MCRegion as created/used by this server to Anvil (or any other format) correctly
2) Genisys server can read MCRegion files.. but ignores the spawn point and just plops you in a random spot... you can set the spawn point back on your own then.
3) MCEdit (v1) doesn't seem to want to read the MCRegion files... haven't tried v2 really at all.


So worlds seem to be portable as long as you can find something that reads mcregion format... but there's no good way to get it to any other format so that other tools can read/use it.

**Comment by Aericio** [comment]
MCEdit won't read MCR files, only MCA.

**Comment by thebigsmileXD** [comment]
@Aericio they fixed some stuff in the latest beta tester builds, it should be able to now

**Comment by Aericio** [comment]
Oh, that's cool.
