### ISSUE TITLE
Synapse

### ISSUE THREAD

**Issue by RoofyManStar** [ClearSkyTeam/ClearSky#688]
Hello. You can add please Synapse for add new server proxy with clearsky? :)

**Comment by thebigsmileXD** [comment]
There are working proxy plugins nowadays. Synapse is slow and buggy.

**Comment by Aericio** [comment]
Synapse is useless, can't you just setup a record to redirect your current server IP (if offline) and just send players to another server?

**Comment by DaMatrix** [comment]
@thebigsmileXD which proxy are you talking about? i can't find anything other than synapse (i.e. Nemisys) and BouncyBall, which hasn't been updated since late 2015.

**Comment by thebigsmileXD** [comment]
I was once talking about dragonproxy, because it "worked" in 0.15
