### ISSUE TITLE
Death cheat (logout glitch)

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ClearSkyTeam/ClearSky#69]
If you die then click main menu while dead and rejoin you will be alive in the spot you died at. Makes it to easy to get your stuff back /: should be a easy fix right?

**Comment by thebigsmileXD** [comment]
@aodzip I have no idea, so i assign you.

**Comment by jojoe77777** [comment]
Same issue in PocketMine.

**Comment by daniktheboss** [comment]
What if when u loose all life (die) u get tp to spawn... not after u press respawn

**Comment by robske110** [comment]
Yea, but that's not minecraft's behavior.

**Comment by thebigsmileXD** [comment]
Yea i see. This is the cause players never spawn where they were
