### ISSUE TITLE
Movement seems to be messed up alot. 

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#696]
Todo: Check in genisys. All movement is "lovely" there.

**Comment by robske110** [comment]
probably only checkmovement, i think you can disable that

**Comment by robske110** [comment]
checkmovement

**Comment by SalmonGER** [comment]
@robske110 Where can I disable checkmovement? Can't find in pocketmine.yml or server.properties

**Comment by robske110** [comment]
Just disable anti cheat

**Comment by SalmonGER** [comment]
@robske110 It never was enabled for me (So it's false). But I still have this bug.

**Comment by robske110** [comment]
This is not even a bug. It's just lag.

**Comment by thebigsmileXD** [comment]
@robske110 movement check is not connected to anti cheat in clearsky.

**Comment by SalmonGER** [comment]
@robske110 Movement is working fine for me now  with Genisys. Is ClearSky now laggier than Genisys?

**Comment by thebigsmileXD** [comment]
*cry* Kind of. Movement isn't forced in genisys, thats why. I asked @dktapps if he may fix it in CS. Nothing so far
