### ISSUE TITLE
Add more gamerules

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#698]

**Comment by robske110** [comment]
do you mean the actual features? I could help with some...

**Comment by thebigsmileXD** [comment]
Actual features ARE already implemented (keepInventory etc.)

**Comment by thebigsmileXD** [comment]
Todo: fix daylightcycle

**Comment by thebigsmileXD** [comment]
Todo: set fire spread to false by default and enable fire ticking.
