### ISSUE TITLE
Plugins with "String/Int/Enum" simply load and bug out the server, causing segfaults

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#701]
i  suggest removing that min api stuff

**Comment by robske110** [comment]
? this is no issue. We do not support these options, but they are options many users use.

**Comment by thebigsmileXD** [comment]
Options disabled, only API changed to 2.0.0 and the plugin will load anyways.

**Comment by robske110** [comment]
?

**Comment by robske110** [comment]
this is not really resolveable, and that are plugins which are not supported. if all options are disabled api 1.x.x plugins do not load, just tested.
