### ISSUE TITLE
Installer fix for android

### ISSUE THREAD

**Issue by SuperAdam47** [ClearSkyTeam/ClearSky#705]
[18:25:41] [Server thread/CRITICAL]: Unable to find the Weakref extension.
[18:25:41] [Server thread/CRITICAL]: Please use the installer provided on the homepage, or recompile PHP again.
[PE Server] Server was stopped.

**Comment by thebigsmileXD** [comment]
Phones should not be used as a serverhost anyways.

**Comment by SuperAdam47** [comment]
Whats recommanded ?

**Comment by dktapps** [comment]
Not a mobile device. (^_^)

**Comment by SuperAdam47** [comment]
:D

**Comment by SuperAdam47** [comment]
then I have no choice but to use genisys

**Comment by thebigsmileXD** [comment]
Well, there was an issue already opened once

**Comment by thebigsmileXD** [comment]
#605
