### ISSUE TITLE
raklib crash

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [ClearSkyTeam/ClearSky#706]
Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Call to undefined method raklib\server\RakLibServer::getTerminationInfo()

**Comment by robske110** [comment]
The error message is not very helpful, due to pthreads not allowing us to get any data out of a crashes thread. Rae you sure you have no other ports?

**Comment by TDMidkwhatisxd** [comment]
I put back genisys and work!
I wanted clearsky becouse genisys now , dont support other auth plugins, ppl can clear inv , etc!
Now i use genisys xboxauth

**Comment by robske110** [comment]
?!
You probably had genisys still running in the background

**Comment by TDMidkwhatisxd** [comment]
Is same server! 
Close it , replace pocketmine.phar , and done 
Btw i tested imagicalmine 0.15.0 , pocketmine-mp too!
Maybe becouse i didnt use phthreads for clearsky!

**Comment by robske110** [comment]
Please wait until i investigate...

**Comment by robske110** [comment]
Can you please try it with the latest build http://robskebueba.no-ip.biz/CSPhar.php again?

**Comment by TDMidkwhatisxd** [comment]
I cant anymore to test:( !
