### ISSUE TITLE
Spawning mobs (not humans) with Slapper causes client crash.

### ISSUE THREAD

**Issue by HimbeersaftLP** [ClearSkyTeam/ClearSky#707]
When I try to do for example `/slapper spawn Pig` the client will crash and can't go in the world until the entity gets removed.

Also this error shows up in console when using the command: ```Warning: assert(): Offset Motion not found failed in phar:///home/minecraft/himbeercraftpe/ClearSky.phar/src/pocketmine/nbt/tag/CompoundTag.php on line 45```

I don't know if this is a plugin issue or ClearSky issue, but it looks like this is a ClearSky issue because nobody reported it on Slapper's github yet (I think).

**Comment by thebigsmileXD** [comment]
Slapper entities are new entities and not related to the core they run on. Will check it anyways.

**Comment by HimbeersaftLP** [comment]
Oh I'm sorry if this is a plugin issue...

**Comment by thebigsmileXD** [comment]
Lol i thought you posed that in the slapper plugin xD

**Comment by HimbeersaftLP** [comment]
Shoukd I close and repost in slapper?

**Comment by thebigsmileXD** [comment]
Not sure yet

**Comment by robske110** [comment]
Closing due to inactivty and most likely plugin related. Feel free to continue to discuss...
