### ISSUE TITLE
Can't join the AsyncAI branch anymore

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#712]

**Comment by robske110** [comment]
not critical external branch and any console errors?

**Comment by thebigsmileXD** [comment]
0 debug information, 0 errors, nothing. worked before the exp mess.

**Comment by robske110** [comment]
Isn't this fixed now?

**Comment by thebigsmileXD** [comment]
no, do you think this MAAAAAAAAAAAAAAGICALLY disappears?

**Comment by robske110** [comment]
I thought rebasing helped

**Comment by thebigsmileXD** [comment]
:tired_face: :hand:

**Comment by thebigsmileXD** [comment]
Sadly no
