### ISSUE TITLE
latest phar

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [ClearSkyTeam/ClearSky#716]
Website down :D ! I wanna the latest .phar

**Comment by thebigsmileXD** [comment]
http://wolvesfortress.de/phar/CSPhar/CSphar.php

**Comment by TDMidkwhatisxd** [comment]
Thanks , and another question! Is xbox login working?

**Comment by thebigsmileXD** [comment]
@robske110 does it? i don't think so. You would need a plugin anyways

**Comment by TDMidkwhatisxd** [comment]
:(  , oh my , someone told me u got xbox login!! Oh , nvm >.<

**Comment by thebigsmileXD** [comment]
Well, we have the variables. Login is still a plugin part

**Comment by TDMidkwhatisxd** [comment]
Oh so u got them xd!!
I will make if is xbox login false = kick !!

I will check the Api!

And i wont need openssl?

**Comment by robske110** [comment]
you will need openssl, and the branch is about to work...

**Comment by TDMidkwhatisxd** [comment]
So! Your php bin , will get openssl or already have!

**Comment by robske110** [comment]
the original php bins from pocketmine on bintray do have openssl...
http://robskebueba.no-ip.biz/CSdirectPhar.php?branch=php7 should be what you want...

**Comment by TDMidkwhatisxd** [comment]
Nope ! Does not have ;-; ! Can you tell me what version got it? I even look in extensions or include , cant find it! And if i use genisys it say no openssl!

**Comment by TDMidkwhatisxd** [comment]
Just checked ! It say i dont have glibc files , but i got them :(  ! I give up! 
I will find a other way!
