### ISSUE TITLE
something weird

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [ClearSkyTeam/ClearSky#719]
Hi! I just downloaded php bin from pocketmine , and now i used clearsky!
All is repeating! I mean!
1. Simpleauth:
I logged in , and it always appear this, 
Player joined the game , please login , logged in,
This is always repeating itself! 
And cant move!
2. Removed any login plugin, 
I logged in , and it always appear , Player joined the game at some intervals!
And i cant move , ifi do i get tped to the place i was or random places!

I checked my disk performance , 412mb/s read/write speed!
Network , i downloaded a file with 15mb/sec , so is enough to hold 1 player xdxdxd!

/status
20 (0.1%) tps

What is wrong? I have a headache xd!

I tryed almost all php binaries from pocketmine xd ! 

I really think is php fault! :(

**Comment by TDMidkwhatisxd** [comment]
Forgot to mention , i can build ,no lag , but i get tped back to spawn or random place! So i dont think is from internet!
Is like everything is repeating every 2 seconds!

**Comment by HimbeersaftLP** [comment]
Strange, SimpleAuth plugin works for me fine, also I have no problems about being tped back. Do you have AntiCheat on, and you have halfslabs in where you walked"

**Comment by robske110** [comment]
Try to remove all plugins temporaily, i do not think that this is related to the core, feel free to continue discussion...

**Comment by TDMidkwhatisxd** [comment]
Was a clean install xd ! All are default! And simpleauth was just for test!
No plugins at all xd!

**Comment by TDMidkwhatisxd** [comment]
I will try to change my OS!

**Comment by Aericio** [comment]
Why would OS change anything...?

**Comment by TDMidkwhatisxd** [comment]
If it got outdated libs, is bad! Xd !

**Comment by Aericio** [comment]
Manually update libs lol. Linux right?

**Comment by TDMidkwhatisxd** [comment]
Ik! But why i would wanna a OS , were  apt-get update , or yum update dont even work!
I use fedora 22 now , works like a charm :). !

**Comment by Aericio** [comment]
Oh, I see.
