### ISSUE TITLE
Idea in 2.1dev(php7)

### ISSUE THREAD

**Issue by aodzip** [ClearSkyTeam/ClearSky#72]

**Comment by aodzip** [comment]
Hunger , Experience ,  Redstone switch won't set in pocketmine.yml . Use plugin to disable them

**Comment by aodzip** [comment]
Use some cache system for hot data storage

**Comment by thebigsmileXD** [comment]
Naaah :) well.. Okay, we have events for weather and hunger. But redstone is a bit too heavy

**Comment by aodzip** [comment]
Not just enable and disable . The event also contain these rainfalls argv too.
It won't heavy.. just a replace

**Comment by aodzip** [comment]
There is an issue when server stop . Seems freeze
