### ISSUE TITLE
Picking up EXP wayyy too slow.

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#721]
TODO: search forge for cooldown time

**Comment by thebigsmileXD** [comment]
2 ticks.

**Comment by thebigsmileXD** [comment]
Fixed.

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/18505906/b9a50160-7a69-11e6-8e6f-49584cc0e862.png)
Thats interesting, will test

**Comment by Aericio** [comment]
this is not finished?

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/19626202/704d0cb0-992c-11e6-8ed6-d8c2e828b744.png)
Read my friend, read.

**Comment by Aericio** [comment]
but why is it not closed?

**Comment by thebigsmileXD** [comment]
Read, my friend.
