### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#723]
![image](https://cloud.githubusercontent.com/assets/16523741/18619812/6be93e6a-7da1-11e6-87d3-ce4481da1567.png)

**Comment by robske110** [comment]
weird exception up there (line 38 is nothing, just a TAB)

**Comment by robske110** [comment]
can you confirm this on the latest build?

**Comment by Aericio** [comment]
Latest.

**Comment by kam187** [comment]
You should extract the phar and check the file.

There's plenty of online phar extractors.  It's possible that file had a typo in some commit or something and it's not totally latest.

**Comment by robske110** [comment]
Closing due to unable to reproduce, aerico try to redownload the phar

**Comment by Aericio** [comment]
Site down

**Comment by robske110** [comment]
MacOSX (fuck you apple) booted in safe mode after it crashed yesterday. That's what i call a fail.

**Comment by thebigsmileXD** [comment]
He uses Apple, thats the error 😆

**Comment by robske110** [comment]
:D
