### ISSUE TITLE
HURRY!

### ISSUE THREAD

**Issue by remotevase** [ClearSkyTeam/ClearSky#725]
Minecraft 0.16 is supposed to be released during or right after Minecon 2016. Minecon is on the 23rd and 24th! We only have a few days to finish updating clearSky to 0.16! Hurry! The only places that have almost updated to 0.16 is ImagicalMine (inactive-to-reactive/imagicalmine) AND Steadfast2 (Hydreon/Steadfast2)

**Comment by ScandiePlay** [comment]
Link for official news about it, please.

**Comment by ScandiePlay** [comment]
And tell, how should the team of ClearSky update to 0.16? They don't know about the official changes in protocols + simple changing of protocol's number and changing the version in PocketMine.php won't work (my opinion).

**Comment by HimbeersaftLP** [comment]
Oh hi remote_vase, you are here, too! XD

**Comment by robske110** [comment]
We're alrady working on this in corporation with iTX :)

**Comment by thebigsmileXD** [comment]
Incorrect, we don't. We collaborate with @dktapps

**Comment by dktapps** [comment]
The only reason you want CS to update is so you can copy-paste from it. Go away.

**Comment by dktapps** [comment]
Also, you didn't even get the dates right.

**Comment by Aericio** [comment]
` We only have a few days to finish updating clearSky to 0.16! `
"We" as in your going to make a pull request to add it or as in "i just made this commit to brag"

**Comment by daniktheboss** [comment]
"We" I think he means by cs and im... bbuuutt I don't remember them two being partners

**Comment by dktapps** [comment]
"We" as in "We don't have a clue what we're doing, pls do it for us so we can copy you"
