### ISSUE TITLE
0.15.9 Version doesn't work

### ISSUE THREAD

**Issue by Akuroma** [ClearSkyTeam/ClearSky#730]
Now there is another problem. Players can't join my server. The got stuck in the loading screen and then get kicked.

**Comment by caspervanneck** [comment]
server freeze i tink -_-

**Comment by Akuroma** [comment]
I think I've got a solution. I've updated SimpleAuth now it works, I think ;)

**Comment by Akuroma** [comment]
But now theres a other problem. Worlds are shown in the player list, when you use ESCAPE or something like that

**Comment by robske110** [comment]
Cannot reproduce, plugin problem.
