### ISSUE TITLE
Renaming / placement of .phar file

### ISSUE THREAD

**Issue by MystiCrafter** [ClearSkyTeam/ClearSky#731]
Hello! i am new to clearsky, but not minecraft pe and servers. I dont know what folder the .phar file goes into or what its name should be. It would be awesome if someone replied with the info! p.s. this is last resort i couldnt find it online.
**Many Thanks!**

**Comment by robske110** [comment]
It's pretty much like PM. Try to name it ClearSky.phar or PocketMine-MP.phar. Please note that this is not the support channel, for further support use our telegram group.

**Comment by Aericio** [comment]
Maybe an IRC would be good, some people dont have phones.

**Comment by robske110** [comment]
Hmm...

**Comment by HimbeersaftLP** [comment]
> some people dont have phones.

How would you play MCPE without a phone? :P

**Comment by Aericio** [comment]
Phone number...

**Comment by thebigsmileXD** [comment]
@HimbeersaftLP Windows 10.

**Comment by HimbeersaftLP** [comment]
Oh yes forgot about that, and there are also tablets...
