### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by Akuroma** [ClearSkyTeam/ClearSky#732]
Everyone is timeouting when they join my server. Please could you fix this?

**Comment by Aericio** [comment]
That isn't clearsky's fault. Internet issue.

**Comment by Akuroma** [comment]
no it isn't. as i had the old version of clearsky everything went fine. but now players can't join. mcpe  is lagging and then crashing and the console says that the player timeouted.

**Comment by HimbeersaftLP** [comment]
Everything works fine for me...

**Comment by thebigsmileXD** [comment]
Check if your pocketmine.yml maybe changed.

**Comment by Akuroma** [comment]
The problem is the pocketmine.yml You can't use plugins anymore, which has a to old API-Version. In recent versions this wasnt the case. You were able to use older plugins...

**Comment by HimbeersaftLP** [comment]
You are still able to use older plugins when changing the setting in pocketmine.yml...

**Comment by thebigsmileXD** [comment]
-.- you can.

**Comment by Akuroma** [comment]
No. I activated this option and everyone who joins the server is going to timeout. When i deactivate the option evrything works fine

**Comment by HimbeersaftLP** [comment]
Then it's a plugin's issue...

**Comment by Akuroma** [comment]
You're sure? Should i give you my plugin list?

**Comment by HimbeersaftLP** [comment]
You can, but I'm not sure if I can help tough...

**Comment by Akuroma** [comment]
well i have a lot of plugins

**Comment by Akuroma** [comment]
HimbeersaftLP du bist Deutscher richtig? Dann muss ich hier nicht zwanghaft Englisch schreiben ^^ Also pass auf. Nochmal so erklärt. Der Server fährt mit der Option, dass man ältere Plugins verwenden kann, ganz normal hoch und bleibt auch on, also stürzt nicht ab. Wenn jetzt ein Spieler joinen will, lädt es ersteinmal ein Stückchen, wie normal und er joint im Spiel in den Anmeldebildschirm. Aber genau in dem Moment freezt das Spiel und stürzt ab. Und in der Console, steht dass derjenige getimeoutet ist.

**Comment by thebigsmileXD** [comment]
Wie gesagt, plugin problem.

**Comment by thebigsmileXD** [comment]
Kann es sein dass du customalerts hast

**Comment by SalmonGER** [comment]
@Akuroma Please join our ClearSky Communicate group on Telegram for top quality ClearSkyTechSupport.
https://telegram.me/joinchat/AlErxD3AN_GOgeSAcS0twA
(Also in German if you wish!)

**Comment by Aericio** [comment]
sounds like those fishy advertisements... hmm...

**Comment by Akuroma** [comment]
Nee habe kein CustomAlerst :/

**Comment by Aericio** [comment]
Need  it for what reason? Remove join messages? Custom motd?

**Comment by SalmonGER** [comment]
@Aericol uhm he aaid he does not have CostumAlerts

**Comment by Aericio** [comment]
costumealerts?? nice plugin
