### ISSUE TITLE
Please fix inventory

### ISSUE THREAD

**Issue by majovec** [ClearSkyTeam/ClearSky#733]
please fix inventory 

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in phar:///root/PM                                                                             1/PocketMine-MP.phar/src/pocketmine/inventory/PlayerInventory.php on line 90

**Comment by thebigsmileXD** [comment]
Thats actually not a bug. Some plugin that you use (maybe a save inventory plugin) try changing it, its deprecated and no longer used since win10 fixes

**Comment by majovec** [comment]
This is aktuali plugin this is bug on bedwars shop only 0.15.x not work and 0.14.x it work

**Comment by thebigsmileXD** [comment]
I'll check back later

**Comment by robske110** [comment]
Plugin issue
