### ISSUE TITLE
 Doesn't locate server

### ISSUE THREAD

**Issue by wolffyx** [ClearSkyTeam/ClearSky#734]
After I start the server and add the ip's(all 3 external ,internale and and the local one)in MCPE 0.15.6  the server isn't locating (like this [http://media-minecraftforum.cursecdn.com/attachments/207/187/636015260814054527.png](url) ) and the server looks like this
![image](https://cloud.githubusercontent.com/assets/14310774/18815446/44cf19be-833a-11e6-8e20-98e42a149e41.png)
When I try to connect(it sows unable to connect to world) nothing changes on console.
Please help

**Comment by HimbeersaftLP** [comment]
Maybe you firewall blocks it?

**Comment by wolffyx** [comment]
No it not block it

**Comment by wolffyx** [comment]
Can be something from php?

**Comment by thebigsmileXD** [comment]
You mean that it shows 0.0.0.0? Actually correct, "local" IP

**Comment by wolffyx** [comment]
192.168.0.x(depepends on pc)

**Comment by thebigsmileXD** [comment]
Hosting on what os? if Windows, read some old issues. @robske110 knows how to fix the firewall stuff

**Comment by wolffyx** [comment]
Windows

**Comment by robske110** [comment]
Enter this cmd in powershell
CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"

**Comment by Aericio** [comment]
Same for me, worked totally fine in 0.14.0

**Comment by wolffyx** [comment]
This is the return:
![image](https://cloud.githubusercontent.com/assets/14310774/18834279/b9217186-83fd-11e6-8720-e10f0cb0f4a5.png)

**Comment by robske110** [comment]
yea, now try to connect.

**Comment by SalmonGER** [comment]
@robske110 You fixed the lan server of my singleplayer worlds <33

**Comment by wolffyx** [comment]
Nothing
![screenshot_2016-09-26-15-41-45](https://cloud.githubusercontent.com/assets/14310774/18834778/74d0c9f2-8400-11e6-825f-5e33cbee1e9c.png)

**Comment by robske110** [comment]
setup problem, check forwarding, firewalls, etc..

**Comment by thebigsmileXD** [comment]
Do you use localhost as ip in MCwin10? if so change that xD

**Comment by wolffyx** [comment]
I use xampp as localhost but is turned off

**Comment by wolffyx** [comment]
I port forwarding my ip, disable my firewall to be sure is not blocking it an nothing doesn't work, what can I do? 
Can I host the server with xampp (if is possible)?

**Comment by wolffyx** [comment]
I think I found the problem, I think is from my router, I will try on an other router in few days and I will find if was from there.
