### ISSUE TITLE
Can't get phar (server issues)

### ISSUE THREAD

**Issue by c-hri-s** [ClearSkyTeam/ClearSky#735]
Hi,

http://robskebueba.no-ip.biz/ seems to be down

http://wolvesfortress.de/phar/CSPhar/CSphar.php seems to lead to a server error when you follow the php7 download link

Is there somewhere else to get it?

**Comment by Aericio** [comment]
Robske's site is homehosted... you could download his website files for csphar once its up again and host it yourself.

**Comment by SalmonGER** [comment]
Newest phar provided by CircleCI (You should go there if those pages up there are down, since both of them use the API of CircleCI)

https://376-49435874-gh.circle-artifacts.com/0//tmp/circle-artifacts.T5PBTiz/DevTools/ClearSky_1.1-php7.phar

**Comment by robske110** [comment]
Sorry for the outage. CSdirectPhar is on github, .you could host it yourself

**Comment by c-hri-s** [comment]
Could you add the code for CSdirectPhar.php please?
I don't see it in https://github.com/ClearSkyTeam/CSphar

**Comment by Aericio** [comment]
https://github.com/robske110/CSphar

**Comment by c-hri-s** [comment]
Got it - thanks.

**Comment by thebigsmileXD** [comment]
My site is currently reworked, don't wonder if it doesn't work.

**Comment by c-hri-s** [comment]
I've hacked together the following that works for me. It's **very** nasty, though.

If anyone is better at bash scripting, regex and string manipulations than me, please help with a more robust update script:

`#!/bin/bash

wrkdir="/home/abc/pocketmine"

rm $wrkdir/ClearSky_1.1-php7.phar

BUILD=$(curl -s https://circleci.com/api/v1/project/ClearSkyTeam/ClearSky |gre
p -m1 build_url |tail -c +64|head -c -3)

DLURL=$(curl -s https://circleci.com/api/v1/project/ClearSkyTeam/ClearSky/$BUI
LD/artifacts |grep -m1 url|tail -c +12|head -c -2)

wget $DLURL -q > $wrkdir/output.log`
