### ISSUE TITLE
on player drop item event

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [ClearSkyTeam/ClearSky#738]
Please read all before baning me!

Hi! I know what are you talking about! 
But no more work if you open inventory!
Please test for yourself !
If you drop item it is gone forever!

I tested it on other servers too , i was clearing players inventory and they rage!
Please just test it! Auth plugins are broken becouse of this, i added auto ban to keep trollers away!

I dont care if im banned , i wanted just to tell you that "You are wrong" , test it please , and if u right ban me!

How to reproduce?
1. Join a server!
2. Dont login!
3. Drop items
4. Check if u can get them back!

**Comment by HimbeersaftLP** [comment]
1. I'm not sure if you will get banned, but I wouldn't recommend you to create a new issue...

2. Are you sure that the server you joined is running ClearSky?

**Comment by TDMidkwhatisxd** [comment]
Was runing Clearsky ! But now i swiched back! Becouse i implemented auto ban , if someone drop items and is not logged in!

And really , items vanish forever! In past i just needed to open inventory , but now , it vanish for good!
Checked with and without plugins!

**Comment by thebigsmileXD** [comment]
> Becouse i implemented auto ban , if someone drop items and is not logged in!

Why the * should you ban someone for dropping an item.. it could be accident

> Checked with and without plugins!

Without can't be. Reason: no login.

It IS and STAYS a plugin fault. I bet you cancel incorrectly.
I recomment:
- stop coding
- learn php
- understand PM/forks/spoons code
- learning english
- ask someone, but NOT US for help with the plugin.
- Its not a reason to get you banned here.

**Comment by TDMidkwhatisxd** [comment]
Wtf ! I told u ! Tested without plugins! Only simpleauth or serverauth ! And event is canceld but items vanish! Wow! I even entered on cuboss server and cleared players items! 

Is not a plugin fault it only happens on latest version!

**Comment by Aericio** [comment]
Auth plugins do work. Dropping items don't get deleted. Check if you are using the actual ClearSky (not modified) and normal bins.

**Comment by TDMidkwhatisxd** [comment]
Give me your sv ip! Imma show u! Even on popular servers i cleared players inventory!

**Comment by HimbeersaftLP** [comment]
Are you sure that the items are really wasted? Try to rejoin the server.

Also don't be so rude, the ClearSky team (and also every other person reading this issue, including me) are only humans... :/

**Comment by Aericio** [comment]
aericio.ddns.net:19132

**Comment by TDMidkwhatisxd** [comment]
Ok! Im just stunned that nobody noticed the bug , only me and few ppl, + im not noob!
I did all i could to be sure im not wrong! Give me your ip , a name , and i clear his items without fail ;)

**Comment by TDMidkwhatisxd** [comment]
Ok , a name? Or i will find in topmoney

**Comment by Aericio** [comment]
???

**Comment by TDMidkwhatisxd** [comment]
Is ok!! Imma clear a random name items!

**Comment by TDMidkwhatisxd** [comment]
Is your sv open? I did aericio.ddns.net  19132

**Comment by Aericio** [comment]
Doesn't seem to work, even though I port forwarded. Make a video or something.

**Comment by TDMidkwhatisxd** [comment]
I can make video with my windows10 ! (no root)
Hope is legit , is still mcpe server!

One moment

**Comment by TDMidkwhatisxd** [comment]
https://m.youtube.com/watch?v=tDdaZciJEbY

And u will see , i put auto ban to stop this! And works on all servers! You should try it! Is funny to troll!

**Comment by HimbeersaftLP** [comment]
Does it IP ban or name ban?

**Comment by TDMidkwhatisxd** [comment]
Ip+cid

**Comment by Aericio** [comment]
Delete autoban and try it...

**Comment by TDMidkwhatisxd** [comment]
1. I told u all again and again ! ServerAuth , SimpleAuth , any login plugin is the same!
2. AutoBan is to avoid having trollers drop players items, and ban them!(i will add something better in future)
3. Other servers have no protection , and i clear players inventory for fun!
4. Please test before commenting here + use google translate if u dont understand!
5. ClearSky team please do just a test ,on new version! It wont kill you!
6. The thing is , no matter what protection i do ! Items still gone even if i ban them , so i need this bug to be fixed!
7.This glich was from windows10 update, i noticed it wen players complain that some stuff was missing!
8. Tested on top factions servers, i cleared many players inventory , and i still see no comment!
9. Dont post here unless u are ClearSky team or u own a Survival/Faction server!

I wont dellete autoban! Why to not punish trollers? In fact i plan to do something more than just banning!

Not logged in? Drop=Ban , best solution for now!

**Comment by Aericio** [comment]
@thebigsmileXD Please lock issue already -_-

**Comment by TDMidkwhatisxd** [comment]
U are not a server owner so please shut up!

**Comment by Aericio** [comment]
gmplus.ddns.net What again?

**Comment by TDMidkwhatisxd** [comment]
Ok! So give me your name to clear inventory ! Be sure to have stuff in inventory! So this will be the best proof!

**Comment by Aericio** [comment]
That is not an issue with my server - Inventories are cleared on logout / world change.

**Comment by TDMidkwhatisxd** [comment]
So , you dont care! And you just try to stop me ! Im right?

**Comment by Aericio** [comment]
Yes, you're items do get removed when you drop them. I'm trying to say, how is this related to ClearSky at all?

**Comment by TDMidkwhatisxd** [comment]
Becouse canceling drop items , dont work so well! Items dont drop , but they are gone!
Understand?

**Comment by HimbeersaftLP** [comment]
It's possibly only a issue for Win10 edition, can u try in MCPE and test if it's the same?

**Comment by TDMidkwhatisxd** [comment]
I use my android tablet for playing! Windows 10 i used for video!
Why you guys dont test? 
I cant prove with my tablet becouse i dont wanna to root it!

**Comment by HimbeersaftLP** [comment]
I can't test because my server, clears inventory automatically on join and quit...

**Comment by thebigsmileXD** [comment]
Closed and locked due to invalid, checked on several devices, several plugins, vanilla and by several users. Talk more invalid content because of lack of knowledge and accepting facts like a tree, and you'll get blocked.
