### ISSUE TITLE
Does the tps lie? -_-

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ClearSkyTeam/ClearSky#74]
So this does seem much faster than pm...but when you do /status it shows a much lower tps than whats on the console...

This is also a bug report lol shows this in the /status also..another message that is bugged is xp the command works but it shows xp.command.message or something along those lines when you use it.

 Uptime: 11 %pocketmine.command.status.minutes 13 seconds

**Comment by XxDXM-hippiexX** [comment]
I think something that would improve lag a lot (witch i have done) is to find a alternative to $this->forcemovement in the player.php people confuse that for lag and that is what annoys players the most.

**Comment by aodzip** [comment]
Do you use phar or src code from git?
the TPS isn't lie , but we show average tps on the console banner instead of the instantaneous tps which is use in official PM.

If you find your player seems lag and be teleported everywhere please check the latest code , there is a fix in raklib that prevent packet lost.

**Comment by nonbe102** [comment]
Uhhmm? Can we atleast request for .phar of the latest code?

**Comment by aodzip** [comment]
New release come out

**Comment by meetloaf13** [comment]
thanks for the update!

i didnt want to start a new issue since the following isnt an issue.  i moticed you uploaded some php files.  

what is the benefit of loading them and how would i go about doing it?
thanks!

**Comment by aodzip** [comment]
you mean this 
https://github.com/ClearSkyTeam/PHPbinary
They are just for windows

**Comment by meetloaf13** [comment]
yes, i switched my server to a windows machine a couple weeks ago, when I overwrote the old files eith the new files i get an error, "couldnt find valid pm installation"

supposing i need to change something in my php.ini?

**Comment by aodzip** [comment]
If you are using php5 version . I suggest you don't update .

**Comment by meetloaf13** [comment]
ok, yeah i just tried comparing the php.ini files and the only thing missing really in the new one is
include_path = ".;.\ext"
but even adding that didnt help.

what are thr bemfits of runnin PHP7?  drawbacks? My machine is a beast i7 2600K 16 GB ram.  any settings i can change or server updates i can implement to increase features on the server and optimize performance, im all for.

thanks for your help

**Comment by meetloaf13** [comment]
crap, i moved the original php folder back and im getting the same error.  any help?

**Comment by SalmonGER** [comment]
@meetloaf13 Couldn't find a valid pm installation?

**Comment by meetloaf13** [comment]
exactly.  files are the same, did i beef some sort of signature verification?

**Comment by SalmonGER** [comment]
@meetloaf13 I only get this error when i don't have a PocketMine-MP.phar or similiar. Check your .phar or src folder.

**Comment by meetloaf13** [comment]
lol, bingo, i feel like a numbnut after that one   somehow i deleted the .phar on accident.  

i am remoting in with my tablet, server is 10000 miles away =)

thanks!

**Comment by SalmonGER** [comment]
@meetloaf13 Np.

**Comment by XxDXM-hippiexX** [comment]
I am running from a src file :p didnt know that would do that lol
