### ISSUE TITLE
Fire items drops when using water

### ISSUE THREAD

**Issue by HimbeersaftLP** [ClearSkyTeam/ClearSky#740]
When I ignite fire (e.g. With a flint and steel) and then place water near it to put it out, the fire will drop the item, but it shouldn't do...

**Comment by Aericio** [comment]
Fire drops the item? The fire block drops?

**Comment by HimbeersaftLP** [comment]
Yes, it drops the fire, strange, right?

**Comment by thebigsmileXD** [comment]
Yea since @robske_110 liquid rewrite

**Comment by robske110** [comment]
*cry* why does always sth have to break

**Comment by HimbeersaftLP** [comment]
Maybe he thought fire is a flower :P

**Comment by thebigsmileXD** [comment]
HimbeersaftLP maybe. But its Minecraft-Pocket-Edition, not Mario xD

**Comment by HimbeersaftLP** [comment]
Well, both start with M :P

**Comment by AliMAltamimi** [comment]
hi 
can anyone tell me how to install?
i get this 
"Couldn't find a valid ClearSky installation"
Press any key to continue . . .

**Comment by robske110** [comment]
Please rename your phar to ClearSky.phar
