### ISSUE TITLE
Online-mode & $player->isAuthenticated() no longer works.

### ISSUE THREAD

**Issue by MCPEPIG** [ClearSkyTeam/ClearSky#745]
Online-mode also blocks xbox live players & $player->isAuthenticated() returns false for both xbox live & non xbox live players. I'm on 0.15.9 (not 0.15.90)

**Comment by SalmonGER** [comment]
Do you have the openssl extension installed in your binaries?

**Comment by robske110** [comment]
Should throw a warning if not

**Comment by MCPEPIG** [comment]
Yeah, I have the openssl extension

**Comment by MCPEPIG** [comment]
Nvm I fixed it.

**Comment by robske110** [comment]
How did you fix it?

**Comment by MCPEPIG** [comment]
Apparently openssl wasn't on...

**Comment by MCPEPIG** [comment]
One of the files weren't in  the ClearSky & Pocketmine bin

**Comment by thebigsmileXD** [comment]
oh dan it xD
