### ISSUE TITLE
CompoundTag bug

### ISSUE THREAD

**Issue by LazzKiller** [ClearSkyTeam/ClearSky#746]
Hi, fix this bug with nbt, the console is flooding this:

04.10 21:19:24 [Server] INFO Warning: assert(): Offset LightPopulated not found failed in phar:///ClearSky.phar/src/pocketmine/nbt/tag/CompoundTag.php on line 45

**Comment by Aericio** [comment]
Modified version?

**Comment by thebigsmileXD** [comment]
This looks like a really old bug that was fixed ages ago

**Comment by LazzKiller** [comment]
Sorry inactivity, i using Anvil map (PC)

**Comment by Aericio** [comment]
Did you convert it into a MCPE world?
