### ISSUE TITLE
/gamerule in /help

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#748]
![image](https://cloud.githubusercontent.com/assets/16523741/19210515/12c9c3a2-8cc1-11e6-8d1a-faface30b62d.png)
%pocketmine.command.gamerule.description is *such* a helpful description, the detail is insane! Well, its *too* much detail for some of us.

**Comment by robske110** [comment]
What language have you selected?
Because, PocketMine's translatoris unable to fall back.

**Comment by Aericio** [comment]
English obviously...

**Comment by thebigsmileXD** [comment]
Who the fuck has set it to %pocketmine, it should be %command for client side translation

**Comment by Aericio** [comment]
Ever going to get fixed?

**Comment by robske110** [comment]
Fixed it locally already, discovered some other translation issues, will commit today

**Comment by thebigsmileXD** [comment]
How about using client translations?

**Comment by thebigsmileXD** [comment]
#758
