### ISSUE TITLE
Grass generates underwater

### ISSUE THREAD

**Issue by stayandwait** [ClearSkyTeam/ClearSky#751]
When you create a new world and you go to a large lake, there will be grass at the button. Grass used to generate underwater in the older versions of MCPE but no longer does.  The world was just generated today with your newest phar release build #403.

* This issue was reported in the past and then closed. I have no idea why? It's still a bug. Nukkit doesn't even have this issue anymore as I had also reported this issue to them in the past and they fixed it a long time ago.

![2016-10-08_1837](https://cloud.githubusercontent.com/assets/15825041/19216361/81ffbb76-8d86-11e6-82dc-76b2bcad1183.png)

**Comment by thebigsmileXD** [comment]
Duplicates: https://github.com/ClearSkyTeam/ClearSky/issues/455

**Comment by thebigsmileXD** [comment]
You see the issue in the last issue message: fixed in generator branch

**Comment by stayandwait** [comment]
@thebigsmileXD You should reopen it. Grass still generates underwater.

**Comment by stayandwait** [comment]
@thebigsmileXD It's not fixed.

**Comment by thebigsmileXD** [comment]
It is fixed. Just not merged to the php7 branch. I could update the php7 branch and then you can use it.
