### ISSUE TITLE
Freezes caused by light calculations (cache overflow?)

### ISSUE THREAD

**Issue by starterdragon** [ClearSkyTeam/ClearSky#756]
Our Server just froze without any error and log on console

Main Memory usage was 109mb/203mb (which is up to 2gb)
TPS: 20
Load: 0% - 7% (max)

no Crashdump to be provided....

**Comment by starterdragon** [comment]
just now, it happened again, have to revert version.. lol 
![image](https://cloud.githubusercontent.com/assets/16812043/19519768/829b1346-9637-11e6-949e-5d7518e32551.png)

**Comment by Aericio** [comment]
There are memory leaks currently, which also means freezes. Reducing plugins or increasing ram won't change much, you'll just need to use another core for now until these memory leaks are fixed.

**Comment by robske110** [comment]
1. You are using windows: This could be the command reader... and the php bins on windows seem to have problems, @XenialDan also has some freezes.
2. @Aericio I literally never had freezes on MacOSX. 
3. Freezes can also be created by plugins [pretty easy: while(true){}]

**Comment by robske110** [comment]
Wait, you at first wrote 'it froze, wow' and the sever still responded... what made you think it forze?

**Comment by Aericio** [comment]
@robske110 linux and windows. LINUX AND WINDOWS.

**Comment by thebigsmileXD** [comment]
@Aericio its only windows

**Comment by caspervanneck** [comment]
its windows not linux i try it

**Comment by starterdragon** [comment]
@robske110 when I said "it froze, wow" which is on the picture, I already restarted the server and I'm informing a player which is CoolGaming, then without any notice when I tried to check who is who's the other 2 online, I realised that the server frozed "again"..

**Comment by caspervanneck** [comment]
@starterdragon my server froze to i have now genisys but if clearsky fix it i update my server to clearsky

**Comment by thebigsmileXD** [comment]
oh plz set memorylimit so we see the overload line
750M is ok

**Comment by Aericio** [comment]
@thebigsmileXD oh... i got freezes on linux and windows though :/

**Comment by thebigsmileXD** [comment]
@kam187 any ideas?

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/19595104/9ae57174-9788-11e6-9675-46116d17e382.png)
Set this and in chunk ticking or sth disable light updates.

Seems to work so far

**Comment by kam187** [comment]
Will check this now.

**Comment by kam187** [comment]
Please test with the latest commit 2b9d3cda1c273f314f480a6828849c27822483ee and turn on debug to monitor the cache level.

**Comment by robske110** [comment]
Response?

**Comment by caspervanneck** [comment]
@robske110  do this work steal?

**Comment by thebigsmileXD** [comment]
Didn't do anything @kam187

**Comment by robske110** [comment]
Important: is once cpu core maxed out if this happens?
