### ISSUE TITLE
Beacon beam client side, on chunk reload gone

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#768]

**Comment by HimbeersaftLP** [comment]
I wonder how the beacon beam works, is it sent by the server, or does the client detect a beacon and then display the beam?

Sorry if that counts as spam

**Comment by thebigsmileXD** [comment]
Pretty sure the clien should check but doesn't xD

**Comment by thebigsmileXD** [comment]
Added Beacon tile
