### ISSUE TITLE
Sound IDs

### ISSUE THREAD

**Issue by thebigsmileXD** [ClearSkyTeam/ClearSky#774]
~~Particles: cause client crashes.~~
Sounds: Wrong id's

**Comment by thebigsmileXD** [comment]
Temporarly disabled particles and sounds

**Comment by thebigsmileXD** [comment]
Sounds: new json way, GenericSound::getSound(string $name);

**Comment by thebigsmileXD** [comment]
Sound: need correct compression

**Comment by robske110** [comment]
Particles: fixed

**Comment by thebigsmileXD** [comment]
Noteblocks: id 64
Step/walking sounds: 2 & 3

**Comment by thebigsmileXD** [comment]
All fixed
