### ISSUE TITLE
What is the code needed for linux because I get an error

### ISSUE THREAD

**Issue by GoldCodes** [ClearSkyTeam/ClearSky#780]
[CRITICAL] Unable to find the pthreads extension.                                                                                                          
[CRITICAL] Please use the installer provided on the homepage.

**Comment by robske110** [comment]
You use the wrong php library. Do not use system php.

**Comment by GoldCodes** [comment]
@robske110 What php should I use? At least leave It open?
You should add a guide on how to install on linux..

**Comment by robske110** [comment]
STOP OPENING ISSUES

**Comment by robske110** [comment]
everything is in the fucking read

**Comment by robske110** [comment]
http://robskebueba.no-ip.biz/CSPhar.php : Download phar
https://raw.githubusercontent.com/ClearSkyTeam/ClearSky/master/start.sh : Download start script
https://github.com/SalmonGER/PocketMine-MP-Binaries : php bins

**Comment by thebigsmileXD** [comment]
Read.
