### ISSUE TITLE
Essentials not supported -> Players can't join on my server

### ISSUE THREAD

**Issue by Akuroma** [ClearSkyTeam/ClearSky#782]
Hey there. I think there many problems now with ClearSky  ;)
As i said in the title, there are problems with some plugins for example Essentials. The plugin starts and loads up as normally. But when a player want's to join, They get kicked and the console says "timeout". But it isn't like that. Also the short sentence "Particles disabled" pops up in the console, everytime a player moves. It's a little bit annoying. 

@thebigsmileXD Ich denke an dich kann ich mich ja in Deutsch wenden ;) Also. Wenn ich das Plugin Essentials verwende, startet es ganz normal und der Server crasht auch nicht. Wenn aber ein Spieler joinen will, wird er gekickt und in der Console erscheint "timeout". Aber das kann echt nicht an der Verbindung liegen. Auch Plugins wie FNPC schlagen fehl..
Mein Server wird durch HK-Hosting gehostet. ICh weiß ja nicht, wie die das handhaben, mit den neuen Versionen aufspielen.
Aber danke erstmal für's Lesen ;) Bitte versucht die Fehler irgendwie auszubügeln ;)

LG Aku

**Comment by Sandertv** [comment]
Yep I discussed this with them too, I think @thebigsmileXD is still testing it sometime soon.

**Comment by thebigsmileXD** [comment]
Do you have walking particles? Particles are currentl removed, @robske110 any update?

Hey Aku, kannst du heute TS?

**Comment by Akuroma** [comment]
@thebigsmileXD Jo. Kannst wenn möglich auf restinpizza.de kommen. Stups mich dann an ich move dich

**Comment by robske110** [comment]
> @robske110 any update?

I do not intend to break rule one by you: don't work with dktapps or pmmp

**Comment by thebigsmileXD** [comment]
I simply said no more cloning from them. But i guess i have to take that back too. Face it, we are fucked up without them. (can't clone anyways - i am banned)
@Akuroma ich hätte vielleicht heute abend einen Moment.

**Comment by Akuroma** [comment]
@thebigsmileXD Ja. Hast du Discord, wenn ja kann ich dir einen Link schicken, dann können wir da sprechen. Anderenfalls können wir auch auf TS sprechen. Bevorzugt restinpizza.de

**Comment by Akuroma** [comment]
@thebigsmileXD https://discord.gg/EDNBe <- Discord

**Comment by robske110** [comment]
Particles are fixed. If you still have this issue let us known

**Comment by thebigsmileXD** [comment]
@robske110 wasnt it about essentialspe

**Comment by caspervanneck** [comment]
@thebigsmileXD  @thebigsmileXD i tink it needs to reopend

**Comment by caspervanneck** [comment]
here is the eror

without dubug


Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

Deprecated: Do not attempt to change hotbar links in plugins! in C:\Users\Gebruiker\Desktop\s server\src\pocketmine\inventory\PlayerInventory.php on line 90

**Comment by caspervanneck** [comment]
i tink i gone try and fix it

**Comment by robske110** [comment]
That is no error, that is Win10 changes/updates

**Comment by thebigsmileXD** [comment]
Yea, win10 support has kind of went away, working on it
