### ISSUE TITLE
Cheat max-player in Multicraft

### ISSUE THREAD

**Issue by iagomcs** [ClearSkyTeam/ClearSky#783]
#### Issue description
Customers can cheat the max-players limit in Multicraft. Isn't a Multicraft bug or problem, it don't happens in SpigotMC or Craftbukkit.

#### Steps to reproduce the issue
1. Start server in Multicraft.
2. Download server.proprierts via FTP.
3. Edit max-players option and upload to FTP.
4. use /reload command on console
Glitch done.

#### OS and versions

* ClearSky: Any
* PHP: Any
* Server OS: Any
* Game version:  Any

**Comment by thebigsmileXD** [comment]
spigot: PC

**Comment by iagomcs** [comment]
@thebigsmileXD  i know Spigot = PC, but i use Multicraft to offer FREE MC:PE and MC:PC servers, in MC:PC versions this glitch don't happens. I ask for help to Multicraft dev and they said it's a some problem in mc:pe softwares.

**Comment by thebigsmileXD** [comment]
its actually a feature.

**Comment by aodzip** [comment]
It happen because we reload the server.properties too.
I dont think this is a bug.
But if you want prevent such cheat , you can just host a self-moded clearsky just not reload server.properties

**Comment by robske110** [comment]
Disallow ftp access to server.properties.
We will not remove server.properties reloading. And we won't add an option for it too. You can force a certain max-player amount through a plugin.

**Comment by iagomcs** [comment]
@robske110 i've do that and i reported the problem, i have reported just why i find.

About have more players with plugins i've made a system with mcapi.ca to check every server and search for servers with more peoples than max permitied.

**Comment by thebigsmileXD** [comment]
Any player could load a phar using the autoupdater, a plugin etc.

**Comment by TDMidkwhatisxd** [comment]
XD! 
Warn/Suspend them for abuse!

You need a program that close servers with more slots than allowed, and auto send to customer a warning!

**Comment by iagomcs** [comment]
@TDMidkwhatisxd already doing it :)
