### ISSUE TITLE
My friends can't get to my server

### ISSUE THREAD

**Issue by MaRoFu** [ClearSkyTeam/ClearSky#785]
At first, it was working fine for them. All of a sudden however, My friends and I are unable to connect to the world! I can only connect via local IP! Someone help please!!! I will try to troubleshoot on my own at the moment.

**Comment by Aericio** [comment]
This isn't clearsky's problem, try checking your port forwarding and your firewall.
Simpler way is to install uTorrent and then go to preferences > connection and change the incoming connections to 19132 (you'll need utorrent open if you want others to be able to join)
Or be that lazy guy and open up your dmz server and let your pc be vulnerable as hell.

**Comment by starterdragon** [comment]
Are you sure you are not using static IP?? *e.g 123.45.678* If you do, then it must automatically change..

**Comment by MaRoFu** [comment]
I don't how I let the PE server through firewall. Port forwarding is fine. When set to TCP, doesn't work. When set to TCP/UCP, it says Server is full. When set to UDP, it locates the server but still doesn't work. I have utorrent already, so after checking firewall, I may try it

**Comment by starterdragon** [comment]
@MaRoFu Then leave it as 'TCP/UCP' ... and re-check your IP...  if you are using STATIC IP, I suggest you get a free Dynamic one, with mcpe.me

**Comment by MaRoFu** [comment]
I'm not using a static ip, and this is a private server, so I'm using my external ip

**Comment by MaRoFu** [comment]
My issue isn't solved yet

**Comment by robske110** [comment]
yea, you can still comment&discuss but it is no issue with this software

**Comment by Aericio** [comment]
So you have a dynamic ip? Use NoIP to make a server link and download their auto update ip thing. Try that since your ip always changes

**Comment by thebigsmileXD** [comment]
Localhost? Maybe the shell stuff again?

**Comment by starterdragon** [comment]
Can I close an issue :dagger:  ?

**Comment by MaRoFu** [comment]
Still doesn't work.

**Comment by thebigsmileXD** [comment]
@starterdragon only your own ones

**Comment by Aericio** [comment]
You have 2 routers or 1 router? Or those 1 router but actually has 2 router routers?

**Comment by MaRoFu** [comment]
@Aericio Yes, I only have one router. Connected to a modem.

**Comment by Aericio** [comment]
Just to make sure:
win+r > cmd > ipconfig
Make sure local address is correct

**Comment by MaRoFu** [comment]
@Aericio Ethernet Adapter Ethernet:
IPv4 Address: 192.168.2.8 

Port forwarding local ip: 192.168.2.8

**Comment by Aericio** [comment]
Ok... Try opening up your DMZ server (in router) and ask your friends to join.

**Comment by MaRoFu** [comment]
@Aericio Server is Full

**Comment by Aericio** [comment]
Shows that even if no one is online? Max players is set at?

**Comment by MaRoFu** [comment]
@Aericio Still says it's full

**Comment by Aericio** [comment]
Huh... try using a different core and see if this happens.

**Comment by starterdragon** [comment]
Maybe CustomAlert's issue, try turning the full message off
