### ISSUE TITLE
Offset LightPopulated not found

### ISSUE THREAD

**Issue by kim-min** [ClearSkyTeam/ClearSky#786]
When I use Commit 6c3036c2afef0b8d6505d3cf24477292718924b0, Sever make this error.

---------------------------------------------------------

File: /src/pocketmine/nbt/tag/CompoundTag
Line: 45
Type: error

Code:
[36] 	public function offsetGet($offset){
[37] 		if(isset($this->{$offset}) and $this->{$offset} instanceof Tag){
[38] 			if($this->{$offset} instanceof \ArrayAccess){
[39] 				return $this->{$offset};
[40] 			}else{
[41] 				return $this->{$offset}->getValue();
[42] 			}
[43] 		}
[44] 
[45] 		assert(false, "Offset $offset not found");
[46] 		return null;
[47] 	}
[48] 
[49] 	public function offsetSet($offset, $value){
[50] 		if($value instanceof Tag){
[51] 			$this->{$offset} = $value;
[52] 		}elseif(isset($this->{$offset}) and $this->{$offset} instanceof Tag){
[53] 			$this->{$offset}->setValue($value);
[54] 		}
[55] 	}

Backtrace:
#0 /src/pocketmine/level/format/mcregion/Chunk(231): pocketmine\nbt\tag\CompoundTag->offsetGet(string LightPopulated)
#1 /src/pocketmine/level/Level(2879): pocketmine\level\format\mcregion\Chunk->isLightPopulated(boolean)
#2 /src/pocketmine/level/Level(2463): pocketmine\level\Level->loadChunk(integer 61, integer -30, boolean )
#3 /src/pocketmine/level/Level(3000): pocketmine\level\Level->getChunk(integer 61, integer -30, boolean )
#4 /plugins/ParticlePlus.phar/src/ImagicalGamer/Particles/Main(28): pocketmine\level\Level->getSafeSpawn(boolean)
#5 /src/pocketmine/scheduler/TaskHandler(130): ImagicalGamer\Particles\ParticlesPlus->onRun(integer 1)
#6 /src/pocketmine/scheduler/ServerScheduler(229): pocketmine\scheduler\TaskHandler->run(integer 1)
#7 /src/pocketmine/Server(2557): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 1)
#8 /src/pocketmine/Server(2284): pocketmine\Server->tick(boolean)
#9 /src/pocketmine/Server(2162): pocketmine\Server->tickProcessor(boolean)
#10 /src/pocketmine/Server(1761): pocketmine\Server->start(boolean)
#11 /src/pocketmine/PocketMine(450): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\......\Desktop\PocketMine-MP\, string C:\Users\......\Desktop\PocketMine-MP\, string C:\Users\......\Desktop\PocketMine-MP\plugins\)

ClearSky version: 1.1 #CuttingEdge [Protocol 91; API 2.1.0]
uname -a: Windows NT DESKTOP-VKPIUN9 10.0 build 14393 (Windows 10) i586
PHP Version: 7.0.9
Zend version: 3.0.0
OS : WINNT, win

------------------------------------------------------------

If I start the server, The server make this error and die. I can't enter to server.

**Comment by thebigsmileXD** [comment]
Damn it

**Comment by thebigsmileXD** [comment]
It may be something related to https://github.com/ClearSkyTeam/ClearSky/commit/59f7ff402ef7fcef239eec100c572664302d0db1

**Comment by thebigsmileXD** [comment]
Confirmed
