### ISSUE TITLE
i need help！

### ISSUE THREAD

**Issue by 2449673842** [ClearSkyTeam/ClearSky#789]
i can't use the CSphar because i am a chinese .who can send the newest phar to me by e-mail. my eamil is 2449673842@qq.com .please！

**Comment by 2449673842** [comment]
[](url)

**Comment by caspervanneck** [comment]
plz use this one:http://robskebueba.no-ip.biz/CSPhar.php?type=1&branch=master

@2449673842

**Comment by 2449673842** [comment]
but it doesn't work either.

**Comment by Aericio** [comment]
Because the site is offline (as usual). I'll send a phar.

**Comment by 2449673842** [comment]
thanks a lot

**Comment by robske110** [comment]
>Because the site is offline (as usual).
:(
