### ISSUE TITLE
Fatal error: Call to undefined method pocketmine\event\HandlerList::quit()

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ClearSkyTeam/ClearSky#79]
Got this error on shut down after [19:03:30] [INFO]: Stopping other threads

**Comment by XxDXM-hippiexX** [comment]
Latest version

**Comment by XxDXM-hippiexX** [comment]
Maybe because of ASR plugin? because thats when it happened...not when i shut it down manually

**Comment by XxDXM-hippiexX** [comment]
Never mine..asr stopped the server without this error happening again. It only happened once and i have no idea what was different that time /: aaannnd im talking to myself XD

**Comment by aodzip** [comment]
I will check the thread stop process , I think it is not a big issue .

**Comment by aodzip** [comment]
This is caused by plugin fault . Handler shouldn't have quit function
