### ISSUE TITLE
Fix inventory Please !

### ISSUE THREAD

**Issue by CookieCode** [ClearSkyTeam/ClearSky#790]
The server does not stop telling me that there is a problem at line 90 in src/pocketmine/inventory/PlayerInventory.php ... 

It is because of this that I do not use ClearSky ... it would be so good without this bug.
I encourage you to continue ;)

**Comment by thebigsmileXD** [comment]
This isn't even a bug. Its a DEBUG, meaning its just some information for server owners

**Comment by robske110** [comment]
That's why I named it close and not fix
