### ISSUE TITLE
ClearSky installation

### ISSUE THREAD

**Issue by Touficbatache** [ClearSkyTeam/ClearSky#792]
Hello,

I wanted to ask a few questions: 
1- How can I install the latest phar for ClearSky?
2- Is it compatible with MCPE 1.0?
3- It needs PHP7 safe-thread or non safe-thread?

Thank you!

**Comment by robske110** [comment]
1.: Simply get it from http://robskebueba.no-ip.biz/CSphar.php and drop it into your server folder
2.: No, unfortunately you have to ask @thebigsmileXD about that. I would recommend using pmmp.
3.: You need to use a PHP compiled with some libs.

**Comment by thebigsmileXD** [comment]
(And how about reading the README.MD????!!!!!)
