### ISSUE TITLE
No Updated Installer

### ISSUE THREAD

**Issue by cnoffsin** [ClearSkyTeam/ClearSky#794]
Guys there is no link to a command to do the install on the Readme.

A git clone says and start.sh says this in the terminal:

minecraft@minecraft:/opt/clearsky/ClearSky$ ./start.sh 
./start.sh: line 28: type: php: not found
Couldn't find a working PHP binary, please use the installer.

Pocketmine had something like:

wget -q -O - https://raw.githubusercontent.com/PocketMine/php-build-scripts/master/installer.sh | bash -s -

I found the installer repo on the ClearSkyTeam project page but it is outdated and doesn't work:

```
   ______ __                   _____  __         
  / ____// /___   ____ _ _____/ ___/ / /__ __  __
 / /    / // _ \ / __ `// ___/\__ \ / //_// / / /
/ /___ / //  __// /_/ // /   ___/ // ,<  / /_/ / 
\____//_/ \___/ \__,_//_/   /____//_/|_| \__, /  
                                        /____/   
Please chose which version of MCPE server you want to install
	1) 0.14.x
	2) 0.13.x
Number (e.g. 2): 1
Also chose which PHP-binary you want to install
	1) Linux x86
	2) Linux x64
Number (e.g. 1): 2
Do you want to enable auto-restarting server when stop/crash? (y/N): y
Downloading install files...
Installing ClearSky...
./Linux.sh: line 68: ../install_log/log: No such file or directory
./Linux.sh: line 69: ../install_log/log: No such file or directory
./Linux.sh: line 70: ../install_log/log: No such file or directory
Installing PHP binary...

ClearSky installation completed! Run ./start.sh (or ./st*) to start ClearSky.
minecraft@minecraft:/opt/clearsky$ ll
```

**Comment by Aericio** [comment]
Download fresh and nice binaries from https://jenkins.pmmp.io/job/PHP-Linux-x64/
Also, I think the installer.sh is outdated, just start it with ./start.sh in the server directory

**Comment by thebigsmileXD** [comment]
@Aericio correct, if you use start.sh, it checks if its already set up, if not it opens the installer

**Comment by thebigsmileXD** [comment]
Due to move to https://github.com/ClearSkyTeam/PocketMine-MP, close

**Comment by daniktheboss** [comment]
@thebigsmileXD Hi?

**Comment by daniktheboss** [comment]
@daniktheboss Ok?
