### ISSUE TITLE
Hey, that's pretty good!

### ISSUE THREAD

**Issue by Aericio** [ClearSkyTeam/ClearSky#795]
I'm back. I code for ClearSky every day. I code ClearSky.I'm back. I code for ClearSky every day. I code ClearSky.When I wake up, I'm grabbing my phone. I wanna patch 'em all. I code for ClearSky, all day long, all day long.I'm back. I code for ClearSky every day. I code ClearSky.I'm back. I code for ClearSky every day. I code ClearSky.

**Comment by Aericio** [comment]
@Aericio Hey, that's pretty good!

**Comment by thebigsmileXD** [comment]
@Aericio banana

**Comment by thebigsmileXD** [comment]
@thebigsmileXD Open

**Comment by starterdragon** [comment]
@thebigsmileXD ....

**Comment by Aericio** [comment]
@starterdragon Hey!

**Comment by thebigsmileXD** [comment]
@Aericio Plz reply bot

**Comment by thebigsmileXD** [comment]
This was a Test-Issue for testing a Telegram Bot integration

**Comment by daniktheboss** [comment]
@Aericio Test

**Comment by daniktheboss** [comment]
@Aericio Hello
