### ISSUE TITLE
On crafting, [Classic UI]

### ISSUE THREAD

**Issue by starterdragon** [ClearSkyTeam/ClearSky#796]
when I craft using classic style, 

this error comes.. 

Notice: Undefined offset: 0 in phar://C:/Users/Administrator/Desktop/Frozen Lave Network/PocketMine-MP.phar/src/pocketmine/Player.php on line 2709

only when I take the finish product.

not tested on Pocket-UI...

**Comment by starterdragon** [comment]
Working perfectly with Pocket-UI

**Comment by thebigsmileXD** [comment]
@starterdragon open issue on pmmp
