### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/ClearSky#81]
It seems like when I hit /gc command it say: Garbge . It supposed to be garbage! Anyway its very small problem so pls fix it in the next update?

**Comment by aodzip** [comment]
You can make a pull request to fix this , I think it is located at src/pocketmine/lang

**Comment by Adam1609** [comment]
I couldnt find it, any other suggestion?

**Comment by Adam1609** [comment]
Is there a translation for given experience in src/pocketmine/lang??
