### ISSUE TITLE
Fatal ERROR!!!

### ISSUE THREAD

**Issue by EmreTr1** [ClearSkyTeam/ClearSky#93]
Fatal error: Out of memory (allocated 846462976) (tried to allocate 32 bytes) in C:\Users\aronf\Desktop\ImagicalMine-mcpe-0.14\src\pocketmine\scheduler\ServerScheduler.php on line 208

**Comment by aodzip** [comment]
x86 php5 can only use a little amount RAM , always cause out of memory crash . Please use linux x64 one.
unfortunately , there is no available x64 php5 for CS.
or change to php7 x64 version .

**Comment by SalmonGER** [comment]
You can try to restart your server every hour. Works fine for me.

**Comment by aodzip** [comment]
If you use x64 bit php it can runs for weeks

**Comment by SalmonGER** [comment]
@aodzip oh wait, i actually use x64 xD

**Comment by aodzip** [comment]
@SalmonGER WIndows or Linux?
It will be amazing have 64bit php5 on windows

**Comment by SalmonGER** [comment]
@aodzip I mean PHP7, sry. :/
