### ISSUE TITLE
Living.php?

### ISSUE THREAD

**Issue by nonbe102** [ClearSkyTeam/ClearSky#96]
[Server] [16:12:16] [INFO]: Disabling EconomyAPI v2.0.9
[Server] [16:12:17] [INFO]: Disabling ServerAuth v2.13
[Server] [16:12:17] [INFO]: Unloading level "frp"
[Server] [16:12:17] [ERROR]: Error while unloading a chunk: Argument 2 passed to pocketmine\level\Level::dropItem() must be an instance of pocketmine\item\Item, array given, called in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/entity/Living.php on line 153 and defined
[Server] [16:12:17] [NOTICE]: InvalidArgumentException: "Argument 2 passed to pocketmine\level\Level::dropItem() must be an instance of pocketmine\item\Item, array given, called in phar:///storage/sdcard0/PocketMine/PocketMine-MP.phar/src/pocketmine/entity/Living.php on line 153 and defined" (E_RECOVERABLE_ERROR) in "/src/pocketmine/level/Level" at line 1604
[Server] [16:12:22] [INFO]: Stopping other threads
[PocketMine] Server was stopped.

**Comment by nonbe102** [comment]
I really have no idea what the error is all about.

**Comment by PocketKiller** [comment]
might be caused by a plugin.

**Comment by PocketKiller** [comment]
@thebigsmileXD maybe look at this^?

**Comment by aodzip** [comment]
Was this happened when you try to stop your server?

**Comment by aodzip** [comment]
Okay……I maybe know what cause this

**Comment by thebigsmileXD** [comment]
I'll fix. Boat, painting or minecart

**Comment by aodzip** [comment]
Yeah . I was looking on these entity can drop items

**Comment by aodzip** [comment]
Wait ... livings? Should paint or Minecart or boat extends livings?

**Comment by thebigsmileXD** [comment]
Because of my latest changes. I am done with the fix

**Comment by TheKillerTacos** [comment]
I have the same problem, no plugin is making the error, but mine doesnt crashes, it may be an item

> [CRITICAL]: Could not tick level "world": Argument 2 passed to pocketmine\level\Level::dropItem() must be an instance of pocketmine\item\Item, array given, called in phar://C:/ITSRV/Pocketmine-MP.phar/src/pocketmine/entity/Living.php on line 153 and defined

**Comment by MCPEPIG** [comment]
Made a pull request.

**Comment by MCPEPIG** [comment]
Fixed.

**Comment by TheKillerTacos** [comment]
Update the Phar soon, really wish to start my PVP Server,

**Comment by nonbe102** [comment]
@MCPEPIG  thanks
