### ISSUE TITLE
About language

### ISSUE THREAD

**Issue by Adam1609** [ClearSkyTeam/ClearSky#99]
Is there any chance that /enchant and /xp command has translated? Im good at english but my staff server doesn't!!!

**Comment by thebigsmileXD** [comment]
I see how good you are ;)
Well, you can add translation to the translation files, would be really nice if you could do so

**Comment by Adam1609** [comment]
should i based on eng.ini?

**Comment by thebigsmileXD** [comment]
What you did was correct

**Comment by Adam1609** [comment]
so i will start translating and fix spelling and make a pull request :)

**Comment by thebigsmileXD** [comment]
:+1:

**Comment by TheKillerTacos** [comment]
so, may i help? I can translate it to Spanish,

**Comment by PocketKiller** [comment]
@TheKillerTacos of course.

**Comment by TheKillerTacos** [comment]
Ok,

**Comment by robske110** [comment]
German translation completed now

**Comment by KubixQ** [comment]
I can add polish translate, when I finish where publish it?

**Comment by robske110** [comment]
Modify the .lang file

**Comment by robske110** [comment]
LOL This should really be closed now
